createdAt: 1599752690953
createdBy: PRoDkZDjsnUiv0BdkOHKfAiXaRJ3
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
city: Munich
name: "Andreas "
username: Andy
gender: Male
community: Munich
styles:
  Bachata:
    level: Interested
    selected: true
  Salsa:
    level: Interested
    selected: true
step: photo
type: Dancer
visibility: Members
locales:
  de: true
language: de
hometown: ""
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
pwaUsed: false
lastLoginAt: 1659553875488
daysUsed: 10
bannerNps: no
updatedAt: 1659553890138
id: PRoDkZDjsnUiv0BdkOHKfAiXaRJ3
