venue:
  website: https://www.salsa-y-corazon.de/
  formatted_address: Zenettistraße 7, 80337 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "7"
      short_name: "7"
    - types:
        - route
      long_name: Zenettistraße
      short_name: Zenettistraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Ludwigsvorstadt-Isarvorstadt
      short_name: Ludwigsvorstadt-Isarvorstadt
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80337"
      short_name: "80337"
  url: https://maps.google.com/?cid=8616399599048238742
  name: Salsa Y Corazon - dance school
  geometry:
    viewport:
      south: 48.12187606970849
      north: 48.12457403029149
      east: 11.5593379802915
      west: 11.5566400197085
    location:
      lng: 11.557894
      lat: 48.12314479999999
  place_id: ChIJ7SAJ9Rd3nkcRlqYWoMiZk3c
  international_phone_number: +49 172 9659579
endDate: 2021-11-07T02:30:00.000Z
organisedBy: ""
claimed: No
description: >+
  Programm:

  *************************************

  +++ Hot Kizomba Night Party +++

  Am 06.11.2021


  Mit DJ Saul & DJ Taurus


  Workshops : mit Saul 


  20:30 bis 21:30 Kizomba Grundstufe



  Einlass Party 22 Uhr Bis 3Uhr


  Eintritt :


  1 Workshop + Party 20 EUR


  Nur Party 10 EUR


  Voranmeldund / Registrations PN,SMS,Mail für die Workshops bitte Email: saulfit@yahoo.de

  Mobil: 0176/43260515



  ACHTUNG: EINTRITT ES GILT NUR MIT 3G-REGEL 


  Ort:

  LOCATION:

  Adresse: SALSA Y CORAZON 

  ZENETTISSTRASSE 7 .

  80337 MÜNCHEN


  *************************************


type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2F49061331-d539-430b-8a72-a7a57ca23791?alt=media&token=f0995775-2dfd-44f7-a574-d83d847cf663
duration: custom
promo: ""
createdAt: 1633976265400
watchersCount: 0
price: 10-20  EUR
promoter: Vitali
id: 0BLTxLyobBSv6sikAmUV
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
international: No
views: 34
updatedAt: 1633976265400
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
facebook: https://facebook.com/events/s/hot-kizomba-night-party-am-611/398373975330203/
eventType: Party
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
name: Kizomba Night @Salsa Y Corazon
online: No
styles:
  UrbanKizz:
    level: Interested
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-06T19:30:00.000Z
username: Vitali
watch:
  count: 1
  list:
    tim: true
commentsCount: 2
commentsLast:
  createdAt: 1669820929976
  updatedBy: VPBDrnfyK6VNyunIYT57nJxWJFn1
  createdBy: VPBDrnfyK6VNyunIYT57nJxWJFn1
  commentId: ""
  postId: 0BLTxLyobBSv6sikAmUV
  body: Cool!
  updatedAt: 1669820929976
  username: tim
star:
  count: 1
  usernames:
    - Inessa
  list:
    Inessa: true
viewsCount: 94
