venue:
  formatted_address: Aschauer Str. 24, 81549 München, Germany
  website: https://www.swingandthecity.com/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "24"
      short_name: "24"
    - types:
        - route
      long_name: Aschauer Straße
      short_name: Aschauer Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Ramersdorf-Perlach
      short_name: Ramersdorf-Perlach
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81549"
      short_name: "81549"
  url: https://maps.google.com/?cid=2981211129621893737
  name: Swing On Stage - Swing and the City of Munich
  geometry:
    viewport:
      south: 48.1040300697085
      north: 48.1067280302915
      east: 11.6013854302915
      west: 11.5986874697085
    location:
      lng: 11.5994392
      lat: 48.1052491
  international_phone_number: +49 172 6756376
  place_id: ChIJ-2shRft1nkcRadKNLbpjXyk
endDate:
  _seconds: 1635625800
  _nanoseconds: 0
claimed: No
organisedBy: ""
link: https://forms.gle/bFDEg8mjn7qHHPt26
description: >-
  

  We bring Salsa with swing from London to Munich 🎶💃🏼🕺🏾


  🔥 Salsa On2 Workshop: 

  20:30 - 21:30 Uhr (Level Intermediate)

  Shines mit Anastasia Susi

  Partnerwork mit Manu & Jasmin (MamboJazz)


  🔥 Salsa On2 Schnupperkurs - Grundschritte Solo und mit Partner

  21:45 - 22:15 Uhr mit Jasmin (in Saal 2)

  GRATIS bei Teilnahme am Social Dance (keine separate Anmeldung nötig)


  _________________


  🎉 SOCIAL DANCE 🎉 SALSA & BACHATA 💃🕺🏽


  21:30 Uhr - 01:30 Uhr 

  mit DJ Manu Ramos & DJ Mel Mori 

  🎶 Live Percussion & Animation mit Manu & Jasmin

  💃🕺🏽 Salsa all night long + extra Bachata Dancefloor ab 22:30 Uhr


  🔥 SHOWS 🔥 

  💃🕺🏽 Premier NEW SHOW by Manu & Jasmin - MamboJazz

  💃 Show by Dasha


  ✅ Location: ON STAGE Swing and the City (Aschauerstr. 24, 81549 München). Giesinger Bahnhof (U2/7/8 & S2/3/4/7; 8 Minuten zu Fuß zum Studio) + kostenlose Parkplätze direkt vor der Tür vorhanden.


  ❗️Anmeldung❗️


  ✅ Salsa On2 Workshop: 10€

  Anmeldung unter: https://forms.gle/bFDEg8mjn7qHHPt26


  ✅ Social Dance: 10€

  Anmeldung unter: https://forms.gle/SGeFjs3gJrkBhETr6


  ❗️Alle weiteren wichtigen Informationen auf unserer Website: www.mambojazz.co.uk


  The spirit of New York 🎶 

  The flow of London 💃🏼🕺🏾

  The soul of Peru 🔥

  The party vibes of Bavaria 🍻

  Brought to you by Manu & Jasmin 💃🏼🕺🏾



  __________________

  Wichtige Infos:

  - Bitte online frühzeitig anmelden (keine Vorab-Zahlung notwendig; Workshop & Social ausschließlich Bar-Zahlung vor Ort). Wir können aufgrund der limitierten Plätze ohne Vor-Anmeldung keinen Platz garantieren.

  - Für Workshop und Party gilt die 3-G Regel. Wir werden die Nachweise (geimpft, genesen, getestet) am Eingang kontrollieren. Bitte habt Verständnis, dass wir uns an die gesetzlichen Regelungen halten müssen.


  Fragen oder Anregungen? Schreibt uns an: mambojazz.munich@gmail.com
type: event
duration: "60"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2F0b10061f-8515-467e-9086-ac0fc53c08f5?alt=media&token=1986830e-69e9-4fe6-a671-13401f09b873
createdAt: 1635104541972
watchersCount: 0
price: FREE
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FYchV8mQrwzJwnfoBfxYL.png?generation=1635104597063663&alt=media
commentsLast: ~
promoter: Vitali
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
id: 0FIoyyYyioehedYGwBuk
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 6
updatedAt: 1635104541972
website: https://www.joyofmovementlondon.com/mambojazz
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
facebook: https://facebook.com/events/s/salsa-swing-by-mambojazz/222456619949746/
eventType: Workshop
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Salsa ON2 basic Workshop
online: No
styles:
  SalsaNewYork:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-30T19:30:00.000Z
username: Vitali
viewsCount: 42
