venue:
  website: https://www.fire-tiger-berlin.de/
  formatted_address: Revaler Str. 7, 10245 Berlin, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "7"
      short_name: "7"
    - types:
        - route
      long_name: Revaler Straße
      short_name: Revaler Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Bezirk Friedrichshain-Kreuzberg
      short_name: Bezirk Friedrichshain-Kreuzberg
    - types:
        - locality
        - political
      long_name: Berlin
      short_name: Berlin
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Berlin
      short_name: Kreisfreie Stadt Berlin
    - types:
        - administrative_area_level_1
        - political
      long_name: Berlin
      short_name: BE
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "10245"
      short_name: "10245"
  url: https://maps.google.com/?cid=13285853219991618602
  name: Fire Tiger - Cocktail Bar - Asiatisch & Sushi
  geometry:
    viewport:
      south: 52.5071546697085
      north: 52.5098526302915
      east: 13.4532386802915
      west: 13.4505407197085
    location:
      lng: 13.451968
      lat: 52.5085937
  international_phone_number: +49 30 29360930
  place_id: ChIJrxrOultOqEcRKoSUsxzVYLg
endDate:
  _seconds: 1633833000
  _nanoseconds: 0
link: https://fb.me/e/41Wmeg9I3
description: >
  Hello guys! We are very happy to present our first party event in cooperation
  with Fire Tiger.



  What you need to know 🧐



  🕓 Date and time - Saturday 09 October at 23:30


  📍 Location - Revaler Str. 7, 10245 Berlin (S-bahn Warschauer straße)


  💸 Entry fee - Because it's our first event you can enjoy FREE entry all night (No Friendslist needed this time, but limited to the capacity of the venue)

  3G Rules apply - Recovered, Vaccinated or Tested


  🎶 Music - Salsa, Bachata, Kizomba and Reggaeton (in a nice and balanced mix) by DJEDDYTHEGUN


  🍻 Drinks - You can enjoy Fire Tiger Fresh cocktails or the traditional soft drinks, beer, etc...


  🍲 Food - You can come earlier and experience Fire Tiger finest Asian cuisine (Food is served until 22:30)

  👌🏽 Special - If you come to eat in Fire Tiger before our event starts you will get a 10% discount on your meal (for that just send us a DM so we can provide you with the voucher)
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FsXlqPDGz2HdSX02QOyZxkte4iF22%2F11dd7506-e9af-4e4e-a77d-f63e366b990c?alt=media&token=0c9a633e-2998-4bc4-9b95-41959528e1fd
duration: "300"
promo: Yes
createdAt: 1632607603288
watchersCount: 0
price: FREE
commentsLast: ~
place: ChIJAVkDPzdOqEcRcDteW0YgIQQ
id: 0GHPVOM2KLF9xLCSEg6r
views: 6
updatedAt: 1632607603288
updatedBy: sXlqPDGz2HdSX02QOyZxkte4iF22
visibility: Public
eventType: Party
organiser: barriolatinoberlin
form: Yes
createdBy: sXlqPDGz2HdSX02QOyZxkte4iF22
commentsCount: 0
name: "Latin Party Mix "
online: No
styles:
  Merengue:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Reggaeton:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Berlin
  location:
    country: Germany
    latitude: 52.52000659999999
    locality: Berlin
    usedGps: false
    place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
    longitude: 13.404954
startDate: 2021-10-09T21:30:00.000Z
username: barriolatinoberlin
viewsCount: 62
