venue:
  formatted_address: Machtlfinger Str., 81379 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png
  html_attributions: []
  address_components:
    - types:
        - route
      long_name: Machtlfinger Straße
      short_name: Machtlfinger Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Thalkirchen-Obersendling-Forstenried-Fürstenried-Solln
      short_name: Thalkirchen-Obersendling-Forstenried-Fürstenried-Solln
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81379"
      short_name: "81379"
  url: https://maps.google.com/?q=Machtlfinger+Str.,+81379+M%C3%BCnchen,+Germany&ftid=0x479dd92698019927:0x2ee814b5db146e66
  name: Machtlfinger Straße
  geometry:
    viewport:
      south: 48.0951492197085
      north: 48.0978471802915
      east: 11.5151862802915
      west: 11.5124883197085
    location:
      lng: 11.5138373
      lat: 48.0964982
  place_id: EipNYWNodGxmaW5nZXIgU3RyLiwgODEzNzkgTcO8bmNoZW4sIEdlcm1hbnkiLiosChQKEgknmQGYJtmdRxFmbhTbtRToLhIUChIJ2V-Mo_l1nkcRfZixfUq4DAE
endDate:
  _seconds: 1640896200
  _nanoseconds: 0
claimed: Yes
organisedBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
link: https://docs.google.com/forms/d/1dISgnOWfRVUhTOv3PCv76irkDBI786M_PZ5e6wfRIdg/viewform?edit_requested=true
description: >+
  FREE WORKSHOP - A little xmas gift for you 🤶 ⛄️ ❄️ 🎁 💝 


  Toan & I want to thank you all for a whole year supporting us and our classes by giving you this free workshop right at the end of 2021


  Please enlist yourself with the link below and let us dance our way to 2022 🙂


  Merry Christmas 🎅 

type: event
promo: Yes
duration: "90"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F8yp79cUd0jZtnVn34NxhBuMpxrx1%2Fb8f9f589-f4a4-42db-8589-e6804becc7fb?alt=media&token=5ce69bdb-5c7a-4a31-894c-d96fba6b87b4
createdAt: 1640276147035
watchersCount: 0
price: Free
commentsLast: ~
promoter: ""
id: 0QA8yOadP5Hwo2RmTm30
promotedBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 10
updatedAt: 1640276147035
updatedBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
visibility: Public
confirmation: |-
  Dear Guest,
  Thank you 
  We are sorry to have to tell you the workshop is full.

  0 places left...

  Hope to see you next time or in our classes starting from January ☺️

  Have nice holidays
  Toan & Anna
eventType: Workshop
organiser: Anna & Toan
form: Yes
createdBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
commentsCount: 0
name: FREE BACHATA WORKSHOP
online: No
styles:
  Bachata:
    level: Intermediate
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-12-30T19:00:00.000Z
username: AnnaMil
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2F0QA8yOadP5Hwo2RmTm30.png?generation=1665499690353844&alt=media
viewsCount: 64
