venue:
  website: https://www.tanzraum-berlin.de/
  formatted_address: Oudenarder Str. 16-20, 13347 Berlin, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: 16-20
      short_name: 16-20
    - types:
        - route
      long_name: Oudenarder Straße
      short_name: Oudenarder Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Mitte
      short_name: Mitte
    - types:
        - locality
        - political
      long_name: Berlin
      short_name: Berlin
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Berlin
      short_name: Kreisfreie Stadt Berlin
    - types:
        - administrative_area_level_1
        - political
      long_name: Berlin
      short_name: BE
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "13347"
      short_name: "13347"
  url: https://maps.google.com/?cid=12871345234978269182
  name: Tanzraum Wedding
  geometry:
    viewport:
      south: 52.55170091970849
      north: 52.55439888029149
      east: 13.3615986802915
      west: 13.3589007197085
    location:
      lng: 13.360076
      lat: 52.5530629
  place_id: ChIJ2Wd0Uw5TqEcR_udLwEs0oLI
  international_phone_number: +49 173 6020040
endDate:
  _seconds: 1633280400
  _nanoseconds: 0
link: http://cspberlin.com/afrocuban
type: event
duration: "120"
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FpH0880yoosdst2YzH0t6hvWMmi63%2F588b8637-d8bb-47aa-9c0c-c66b5d42c1e6?alt=media&token=68a6d24e-707c-497c-bd6c-a7006bdac599
createdAt: 1631713488394
watchersCount: 0
price: From 13,50
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2F0rO8nUZ1k59edHCxRo8J.png?generation=1632578440537771&alt=media
commentsLast: ~
place: ChIJAVkDPzdOqEcRcDteW0YgIQQ
id: 0rO8nUZ1k59edHCxRo8J
views: 6
updatedAt: 1631713488394
updatedBy: pH0880yoosdst2YzH0t6hvWMmi63
visibility: Public
eventType: Course
organiser: Juli
form: Yes
createdBy: pH0880yoosdst2YzH0t6hvWMmi63
commentsCount: 0
name: Afrocuban Dances | Beginner & Advanced | Okt 2021
online: No
styles:
  Afro:
    level: Beginner
    highlighted: false
    selected: true
region:
  name: Berlin
  location:
    country: Germany
    latitude: 52.52000659999999
    locality: Berlin
    usedGps: false
    place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
    longitude: 13.404954
startDate: 2021-10-03T15:00:00.000Z
username: Juli
viewsCount: 41
