venue:
  website: https://www.kultur-im-oberbraeu.de/
  formatted_address: Marktpl. 18A, 83607 Holzkirchen, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: 18A
      short_name: 18A
    - types:
        - route
      long_name: Marktplatz
      short_name: Marktpl.
    - types:
        - locality
        - political
      long_name: Holzkirchen
      short_name: Holzkirchen
    - types:
        - administrative_area_level_3
        - political
      long_name: Miesbach
      short_name: MB
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "83607"
      short_name: "83607"
  url: https://maps.google.com/?cid=17973752425292884048
  name: KULTUR im Oberbräu
  geometry:
    viewport:
      south: 47.87586981970851
      north: 47.8785677802915
      east: 11.7017974802915
      west: 11.6990995197085
    location:
      lng: 11.7004793
      lat: 47.87728200000001
  international_phone_number: +49 8024 478505
  place_id: ChIJWcotCyvsnUcRUOhlDpqYb_k
endDate:
  _seconds: 1634412600
  _nanoseconds: 0
organisedBy: ""
claimed: No
link: https://www.treffpunkt-jazz.de/event/10-holzkirchner-blues-und-jazztage-el-vikingo-de-la-salsa/
description: Unter dem Künstlernamen „El Vikingo de la Salsa“ sorgte der
  Posaunist Thorben Schütt international für Furore und tourte mit Salsabands
  wie „La Maxima 79“ in über 20 Ländern. Mit seinem neuen Projekt bringt er
  karibische Rhythmen voller Lebensfreude und Leidenschaft auf die Bühne.
type: event
duration: "90"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2Fbf0d5039-9854-4c1d-a88a-cbd3ff2ee6fd?alt=media&token=bd9379a2-1e2a-4be5-ba1d-55a00f7fa3e9
createdAt: 1633769551555
watchersCount: 0
price: 21 EUR
commentsLast: ~
promoter: Vitali
id: 0skrQ93FkQNqS2zGfXuf
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
international: No
views: 6
updatedAt: 1633769551555
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Concert
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: "Holzkirchner Blues- und Jazztage: El Vikingo de la Salsa"
online: No
styles:
  Salsa:
    level: Interested
    highlighted: false
    selected: true
  Jazz:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-16T18:00:00.000Z
username: Vitali
viewsCount: 40
