venue:
  formatted_address: Greifswalder Str. 52, 10405 Berlin, Germany
  website: https://digitalcosmonaut.com/2012/111-places-in-berlin-ernst-thaelmann-monument/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "52"
      short_name: "52"
    - types:
        - route
      long_name: Greifswalder Straße
      short_name: Greifswalder Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Bezirk Pankow
      short_name: Bezirk Pankow
    - types:
        - locality
        - political
      long_name: Berlin
      short_name: Berlin
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Berlin
      short_name: Kreisfreie Stadt Berlin
    - types:
        - administrative_area_level_1
        - political
      long_name: Berlin
      short_name: BE
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "10405"
      short_name: "10405"
  url: https://maps.google.com/?cid=13575927848617907638
  name: Ernst-Thälmann-Denkmal
  geometry:
    viewport:
      south: 52.5367857197085
      north: 52.5394836802915
      east: 13.43511908029151
      west: 13.4324211197085
    location:
      lng: 13.4337701
      lat: 52.5381347
  international_phone_number: +49 30 902593652
  place_id: ChIJL5OVSAhOqEcRthU0MXNiZ7w
endDate:
  _seconds: 1630087200
  _nanoseconds: 0
link: https://freebollywooddanceclassberlin.eventbrite.de
description: >
  We will learn a easy, dance choreo to peppy Bollywood beats which will make us
  feel like we are at an Indian wedding or a dance party!!😎 Added benefits will
  be improving your rhythm sense, and keeping your brain and body agile!!


  ✅Save your spot & get your ticket!!


  ❤ OPEN TO ALL GENDERS!

  💛Beginner Friendly!

  💚All Ages welcome!


  So invite your friends,colleagues, family & come have FUN!!


  Time to be spontaneous!

  ✅ Register for the class, limited spots!

  https://freebollywooddanceclassberlin.eventbrite.de


  Who's the Teacher & Choreographer?

  Shailee Mody!

  She is a professional dance teacher from India living in Berlin,Germany. She has a decade of choreographing and teaching knowledge & experience behind her, so you are in safe hands & feet 😉

  She is trained in 9 dance forms including Indian classical dance, Bharatnatayam and currently training in Kathak. She uses her knowledge of Salsa, Bachata, Belly, Indian folk to create her fusion choreographies, like this one!!
type: event
promo: Yes
duration: 60
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FycKweicuUqf5EhUFmQmVlCXeVs92%2Fd72d36de-923b-44f7-90d0-a7fb621ceebc?alt=media&token=b5afefbd-b268-4166-a8a7-a856fa2a1f21
createdAt: 1629378305566
watchersCount: 0
price: FREE
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2F12gsYsY011vwEQWBQLcL.png?generation=1629378375627253&alt=media
commentsLast: ~
id: 12gsYsY011vwEQWBQLcL
place: ChIJAVkDPzdOqEcRcDteW0YgIQQ
views: 1
updatedAt: 1629378305566
updatedBy: ycKweicuUqf5EhUFmQmVlCXeVs92
visibility: Public
eventType: Course
organiser: smellslikebollyspiritbyshaileemody
form: Yes
createdBy: ycKweicuUqf5EhUFmQmVlCXeVs92
commentsCount: 0
name: FREE Bollywood Dance Class - BERLIN Open Air - Beginner Friendly Fun Choreo!
online: No
styles:
  Bollywood:
    level: Beginner
    highlighted: false
    selected: true
region:
  name: Berlin
  location:
    country: Germany
    latitude: 52.52000659999999
    locality: Berlin
    usedGps: false
    place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
    longitude: 13.404954
startDate: 2021-08-27T17:00:00.000Z
username: smellslikebollyspiritbyshaileemody
viewsCount: 53
