venue:
  website: http://www.kulturschranne.com/
  formatted_address: Pfarrstraße 13, 85221 Dachau, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "13"
      short_name: "13"
    - types:
        - route
      long_name: Pfarrstraße
      short_name: Pfarrstraße
    - types:
        - locality
        - political
      long_name: Dachau
      short_name: Dachau
    - types:
        - administrative_area_level_3
        - political
      long_name: Dachau
      short_name: DAH
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "85221"
      short_name: "85221"
  url: https://maps.google.com/?cid=7807127586167955130
  name: Kulturschranne Dachau
  geometry:
    viewport:
      south: 48.25836511970849
      north: 48.26106308029149
      east: 11.4351043302915
      west: 11.4324063697085
    location:
      lng: 11.4341333
      lat: 48.2597164
  place_id: ChIJR5pd8q17nkcRup6x-Sx9WGw
  international_phone_number: +49 8131 6681100
endDate:
  _seconds: 1636668000
  _nanoseconds: 0
claimed: No
organisedBy: ""
description: |-
  Kubanisches Konzert mit der besten Musik aus Kuba 
  Buena Vista Social Club , Mambo , Cha Cha  Cha, Salsa 
type: event
duration: "240"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2F10a05ac2-6356-4095-8f38-4c21e22e01dc?alt=media&token=275fe3df-039c-4fd8-93b8-a55e0f0bd0ef
createdAt: 1633768183479
watchersCount: 0
price: FREE
commentsLast: ~
promoter: Vitali
id: 18rFtcaE9wsTDgUBpzw1
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
international: No
views: 21
updatedAt: 1633768183479
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Party
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Kubanische Weihnachtsparty
online: No
styles:
  Timba:
    level: Interested
    highlighted: false
    selected: true
  RumbaColumbia:
    level: Interested
    selected: true
  Merengue:
    level: Interested
    highlighted: false
    selected: true
  DominicanBachata:
    level: Interested
    selected: true
  Cubaton:
    level: Interested
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-11T18:00:00.000Z
username: Vitali
viewsCount: 85
