venue:
  website: http://www.salsabor.de/
  formatted_address: Heßstr. 48b-UG, 80798 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Maxvorstadt
      short_name: Maxvorstadt
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80798"
      short_name: "80798"
  url: https://maps.google.com/?cid=13068910098957006739
  name: Salsabor Dance Academy
  geometry:
    viewport:
      south: 48.1506543197085
      north: 48.1533522802915
      east: 11.5672969802915
      west: 11.5645990197085
    location:
      lng: 11.5659788
      lat: 48.1520512
  international_phone_number: +49 89 52059610
  place_id: ChIJneG5QOZ1nkcRk_fYMX4YXrU
endDate:
  _seconds: 1641843000
  _nanoseconds: 0
organisedBy: ""
claimed: No
link: http://www.salsabor.de/kursanmeldung/
description: >-
  Learn the beautyfull Salsa LA Style at Beginner 1 Dance Classes

  Price: 90 EUR 4 Classes (75 EUR Students)




  Attention

  This is a 2G+. You should be vaccinated / recovered + need a negative test to come in.
type: event
cover: ""
duration: "90"
createdAt: 1640293488882
watchersCount: 0
price: 75-90 EUR
commentsLast: ~
promoter: Vitali
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
id: 1i1UckbjerNrWIvuMBqw
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 8
updatedAt: 1640293488882
website: http://www.salsabor.de/kurse/salsa/
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Course
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: "Salsa LA Beginner 1 "
online: No
styles:
  SalsaLA:
    level: Beginner
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2022-01-10T18:00:00.000Z
username: Vitali
star:
  count: 0
  list: {}
viewsCount: 59
