venue:
  formatted_address: Rosenheimer Str. 139, 81671 München, Germany
  website: http://www.circulo.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "139"
      short_name: "139"
    - types:
        - route
      long_name: Rosenheimer Straße
      short_name: Rosenheimer Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Berg am Laim
      short_name: Berg am Laim
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81671"
      short_name: "81671"
  url: https://maps.google.com/?cid=10790597757153464934
  name: CIRCULO Tanzschule München
  geometry:
    viewport:
      south: 48.1229421197085
      north: 48.1256400802915
      east: 11.6034035302915
      west: 11.6007055697085
    location:
      lng: 11.6024306
      lat: 48.1242407
  place_id: ChIJ30VdnYPfnUcRZlJCNX3nv5U
  international_phone_number: +49 89 494888
endDate: 2021-10-23T19:00:00.000Z
claimed: No
organisedBy: ""
link: https://doo.net/event/88723/order
description: >-
  Cédric from Marseille will be in town to teach Zouk. Don’t miss this rare
  opportunity to improve ur zouk with an international teacher in Munich! His
  workshops at Zouktime Croatia were a huge success. It'll be the first time
  Cédric will teach in Germany - make sure he comes back ;)


  Munich will be on fire! Register here:  https://doo.net/event/88723/order



  Schedule:


  *****Saturday, Oct 23rd****

  17:00 - 17:30 Check-In incl. 3G check for Intermediate

  17:30 - 19:30 Intermediate: Infinite fun with variations


  19:15 - 19:45 Check-In incl. 3G check for Beginners

  19:45 - 21:45 Beginners: Strong basics


  21:45 - ca. 1:45 Practice night with DJ Baui (oh yes!!!)



  📍Location: Salsa y Corazon, Zenettistraße 7, 80337 München


  *****Sunday, Oct 24th****

  13:30 - 18:00 Intermediate: Isolations, head movements and a nice sequence combining flow, connection and cool moves (incl. 30mins break)


  📍Location: Circulo, Rosenheimer Str. 139, 81671 München


  Save your spot here:  https://doo.net/event/88723/order


  And friends from outside Munich - find your couch here: https://www.facebook.com/groups/874196540197615
type: event
duration: custom
promo: ""
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2Fb270af14-a9db-4615-8792-53a92446eb7c?alt=media&token=12841cf5-ec3e-4378-9fb2-323effa86e5b
createdAt: 1633765590770
watchersCount: 0
price: 35-80 EUR
commentsLast: ~
promoter: Vitali
id: 2fTT8wbrBBU7xkozDZYi
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
international: No
views: 9
updatedAt: 1633765590770
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Workshop
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Zouk Workshop Beginner and Intermediate
online: No
styles:
  BrazilianZouk:
    level: Intermediate
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-23T15:00:00.000Z
username: Vitali
watch:
  count: 1
  list:
    Vitali: true
star:
  count: 1
  list:
    Vitali: true
viewsCount: 44
