endDate: 2021-07-24T20:00:00.000Z
link: https://hofgarten.splashthat.com/
description: >-
  🎶🎵Buenos días ☀️SALSAFREAKS !! 


  Am Samstag den 24.07.21 findet wieder Mal unser Treff ab 19 Uhr in DIANATEMPEL im HOFGARTEN statt.


  🔥🔥 SALSAHOTMIX🔥🔥


  👉🏻NUR MIT ONLINE ANMELDUNG


  👉🏻LASST EUCH REGISTRIEREN !! 


  👉🏻Jeder registrierte bekommt ein Armband, bitte bei mir abholen


  👉🏻Teilnehmerzahl ist begrenzt!!


  👉🏻Hygiene-Station mit Desinfektionsmittel ist vorhanden


  ⛔️ ES WIRD VOR ORT

  NICHT REGISTRIERT!!!⛔️


  👉🏻Findet bei jedem Wetter statt👈🏻


  👉🏻 Eintritt: Spende, um die Unkosten decken zu können 


  👉🏻Nicht vergessen Euren Müll und Flaschen zu entsorgen 


  Anbei den Link für die Anmeldung:🎵🎶


  Wegen Platzmangels diesen Link nicht weiterleiten


  hofgarten.splashthat.com


  Salsaludos DJHEC
type: event
duration: custom
createdAt: 1626870684838
watchersCount: 0
price: Spende
commentsLast: ~
id: 3wHBCJKLS4EcUmhYO1Wk
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 7
updatedAt: 1626870684838
address: Hofgarten
updatedBy: yj4bkZGCKRVNew48YXtuZAirlU82
visibility: Public
eventType: Party
form: Yes
createdBy: yj4bkZGCKRVNew48YXtuZAirlU82
commentsCount: 0
name: Salsa Freaks (nur mit Anmeldung)
online: No
styles:
  SalsaCalena:
    level: Interested
    highlighted: false
    selected: true
  SalsaLA:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
  Casino:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-07-24T17:00:00.000Z
username: DJHEC
viewsCount: 26
