venue:
  formatted_address: Lenbachpl. 8, 80333 München, Germany
  website: http://www.kuenstlerhaus-muc.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "8"
      short_name: "8"
    - types:
        - route
      long_name: Lenbachplatz
      short_name: Lenbachpl.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Altstadt-Lehel
      short_name: Altstadt-Lehel
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80333"
      short_name: "80333"
  url: https://maps.google.com/?cid=14501397795809277328
  name: Künstlerhaus am Lenbachplatz
  geometry:
    viewport:
      south: 48.1389776697085
      north: 48.1416756302915
      east: 11.5692519302915
      west: 11.5665539697085
    location:
      lng: 11.568013
      lat: 48.140167
  place_id: ChIJSQbzt_Z1nkcRkDXYrXZQP8k
  international_phone_number: +49 89 5991840
endDate:
  _seconds: 1635634800
  _nanoseconds: 0
claimed: No
organisedBy: ""
description: >-
  Liebe Tangueros und Tangueras,


  Wir dürfen wieder Tango richtig atmen in einer wunderbare Tanzfläche, elegantem  grandiosem und sehr gut belüftet Ballsaal !

  Die Begrenzung auf 150 Gäste wurde aufgehoben, Wir haben den Vorverkauf wieder begonnen.

  Ihr könnt auch am Samstagabend ein Ticket erwerben. 


  Wir bieten am dem Abend Tangomode La Lucila : Tangokleider, Schuhe aus Italien für Damen und Herren!


  Wir freuen uns sehr auf eine  wunderbare Tangoball wie damals wieder mit Euch zu genießen!


  Laura , Ulrich und Team

  DJ Baki

  Eintrittspreis: 25 €

  3G Regel-Veranstaltung


  Vorverkauf ab sofort im Studio Lo de Laura, Hans-Sachs-str. 6

  oder auf unsere Webseite

  www.lodeaura.de
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2Fef730f19-6763-4a4f-a992-6caf579f18a5?alt=media&token=88a2b1ab-1092-423b-a5ba-a6c3a632d331
duration: "300"
promo: ""
createdAt: 1635489733083
watchersCount: 0
price: 25 EUR
commentsLast: ~
promoter: Vitali
id: 4phfHO2rZpBM8pgPusit
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
international: No
views: 3
updatedAt: 1635489733083
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
facebook: https://facebook.com/events/s/lo-de-laura-im-kunstlerhaus/153101510271689/
eventType: Party
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Tango im Künstlerhaus
online: No
styles:
  Tango:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-30T18:00:00.000Z
username: Vitali
viewsCount: 33
