venue:
  website: https://www.salsa-y-corazon.de/
  formatted_address: Zenettistraße 7, 80337 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "7"
      short_name: "7"
    - types:
        - route
      long_name: Zenettistraße
      short_name: Zenettistraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Ludwigsvorstadt-Isarvorstadt
      short_name: Ludwigsvorstadt-Isarvorstadt
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80337"
      short_name: "80337"
  url: https://maps.google.com/?cid=8616399599048238742
  name: Salsa Y Corazon - dance school
  geometry:
    viewport:
      south: 48.12187606970849
      north: 48.12457403029149
      east: 11.5593379802915
      west: 11.5566400197085
    location:
      lng: 11.557894
      lat: 48.12314479999999
  international_phone_number: +49 172 9659579
  place_id: ChIJ7SAJ9Rd3nkcRlqYWoMiZk3c
endDate:
  _seconds: 1640473200
  _nanoseconds: 0
claimed: No
organisedBy: ""
link: https://salsafreaks.splashthat.com/
description: >
  Hola liebe

  🌴SALSAFREAKS🌴

  Vielen lieben Dank für die tolle Feier am letzten Samstag, es hat mir sehr, sehr gut gefallen 🙏🏼❤️🙏🏼

  Nach Rücksprache und Absicherung mit der bayerischen Staatsregierung können wir am Samstag den 25.12. nach den Vorgaben der 2G+ Regel einen Salsa Bachata Übungsabend durchführen.


  🎄XMAS ÜBUNGSABEND🎄

  👉🏾*TEILNEHMERZAHL IST BEGRENZT *👈🏾


  Nach 15 Tage Booster Impfung ist KEIN Test nötig!


  👉🏾ES WERDEN KEINE ANTIGEN TEST MEHR BEI UNS ZUR VERFÜGUNG GESTELLT!!👈🏾

  🎄Eigene Antigen Test können unter Aufsicht vor Ort durchgeführt werden🎄

  NUR ONLINE REGISTRIERUNG, vor Ort wird nicht registriert ‼️‼️


  TESTSTATION AN DER TUMBLINGERSTR.29 / ECKE ZENETTISTR. BIS 20:00 UHR GEÖFFNET!!

  Maske von Eingang bis zur Kasse tragen

  Bitte das Impf- oder Genesen Zertifikat mit PCR oder Antigen Test an der Tür, mit Ausweis, vorzeigen.

  PCR (< 48 Std.) oder Antigen Test (< 24 Std.) 
          🌴 🌴 🌴 🌴 🌴
  WORKSHOP:

  SALSA L.A. Style Mittelstufe mit *MARION 

  Möglichst paarweise anmelden

  18 - 19 Uhr Workshop: 10€

  👇🏽Anmeldung unter:👇🏽

  Info@salsa-y-corazon.de

         🌴 🌴 🌴 🌴 🌴
  *19 - 23:45 Uhr 

  *Salsa/Bachata MIX mit DJHEC *

  Veranstalter: SALSAFREAKS 
          🌴 🌴 🌴 🌴 🌴
type: event
promo: No
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FYIbvg9vcOXbRapL8CqODDE5rQcg2%2Ff33541a4-610b-4d4d-a713-f67a9b0fe287?alt=media&token=45f4e76a-60b5-491a-a7d6-d1552b798caf
duration: "300"
createdAt: 1640026794010
watchersCount: 0
price: 10 EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2F67cY5ZIHFA32WbvUa9sp.png?generation=1640192062893251&alt=media
commentsLast: ~
promoter: Lakkana
id: 67cY5ZIHFA32WbvUa9sp
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: YIbvg9vcOXbRapL8CqODDE5rQcg2
international: No
views: 20
updatedAt: 1640026794010
website: ""
updatedBy: YIbvg9vcOXbRapL8CqODDE5rQcg2
visibility: Members
eventType: Workshop
organiser: ""
form: Yes
createdBy: YIbvg9vcOXbRapL8CqODDE5rQcg2
commentsCount: 0
name: 🎄XMAS ÜBUNGSABEND🎄
online: No
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-12-25T18:00:00.000Z
username: Lakkana
viewsCount: 38
