venue:
  website: http://www.tanzhausemotion.de/
  formatted_address: Biberger Str. 91, 82008 Unterhaching, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "91"
      short_name: "91"
    - types:
        - route
      long_name: Biberger Straße
      short_name: Biberger Str.
    - types:
        - locality
        - political
      long_name: Unterhaching
      short_name: Unterhaching
    - types:
        - administrative_area_level_3
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "82008"
      short_name: "82008"
  url: https://maps.google.com/?cid=9015721869128002009
  name: Tanzschule München Tanzhaus emotion ADTV
  geometry:
    viewport:
      south: 48.0718735697085
      north: 48.0745715302915
      east: 11.6214237802915
      west: 11.6187258197085
    location:
      lng: 11.6200113
      lat: 48.0733528
  place_id: ChIJHS2vnMnYnUcR2WkYy0VHHn0
  international_phone_number: +49 89 74329895
endDate:
  _seconds: 1637456400
  _nanoseconds: 0
organisedBy: rCBDTQtDQnaEl1Bm3LF9WE0HVvp2
claimed: Yes
description: |-
  Salsa 50% Bachata 50% und Kizomba

  Corona: 2G+
type: event
promo: Yes
duration: "300"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FrCBDTQtDQnaEl1Bm3LF9WE0HVvp2%2F894e3655-abad-4de8-9604-f90a5e82b571?alt=media&token=7b8f0649-b6eb-41e8-a90c-27cefad23f17
createdAt: 1637023560684
watchersCount: 0
price: 10€
commentsLast: ~
promoter: Sandrdida
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: 6CkwQjJcMxOskFl79xFs
promotedBy: rCBDTQtDQnaEl1Bm3LF9WE0HVvp2
international: No
views: 15
updatedAt: 1637023560684
updatedBy: rCBDTQtDQnaEl1Bm3LF9WE0HVvp2
visibility: Public
facebook: Sandra Dida
confirmation: ""
eventType: Party
organiser: ""
form: No
createdBy: rCBDTQtDQnaEl1Bm3LF9WE0HVvp2
commentsCount: 0
name: Noche de Emoción Latina in Unterhaching
online: No
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-20T20:00:00.000Z
username: Sandrdida
viewsCount: 22
