venue:
  formatted_address: Landsberger Str. 18, 80339 München, Germany
  website: http://www.salsacubaclub.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "18"
      short_name: "18"
    - types:
        - route
      long_name: Landsberger Straße
      short_name: Landsberger Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Schwanthalerhöhe
      short_name: Schwanthalerhöhe
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80339"
      short_name: "80339"
  url: https://maps.google.com/?cid=13465701088836487314
  name: Salsa Cuba Club
  geometry:
    viewport:
      south: 48.13810136970851
      north: 48.14079933029151
      east: 11.5472657802915
      west: 11.5445678197085
    location:
      lng: 11.5459098
      lat: 48.13950500000001
  international_phone_number: +49 179 5456322
  place_id: ChIJKTBBsgF2nkcRkoiww8vH37o
endDate:
  _seconds: 1636074000
  _nanoseconds: 0
claimed: No
organisedBy: ""
link: https://salsaclub-munich.de/course.php?kid=114
description: |-
  Social Dancing ab 21.00 Uhr

  * Cocktails & Longdrings
  * NYC Dance sounds DJ Hakan & Manu

  Teilnahme:
  - nur mit einer Voranmeldung möglich !
  - 3G Regel ( genesen, geimpft, getestet) Alle Arten von Tests sind zugelassen.
  - Nachweis an der Tür oder vorab per Mail möglich !
type: event
duration: "300"
cover: ""
createdAt: 1634057680270
watchersCount: 0
price: 10 EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FLgoA0sH8mFxtomKJze8L.png?generation=1634379768689290&alt=media
commentsLast: ~
promoter: Vitali
id: 6LDEOoaaBLZLsmCNCGlM
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
international: No
views: 26
updatedAt: 1634057680270
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Party
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Mambo Social @ Salsa Club Munich
online: No
styles:
  SalsaNewYork:
    level: Interested
    highlighted: false
    selected: true
  Mambo:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-04T20:00:00.000Z
username: Vitali
viewsCount: 73
