endDate:
  _seconds: 1636160400
  _nanoseconds: 0
claimed: Yes
organisedBy: GOiMAEyBEZXKlHSYBAhfAg3RfDB3
link: http://www.bachata-sensual.party
description: >-
  Die Bachata Open Air Parties gehen weiter: die beste Musik, die besten Tänzer,
  die besten Locations innendrin.


  Vamos a dentro, chicos!


  Heiß, heißer, Herbst 2021! Der Sommer ist vorbei aber unsere Hüften schwingen weiter. Die heißesten Bachata Beats der Stadt gibt es jetzt jeden Freitag ab dem 24. September. Der Salsa Club Munich, einer der schönsten Locations im Herzen Münchens, wartet auf Euch. Vorbei sind die Zeiten mit Steinboden, Regen und Non-Tänzer, wir sagen: hallo Tanzparkett! Im Tanzherbst geboten: Von Bachata Sensual, über Dominicana bis hin zu Bachata Moderna (und vielleicht sogar etwas Salsa).


  Wir freuen uns auf euch!


  COVID INFO:


  DE


  Solltest du weder geimpft , genesen oder negativ getestet sein, ist der Einlass nicht gestattet, wir bitten um dein Verständnis.


  Aufgrund des Corona-Hygienekonzepts & der laufenden Verordnungen sind limitierte Tickets verfügbar.


  Wir freuen uns über deinen Ausweis/Reisepass und die notwendigen Dokumente, die deine Impfung / Genesung / negativ Test belegen.


  EN


  If you are not vaccinated , recovered or tested there is no entry permitted, we appreciate your understanding.


  Limited tickets available due to the corona hygiene concept & ongoing regulations.


  We would appreciate your ID, passport, and necessary documents that prove your vaccination & recovery or tested ready at the door.


  ![](https://uploads.tickettailor.com/c_limit,w_630/v1/production/userfiles/event_description_image_105946_1634544056_45bd9.png)


  ![](https://uploads.tickettailor.com/c_limit,w_630/v1/production/userfiles/event_description_image_105946_1633263046_91f33.jpg)


  ![](https://uploads.tickettailor.com/c_limit,w_630/v1/production/userfiles/event_description_image_105946_1633263642_62f1a.jpg)


  <w-teaser

  title="TICKETS SALE OPEN NOW"

  description="You can buy the tickets now on www.bachata-sensual.party"

  button="GET TICKETS"

  href="https://www.tickettailor.com/events/bachatasensualnight/596579/">

  </w-teaser>
type: event
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FGOiMAEyBEZXKlHSYBAhfAg3RfDB3%2Fa76db6ec-2a5a-41df-85a8-16ff85d2ea59?alt=media&token=4a11720d-77e8-4879-abcd-fecb48d5693a
duration: "300"
createdAt: 1634544361668
watchersCount: 0
price: 10EUR
commentsLast: ~
promoter: Djobi_bachata
promotedBy: GOiMAEyBEZXKlHSYBAhfAg3RfDB3
id: 7CnwSYK6SJrl2R4pIjVT
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 30
updatedAt: 1634544361668
website: https://www.bachata-sensual.party
updatedBy: GOiMAEyBEZXKlHSYBAhfAg3RfDB3
visibility: Public
confirmation: "Thank you for registering. "
eventType: Party
organiser: Djobi_bachata
form: No
createdBy: GOiMAEyBEZXKlHSYBAhfAg3RfDB3
commentsCount: 0
name: Bachata Sensual Night Dj Obi
online: No
styles:
  Bachata:
    level: Interested
    selected: true
  Salsa:
    level: Interested
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-05T20:00:00.000Z
username: Djobi_bachata
viewsCount: 38
