endDate:
  _seconds: 1638471600
  _nanoseconds: 0
claimed: No
organisedBy: ""
description: |-
  Ablauf:

  19:30 Uhr: Salsa Ladies Styling (Mittelstufe)

  20:15 Uhr: Salsa Men Styling (Mittelstufe)

  21:00 Uhr: Salsa Cubana Figuren (Open Level)

  Jeder Kurs dauert(every Course lasts): 30 Minuten

  Kosten: 5€ / Kurs

  Registrierung:

  joyccedancer@gmail.com

  diamaryssarabaza@yahoo.es


  Zahlung: Bank/PayPal

  Joycce Vasallo Martinez

  IBAN: Auf Anfrage

  PayPal: joyccedancer@gmail.com


  <w-youtube url="https://www.youtube.com/watch?v=GRvSBcKgmVw"></w-youtube>
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FdTkY7Qsrz8OxZQ3GW2ShP5BFV282%2F03ec4eaa-4780-4cf3-bdc7-b78dc66ab518?alt=media&token=498d5e68-cdb2-406f-9459-d7d12de46303
promo: Yes
duration: "30"
createdAt: 1638117016391
watchersCount: 0
price: 5EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2F7FQUFpRcHKA94hwcmtVz.png?generation=1638381796640947&alt=media
commentsLast: ~
promoter: VladimirCuba
promotedBy: dTkY7Qsrz8OxZQ3GW2ShP5BFV282
id: 7FQUFpRcHKA94hwcmtVz
place: ""
international: Yes
views: 10
updatedAt: 1638117016391
updatedBy: dTkY7Qsrz8OxZQ3GW2ShP5BFV282
visibility: Public
facebook: https://fb.watch/9z2GjBKflU/
eventType: Course
organiser: ""
form: No
createdBy: dTkY7Qsrz8OxZQ3GW2ShP5BFV282
commentsCount: 0
name: Joycce Salsa Cubana Clubs (online via invitation)
online: Yes
styles:
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
startDate: 2021-12-02T18:30:00.000Z
username: VladimirCuba
viewsCount: 14
