venue:
  formatted_address: Bundesallee 31A, 10717 Berlin, Germany
  website: http://www.axelhotels.com/int/two-hotel-berlin/hotel.html
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: 31A
      short_name: 31A
    - types:
        - route
      long_name: Bundesallee
      short_name: Bundesallee
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Bezirk Charlottenburg-Wilmersdorf
      short_name: Bezirk Charlottenburg-Wilmersdorf
    - types:
        - locality
        - political
      long_name: Berlin
      short_name: Berlin
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Berlin
      short_name: Kreisfreie Stadt Berlin
    - types:
        - administrative_area_level_1
        - political
      long_name: Berlin
      short_name: BE
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "10717"
      short_name: "10717"
  url: https://maps.google.com/?cid=12289175319981191059
  name: TWO Hotel Berlin by Axel
  geometry:
    viewport:
      south: 52.4890163197085
      north: 52.4917142802915
      east: 13.3320615302915
      west: 13.3293635697085
    location:
      lng: 13.330592
      lat: 52.4903594
  place_id: ChIJm541YF9QqEcRk-_5udfri6o
  international_phone_number: +49 30 767589370
endDate:
  _seconds: 1636236000
  _nanoseconds: 0
claimed: Yes
organisedBy: sXlqPDGz2HdSX02QOyZxkte4iF22
link: https://h5hfts3h1e4.typeform.com/to/oPWkRVhQ
description: DJ Fabinho FM and DJ Eddythegun playing the best Latin hits for you
  in a Rooftop location where you can enjoy some gorgeous views and while
  drinking fresh Peruvian Cocktails
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FsXlqPDGz2HdSX02QOyZxkte4iF22%2F45dc1e8e-63c7-4a5b-bf22-65813a7b6788?alt=media&token=a7cf18b5-3390-4143-bcc1-72c8b10de8e5
duration: "300"
createdAt: 1635793535265
watchersCount: 0
price: 5EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2F7VYWjqB92ybRfVhCh8XK.png?generation=1635793900205900&alt=media
commentsLast: ~
promoter: barriolatinoberlin
place: ChIJAVkDPzdOqEcRcDteW0YgIQQ
id: 7VYWjqB92ybRfVhCh8XK
promotedBy: sXlqPDGz2HdSX02QOyZxkte4iF22
international: No
views: 4
updatedAt: 1635793535265
website: https://barriolatinoberlin.mystrikingly.com/
updatedBy: sXlqPDGz2HdSX02QOyZxkte4iF22
visibility: Public
eventType: Party
organiser: barriolatinoberlin
form: Yes
createdBy: sXlqPDGz2HdSX02QOyZxkte4iF22
commentsCount: 0
name: Latin Rooftop Party
online: No
styles:
  Cumbia:
    level: Interested
    highlighted: false
    selected: true
  Afrobeats:
    level: Interested
    highlighted: false
    selected: true
  Merengue:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Reggaeton:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Berlin
  location:
    country: Germany
    latitude: 52.52000659999999
    locality: Berlin
    usedGps: false
    place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
    longitude: 13.404954
startDate: 2021-11-06T17:00:00.000Z
username: barriolatinoberlin
viewsCount: 74
