endDate:
  _seconds: 1635008400
  _nanoseconds: 0
type: event
promo: Yes
duration: "180"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FqTPAP7OhWMYjtoPXtpUJavNz5Fr2%2F13076a64-f0b3-4af9-accc-721fa10f9a2b?alt=media&token=99884f18-0ea1-4fce-8b12-70435dedb8c7
createdAt: 1632871991777
watchersCount: 0
price: "39"
commentsLast: ~
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: 895JOkdUPXhLMvpqTL58
views: 1
updatedAt: 1632871991777
updatedBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
visibility: Public
eventType: Workshop
organiser: lakossa
form: No
createdBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
commentsCount: 0
name: Ben Skin mit Live Percussion & Afrobeats Dance Workshop
online: No
styles:
  Afrobeats:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-23T14:00:00.000Z
username: lakossa
viewsCount: 55
