endDate: 2021-11-12T21:00:00.000Z
claimed: No
organisedBy: ""
link: https://www.eventbrite.de/e/brazilian-weekend-2021-samba-de-gafieira-forro-zouk-workshopsparty-tickets-192659077487
description: >+
  

  Brazilian Weekend


  Wir wollen 11 Jahre “Tanze samba mit mir “ feiern!!! Keine runde Zahl, aber das Leben läuft auch nicht immer rund.Denn Corona hat uns letztes Jahr einen Strich durch die Rechnung gemacht und jegliche Feiern verhindert. Um so mehr wollen wir die Chance das nachzuholen nutzen. - Natürlich mit euch gemeinsam! Workshops mit professionellen Tanzlehrern aus Brasilien und eine Party mit Live Musik und DJ erwarten euch an einem Wochenende an dem wir ein Stück Brasilien nach München bringen in dieser schweren Zeit.


  Mit dabei:


  Tanzlehrer - Dadinho und Kelly , Carlos Frevo , Hugo Silva, Isaac Douglas, Noemia 


  DJ - Hugo Silva , Galaxi


  Musiker - Vando Oliveira 



  Für den Einlass ist ein gültiger Nachweis nach der 3G plus-Regelung erforderlich: genesen, geimpft, getestet (nur PCR!).


  Interim-Programm

  Unser Programm ist noch in Arbeit - das endgültige Programm wird in Kürze veröffentlicht. Änderungen vorbehalten… 


  11.11  Donnerstag Tanzen im Park 


  Donnerstag bein schönem Wetter:

  Wir begrüßen alle, die einen Tag vorher nach München kommen wollen, mit einem kleinen Warm-Up: „Tanzen im Park“. Wir möchten mit euch am überdachten Dianatempel einen gemütlichen Herbstabend genießen.

  Kommt alle und tanzt euch warm!

  Was: Tanzen Draußen / Samba, Forró  und Zouk no parque

  Wo: Dianatenpel  im Hofgarten am Odeonsplatz


  Programm.

  19:00-22:00 Frei Tanzen ( Samba Forró und Zouk)

      ---------------///-----------------

  12.11 Freitag "Eine Nacht in Brasilien"


  Programm:

  17:00-18:00 Anmeldung 

  18:00 -22:30 Workshops ( Samba , Forró und Zouk)

  Ab 22:30 Party “Eine Nacht in Brasilien”

  mit Live Musik und DJs Hugo und Galaxi

      ---------------///-----------------

  13.11 Samstag


  Programm

  13:00-14:00 Uhr  Anmeldung 

  14:00-19:00 Workshops ( Samba , Forró und Zouk)

  Ab 22:30 Black & White Party

  mit Tanz Show und DJs Hugo und Galaxi


  Tickets Kaufen 

  https://www.eventbrite.de/e/192659077487/
   
  ------------------------------------
                       Englisch
  ------------------------------------


  Brazilian Weekend


  We want to celebrate 11 years "Tanze Samba mit mir "!!! Not the usual number for an anniversary but it hasn't been a usual year, right? Because Corona caused us lots of trouble and didn`t allow us to celebrate.So know that we have the chance to make up for it, we are using it. And we want you to join us! Workshops with professional dance teachers from Brazil and a party with live music and DJ await you on a weekend where we bring a piece of Brazil to Munich in this difficult time.


  With us:

  Dance teacher - Dadinho und Kelly , Carlos Frevo , Hugo Silva, Isaac Douglas, Noemia 

  DJ - Hugo Silva , Galaxi

  Musician - Vando Oliveira


  For admission, a valid proof according to the 3G plus regulation is required: recovered, vaccinated, tested (PCR only!).



  Interim Program

  Our program is still in progress - the final program will be published soon. Subject to change... 


  11.12 Thursday Dancing in the Park 

  Thursday with nice weather:

  We welcome all who want to come to Munich one day before with a little warm-up: "Dancing in the Park". We would like to enjoy a cozy autumn evening with you at the covered Dianatempel.

  Come on everybody and warm up!

  What: Dancing outside / Samba, Forró and Zouk no parque

  Where: Dianatenpel in the Hofgarten at Odeonsplatz


  Program.

  19:00-22:00 Free Dancing ( Samba Forró and Zouk


  ---------------///-----------------


  12.11 Friday "A Night in Brazil"


  Program:

  17:00-18:00 Registration 

  18:00 -22:30 Workshops ( Samba , Forró and Zouk)

  From 22:30 Party "A Night in Brazil

  with live music and DJs Hugo and Galaxi

     ---------------///-----------------

  13.11 Saturday


  Program

  13:00-14:00 Registration 

  14:00-19:00 Workshops ( Samba , Forró and Zouk)

  From 22:30 Black & White Party

  with dance show and DJs Hugo and Galaxi


  Buy tickets :

  https://www.eventbrite.de/e/192659077487/


  --------------------------------------
                     portuguiesisch 
  --------------------------------------


  Brazilian Weekend


  Queremos celebrar 11 anos de "Tanze Samba mit mir"!!! Não é o número habitual para comemorarmos um aniversário, mas não tem sido um ano habitual, certo? Porque a Corona causou-nos muitos problemas e não nos permitiu celebrar. Por isso, sabendo que temos a oportunidade de o compensar, estamos a usá-lo. E queremos que se junte a nós! Workshops com professores de dança e profissionais maravilhosos  do Brasil e da Europa , festa com música ao vivo e DJ esperam voces  num fim-de-semana em que vamos tentar trazer pra voces um pedaço do Brasil para Munique, atravez da musica , da culinaria , da danca e tudo isso com muita a alegria  e o calor que acredito todos queremos neste momento difícil para todos nós .


  Vao estar com a gente :


  Professor de dança - Dadinho und Kelly , Carlos Frevo , Hugo Silva, Isaac Douglas, Noemia


  DJ - Hugo Silva , Galaxi


  Músico - Vando Oliveira


  Para participar  é necessária uma prova válida de acordo com o regulamento 3G plus: recuperada, vacinada, testada (apenas PCR!).



  Programa Provisório

  O nosso programa ainda está em curso - o programa final será publicado em breve. Ainda sujeito a alterações...


  11.12 Quinta-feira Dançando no Parque


  Quinta-feira com bom tempo:

  Damos as boas-vindas a todos os que desejem vir a Munique um dia antes com um pouco de aquecimento: "Dançando no Parque". Gostaríamos de desfrutar de uma noite aconchegante de Outono convosco no Dianatempel coberto.

  Venham todos e aqueçam-se!

  O quê: Dançando fora / Samba, Forró e Zouk no parque

  Onde: Dianatenpel no Hofgarten em Odeonsplatz


  Programa
   19:00-22:00 Samba Forró und Zouk no Parque 

       ---------------///-----------------

  12.11 de sexta-feira "Uma Noite no Brasil

  Programa:

  17:00-18:00 Inscrição

  18:00 -22:30 Workshops ( Samba , Forró e Zouk)

  A partir das 22:30 Festa "Uma Noite no Brasil

  com música ao vivo e DJs Hugo e Galaxi

     ---------------///-----------------

  13.11 Sábado

  Programa

  13:00-14:00 Inscrição

  14:00-19:00 Workshops ( Samba , Forró e Zouk)

  A partir das 22:30 Black & White Party

  com espectáculo de dança e DJs Hugo e Galaxi

  Comprar bilhetes :


  https://www.eventbrite.de/e/192659077487/





type: event
promo: ""
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2F430da6c2-6430-45c0-a3fe-b041141a7469?alt=media&token=e528f2e9-4982-48ef-84c3-0809c666a024
createdAt: 1635100194368
watchersCount: 0
price: 60-110 EUR
commentsLast: ~
promoter: Vitali
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
id: 8lMYQXuyRvyPQv6VsL15
international: No
views: 16
updatedAt: 1635100194368
website: https://www.tanzesamba.de/2021/10/brazilian-weekend-save-the-date-12-13-november-2021/
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
facebook: https://facebook.com/events/s/brazilian-weekend/1220716965120105/
eventType: Festival
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: "Brasilianisches Wochenende "
online: No
styles:
  ForroLove:
    level: Interested
    highlighted: false
    selected: true
  BrazilianZouk:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-12T17:00:00.000Z
username: Vitali
viewsCount: 27
