venue:
  website: http://www.sonlatino.de/
  formatted_address: Gablonzer Str. 9, 76185 Karlsruhe, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "9"
      short_name: "9"
    - types:
        - route
      long_name: Gablonzer Straße
      short_name: Gablonzer Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Mühlburg
      short_name: Mühlburg
    - types:
        - locality
        - political
      long_name: Karlsruhe
      short_name: Karlsruhe
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Karlsruhe
      short_name: Kreisfreie Stadt Karlsruhe
    - types:
        - administrative_area_level_2
        - political
      long_name: Karlsruhe
      short_name: KA
    - types:
        - administrative_area_level_1
        - political
      long_name: Baden-Württemberg
      short_name: BW
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "76185"
      short_name: "76185"
  url: https://maps.google.com/?cid=8926798613940117231
  name: Son Latino Dance Studio
  geometry:
    viewport:
      south: 49.02229426970851
      north: 49.02499223029151
      east: 8.354233980291502
      west: 8.351536019708497
    location:
      lng: 8.352825700000002
      lat: 49.0236634
  international_phone_number: +49 721 6638886
  place_id: ChIJ12tDlScHl0cR755ZDQtc4ns
endDate: 2021-08-22T01:00:00.000Z
link: https://forms.gle/nGsDK5tGfQ59VVix6
description: >-
  DANSECRECY meets Son Latino - Bachata Workshops und Übungsabend


  WS1 (20:00-20:45) - Bachata Sensual lernen mit Martin & Esra 


  WS2 (20:50-21:35) - Bachata Fusion mit Migo & Rebeca (Munich)


  Niveau: Open Level


  Übungsabend (21:45-3:00) mit DJ Milad (Stuttgart) - Bachata & Salsa (ca. 80:20)


  Hygienekonzept vorhanden unter Berücksichtigung der aktuellen CoronaVO. Einlass kann nur unter Einhaltung von 3G (Genesen, Getestet, Geimpft) erfolgen. 


  Weitere Informationen via Instagram @flo.oteca 


  Änderungen und Irrtümer vorbehalten.
type: event
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FTv49tJF9gQbN5et4IAsF4Hlg8V63%2Fa2a599b4-be3e-4551-8668-be822d1e6a94?alt=media&token=62c6ad44-6efb-4f7b-b220-1e9b07ee8dde
duration: custom
createdAt: 1628756206001
watchersCount: 0
price: 17EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2F8P6bb9ghcyKtUgcmI78D.png?generation=1628756584874935&alt=media
commentsLast: ~
id: 8P6bb9ghcyKtUgcmI78D
place: ChIJCXjgokgGl0cRf-63THNV_LY
views: 7
updatedAt: 1628756206001
updatedBy: Tv49tJF9gQbN5et4IAsF4Hlg8V63
visibility: Public
eventType: Party
organiser: Flo.Oteca
form: Yes
createdBy: Tv49tJF9gQbN5et4IAsF4Hlg8V63
commentsCount: 0
name: DANSECRECY Bachata Karlsruhe
online: No
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Karlsruhe
  location:
    country: Germany
    latitude: 49.0068901
    locality: Karlsruhe
    usedGps: false
    place_id: ChIJCXjgokgGl0cRf-63THNV_LY
    longitude: 8.4036527
startDate: 2021-08-21T18:00:00.000Z
username: Flo.Oteca
viewsCount: 54
