city: ""
endDate:
  _seconds: 1613847600
  _nanoseconds: 0
description: >-
  Hi I'm Carlos Armando, some of you already know me! I hope you had fun at the
  SINGLE STEPS BACHATA CLASS. 


  Now I'm offering a free bachata class for couples intermediate level this February 20th with the intention to forget a little bit about all this CORONA VIRUS for a moment.


  📛 I hope you can be there and see you that day with a lot of good vibes! 📛

   It will be broadcast on ZOOM and you can get the link 5 minutes before asking via PM in the next instagram account ( @soycarlosarmando)

  ✅ EVERYONE IS WELCOME TO TAKE IT! ✅ 
   
  DATE: Saturday 20 February 19:00 IG ACC: www.instagram.com/soycarlosarmando
type: event
duration: 60
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FjhgbKgGQR0T3M7m2riKwPGE2SFO2%2F3a459706-1541-4da0-8750-d014731cdd9a?alt=media&token=abbf87b0-b232-4fcd-a38d-e661446a0b24
createdAt: 1611835066047
watchersCount: 0
price: FREE
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2F9AuoTSnD1SEBv0SPlkiN.png?generation=1613152389820048&alt=media
commentsLast: ~
id: 9AuoTSnD1SEBv0SPlkiN
views: 1
updatedAt: 1611835066047
updatedBy: jhgbKgGQR0T3M7m2riKwPGE2SFO2
address: ONLINE
visibility: Public
viewsCount: 1
eventType: Course
organiser: Carlos Armando
form: No
createdBy: jhgbKgGQR0T3M7m2riKwPGE2SFO2
commentsCount: 0
name: Bachata FREE class
styles:
  Bachata:
    level: Interested
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
startDate: 2021-02-20T18:00:00.000Z
username: Carrenomtz
