endDate:
  _seconds: 1637431200
  _nanoseconds: 0
organisedBy: ""
claimed: No
link: https://cspberlin.com/son-cubano-workshop/
description: >
  SON CUBANO WORKSHOP

  Mit Leivan & Julia

  Sa, 20.11.2021 17:00 – 19:00 Uhr


  In diesem zwei-stündigen Workshop beschäftigen wir uns im ersten Teil mit dem Rhythmusverständnis, Grundschritten und Varianten sowie der geschlossenen und offenen Haltung als Tanzpaar. Ihr lernt hierbei auf was ihr im Führen und Führen lassen beachten müsst.  

  Im zweiten Teil erarbeiten wir Drehungen und Son-Figuren mit typischen Gesten sowie eine Kombination aus diesen Elementen im Paartanz.


  Der Son Cubano gilt als „Mutter“ vieler Rhythmen Kubas und wichtigster Ursprung für den Casino/Salsa. Als Musik- und Tanzgenre ist es Ende des 19. Jahrhunderts entstanden. 


  ORT: TRYBE DANCE STUDIO, Berlin

  OPEN LEVEL


  PREISE:         30,00 Euro     EARLYBIRD
                  35,00 Euro     danach
  Studentenrabatt -5€


  *Nur mit VORANMELDUNG über unsere Website: cspberlin.com


  WICHTIGER HINWEIS:

  Im Studio sind Straßenschuhe nicht gestattet. Bitte bringt Wechselschuhe mit :-)

  ES GELTEN DIE 3-G REGELN


  DOZENTEN

  Leivan García Valle ist erster Solist, Lehrer und Choreograf des Conjunto Folklórico Nacional de Cuba mit Sitz in Havanna. Seit 11 Jahren tanzt und choreografiert er für die Company auf nationaler und internationaler Ebene. Unter anderem wurde er mit dem Premio Nacional de Danza (Nationalpreis Kubas) für seine Rumba-Inszenierung "En mi patio" ausgezeichnet. Er ist Dozent des Folkuba, welches zweimal jährlich für Kubaner und Ausländer als Fortbildung in Yoruba- und Congo-Tänzen sowie Bailes Populares (Cha-cha-cha, Mambo, Son, Rumba und Casino) angeboten wird.


  Julia von Oy ist Tänzerin, Tanzlehrerin und Choreographin und lebt und arbeitet in Berlin und Havanna. Ihre Ausbildung machte sie teils in Berlin, Barcelona und teils auf Kuba und nahm dort an nationalen und internationalen Tanzprojekten teil. Julia widmete sich intensiv dem afrokubanischen Folklore, der Salsa Cubana und zeitgenössischen Tanz. Seit über 4 Jahren arbeitet sie bei Cuban Salsa Power Berlin.

  Die Stunde ist also perfekt für dich wenn du andere kubanische Tänze kennen lernen möchtest.
type: event
promo: Yes
duration: "120"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FpH0880yoosdst2YzH0t6hvWMmi63%2F9b7bc8c0-325a-4780-a852-079aa933324e?alt=media&token=ff176114-61e1-4dad-9f81-dd76c50d8ea6
createdAt: 1635765760910
watchersCount: 0
price: from 25
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2F9gdm403Ik2Lxb1ONFiW0.png?generation=1635766823692014&alt=media
commentsLast: ~
promoter: Juli
place: ChIJAVkDPzdOqEcRcDteW0YgIQQ
id: 9gdm403Ik2Lxb1ONFiW0
promotedBy: pH0880yoosdst2YzH0t6hvWMmi63
international: No
views: 8
updatedAt: 1635765760910
website: https://cspberlin.com
updatedBy: pH0880yoosdst2YzH0t6hvWMmi63
visibility: Public
facebook: julia.vonoy
eventType: Workshop
organiser: ""
form: Yes
createdBy: pH0880yoosdst2YzH0t6hvWMmi63
commentsCount: 0
name: SON CUBANO WORKSHOP Mit Leivan & Julia
online: No
styles:
  Son:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Berlin
  location:
    country: Germany
    latitude: 52.52000659999999
    locality: Berlin
    usedGps: false
    place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
    longitude: 13.404954
startDate: 2021-11-20T16:00:00.000Z
username: Juli
viewsCount: 53
