venue:
  formatted_address: Oudenarder Str. 16-20, 13347 Berlin, Germany
  website: https://www.tanzraum-berlin.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: 16-20
      short_name: 16-20
    - types:
        - route
      long_name: Oudenarder Straße
      short_name: Oudenarder Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Mitte
      short_name: Mitte
    - types:
        - locality
        - political
      long_name: Berlin
      short_name: Berlin
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Berlin
      short_name: Kreisfreie Stadt Berlin
    - types:
        - administrative_area_level_1
        - political
      long_name: Berlin
      short_name: BE
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "13347"
      short_name: "13347"
  url: https://maps.google.com/?cid=12871345234978269182
  name: Tanzraum Wedding
  geometry:
    viewport:
      south: 52.55170091970849
      north: 52.55439888029149
      east: 13.3615986802915
      west: 13.3589007197085
    location:
      lng: 13.360076
      lat: 52.5530629
  place_id: ChIJ2Wd0Uw5TqEcR_udLwEs0oLI
  international_phone_number: +49 173 6020040
endDate:
  _seconds: 1636308000
  _nanoseconds: 0
claimed: Yes
organisedBy: pH0880yoosdst2YzH0t6hvWMmi63
link: https://cspberlin.com/afrocuban/
description: >-
  AFROKUBANISCHE TÄNZE

  ab Sonntag 3.10

  17:00 - 18:00 Uhr (BEGINNER)

  18:00 - 19:00 Uhr (MIT VORKENNTNISSEN)


  Wir beschäftigen wir uns mit den afrokubanischen Yoruba-Tänzen, wobei wir uns sowohl den femininen Orishas, als auch den maskulinen Orishas widmen. Wir werden die verschiedenen Schritte und die Gestik der Orisha-Tänze (Gottheiten) zu den jeweiligen toques und cantos (Gesang) kennen lernen.

  Yemaya verkörpert beispielsweise die universelle Schöpfung, die Geburt und das Wassers. Ochún steht für Fruchtbarkeit, Liebe und Fröhlichkeit. Ihre Bewegungen sind weich und verführerisch. Oya, Ogún und Shango sind Krieger-Orisha, stark und kämpferisch.


  [BEGINNER]

  In der ersten Stunde ist das Hauptziel die Vermittlung der Grundschritte und Grundhaltung (Yoruba-Technik). Wir erlernen unter anderem die generischen Schritte, die alle Orisha-Tänze gemeinsam haben. Dieser Kurs eignet sich auch als Vertiefung und Festigung der Yoruba-Technik!

  [TÄNZER MIT VORKENNTNISSEN]

  Die Yoruba-Tänze besitzen einen starken theatralischen Charakter. Wir beschäftigen uns in der zweiten Stunde deshalb intensiver mit den Gestiken und der Mimik des jeweiligen Orishas im Tanz. Ihr erlernt komplexere Schrittkombinationen und Armbewegungen zu den jeweiligen toques sowie Schrittvariationen
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FpH0880yoosdst2YzH0t6hvWMmi63%2F34afd342-b916-4963-acbb-06d80380d0d7?alt=media&token=585531df-082b-4aa3-8687-01b36481926d
duration: "120"
promo: Yes
createdAt: 1635771368582
watchersCount: 0
price: 13,50
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2Fa6VfxIvsEeXr2W40kuTp.png?generation=1636222494211939&alt=media
commentsLast: ~
promoter: Juli
place: ChIJAVkDPzdOqEcRcDteW0YgIQQ
id: a6VfxIvsEeXr2W40kuTp
promotedBy: pH0880yoosdst2YzH0t6hvWMmi63
international: No
views: 7
updatedAt: 1635771368582
website: https://cspberlin.com/afrocuban/
updatedBy: pH0880yoosdst2YzH0t6hvWMmi63
visibility: Public
eventType: Course
organiser: Juli
form: No
createdBy: pH0880yoosdst2YzH0t6hvWMmi63
commentsCount: 0
name: AFROKUBANISCHE TÄNZE (Yoruba) mit Leivan und Julia
online: No
styles:
  RumbaGuaguanco:
    level: Interested
    highlighted: false
    selected: true
  RumbaYambu:
    level: Interested
    highlighted: false
    selected: true
  RumbaColumbia:
    level: Interested
    highlighted: false
    selected: true
  Casino:
    level: Interested
    highlighted: false
    selected: true
  RuedaDeCasino:
    level: Interested
    highlighted: false
    selected: true
  Afro:
    level: Interested
    highlighted: true
    selected: true
region:
  name: Berlin
  location:
    country: Germany
    latitude: 52.52000659999999
    locality: Berlin
    usedGps: false
    place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
    longitude: 13.404954
startDate: 2021-11-07T16:00:00.000Z
username: Juli
viewsCount: 14
