updatedBy: kGDD595byJY19rMbUCDsmFtvPDq2
address: "Pinakothek der Moderne "
visibility: Public
endDate: 2021-07-29T21:00:00.000Z
eventType: Party
type: event
duration: custom
createdAt: 1627388417402
watchersCount: 0
form: No
createdBy: kGDD595byJY19rMbUCDsmFtvPDq2
commentsCount: 0
name: "Salsa Party "
online: No
commentsLast: ~
styles:
  Salsa:
    level: Interested
    highlighted: false
    selected: true
id: ahShgXjBRpBgy6aH8xj3
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-07-29T17:00:00.000Z
views: 1
username: Salseros_y_Companeros
updatedAt: 1627388417402
viewsCount: 47
