endDate:
  _seconds: 1628348400
  _nanoseconds: 0
description: >-
  Learn Casino (Salsa Cubana) basics in 1 month.


  - **Price:** free, optional donation

  - **Duration:** course includes 4 lessons, 1h every Saturday


  ### Course Program


  - **Lesson 1. Introduction to rhythm and basic steps**

  - Lesson 2. Partner work and turns

  - Lesson 3. Cross-body lead

  - Lesson 4. First choreography



  ### Instructor


  <w-profile username="Guantanamero"></w-profile>



  ### Reviews


  > Viktoria: Alex gives a great Salsa lesson for very beginners. I can highly recommend it, because he teaches not only basic steps, but gives a lot of information about Salsa. The atmosphere is very friendly and relaxing. 

  I will definitely take more lessons with Alex as soon as I am back in Munich.


  > Masha: Montuno Club is the perfect place to start learning salsa - even for the real beginners with no dancing skills. Alexey is giving as much staff as needed so that you don't get bored, but also don't get overwhelmed. It's a very nice and friendly atmosphere here. As a nice bonus, Alex gives his best not only to teach you salsa, but also to introduce the salsa/dance world of Munich to you and connect all dancers together within a community. He also arranges rueda evenings where people with different knowledge and skills get togetger and enjoy dancing. As a bonus #2, you learn a bit of Spanish 🙂 I strongly recommend Montuno club for everyone who would like to start dancing/keep dancing 🙂


  [See all reviews on Facebook](https://www.facebook.com/montunoclub/reviews/)
type: event
duration: "60"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2Fef717276-b15e-4b8f-a3c6-395de9fce30b?alt=media&token=51f72e98-29e1-431e-a413-217f974d6a6e
createdAt: 1627228515311
watchersCount: 0
price: FREE
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FakRrVjMYXoAAl8u6xdxu.png?generation=1628363336972618&alt=media
commentsLast: ~
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: akRrVjMYXoAAl8u6xdxu
views: 2
updatedAt: 1627228515311
address: Pinakothek der Moderne
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
visibility: Public
eventType: Course
form: No
createdBy: ICpCp7IBpMe30vAHqYfw4FmQp382
commentsCount: 0
name: Salsa Cubana from Zero 1/4
online: No
styles:
  Salsa:
    level: Interested
    highlighted: false
    selected: true
  Casino:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-08-07T14:00:00.000Z
username: MontunoClub
viewsCount: 60
