endDate:
  _seconds: 1630778400
  _nanoseconds: 0
link: la-kossa.eventbrite.com
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FqTPAP7OhWMYjtoPXtpUJavNz5Fr2%2F13076a64-f0b3-4af9-accc-721fa10f9a2b?alt=media&token=99884f18-0ea1-4fce-8b12-70435dedb8c7
promo: Yes
duration: "180"
createdAt: 1629286986639
watchersCount: 0
price: "39"
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FB3u9SRSWtMNKWihq8BSU.png?generation=1629287016310803&alt=media
commentsLast: ~
id: B3u9SRSWtMNKWihq8BSU
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 1
updatedAt: 1629286986639
updatedBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
visibility: Public
eventType: Workshop
organiser: lakossa
form: Yes
createdBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
commentsCount: 0
name: Bikutsi mit Live Percussion und Ndombolo Workshop
online: No
styles:
  Afrobeats:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-09-04T15:00:00.000Z
username: lakossa
viewsCount: 26
