endDate: 2021-05-10T07:00:00.000Z
link: https://бачата-сальса.рф/shinefest
description: >-
  Друзья! 7-10 мая в Москве состоится уникальное и масштабное событие SHINE
  BACHATA FESTIVAL, завершит которое наш любимый Open-Air Sensual
  Bachata/Kizomba open Dj Zhdan-of


  Почему тебе обязательно понравится:


  💫 Встречи друзей и новые знакомства

  💛 24 часа вечеринок

  💫 Конкурсы и шоу программа

  💛 3 дня мастер-классов по бачате

  💫 Красивые фото и видео после вечеринок

  💛 700 гостей из разных городов России

  💫 Легендарная концертная площадка Известия Hall

  💛 Более 100 преподавателей вместе с нами


  Билеты и подробности на сайте 👉 https://бачата-сальса.рф/shinefest


  По промокоду OPEN скидка


  Бачата фестиваль в Москве

  https://xn----7sbaabab9f7bcf2dyd.xn--p1a…
type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FErP9WITL4eMyf36LQ5iR9nCAIJ82%2F888a1840-dd1d-4ce8-bcc8-a5105f6e176a?alt=media&token=f86e9586-80d6-46a7-887d-b87b768e8167
createdAt: 1618561672420
watchersCount: 0
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FbFsOw1OtoQHaKAejNTPk.png?generation=1619254660601562&alt=media
commentsLast: ~
id: bFsOw1OtoQHaKAejNTPk
place: ChIJybDUc_xKtUYRTM9XV8zWRD0
views: 6
updatedAt: 1618561672420
updatedBy: ErP9WITL4eMyf36LQ5iR9nCAIJ82
visibility: Public
eventType: Festival
form: Yes
createdBy: ErP9WITL4eMyf36LQ5iR9nCAIJ82
commentsCount: 0
name: "SHINE BACHATA FESTIVAL 💫 "
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Moscow
  location:
    country: Russia
    latitude: 55.755826
    locality: Moscow
    usedGps: false
    place_id: ChIJybDUc_xKtUYRTM9XV8zWRD0
    longitude: 37.6172999
startDate: 2021-05-07T07:00:00.000Z
username: MaryRys
viewsCount: 21
