venue:
  formatted_address: Sonnenstraße 24-26, 80331 München, Germany
  website: http://www.isarpost-eventlocation.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: 24-26
      short_name: 24-26
    - types:
        - route
      long_name: Sonnenstraße
      short_name: Sonnenstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Ludwigsvorstadt-Isarvorstadt
      short_name: Ludwigsvorstadt-Isarvorstadt
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80331"
      short_name: "80331"
  url: https://maps.google.com/?cid=14604975425998091393
  name: ISARPOST Eventlocation
  geometry:
    viewport:
      south: 48.1337302197085
      north: 48.1364281802915
      east: 11.5665639302915
      west: 11.5638659697085
    location:
      lng: 11.5650711
      lat: 48.13503660000001
  place_id: ChIJg2EMgljfnUcRgfTs-8RLr8o
  international_phone_number: +49 89 1499037894
endDate: 2021-11-13T04:30:00.000Z
claimed: No
organisedBy: ""
description: >-
  Hola amig@s de LA fiesta española!

  Ihr habt richtig gelesen. Am FR. den 12. November sind wir für euch in der Isarpost wieder da. 


  ☝ FAKTEN / ECKDATEN ☝


  ► Bitte 3G Nachweis bereithalten – möglichst digitales Impfzertifikat,

  digitales Genesungszertifikat oder gültigen PCR-Test.

  ► FR. 12. November ab 21:30 Uhr - Isarpost

  ►  Spanische, latino und internationale Musikhits / 2 DJs 💃💃

  ►  Welcome Chupa Chups (es ist ja eine spanische Erfindung 😉 🍭

  ►  Exclusive Original Video Show!


  ☆★☆☆★☆★ LINE UP ☆★☆☆★☆★


  Coming soon


  ☆★☆★☆★☆☆★☆★☆☆★☆★☆★★


  Abendkasse: 9€


  Schon geliked?

  www.facebook.com/MunichLAfiestaespanola/

  www.facebook.com/unitedmusicevents


  Follow us on Instagram: @la_fiesta_espanola


  www.lafiestaespanola.de


  LA fiesta española, seit 2012 präsent in München. Jetzt auch in Stuttgart, Berlin und Köln!


  #españolesenmunich #munichevents #lafiestaespañola #españolesporelmundo #españolesenalemania #munichatnight Ver menos
type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2Fc20a64c4-f3e4-4975-a3c2-275fc1eb6172?alt=media&token=eea2b920-e28a-496d-bcb6-7969a8ac47c3
createdAt: 1635102576754
watchersCount: 0
price: 9 EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FBJ8ysUfzTdyIM5IBMfHP.png?generation=1636713064615502&alt=media
commentsLast: ~
promoter: Vitali
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: BJ8ysUfzTdyIM5IBMfHP
international: No
views: 25
updatedAt: 1635102576754
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
facebook: https://facebook.com/events/s/la-fiesta-espanola-isarpost/209201601302405/
eventType: Party
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: La fiesta española @ Isarpost
online: No
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Merengue:
    level: Interested
    highlighted: false
    selected: true
  Reggaeton:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-12T18:30:00.000Z
username: Vitali
viewsCount: 118
