venue:
  website: http://www.salsaclub-munich.de/
  formatted_address: Westenriederstraße 41, 80331 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "41"
      short_name: "41"
    - types:
        - route
      long_name: Westenriederstraße
      short_name: Westenriederstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Altstadt-Lehel
      short_name: Altstadt-Lehel
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80331"
      short_name: "80331"
  url: https://maps.google.com/?cid=17999243784988121499
  name: Salsa Club Munich by Hakan
  geometry:
    viewport:
      south: 48.1337395197085
      north: 48.1364374802915
      east: 11.5813472302915
      west: 11.5786492697085
    location:
      lng: 11.5800107
      lat: 48.1351437
  place_id: ChIJU60HW-F1nkcRm9nfvdsoyvk
  international_phone_number: +49 172 8533891
endDate: 2021-09-17T19:00:00.000Z
link: https://salsaclub-munich.de/course.php?kid=103
description: >-
  Für Schüler , die bereits Beginner Kurse besucht haben.


  Du lernst Schritt für Schritt die Grundelemente des Bachata Sensual tanzen. Du hast eine deutlich bessere Kontrolle über deine Körperbewegungen und genießt Bachata im Paartanz.


  Inhalte an Kombinationen und Figuren werden über 2 Monate bzw über 2 Kurse unterrichtet. Also jeder sollte mindestens 2-3 mal den Kurs besucht haben.


  Dauer = 4 x 1,5 h

  Schwierigkeitsgrad = BA-2


  Preise:

  Mitglieder  70 € Mitglieder!

  Regulär     90 €

  Studenten   80 €
type: event
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F8yp79cUd0jZtnVn34NxhBuMpxrx1%2F96d1607b-8d77-4cf2-b568-b89b795e0992?alt=media&token=5f73789e-4bbf-43f6-9779-49be818b65a3
duration: custom
createdAt: 1628689406640
watchersCount: 0
price: 90EUR
commentsLast: ~
id: BRpgvhIs4ovo5vnIjheT
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 2
updatedAt: 1628689406640
updatedBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
visibility: Public
viewsCount: 2
eventType: Course
organiser: AnnaMil
form: Yes
createdBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
commentsCount: 0
name: BACHATA - Level 2 Course
online: No
styles:
  Bachata:
    level: Intermediate
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-09-17T17:30:00.000Z
username: AnnaMil
