venue:
  formatted_address: Willy-Brandt-Allee, 81829 München, Germany
  website: http://www.ana-ana.de
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - route
      long_name: Willy-Brandt-Allee
      short_name: Willy-Brandt-Allee
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Trudering-Riem
      short_name: Trudering-Riem
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81829"
      short_name: "81829"
  url: https://maps.google.com/?cid=4089721698687383429
  name: Ballett in Riem
  geometry:
    viewport:
      south: 48.1321836197085
      north: 48.1348815802915
      east: 11.6999378302915
      west: 11.6972398697085
    location:
      lng: 11.69859
      lat: 48.133501
  place_id: ChIJ17OwYZoKnkcRhfd3eDecwTg
endDate:
  _seconds: 1634808600
  _nanoseconds: 0
organisedBy: ""
claimed: No
link: info@la-kossa.de
type: event
duration: "60"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FqTPAP7OhWMYjtoPXtpUJavNz5Fr2%2F13076a64-f0b3-4af9-accc-721fa10f9a2b?alt=media&token=99884f18-0ea1-4fce-8b12-70435dedb8c7
promo: Yes
createdAt: 1634507084656
watchersCount: 0
price: FREE
commentsLast: ~
promoter: lakossa
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: btxH7tbW1NH5Aj3e6x6a
promotedBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
international: No
views: 5
updatedAt: 1634507084656
website: http://www.la-kossa.de
updatedBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
visibility: Public
facebook: https://www.facebook.com/lakossa.fitness
eventType: Course
organiser: ""
form: No
createdBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
commentsCount: 0
name: La Kossa - Tanzfitness mit Spaßfaktor
online: No
styles:
  Afrobeats:
    level: Advanced
    highlighted: false
    selected: true
  AfroHouse:
    level: Advanced
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-21T08:30:00.000Z
username: lakossa
viewsCount: 10
