venue:
  formatted_address: Berlin, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png
  html_attributions: []
  address_components:
    - types:
        - locality
        - political
      long_name: Berlin
      short_name: Berlin
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Berlin
      short_name: Kreisfreie Stadt Berlin
    - types:
        - administrative_area_level_1
        - political
      long_name: Berlin
      short_name: BE
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
  url: https://maps.google.com/?q=Berlin,+Germany&ftid=0x47a84e373f035901:0x42120465b5e3b70
  name: Berlin
  geometry:
    viewport:
      south: 52.33823404386677
      north: 52.67545420869131
      east: 13.76111748460941
      west: 13.08834600183454
    location:
      lng: 13.404954
      lat: 52.52000659999999
  place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
endDate: 2021-08-30T19:00:00.000Z
description: >-
  Hey everyone,


  We are Bhavin and Soonruta, international Bachata and Salsa teachers. We currently live in Köln, Germany and are very excited to start travelling and teaching again after the lockdowns. We specialise in Dominican Bachata and Salsa.


  We are super excited to be in Berlin after many years.


  Dates - 27th to 30th August 2021


  If you are interested in giving a boost to your dancing, please contact us for private classes while we are there.


  Email - latin.bhavinsoonruta@gmail.com WhatsApp/Signal/Telegram - +49-1745716671
type: event
duration: custom
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2Fh31z2ww5PDeFB9IeguK1cb3fSqx1%2F96809c37-3ed9-42ec-9f7e-22091e9a81aa?alt=media&token=6675b554-3b8f-470a-ba46-373cd066a4dd
createdAt: 1628773197013
watchersCount: 0
price: "50 EUR per hour "
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FbZYdV30TTvOReHMFLNXv.png?generation=1628780229799527&alt=media
commentsLast: ~
place: ChIJAVkDPzdOqEcRcDteW0YgIQQ
id: bZYdV30TTvOReHMFLNXv
views: 3
updatedAt: 1628773197013
updatedBy: h31z2ww5PDeFB9IeguK1cb3fSqx1
visibility: Public
eventType: Workshop
organiser: Bhavinandsoonruta
form: No
createdBy: h31z2ww5PDeFB9IeguK1cb3fSqx1
commentsCount: 0
name: Bhavin and Soonruta in Berlin
online: No
styles:
  DominicanBachata:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Berlin
  location:
    country: Germany
    latitude: 52.52000659999999
    locality: Berlin
    usedGps: false
    place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
    longitude: 13.404954
startDate: 2021-08-27T07:00:00.000Z
username: Bhavinandsoonruta
viewsCount: 66
