venue:
  formatted_address: Sonnenstraße 7, 80331 München, Germany
  website: http://www.tanzschuleamstachus.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "7"
      short_name: "7"
    - types:
        - route
      long_name: Sonnenstraße
      short_name: Sonnenstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Altstadt-Lehel
      short_name: Altstadt-Lehel
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80331"
      short_name: "80331"
  url: https://maps.google.com/?cid=7618752569010268631
  name: Tanzschule am Stachus
  geometry:
    viewport:
      south: 48.13684386970849
      north: 48.13954183029149
      east: 11.5668774802915
      west: 11.5641795197085
    location:
      lng: 11.56564
      lat: 48.13818409999999
  place_id: ChIJCxXM5ZV1nkcR16lzexg_u2k
  international_phone_number: +49 1590 1227277
claimed: Yes
link: https://docs.google.com/forms/d/1Chwshn4vEozwQf0AFi1eZlopCuJ8RPOmfdPgX-_LHYE/edit
description: >-
  3 Ladystyling Workshops

  1 Preparty Bachata Workshop

  SBK Party 


  ## Attention


  This is a 2G+. You should be vaccinated / recovered + need a negative test to come in.
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F8yp79cUd0jZtnVn34NxhBuMpxrx1%2F35eacbf7-0ab3-4d8d-bf06-865a799ceb19?alt=media&token=58b2a0dc-3d08-4e0d-8d6e-ddf58b6c2249
promo: Yes
createdAt: 1640464305989
watchersCount: 0
price: From 50 EUR
promoter: AnnaMil
id: C9viD5DZ8T27n7tbK3ly
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 2
updatedAt: 1640464305989
updatedBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
visibility: Public
confirmation: Dear Guest, pls register yourself in the Google Form. Contact us
  for any questions. Thank you.
organiser: Anna Milite + Sylvia Pires Nuevo
form: No
createdBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
name: SBK Event 29.01.2022
online: No
styles:
  UrbanKizz:
    level: Intermediate
    highlighted: false
    selected: true
  Bachata:
    level: Intermediate
    highlighted: false
    selected: true
  SensualBachata:
    level: Intermediate
    highlighted: false
    selected: true
  DominicanBachata:
    level: Intermediate
    highlighted: false
    selected: true
  Kizomba:
    level: Intermediate
    highlighted: false
    selected: true
  Salsa:
    level: Intermediate
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
username: AnnaMil
hide:
  count: 0
  list: {}
watch:
  count: 2
  list:
    alejito: true
    AnnaMil: true
commentsCount: 2
commentsLast:
  updatedBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
  postId: C9viD5DZ8T27n7tbK3ly
  body: >
    The workshops during the day are for the girls. Men can join the Preparty
    Workshop & Party 🤩
  createdAt: 1641174144861
  createdBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
  commentId: ""
  updatedAt: 1641174144861
  username: AnnaMil
duration: "180"
endDate:
  _seconds: 1643490000
  _nanoseconds: 0
organisedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
eventType: Workshop
startDate: 2022-01-29T19:00
star:
  count: 1
  list:
    Vitali: true
viewsCount: 57
