endDate: 2021-03-31T18:00:00.000Z
city: Berlin
link: ""
description: >
  Let's escape the lockdown and dance!


  We have found a great way to bring together home office and our passion dancing despite lockdown.


  Work and dance in El Gouna, Egyptian Venice, during hard time. With this we have unique possibilities paradisiacal place to make our dance floor. 


  #### Benefits


  - 4K 40GB high-speed connection

  - organized practice dance sessions for all levels

  - besides dancing there are also other activities like kitesurfing, boat trips etc to choose from


  #### Price


  - 40 EUR per person per night in double room in B/B

  - flight will cost about 300€


  #### Conditions


  - this offer works if we get a group of minimum 20 people. Also non-dancers are welcome

  - if we get 130 people we can book a private flight

  - offer is valid until 31.3

  - there are also possibilities to book single room, all inclusive service or get cheaper price for staying 60 days and more


  **Click Register** to join our group on Telegram and discuss the details.


  ---


  [CharlyAl](https://wedance.vip/u/CharlyAl) will be on site and will be very happy and organizational to help.


  If you want personal advice or have any questions please contact.


  Contact via WhatsApp, Viber, Telegram: +491715109260
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2F52b5bbb0-1b3f-421b-84e7-16f998ea74bc?alt=media&token=71b79e17-18fa-47e8-a2d6-b707a87ea1bf
duration: custom
createdAt: 1610973160441
watchersCount: 0
price: ""
socialCover: ""
commentsLast: ~
id: CkEZdVdMNWVSyGadqFhE
place: ChIJAVkDPzdOqEcRcDteW0YgIQQ
views: 3
updatedAt: 1617065896883
address: El Gouna
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
visibility: Public
eventType: Party
organiser: CharlyAl
form: No
createdBy: Iqj4woO0XQQlNdBaf9Nww6u538M2
commentsCount: 0
name: Escape Lockdown in Egypt
styles:
  UrbanKizz:
    level: Interested
    selected: true
  Bachata:
    level: Interested
    selected: true
  Kizomba:
    level: Interested
    selected: true
  Salsa:
    level: Interested
    selected: true
region:
  name: Berlin
  location:
    country: Germany
    latitude: 52.52000659999999
    locality: Berlin
    usedGps: false
    place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
    longitude: 13.404954
startDate: 2021-02-11T17:00:00.000Z
username: DELETED
viewsCount: 12
