venue:
  website: http://www.salsabor.de/
  formatted_address: Heßstr. 48b-UG, 80798 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Maxvorstadt
      short_name: Maxvorstadt
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80798"
      short_name: "80798"
  url: https://maps.google.com/?cid=13068910098957006739
  name: Salsabor Dance Academy
  geometry:
    viewport:
      south: 48.1506543197085
      north: 48.1533522802915
      east: 11.5672969802915
      west: 11.5645990197085
    location:
      lng: 11.5659788
      lat: 48.1520512
  place_id: ChIJneG5QOZ1nkcRk_fYMX4YXrU
  international_phone_number: +49 89 52059610
endDate:
  _seconds: 1638914400
  _nanoseconds: 0
claimed: Yes
organisedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
link: http://www.salsabor.de/kursanmeldung/
description: >-
  Liebe Salsa & Bachata Tänzer!


  Wenn ihr auf tollem Parkettboden zu guter Musik üben möchtet, heißen wir euch herzlich willkommen zu unserem


  **Salsa & Bachata Übungsabend im Salsabor!**


  Es spielt keine Rolle, auf welchem ​​Niveau ihr seid oder von welcher Schule ihr kommt! ;)


  _____________________________

  ÜBUNGSABEND AUF 2 AREAS:


  ▶️ SALSA / MAMBO mit DJ

  20:00 - 23:00 Uhr


  ▶️ BACHATA mit DJ

  20:00 - 23:00 Uhr


  _____________________________


  EINTRITT:


  ▶️ Standard: 10 € pro Person


  ▶️ Studenten: 7 € pro Person


  _____________________________


  ❗️Wir bitten um vorherige Anmeldungen wegen beschränkter Teilnehmerzahl! ❗️


  Bitte benutzt für die Teilnahme an unserem Übungsabend unser:

  ▶️ Anmeldeformular 

  www.salsabor.de/kursanmeldung/ 


  _____________________________


  ▶️ Es gilt die 2G Plus Regel: Genesen / geimpft, in beiden Fällen mit zusätzlichem Test (PCR-Test, Antigen-Schnelltest oder Selbsttest unter Aufsicht vor Ort). Nachweis bitte am Eingang vorzeigen.


  Wir freuen uns auf euch!

  Euer Salsabor Team
type: event
duration: "180"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F6J1CzSRNBZbmuKb2J5E0YZRLC0k2%2F51225f9f-2ce8-4437-9172-54c956ee6a0f?alt=media&token=c5ba084e-f39d-4f9e-b575-ccc6f9418c5c
createdAt: 1638635976863
watchersCount: 0
price: 7 - 10 EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2Fd2MEwoYAtTqoojxzHCFY.png?generation=1638654096879761&alt=media
commentsLast: ~
promoter: Carlos
id: d2MEwoYAtTqoojxzHCFY
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 10
updatedAt: 1638635976863
updatedBy: 6J1CzSRNBZbmuKb2J5E0YZRLC0k2
visibility: Public
eventType: Party
organiser: Carlos
form: No
createdBy: 6J1CzSRNBZbmuKb2J5E0YZRLC0k2
commentsCount: 0
name: Salsa & Bachata Übungsabend
online: No
styles:
  Timba:
    level: Interested
    highlighted: false
    selected: true
  Mambo:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
  Casino:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-12-07T19:00:00.000Z
username: Carlos
viewsCount: 16
