venue:
  formatted_address: Sonnenstraße 24-26, 80331 München, Germany
  website: http://www.isarpost-eventlocation.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: 24-26
      short_name: 24-26
    - types:
        - route
      long_name: Sonnenstraße
      short_name: Sonnenstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Ludwigsvorstadt-Isarvorstadt
      short_name: Ludwigsvorstadt-Isarvorstadt
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80331"
      short_name: "80331"
  url: https://maps.google.com/?cid=14604975425998091393
  name: ISARPOST Eventlocation
  geometry:
    viewport:
      south: 48.1337302197085
      north: 48.1364281802915
      east: 11.5665639302915
      west: 11.5638659697085
    location:
      lng: 11.5650711
      lat: 48.13503660000001
  international_phone_number: +49 89 1499037894
  place_id: ChIJg2EMgljfnUcRgfTs-8RLr8o
endDate: 2021-10-17T03:00:00.000Z
link: https://bit.ly/3B9daRv
description: >-
  Se acabó la cuarentena!! Volvemos con la Noche Colombiana. Nach über 15
  Monaten Zwangspause, kehren wir zurück mit der Kultparty von Munich de Noche!
  Am Sa, 16.10.21 erwartet euch ein verrückter Abend mit DJs, Folklore Shows,
  Aguardiente und natürlich jeder Menge RUMBA. 🇨🇴


  🇨🇴 Ticketlink: https://bit.ly/3B9daRv 🇨🇴


  Salsa, Reggaeton, Cumbia, Vallenato steht auf der Playlist der Munich de Noche Residents DJ Andres & DJ Deli. Kolumbien prägt kulturell den südamerikanischen Kontinent wie kein anderes Land. Diese Kulturvielfalt bringt euch unsere Folkloregruppe "Son Colombiano" näher. Zudem gibt es das Nationalgetränk #Aguardiente Antioqueño zum Special Preis und leckere Empanadas!


  Wer schonmal auf einer Noche Colombiana war, weiß dass die Isarpost bis auf den letzten Platz ausverkauft sein wird. Wir empfehlen frühzeitig zu erscheinen!


  ❌ WICHTIGE INFO ❌

  Dieses Event findet gemäß der aktuellen Coronaverordnung statt. Wir bitten euch daher folgende Punkte zu beachten:

  • Zutritt zur Veranstaltung nach dem 2G-Prinzip nur für Geimpfte oder Genesene. Impfausweis / Genesenennachweis muss am Einlass vorgezeigt werden.

  • Keine Maskenpflicht

  • Es darf getanzt werden 💃

  • Um einen sicheren Einlass zu garantieren empfehlen wir die Karten im Vorverkauf zu erwerben.

  • Vorverkauf // Entradas: 10€ - Ticketlink: https://bit.ly/3B9daRv
type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2F6f2e90c4-64e8-4f7a-87a5-1548aaeb5a1a?alt=media&token=aa98d1b2-a6ee-4e91-b7e7-ecc35123fc9d
createdAt: 1633361225050
watchersCount: 0
price: 10 EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FDBfV0rGLnoHaAJzBMFBu.png?generation=1634379835327939&alt=media
commentsLast: ~
id: DBfV0rGLnoHaAJzBMFBu
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 21
updatedAt: 1633361225050
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Party
organiser: LatinoDancer
form: Yes
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Noche Colombiana Isarpost
online: No
styles:
  Bachata:
    level: Intermediate
    highlighted: false
    selected: true
  Reggaeton:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
  Cubaton:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-16T20:00:00.000Z
username: Vitali
viewsCount: 28
