venue:
  website: https://www.salsamas-pasing.de/de/
  formatted_address: Am Schützeneck 3, 81241 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "3"
      short_name: "3"
    - types:
        - route
      long_name: Am Schützeneck
      short_name: Am Schützeneck
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Pasing-Obermenzing
      short_name: Pasing-Obermenzing
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81241"
      short_name: "81241"
  url: https://maps.google.com/?cid=8948474523406618165
  name: Salsamás Pasing - Tanzkurse für Singles und Paare
  geometry:
    viewport:
      south: 48.1464650697085
      north: 48.1491630302915
      east: 11.4637166802915
      west: 11.4610187197085
    location:
      lng: 11.4623658
      lat: 48.14774430000001
  international_phone_number: +49 89 17929039
  place_id: ChIJ0QgbwuJ3nkcRNc5IASteL3w
endDate:
  _seconds: 1635028200
  _nanoseconds: 0
organisedBy: ""
claimed: No
link: https://salsamas-pasing.de/de/course/details/361
description: |
  Es gilt die 3G Regel.
type: event
promo: ""
duration: "240"
cover: ""
createdAt: 1634712375010
watchersCount: 0
price: 10-13 EIR
commentsLast: ~
promoter: Vitali
id: dIcsW3DzFH6NmXech5sz
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
international: No
views: 12
updatedAt: 1634712375010
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Party
organiser: ""
form: Yes
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Salsamas Social
online: No
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-23T18:30:00.000Z
username: Vitali
viewsCount: 14
