endDate: 2021-05-20T22:00:00.000Z
link: https://vk.cc/9x47CQ
description: >-
  Привет!!!

  20.05.2021 комфортные +18 градусов, вечером без осадков - мы анализируем и направление ветра и дождевые тучки.

  Встречай бомбический закат с @sensualopen

  💃🕺 Dress code: Office Style с работы  бегом на танцы.


  Регистрация разовая - вот здесь: https://vk.cc/9x47CQ


  ⏰Начало Party в 19:00, до 00:00


  Место: Смотровая площадка РАН

  Музыка: с 19:00 -00:00

  🎼🎵🎼Формат 4 бачаты 1 кизомба 1 сальса /от состава танцоров может незначительно меняться.


  Организация качественного опена - финансово затратное мероприятие.

  Организационный взнос для всех:

  300 р. с репостом этой записи до 18:00, 400 р. без. (браслет у DJ)


  Это минимальная сумма для покрытия организационных и материальных затрат: взамен, каждый получает возможность пользоваться кулером, танцевать под профессиональный звук, фото и видео.

  Если, по весомым причинам, у вас не найдется минимальной суммы - напишите мне в личку Владимир я найду вариант, как можете помочь проекту без оплаты нам очень нужны ваши руки.

  💥Все преподаватели (FREE), приходя на вечеринку - этим уже поддержали проект. У преподавателей красный цвет браслета 💥


  🚑На столе всегда стоят антисептики для рук, воспользуйтесь при получении браслета. (есть аптечка, пластыри и все необходимое)

  Кулер с водой - горячий чай и кофе со сливками рядом с DJ пультом.

  Для вас также световое и лазерное оборудование, включая ультрафиолет.

  К Вашим услугам:

  👉🏻- зарядки для телефонов, самокатов, моно-колёс.

  👉🏻- вода, газированные напитки, фрукты, печеньки.

  👉🏻- профессиональные фото и видео.

  Алкоголь и курение запрещены на площадке.

  Оплатить можно переводом на любой банк по номеру 89032221118 Владимир Александрович Ж.


  Репост этой записи до 18:00:


  Мы в INSTAGRAM https://www.instagram.com/sensualopen

  #sensualopen

  Все видео уже можно скачать в телеграмм  https://t.me/sensualopenchat

  [2 вложения]
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FErP9WITL4eMyf36LQ5iR9nCAIJ82%2Ff5e36b3b-a6af-4cc7-a60e-22ee8a2a4745?alt=media&token=47ba6f11-3273-4823-89d0-7134279f509f
duration: custom
createdAt: 1621522825059
watchersCount: 0
price: 300 - 400 руб.
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FdJHV53tXpPYQsCIAl5ES.png?generation=1621522846779247&alt=media
commentsLast: ~
place: ChIJybDUc_xKtUYRTM9XV8zWRD0
id: dJHV53tXpPYQsCIAl5ES
views: 4
updatedAt: 1621522825059
updatedBy: ErP9WITL4eMyf36LQ5iR9nCAIJ82
address: Смотровая площадка РАН
visibility: Public
eventType: Party
form: Yes
createdBy: ErP9WITL4eMyf36LQ5iR9nCAIJ82
commentsCount: 0
name: Bachata sensual open party
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  SensualBachata:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Moscow
  location:
    country: Russia
    latitude: 55.755826
    locality: Moscow
    usedGps: false
    place_id: ChIJybDUc_xKtUYRTM9XV8zWRD0
    longitude: 37.6172999
startDate: 2021-05-20T17:00:00.000Z
username: MaryRys
viewsCount: 12
