venue:
  formatted_address: (bei) Bahnhof, Güterbahnhofstraße 9, 76532 Baden-Baden, Germany
  website: https://www.sonlatino.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "9"
      short_name: "9"
    - types:
        - route
      long_name: Güterbahnhofstraße
      short_name: Güterbahnhofstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Oos
      short_name: Oos
    - types:
        - locality
        - political
      long_name: Baden-Baden
      short_name: Baden-Baden
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Baden-Baden
      short_name: Kreisfreie Stadt Baden-Baden
    - types:
        - administrative_area_level_2
        - political
      long_name: Karlsruhe
      short_name: KA
    - types:
        - administrative_area_level_1
        - political
      long_name: Baden-Württemberg
      short_name: BW
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "76532"
      short_name: "76532"
  url: https://maps.google.com/?cid=3411842324123396532
  name: Tanzschule Son Latino
  geometry:
    viewport:
      south: 48.7850583197085
      north: 48.7877562802915
      east: 8.1891742302915
      west: 8.186476269708495
    location:
      lng: 8.187567099999997
      lat: 48.7861766
  international_phone_number: +49 721 6638886
  place_id: ChIJxVb55csfl0cRtKkEX4RMWS8
endDate:
  _seconds: 1633456800
  _nanoseconds: 0
link: https://www.sonlatino.de/tanzschule/courses.php?Gesellschaftstanz=info&cID=5937
description: >-
  Taucht in die Welt des Gesellschaftstanzes mit dem Vizemeisterin Europas Olga
  Osadcenko ein!

  Meldet euch bis 30.09.21 als Paar zum Standart & Latein 1 Kurs an und erhaltet 50% Rabatt auf die zweite Person.

  Nächster Kurs:


  https://www.sonlatino.de/tanzschule/courses.php?Standard+%26+Latein=info&lID=57&ccID=29
type: event
promo: Yes
duration: 60
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FfPFOWINB1LNTCvLqLWxxgLuYhsX2%2F114a5e45-b2a4-4af5-895b-25bf877a019f?alt=media&token=2193fafb-7393-4a83-942e-72881be49352
createdAt: 1630753147123
watchersCount: 0
price: ""
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FdjIzhfPFJrlsJrrQt3h8.png?generation=1630753247196496&alt=media
commentsLast: ~
id: djIzhfPFJrlsJrrQt3h8
place: ChIJCXjgokgGl0cRf-63THNV_LY
views: 1
updatedAt: 1630753147123
updatedBy: fPFOWINB1LNTCvLqLWxxgLuYhsX2
visibility: Public
eventType: Course
organiser: alyonadance
form: Yes
createdBy: fPFOWINB1LNTCvLqLWxxgLuYhsX2
commentsCount: 0
name: GESELLSCHAFTSTANZ MIT OLGA IN BADEN-BADEN
online: No
styles:
  Ballroom:
    level: Beginner
    highlighted: false
    selected: true
region:
  name: Karlsruhe
  location:
    country: Germany
    latitude: 49.0068901
    locality: Karlsruhe
    usedGps: false
    place_id: ChIJCXjgokgGl0cRf-63THNV_LY
    longitude: 8.4036527
startDate: 2021-10-05T17:00:00.000Z
username: alyonadance
viewsCount: 45
