endDate: 2021-09-06T00:00:00.000Z
link: https://www.billetweb.fr/kizzadar-paradise-festival
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FlTTCw3EEjVPuWsUEqBp619n8ugz2%2F8e54821e-282f-4ff6-9cc6-7ff70b8cf499?alt=media&token=187c6177-c28b-45e4-a2f4-aca77196eb87
duration: custom
createdAt: 1628761479884
watchersCount: 0
price: 60EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FDneduYYw5ug8isV77Vi4.png?generation=1628763001810450&alt=media
commentsLast: ~
place: ""
id: DneduYYw5ug8isV77Vi4
views: 1
updatedAt: 1628761479884
updatedBy: lTTCw3EEjVPuWsUEqBp619n8ugz2
visibility: Public
eventType: Festival
organiser: KizzadarParadise
form: Yes
createdBy: lTTCw3EEjVPuWsUEqBp619n8ugz2
commentsCount: 0
name: Kizzadar Paradise Festival
online: No
styles:
  Tarraxinha:
    level: Interested
    highlighted: false
    selected: true
  UrbanTarraxa:
    level: Interested
    highlighted: false
    selected: true
  UrbanKizz:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
  Semba:
    level: Interested
    highlighted: false
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
startDate: 2021-09-03T15:00:00.000Z
username: KizzadarParadise
viewsCount: 13
