venue:
  formatted_address: Machtlfinger Str. 10, 81379 München, Germany
  website: http://www.tanzstudio-rebecca.com/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "10"
      short_name: "10"
    - types:
        - route
      long_name: Machtlfinger Straße
      short_name: Machtlfinger Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Thalkirchen-Obersendling-Forstenried-Fürstenried-Solln
      short_name: Thalkirchen-Obersendling-Forstenried-Fürstenried-Solln
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81379"
      short_name: "81379"
  url: https://maps.google.com/?cid=6594774642282850911
  name: Tanzstudio Rebecca
  geometry:
    viewport:
      south: 48.0955072197085
      north: 48.09820518029149
      east: 11.5149687302915
      west: 11.5122707697085
    location:
      lng: 11.5135799
      lat: 48.0969446
  place_id: ChIJtabxvibZnUcRX-oFt5hYhVs
  international_phone_number: +49 176 24414498
endDate:
  _seconds: 1634668200
  _nanoseconds: 0
claimed: Yes
organisedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
link: https://www.facebook.com/events/1050441559058247
description: RUEDA-WORKSHOP💃🕺(intermediate Level)🙂🙂 am  19.10 / 19:00-20;30
  Uhr, in der Tanzschule Rebecca, Machtlfinger Straße10 💃🕺Dieser Worksho ist
  geeignet für alle Salseros y Salseras, die mit den Rueda Grundschritten
  und  Basic- Fuguren schon vertraut sind.🙂Wenn du dich angesprochen
  fühlst  und  Zeit und Lust  hast mit dem Workshop mitzumachen, dann
  registriere dich bitte in den unterstehenden Link Ich freu mich auf euch
  allen.💃https://www.facebook.com/events/1050441559058247
type: event
duration: "90"
cover: ""
createdAt: 1634383733802
watchersCount: 0
price: 15.- Euro
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FdPAvhOoqxlOh57IqE8x8.png?generation=1634383936219321&alt=media
commentsLast: ~
promoter: Peyman
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
id: dPAvhOoqxlOh57IqE8x8
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 8
updatedAt: 1634383733802
website: https://peymansaba.com/salsa
updatedBy: MSxq3sqswZe9VfpHqFsI7OGngSD3
visibility: Public
facebook: https://www.facebook.com/events/1050441559058247
eventType: Party
organiser: Peyman
form: No
createdBy: MSxq3sqswZe9VfpHqFsI7OGngSD3
commentsCount: 0
name: Rueda-Workshop (Intermediate)
online: No
styles:
  Salsa:
    level: Interested
    selected: true
  SalsaLA:
    level: Interested
    selected: true
  Casino:
    level: Interested
    selected: true
  RuedaDeCasino:
    level: Interested
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-19T17:00:00.000Z
username: Peyman
viewsCount: 50
