venue:
  website: http://steelvenue.com/
  formatted_address: Ul. Vijenac Braće Lorenzetto 17, 52210, Rovinj, Croatia
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "17"
      short_name: "17"
    - types:
        - route
      long_name: Ulica Vijenac Braće Lorenzetto
      short_name: Ul. Vijenac Braće Lorenzetto
    - types:
        - locality
        - political
      long_name: Rovinj
      short_name: Rovinj
    - types:
        - administrative_area_level_2
        - political
      long_name: Općina Rovinj
      short_name: Općina Rovinj
    - types:
        - administrative_area_level_1
        - political
      long_name: Istarska županija
      short_name: Istarska županija
    - types:
        - country
        - political
      long_name: Croatia
      short_name: HR
    - types:
        - postal_code
      long_name: "52210"
      short_name: "52210"
  url: https://maps.google.com/?cid=647354496231779742
  name: Steel Bar & Club
  geometry:
    viewport:
      south: 45.0837216697085
      north: 45.08641963029149
      east: 13.6415590802915
      west: 13.6388611197085
    location:
      lng: 13.6402746
      lat: 45.0850541
  place_id: ChIJDThP0I2_fEcRnq2lB3zd-wg
  international_phone_number: +385 91 111 1500
endDate:
  _seconds: 1630510200
  _nanoseconds: 0
link: https://www.crosalsafestival.com/workshops/intensives_bootcamps/mambo_fusion_choreo_bootcamp_by_chiara
description: >
  Mambo bootcamp with one of the most talented young mambo artists today!


  Aimed at intermediate/advanced dancers - BOTH WOMEN & MEN - who wish to expand their dance knowledge and experience with new insights into dance and sugar on top - a dance performance next to Chiara Tofani!


  Don't miss out on this unique opportunity to spend 8 hours learning from one of the most talented young mambo dancers today and spicing it all up with a performance on the main stage on Saturday night. It means performing in front of the audience of 1000 dancers at one of the premium events in the salsa world today. 


  Chiara will go with you through secrets of mambo and Afro body movement, fuse these two through footwork, make you explore musicality, work on bettering your styling and encourage your self confidence, leading you to present yourself in the best possible way on stage. 



  ### Who's Chiara Tofani?


  Originally from Rome, Chiara has a dance background in both modern and classical dances as well as Cuban dances, Afro-Cuban folklore and salsa/mambo dancing. Constantly working on her skills she is both a student and a master, learning from the best but also traveling the world, teaching and performing. A rising star indeed, already recognised by mambo dancers worldwide. [Read more about Chiara](https://www.crosalsafestival.com/artists/instructors/chiara_tofani).


  ### When and Where?


  - WED 14.30-17.30 (STEEL CLUB)

  - THU 12.00-15.00h (STEEL CLUB)

  - FRI 15-17.00h (STEEL CLUB)

  - SAT - Performance night


  ### Show performance


  Saturday evening (subject to change!)


  ### Price and level


  - Bootcamp price is 120 EUR (900kn). 

  - INTERMEDIATE/ADVANCED level.

  - Limited to 40 participants only.


  ### IMPORTANT NOTES


  - MAMBO FUSION CHOREO BOOTCAMP is not included in any of your passes

  - this ticket doesn't include any other workshops or parties

  - the instructor reserves the right to choose who's going to perform

  - if you are performing you need to have a festival pass which includes Saturday night
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2F62bdddbd-576b-4707-b228-ea2c64ef2d2b?alt=media&token=d5cf78ee-b3a7-4957-bcd7-c5a17fb7b9c8
duration: "180"
createdAt: 1628239077868
watchersCount: 0
price: 120EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FdQTKjCvHthe0OFexq5aA.png?generation=1628239239539671&alt=media
commentsLast: ~
id: dQTKjCvHthe0OFexq5aA
place: ""
views: 3
updatedAt: 1628239077868
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
address: Steel Club, Rovinj
visibility: Public
eventType: Workshop
form: Yes
createdBy: szPaBdUVRxOPEQBKblAhyE7iInl2
commentsCount: 0
name: Mambo Fusion Choreo Bootcamp by Chiara
online: No
styles:
  Mambo:
    level: Intermediate
    highlighted: false
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
startDate: 2021-09-01T12:30:00.000Z
username: SeaSunSalsa
viewsCount: 7
