endDate:
  _seconds: 1633989600
  _nanoseconds: 0
description: >
  
  Attendees age: 25-35 


  Gute Laune Lust zum Tanzen und deine Zeit

  ----


  Registration by email

  secret.milonga@gmail.com


  What you can bring:

  Good mood, desire to dance and your time


  nach der registrierung melden wir uns bei dir 


  -----


  Registration with the subject "Secret Milonga" at secret.milonga@gmail.com



  You will receive an exact description of the location by email, it is in Center of Munich
   
  Du bekommst eine genaue Beschreibung des Standorts per E-Mail


  Preis:

  10-20 Euro



  only register if you really want to come

  -----
type: event
cover: ""
duration: "300"
createdAt: 1633484552085
watchersCount: 0
price: 10-20  EUR
commentsLast: ~
id: DUNUweZTtM7wC87cSrQh
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 3
updatedAt: 1633484552085
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Party
organiser: LatinoDancer
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Tango Young Secret Milonga
online: No
styles:
  Tango:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-11T17:00:00.000Z
username: Vitali
viewsCount: 58
