venue:
  formatted_address: Heßstr. 48b-UG, 80798 München, Germany
  website: http://www.salsabor.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Maxvorstadt
      short_name: Maxvorstadt
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80798"
      short_name: "80798"
  url: https://maps.google.com/?cid=13068910098957006739
  name: Salsabor Dance Academy
  geometry:
    viewport:
      south: 48.1506543197085
      north: 48.1533522802915
      east: 11.5672969802915
      west: 11.5645990197085
    location:
      lng: 11.5659788
      lat: 48.1520512
  international_phone_number: +49 89 52059610
  place_id: ChIJneG5QOZ1nkcRk_fYMX4YXrU
endDate:
  _seconds: 1635285600
  _nanoseconds: 0
organisedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
description: >-
  

  ► SALSA & BACHATA SCHNUPPERKURS für Beginner

  19:00 - 20:00 Uhr mit Rafael, Salsabor Team & Live Percussion


  ► RUEDA CLUB

  19:00 - 20:00 Uhr mit Carlos


  ► SALSA / MAMBO / BACHATA PARTY

  20:15 - 24:00 Uhr mit DJ


  ► ÜBUNGSSTUNDE mit BETREUUNG

  20:15 - 21:15 Uhr mit Carlos


  ————————————————————————


  ► EINTRITT

  Standard: 10,- €

  Studenten: 7,- €


  ————————————————————————


  ► Wegen beschränkter Teilnehmerzahl benötigen wir eine Voranmeldung unter:

  www.salsabor.de/kursanmeldung/ 


  ► Es gilt die 3G-Regel (genesen, geimpft, getestet). Nachweis bitte am Eingang vorzeigen.


  ► Damen bitte keine Schuhe mit „Pfennigabsätzen“ anziehen, um unseren Parkettboden zu schonen.


  ► Bitte ein zweites Paar saubere Schuhe mitnehmen, am besten nicht mit Gummisohle sondern mit Ledersohle.


  ————————————————————————


  ÜBUNGSSTUNDE MIT BETREUUNG

  (Für alle Levels, während der Social Dance Party)


  Parallel zu unserer Social Dance Party bieten wir jeden Dienstag von 20:15 bis 21:15 Uhr allen Schülern die Möglichkeit mit einer zusätzlichen Betreuung, das im Kurs Erlernte selbständig zu üben und so sicherer in den Schritten und Figuren zu werden.


  Der Sinn der Übungsstunde ist, dass unsere Schüler in der gewohnten Umgebung mit nicht zu schneller Musik die Figuren anwenden. Des Weiteren steht unser Lehrer Carlos als Hilfestellung zur Verfügung, der euch entsprechend korrigiert und nützliche Tipps gibt.
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2F0882157b-0211-4d81-a70d-0d0224214a3b?alt=media&token=0839ed33-d892-4033-8c27-8397deb75e5c
duration: "300"
createdAt: 1633176908121
watchersCount: 0
price: 7-10 EUR
commentsLast: ~
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: ECuI7OclCRFGjijWnH5y
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
views: 18
updatedAt: 1633176908121
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Party
organiser: LatinoDancer
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: THE LEGENDARY SOCIAL DANCE PARTY
online: No
styles:
  RumbaGuaguanco:
    level: Interested
    selected: true
  Timba:
    level: Interested
    selected: true
  BachataModerna:
    level: Intermediate
    highlighted: false
    selected: true
  SalsaCalena:
    level: Interested
    selected: true
  Salsaton:
    level: Interested
    selected: true
  RumbaColumbia:
    level: Interested
    selected: true
  Merengue:
    level: Interested
    selected: true
  SensualBachata:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Intermediate
    highlighted: false
    selected: true
  DominicanBachata:
    level: Interested
    selected: true
  SalsaLA:
    level: Interested
    selected: true
  Salsa:
    level: Intermediate
    highlighted: false
    selected: true
  Son:
    level: Interested
    selected: true
  Cubaton:
    level: Interested
    selected: true
  Bachatango:
    level: Interested
    selected: true
  RuedaDeCasino:
    level: Intermediate
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-26T17:00:00.000Z
username: Vitali
viewsCount: 25
