venue:
  formatted_address: Am Sportpl. 1, 83098 Brannenburg, Germany
  website: https://www.facebook.com/Berggold-103612017988687/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "1"
      short_name: "1"
    - types:
        - route
      long_name: Am Sportplatz
      short_name: Am Sportpl.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Degerndorf
      short_name: Degerndorf
    - types:
        - locality
        - political
      long_name: Brannenburg
      short_name: Brannenburg
    - types:
        - administrative_area_level_3
        - political
      long_name: Rosenheim
      short_name: RO
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "83098"
      short_name: "83098"
  url: https://maps.google.com/?cid=1644950082242801659
  name: Restaurant Berggold
  geometry:
    viewport:
      south: 47.7323855197085
      north: 47.73508348029149
      east: 12.1164686302915
      west: 12.1137706697085
    location:
      lng: 12.1152446
      lat: 47.7337325
  international_phone_number: +49 8034 9087323
  place_id: ChIJtSt-PLYjdkcR--9UbWIJ1BY
endDate: 2021-10-31T23:00:00.000Z
organisedBy: ""
claimed: No
description: >-
  Hola Familia, 


  wir feiern dieses Mal am Sonntag den 31.10.21 (nächster Tag ist Feiertag) im Berggold in Brannenburg. Euch erwartet eine tolle Location, tolle Musik, tolle Leute und ein tolles Ambiente.   


  Bitte gebt bei eurer Anmeldung euren 3G Status an.


  Wir freuen uns auf euch! 


  Salsaludos 

  Euere Salsabina und das Baila y Fiesta Team💃🏼🕺🏽



  Anmeldung bitte direkt bei Salsabina 0176/83209699 (Anruf/Whatsapp)


  Ort: 

  Berggold, Am Sportplatz, 83098 Brannenburg 


  Zeit: 18:30 Uhr bis 24 Uhr
type: event
promo: Yes
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FuZ1VEvLP7bP7ryCIyMFyuUDWm7n1%2Fd35af988-690f-498a-815f-5fd10c7110c9?alt=media&token=e5f450ea-0082-415f-bee4-1aa9d1f87c14
createdAt: 1633971977633
watchersCount: 0
price: FREE
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FettMYKKd9xXNyMpB2oop.png?generation=1635182732061807&alt=media
commentsLast: ~
promoter: MiMe72
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: ettMYKKd9xXNyMpB2oop
promotedBy: uZ1VEvLP7bP7ryCIyMFyuUDWm7n1
international: No
views: 56
updatedAt: 1633971977634
updatedBy: uZ1VEvLP7bP7ryCIyMFyuUDWm7n1
visibility: Public
eventType: Party
organiser: ""
form: No
createdBy: uZ1VEvLP7bP7ryCIyMFyuUDWm7n1
commentsCount: 0
name: Salsajubiläum Brannenburg/Rosenheim
online: No
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
  Casino:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-31T17:30:00.000Z
username: MiMe72
viewsCount: 91
