title: What is Kizomba?
tags:
  Kizomba: true
createdAt: 1599560264355
createdBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
id: ExDp9QcVBzSWOhBb3nvI
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2Fb096ff7a-f3b0-47e3-9910-1ec5896f9852?alt=media&token=7b565ff5-d342-4dbb-9ee1-841c366506ba
styles:
  Tarraxinha:
    level: Interested
    selected: true
  UrbanKizz:
    level: Interested
    selected: true
  Kizomba:
    level: Interested
    selected: true
  Semba:
    level: Interested
    selected: true
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fposts%2FExDp9QcVBzSWOhBb3nvI.png?generation=1615054705003737&alt=media
description: >-
  Kizomba is an extremely beautiful and sensual dance, besides explosive and
  contagious, which conquered the world in recent years as a catchy melody and a
  dance which seduces our souls. Kizomba is for many of the Latin dancers a
  breath of fresh air, bringing something new and exciting, and perfect for
  anyone who wants to enter the world of dance due to its softness and easy
  basic steps, allowing any novice to gradually evolve to more complex steps,
  and more importantly allowing a beginner to enjoy the pleasure of social
  dancing much earlier than any other type of dance in pairs.


  Kizomba is a dance that allows the pair to play the music they are dancing to and, according to the couple’s intimacy, becoming an extremely close dance with slow and sensual moves, requiring great leading skills and complicity between man and woman, or a more open dance with faster steps, footwork and tricks. In both cases, dancing Kizomba provides a warm and unique experience that you will want to repeat over and over again.


  ### Kizomba


  Kizomba music springs from the tradition of semba in Angola, and takes inspiration from other African music forms as well as Caribbean Zouk. Kizomba was born on 1979-1984.


  The word ‘kizombada’ originally just meant ‘party’ in the Angolan dialect Kimbundu. ‘Kizomba’ was first used to describe the style of music and later to name the steps that had been done to quite a few kinds of music.


  <w-youtube url="https://www.youtube.com/watch?v=JOVvaQ3UAto"></w-youtube>


  ### UrbanKiz


  UrbanKiz (Urban Kizomba, Neo Kizomba) is the European style of dancing kizomba. Traditional kizomba is danced in circles and has mostly the same flow, only direction changes and music interpretation. Neo Kizomba is danced on Ghetto Zouk music, has a lot of leg leading, also interpretation of music and has a line technique, contains change of speed, slow interpretation of music — tarraxa, syncopation…


  <w-youtube url="https://www.youtube.com/watch?v=7AU45xoxuqc"></w-youtube>


  ### Tarraxihna


  Tarraxinha is the sexy, percussive cousin of kizomba; the name means “little screw in a bolt”. The music often has little melody and a much heavier-hitting beat than kizomba. Make no mistake, this is a dance to do with someone you want to get very close to. Danced on the spot, tarraxinha has very little in the way of steps and is focused on isolations and two bodies moving as one.


  <w-youtube url="https://www.youtube.com/watch?v=RyCk0vRcxNg"></w-youtube>


  ### Semba


  Semba is a traditional type of music from Angola. Semba comes from the singular Masemba, meaning “a touch of the bellies”, a move that characterizes the Semba dance.


  Semba is the predecessor to a variety of music styles originated from Africa like Kizomba and Kuduro (or Kuduru, energetic, fast-paced Angolan Techno/House music, so to speak).


  <w-youtube url="https://www.youtube.com/watch?v=NqbA8TgsSqc"></w-youtube>


  Which style is your favourite so far?
savedBy:
  oEXg7Vufy8VYbclGssa3yZIS9c33: true
  TjDilYk1ZRa7WrymmCEkGwRfHO03: true
  ryHByS7Yb7MsrrESdY7IOOBSBs22: true
  7amvgN8DWCY7R342xkdRFMsfEUu2: true
  tvR012ArEpQhCJdPHh6G7sLuqoO2: true
  IHM1bU25IAeuuntSR1OU5QtIjQy1: true
  Dc1N081y1sTRGi4VUqhXuItfueY2: true
  2SWPOxN7cPc7O1WwRdkImYtEVi52: true
watchersCount: 0
region:
  placeId: ""
  loaded: true
  name: Anywhere
type: post
commentsCount: 5
commentsLast:
  createdAt: 1662736871647
  updatedBy: ~
  createdBy: ~
  commentId: ""
  postId: ExDp9QcVBzSWOhBb3nvI
  body: |
    test
  updatedAt: 1662736871647
  username: ""
username: alexrazbakov
watch:
  list:
    DanilBachatero: true
    N: true
    salsera0908: true
    BachataFiesta: true
    katherinearnaizs: true
    __saracc: true
    Vlachet: true
    Coco: true
    sf: true
    alexrazbakov: true
  count: 10
views: 1
star:
  count: 0
  usernames: []
  list:
    DanilBachatero: true
    N: true
    salsera0908: true
    BachataFiesta: true
    __saracc: true
    katherinearnaizs: true
    Vlachet: true
    alejito: true
    sf: true
updatedBy: PvkPWP5CxXP8dWdR2uBbHLD3Mvp1
updatedAt: 1707816312915
viewsCount: 869
