endDate:
  _seconds: 1602352800
  _nanoseconds: 0
city: Munich
link: "@aljonali"
description: >-
  Hi bachata lovers 


  In this workshop you have the chance to learn simple but very effective moves for bachata social dancing. Those are combinations that will make your dance partner SMILE A LOT. Isn't it the ultimate goal to make both of you enjoy the dancing to the fullest?


  Bachata level requirement: not for absolute beginners.


  In two hours you can learn some footwork, partnerwork and have a whole half an hour to practice at the end of the work shop.


  Price: 15 € / Person for 2 hours Workshop


  Looking forward to our amazing bachata time together 😃


  @wedancemunich @aljonali
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2F76347b36-957d-44cb-9429-041edeb86476?alt=media&token=cbf93af0-5cc3-4566-876f-15dceccb2e29
createdAt: 1601897689330
watchersCount: 0
commentsLast: ~
id: F57NC1O9vPYFk4H08Lwz
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 1
updatedAt: 1617065897148
address: Machtlfinger Straße 10
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
eventType: Course
organiser: Toan & Elena
createdBy: kNDQo4gmNYQKAnxY4bbSDQpJzrH2
commentsCount: 0
name: Bachata Creativa Workshop
styles:
  Bachata:
    level: Interested
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate:
  _seconds: 1602345600
  _nanoseconds: 0
username: Aljonali
viewsCount: 53
