endDate:
  _seconds: 1628449200
  _nanoseconds: 0
description: Beautiful get-together of Brazilian Zouk dancers from all over
  bavaria! Have a beautiful Sunday afternoon with Zouk until sunset! Get to know
  the people and dive into this mesmerizing dance!
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FG008dEeTZJcXLBzzL2krS0Ynumu2%2F51c294b8-8cb9-4458-97c0-c1ff6446ef0d?alt=media&token=8f896c88-f0c3-4289-bfb4-97f903f5b83a
duration: "300"
createdAt: 1627949629319
watchersCount: 0
price: Free
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FQFD6j16Y8RzHSlbLIjql.png?generation=1635357825778827&alt=media
commentsLast: ~
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: f5N4OJ1ENWLqi0SR9zvp
views: 3
updatedAt: 1627949629319
updatedBy: G008dEeTZJcXLBzzL2krS0Ynumu2
address: Pinakothek der Moderne
visibility: Public
eventType: Party
organiser: ""
form: ""
createdBy: G008dEeTZJcXLBzzL2krS0Ynumu2
commentsCount: 0
name: Zouk Tea Time
styles:
  BrazilianZouk:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-08-08T14:00:00.000Z
username: Thomas
viewsCount: 29
