venue:
  website: https://www.salsa-y-corazon.de/
  formatted_address: Zenettistraße 7, 80337 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "7"
      short_name: "7"
    - types:
        - route
      long_name: Zenettistraße
      short_name: Zenettistraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Ludwigsvorstadt-Isarvorstadt
      short_name: Ludwigsvorstadt-Isarvorstadt
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80337"
      short_name: "80337"
  url: https://maps.google.com/?cid=8616399599048238742
  name: Salsa Y Corazon - dance school
  geometry:
    viewport:
      south: 48.12187606970849
      north: 48.12457403029149
      east: 11.5593379802915
      west: 11.5566400197085
    location:
      lng: 11.557894
      lat: 48.12314479999999
  place_id: ChIJ7SAJ9Rd3nkcRlqYWoMiZk3c
  international_phone_number: +49 172 9659579
endDate: 2021-11-21T01:00:00.000Z
claimed: No
organisedBy: ""
link: https://docs.google.com/forms/d/e/1FAIpQLScUFR6OIcn6kgfgzTw0T0PEFH6VbsyGcl6DTPdfgPBEZUlMFQ/viewform
description: >-
  PROGRAMM 20.11.2021


  3 Stunden Workshop (18-21 Uhr) anschließend 


  5 Stunden Tanzen (21-2 Uhr)


  Adresse:


  Salsa y Corazon

  Zenettistr. 7, 80337 München


  Dieses Mal kommt das KizInvasion Team aus Frankfurt (Steve, Franky, Lamsca, Ernest....)

  🤓 Steve & Franky geben 2 Stunden Workshop 

  Class 1: harmony and feeling from Tarraxinha to douceur

  Class 2: Konpa

  🤓 mit Ibi & Nataliya gibt es 1 Stunde UrbanKiz


  Für Musik sorgen unsere hervorragenden DJs:

  🎧 DJ El Momo

  🎧 DJ Longshamp

  🎧 DJ Peacebro

  🎧 DJ Charley Raymdtc


  Sie spielen ALLES: UrbanKiz, Kizomba, Douceur, Tarraxinha, Konpa, Semba


  DRESSCODE BLACK & WHITE 🖤🤍


  Und es wartet noch eine Überraschung auf dich 🤫 Sei neugierig 🧐


  Und du darfst gerne diesen Link an deine Freunde weiterleiten 🤩


  WICHTIGE INFO ZU CORONA:

  Nachdem die Krankenhausampel in Bayern auf Rot steht und der Katastrophenfall ausgerufen wurde, sind wir verpflichtet dieses Event unter 2G zu machen. 2G heißt: geimpft und genesen. Auch das Raumhygienekonzept schreibt uns die 2G Regel vor.
type: event
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2F09dce8d1-e152-4fcd-a770-bf2d9bec108a?alt=media&token=84201e07-dc8c-471e-b1d9-247df8118bc6
duration: custom
createdAt: 1637020176413
watchersCount: 0
price: 10-45EUR
commentsLast: ~
promoter: alejito
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: fjZFvr2YQ1tcMsicordI
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
international: No
views: 12
updatedAt: 1637020176413
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
visibility: Public
eventType: Party
organiser: ""
form: No
createdBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
commentsCount: 0
name: Kizaddict Munich
online: No
styles:
  UrbanTarraxa:
    level: Interested
    highlighted: false
    selected: true
  UrbanKizz:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
  Douceur:
    level: Interested
    highlighted: false
    selected: true
  Semba:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-20T17:00:00.000Z
username: alejito
viewsCount: 27
