venue:
  formatted_address: Berliner Straße 120, 10713 Berlin, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "120"
      short_name: "120"
    - types:
        - route
      long_name: Berliner Straße
      short_name: Berliner Straße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Bezirk Charlottenburg-Wilmersdorf
      short_name: Bezirk Charlottenburg-Wilmersdorf
    - types:
        - locality
        - political
      long_name: Berlin
      short_name: Berlin
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Berlin
      short_name: Kreisfreie Stadt Berlin
    - types:
        - administrative_area_level_1
        - political
      long_name: Berlin
      short_name: BE
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "10713"
      short_name: "10713"
  url: https://maps.google.com/?q=Berliner+Stra%C3%9Fe+120,+10713+Berlin,+Germany&ftid=0x47a8508ceb403ed1:0xe0a5b98ec919ee68
  name: Berliner Straße 120
  geometry:
    viewport:
      south: 52.48501416970851
      north: 52.48771213029151
      east: 13.3192756802915
      west: 13.3165777197085
    location:
      lng: 13.3180046
      lat: 52.4862168
  place_id: ChIJ0T5A64xQqEcRaO4ZyY65peA
endDate:
  _seconds: 1636576800
  _nanoseconds: 0
claimed: Yes
organisedBy: 9k2NG4ByGVcCaYVoNJxtwghhRmi2
link: https://tumbao-danzas.de/kurse/#Bachata
description: >-
  Bachata - Dominican Fusion in Berlin

  --------------------------

  Lernt und erlebt mit uns diesen schönen Lateinamerikanischen Paartanz

  Von 20:40 - 21:40 - Bachata - Dominican Fusion

  Kursinhalt in den 7 Wochen:

  - Aufbau Bachata Dominican

  - Erweiterte Bachata Schritte

  - Bachata Moderna Elemente

  - Bachata Footwork & Stylin

  - Dominican Flow

  Dozenten: Leslie & Anna

  Schnupperstunden (ein mal kostenlos pro Person) sind jederzeit nach vorherige Nachricht möglich.

  Kommt vorbei und lasst euch begeistern....🙂
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F9k2NG4ByGVcCaYVoNJxtwghhRmi2%2F48d974a7-d4b0-4c18-a641-dd9f16b781d9?alt=media&token=31b42904-0031-486c-b3d0-3b1ac7bc248b
promo: Yes
duration: 60
createdAt: 1636483918122
watchersCount: 0
price: ""
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FFPlFxwQIfQXMgGCdqbQl.png?generation=1636485777026608&alt=media
commentsLast: ~
promoter: Leslie_Nox
promotedBy: 9k2NG4ByGVcCaYVoNJxtwghhRmi2
place: ChIJAVkDPzdOqEcRcDteW0YgIQQ
id: FPlFxwQIfQXMgGCdqbQl
international: No
views: 3
updatedAt: 1636483918122
website: www.tumbao-danzas.de
updatedBy: 9k2NG4ByGVcCaYVoNJxtwghhRmi2
visibility: Public
facebook: https://facebook.com/events/s/dominican-fusion/3024891044436897/
eventType: Course
organiser: Leslie_Nox
form: Yes
createdBy: 9k2NG4ByGVcCaYVoNJxtwghhRmi2
commentsCount: 0
name: Dominican Fusion
online: No
styles:
  Bachata:
    level: Beginner
    highlighted: false
    selected: true
region:
  name: Berlin
  location:
    country: Germany
    latitude: 52.52000659999999
    locality: Berlin
    usedGps: false
    place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
    longitude: 13.404954
startDate: 2021-11-10T19:40:00.000Z
username: Leslie_Nox
viewsCount: 6
