venue:
  formatted_address: Willy-Brandt-Allee, 81829 München, Germany
  website: http://www.ana-ana.de
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - route
      long_name: Willy-Brandt-Allee
      short_name: Willy-Brandt-Allee
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Trudering-Riem
      short_name: Trudering-Riem
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81829"
      short_name: "81829"
  url: https://maps.google.com/?cid=4089721698687383429
  name: Ballett in Riem
  geometry:
    viewport:
      south: 48.1321836197085
      north: 48.1348815802915
      east: 11.6999378302915
      west: 11.6972398697085
    location:
      lng: 11.69859
      lat: 48.133501
  place_id: ChIJ17OwYZoKnkcRhfd3eDecwTg
endDate:
  _seconds: 1636742700
  _nanoseconds: 0
organisedBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
claimed: Yes
link: https://www.la-kossa.de/produkt/5erkarte
description: "Immer Freitags ab dem 12. November: Du lernst coole Tanzschritte,
  trainierst Cardio, Beweglichkeit und verbesserst dein Körpergefühl im Tanz. "
type: event
duration: 60
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FqTPAP7OhWMYjtoPXtpUJavNz5Fr2%2F967be1e3-a6c6-4e4c-80f8-665dfc61e170?alt=media&token=a90386b3-e2da-4c33-9308-167a39eac9a2
promo: Yes
createdAt: 1635635692786
watchersCount: 0
price: ""
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FfrdYy4muoagvkQ75DiRT.png?generation=1635853862186172&alt=media
commentsLast: ~
promoter: lakossa
promotedBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: frdYy4muoagvkQ75DiRT
international: No
views: 5
updatedAt: 1635635692786
website: http://www.la-kossa.de
updatedBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
visibility: Public
facebook: www.facebook.com/lakossa.fitness
eventType: Course
organiser: la.kossa
form: Yes
createdBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
commentsCount: 0
name: La Kossa - Afrobeats, Bewegung, Spaß
online: No
styles:
  Afrobeats:
    level: Beginner
    highlighted: false
    selected: true
  AfroHouse:
    level: Beginner
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-12T17:45:00.000Z
username: lakossa
viewsCount: 35
