venue:
  website: http://www.salsaclub-munich.de/
  formatted_address: Westenriederstraße 41, 80331 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "41"
      short_name: "41"
    - types:
        - route
      long_name: Westenriederstraße
      short_name: Westenriederstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Altstadt-Lehel
      short_name: Altstadt-Lehel
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80331"
      short_name: "80331"
  url: https://maps.google.com/?cid=17999243784988121499
  name: Salsa Club Munich by Hakan
  geometry:
    viewport:
      south: 48.13373901970849
      north: 48.13643698029149
      east: 11.5813456802915
      west: 11.5786477197085
    location:
      lng: 11.5800076
      lat: 48.1351427
  international_phone_number: +49 172 8533891
  place_id: ChIJU60HW-F1nkcRm9nfvdsoyvk
endDate: 2021-10-15T19:00:00.000Z
link: "https://bit.ly/3of0S6M "
description: |-
  💥New ! Bachata Courses at Salsa Club Munich with me and Paolo Mastriani 💃🕺

  🔸 Level 2 Start Fr.15.10. | 4 x 75 min. Time: 19.30 - 21.00

  Prices: Members: 70 € Regular: 90 € Student: 80 €
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F8yp79cUd0jZtnVn34NxhBuMpxrx1%2F5c6095ed-0e61-4cca-97c6-795f8e1d246e?alt=media&token=565e9007-f1e2-4dff-9c32-a36f66ce2156
duration: custom
createdAt: 1632841939337
watchersCount: 0
price: 70 - 90 EUR
commentsLast: ~
id: FrGnjNq0m2HluSGQDdtp
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 4
updatedAt: 1632841939337
updatedBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
visibility: Public
eventType: Course
organiser: AnnaMil
form: Yes
createdBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
commentsCount: 0
name: Bachata Course - Level 2
online: No
styles:
  SensualBachata:
    level: Intermediate
    highlighted: false
    selected: true
  Bachata:
    level: Intermediate
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-15T17:30:00.000Z
username: AnnaMil
viewsCount: 7
