endDate: 2021-08-06T21:00:00.000Z
link: https://fb.me/e/3WZx88T5u
description: >-
  "𝐃𝐢𝐞 𝐅𝐅𝐅 𝐒𝐨𝐦𝐦𝐞𝐫-𝐒𝐞𝐚𝐬𝐨𝐧 𝐚𝐦 𝐆𝐮𝐠𝐠𝐢"


  𝐅eiere 𝐅reitags im 𝐅reien mit El Papacho DJ aus Passau in der besten Lage am See und mit den besten Latino-Rhythmen!!!...
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2F7cb26241-4d60-4e82-9011-574fa09edc54?alt=media&token=700937c6-17ad-49af-bf3a-4b190c17a048
duration: custom
createdAt: 1627288473721
watchersCount: 0
price: Kostenlos
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FFSAzMKFeSDNpq0JHVIn9.png?generation=1627293490700531&alt=media
commentsLast: ~
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: FSAzMKFeSDNpq0JHVIn9
views: 5
updatedAt: 1627288473721
address: Cantina - die Bar am Guggi, am Guggenberger See Westufer 93073
  Neutraubling, Regensburg
updatedBy: xVFXq4lPYzPhITIbk4BMDIoxR5J3
visibility: Public
eventType: Party
form: Yes
createdBy: xVFXq4lPYzPhITIbk4BMDIoxR5J3
commentsCount: 0
name: Latineando Regensburg mit "El Papacho DJ"
online: No
styles:
  Cumbia:
    level: Interested
    highlighted: false
    selected: true
  ChaChaCha:
    level: Interested
    highlighted: false
    selected: true
  Mambo:
    level: Interested
    highlighted: false
    selected: true
  Bolero:
    level: Interested
    highlighted: false
    selected: true
  Merengue:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  RockAndRoll:
    level: Interested
    highlighted: false
    selected: true
  ForroLove:
    level: Interested
    highlighted: false
    selected: true
  Reggaeton:
    level: Interested
    highlighted: false
    selected: true
  FunkCarioca:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
  Son:
    level: Interested
    highlighted: false
    selected: true
  Dembow:
    level: Interested
    highlighted: false
    selected: true
  Perreo:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-08-06T15:00:00.000Z
username: ElPapachoDJ
viewsCount: 47
