venue:
  website: http://www.isarpost-eventlocation.de/
  formatted_address: Sonnenstraße 24-26, 80331 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: 24-26
      short_name: 24-26
    - types:
        - route
      long_name: Sonnenstraße
      short_name: Sonnenstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Ludwigsvorstadt-Isarvorstadt
      short_name: Ludwigsvorstadt-Isarvorstadt
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80331"
      short_name: "80331"
  url: https://maps.google.com/?cid=14604975425998091393
  name: ISARPOST Eventlocation
  geometry:
    viewport:
      south: 48.1337302197085
      north: 48.1364281802915
      east: 11.5665639302915
      west: 11.5638659697085
    location:
      lng: 11.5650711
      lat: 48.13503660000001
  international_phone_number: +49 89 1499037894
  place_id: ChIJg2EMgljfnUcRgfTs-8RLr8o
endDate:
  _seconds: 1636398000
  _nanoseconds: 0
claimed: Yes
organisedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
description: >-
  Let's practice Rueda de Casino. Beginner friendly. Starting with basics and
  building up to easy and fun figures.


  Let's have some fun!


  This is part of [Salsa and Bachata Party at Isarpost](https://wedance.vip/events/9T8cdX8Bz1BG7KMFiu7u)
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2Fcb815bb7-c35d-42bc-978e-2bdb3666564f?alt=media&token=3768d053-8b51-4b7a-bb9c-5723c5afdacc
duration: "30"
promo: Yes
createdAt: 1636220076396
watchersCount: 0
price: ""
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FfTCl4annWULmXx0EQ6Fl.png?generation=1636220103730511&alt=media
commentsLast: ~
promoter: alejito
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
id: fTCl4annWULmXx0EQ6Fl
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 16
updatedAt: 1636220076396
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
visibility: Public
eventType: Workshop
organiser: MontunoClub
form: No
createdBy: ICpCp7IBpMe30vAHqYfw4FmQp382
commentsCount: 0
name: Rueda de Casino
online: No
styles:
  RuedaDeCasino:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-08T18:30:00.000Z
username: MontunoClub
viewsCount: 67
