venue:
  formatted_address: Lenbachpl. 1, 80333 München, Germany
  website: http://www.enterthedragon.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "1"
      short_name: "1"
    - types:
        - route
      long_name: Lenbachplatz
      short_name: Lenbachpl.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Maxvorstadt
      short_name: Maxvorstadt
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80333"
      short_name: "80333"
  url: https://maps.google.com/?cid=2169458608303372508
  name: Enter The Dragon
  geometry:
    viewport:
      south: 48.13963001970851
      north: 48.1423279802915
      east: 11.5683585302915
      west: 11.5656605697085
    location:
      lng: 11.5669402
      lat: 48.14102260000001
  international_phone_number: +49 89 125036810
  place_id: ChIJPYJKL_F1nkcR3PjVJhx3Gx4
endDate: 2021-10-10T03:00:00.000Z
organisedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
link: https://www.eventbrite.de/e/viva-latina-munchen-tickets-186060621327
description: >-
  Liebe Partyfreunde, Señoras y Señores, Chicas y Chicos:


  Die Fiesta Latina meldet sich nun auch in München nach der langen Corona-Durststrecke mit einer ganz besonderen Party-Kooperation zurück:


  Wir starten die VIVA LATINA Partyreihe in unserer neuen Stamm-Location ENTER THE DRAGON!


  Gemeinsam mit der Crew der Frauen26 Clubtour lassen wir die heißeste Latino Party Münchens steigen. Tanzt und feiert mit uns zu feinster Latin Party Music mit viel RITMO Y PERREO.  


  —> Samstag, den 9. Oktober 2021 ab 23:00 Uhr

  —> Enter The Dragon Restaurant - Bar - Music, Lenbachplatz 1 München

  —> Münchens Latino Mix „más caliente“ aus Reggaeton, Salsa, Bachata und Merengue

  —> Corona-Regeln: 3G Plus d.h. Geimpft, Genesen oder mit negativem PCR-Testnachweis

  —> Tickets: Abendkasse 


  +++Latin Party Music all night long +++


  by DJ Rafa & DJ Soley & DJ Naudy


  Seid ihr der Meinung, dass ein bestimmtes Lied auf der Party nicht fehlen darf? Schreibt uns einfach auf Facebook und wir werden es für Euch auflegen!!


  Fragen? Gerne an info@fiestalatina.de


  Enter The Dragon Restaurant - Bar - Music | Lenbachplatz 1 | 80333 München | www.enterthedragon.de


  Wir freuen uns auf Euch!


  Eure Crew von Frauen26 und Fiesta Latina
type: event
cover: ""
duration: custom
createdAt: 1633362226874
watchersCount: 0
price: 15EUR
commentsLast: ~
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
id: ftgj1E0Ub7BboZjxsWGF
views: 7
updatedAt: 1633362226874
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Party
organiser: LatinoDancer
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Viva Latina
online: No
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Reggaeton:
    level: Interested
    highlighted: false
    selected: true
  Casino:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-09T21:00:00.000Z
username: Vitali
viewsCount: 11
