venue:
  website: http://taiyosportcenter.com/
  formatted_address: Holstenstraße 79, 22767 Hamburg, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "79"
      short_name: "79"
    - types:
        - route
      long_name: Holstenstraße
      short_name: Holstenstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Bezirk Altona
      short_name: Bezirk Altona
    - types:
        - locality
        - political
      long_name: Hamburg
      short_name: Hamburg
    - types:
        - administrative_area_level_3
        - political
      long_name: Hamburg
      short_name: Hamburg
    - types:
        - administrative_area_level_1
        - political
      long_name: Hamburg
      short_name: HH
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "22767"
      short_name: "22767"
  url: https://maps.google.com/?cid=6865231638099405762
  name: Taiyo Sport Center
  geometry:
    viewport:
      south: 53.5555279197085
      north: 53.5582258802915
      east: 9.951915080291501
      west: 9.949217119708498
    location:
      lng: 9.950459099999998
      lat: 53.5567289
  place_id: ChIJvYJxpGaPsUcRwiuwIc0zRl8
  international_phone_number: +49 40 436414
endDate: 2021-10-18T18:00:00.000Z
link: "www.kizombagala.com "
description: >-
  Dear Dancers. For the 10th time in a roll (Golden Jubilee) we are inviting
  first class International Kizomba ,Urban Kizz & Zouk Teachers, DJs to Hamburg
  from the 15. -18.. October.21. to teach and celebrate our 10th anniversary of
  hard work with us.
   Lucky, we have Mister Nino Kizomba this Year for them 2nd time, . We will dance Live to his warm and touching songs .

  As pioneers of Kizomba Germany we have promoted Kizomba to a high level and never cancelled this Event before even in the difficult times of Covid - 19, because we are truly dedicated to Dance, Love Culture & Sharing.


  We are very happy that today there are lot of Festivals in Germany. But we have keep the speciality of this Festival, which make us an eception among many.

  This year we are adding again Top Zouk , Urban Kizz Teachers & DJs for the Love of Dance to our unique Festival (Gala) in Hamburg.


  There will be fantastic Workshops, Social Dance & Explosives Night Partys


  2 Rooms in the night. 

  Room 1. Kizomba, Semba, Urban Kizz Room

  Room 2, Salsa, Bachata, Cha Cha, Zouk Brazil.

   During the Day there will will be 2 Rooms for Workshops and 1  extra Lounge for Social Dance with all the DJs.
  Live Concert By Mister Nino Kizomba. 16.Oct.21.


  Confirmed Teachers Now. More Coming


  1, Donny (UK) 2x Kizomba Semba Champion

  2,Ebo & Nana (Kizomba King & Queen Ghana)

  3, Claudio & Efy Afro Ginga (France)

  4, Tomas Kaita (Spain) 

  5, Rokhaya (France ) 

  6,  Moussa Diop (Urban Kizz France)

  7, Rico Suave (UK)

  8, Lionel (France) 

  9, Cesar Sancherz (Salsa on 1&2 Germany)



  Confirmed DJs for now.

  DJ Zezom (Denmark)

  DJ Matt De Camona (France)

  DJ Ben (Germany)

  DJ Julius (Nertherlands)

  DJane Kirmen(Spain)

  DJ Duke Monteiro (Germany)




  More Artist & DJs are Coming Soon.

  Stay turned

  SALES STARTS  NOW!

  Fullpass, Workshoppass, Daypass,
   Partypass, Socialpass, Party & Socialpass
  *Depending on availability. Places are limited.

  ab 1. Feb. €70 €59  €50  €40 

  ab 1. Mar. €73 €62  €53   €42

  ab 1. April. €75 €65  €55  €43 

  ab 1. May. €85 €70  €60  €45 

  ab 1.June €87 €75  €65  €47 

  ab 1 July.  €90 €79 €75 €50 

  ab 1.Aug. €100 €90 €85 €53

  ab 01.Sept. €105 €95  €90 €55

  ab 01.Oct. €110 €100  €95 €60

  Combi Party Pass & Socials 60€ till October.08.


  ***Friday.* **This is Africa Party***DRESS-CODE: "African Dress & a Mask"

  ***Saturday.*** Party. Love is the MessageDresscode: Elegance.

  Gala Night Party. Extra Room for Salsa, Bachata. 

  10.10.20.*** Live Concert by Mister Nino Kizomba***


  ***Sunday.***KIZZ IT ON A SUN*** Dresscode: Casual Elegance*


  There will be a social room which is open for those who dont want to be part of the workshop.It will be open from 16:00  – 20:00 = 04::00pm - 8pm



  www.kizombagala.com
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2Ffdihs1Ct28c08RbLq4Loh43k4Dx2%2Ffc53f26c-93ac-4e65-b006-54cedddbc566?alt=media&token=02f02726-8421-4fa2-b994-5f2596656c1a
promo: Yes
duration: custom
createdAt: 1631716595381
watchersCount: 0
price: 105€
commentsLast: ~
place: ChIJuRMYfoNhsUcRoDrWe_I9JgQ
id: G1r0FXGwp0rK6L5nc61O
views: 6
updatedAt: 1631716595381
updatedBy: fdihs1Ct28c08RbLq4Loh43k4Dx2
visibility: Public
eventType: Festival
organiser: BenKizombaCraic
form: Yes
createdBy: fdihs1Ct28c08RbLq4Loh43k4Dx2
commentsCount: 0
name: "10th Anniversary Golden Jubilee International Kizomba Festival(Gala)Hamburg "
online: No
styles:
  DominicanBachata:
    level: Advanced
    highlighted: false
    selected: true
  Kizomba:
    level: Advanced
    highlighted: false
    selected: true
  Salsa:
    level: Advanced
    highlighted: false
    selected: true
region:
  name: Hamburg
  location:
    country: Germany
    latitude: 53.5510846
    locality: Hamburg
    usedGps: false
    place_id: ChIJuRMYfoNhsUcRoDrWe_I9JgQ
    longitude: 9.9936818
startDate: 2021-10-15T17:00:00.000Z
username: BenKizombaCraic
viewsCount: 33
