endDate:
  _seconds: 1613757600
  _nanoseconds: 0
city: Munich
description: >-
  Diese Klasse ist für alle Tänzer gedacht. Männer und Frauen willkommen ! Wir
  werden dynamische Stretching Übungen (für vor dem Tanzen durchgehen) sowie
  statische Stretching Übungen (nach dem Tanzen). Eine Art von Warm Up und Cool
  Down!


  Wir freuen uns auf euch!

  Klasse wird kostenlos Live über Facebook und Instagram gesendet.
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F8yp79cUd0jZtnVn34NxhBuMpxrx1%2F4b17dafc-a988-4d53-9d34-0470b0dec4f1?alt=media&token=acd928e8-61e8-48d3-a73b-9da2d84c2846
duration: "30"
createdAt: 1612853283947
watchersCount: 0
price: Free
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FG8sy8Gjnn2tLpoagS3kG.png?generation=1613679480795627&alt=media
commentsLast: ~
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: G8sy8Gjnn2tLpoagS3kG
views: 1
updatedAt: 1617065897352
address: Online
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
visibility: Public
eventType: Course
organiser: ""
form: No
createdBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
commentsCount: 0
name: Stretching Class for Dancers
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-02-19T17:30:00.000Z
username: AnnaMil
viewsCount: 3
