endDate: 2021-07-23T19:15:00.000Z
link: an.milite@gmail.com
description: >-
  ----------------🇬🇧English

  💃 Bachata LadyStyling Choreo 💃

   In this workshop we will learn a choreo and record it together 😉

   -> of course if you like and feel like it! 😅😁

  In any case we will have fun, learn, laugh and make new connections together🤗

   Duration & Price:
   2.5 h = 25 €

  If you have any questions, please write to me at any time! 📨


  Registrations via Messenger or at an.milite@gmail.com 💻


  ----------------🇩🇪German

  💃 Bachata LadyStyling Choreo 💃


  In diesem Workshop werden wir eine Choreo erlernen und zusammen aufnehmen 😉


  --> natürlich wer mag und sich danach fühlt!😅😁


  AUFJEDENFALL werden wir zusammen Spaß haben, lernen, lachen und neue Verbindungen aufbauen🤗


  Dauer & Preis:

  2,5 h = 25 €


  Bei Fragen schreibt mich jederzeit gerne an!📨


  Anmeldungen per Messenger oder unter an.milite@gmail.com 💻
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F8yp79cUd0jZtnVn34NxhBuMpxrx1%2Ff548dbf1-403f-4412-8067-9fa21d552bc3?alt=media&token=8ea2ca08-b0a9-40ef-9198-f417582f4a42
duration: custom
createdAt: 1625754815162
watchersCount: 0
price: "25"
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FGsB3WDgKejKn1s3KTVgF.png?generation=1626198327388229&alt=media
commentsLast: ~
id: GsB3WDgKejKn1s3KTVgF
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 1
updatedAt: 1625754815162
address: Zenettistrasse 7, München
updatedBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
visibility: Public
eventType: Workshop
form: Yes
createdBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
commentsCount: 0
name: Bachata LadyStyling Workshop - Choreo
online: No
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  SensualBachata:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-07-23T16:45:00.000Z
username: AnnaMil
viewsCount: 26
