venue:
  formatted_address: Tal 16, 80331 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "16"
      short_name: "16"
    - types:
        - route
      long_name: Tal
      short_name: Tal
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Altstadt-Lehel
      short_name: Altstadt-Lehel
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80331"
      short_name: "80331"
  url: https://maps.google.com/?q=Tal+16,+80331+M%C3%BCnchen,+Germany&ftid=0x479e758a43dc6eaf:0xc96070f51b28282a
  name: Tal 16
  geometry:
    viewport:
      south: 48.13460831970851
      north: 48.1373062802915
      east: 11.5802492302915
      west: 11.5775512697085
    location:
      lng: 11.5788135
      lat: 48.1358417
  place_id: ChIJr27cQ4p1nkcRKigoG_VwYMk
endDate:
  _seconds: 1638023400
  _nanoseconds: 0
organisedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
claimed: Yes
link: https://www.eventbrite.de/e/schnupperstunde-fur-tanzinteressierte-tickets-204405671867
description: >-
  Komm zu unserer Schnupperstunde vorbei, lerne uns kennen und triff andere
  Tanzbegeisterte, die auch gerne einen Tanzkurs machen möchten. Wähle aus den
  zwei Workshops aus ob du als kompletter Beginner starten möchtest oder schon
  etwas Tanzerfahrung hast.


  Reserviere jetzt deinen Platz (pro Workshop gibt es nur begrenzte Plätze).


  Der Workshop findet auf Basis der aktuellen Regelungen statt. Informiere dich bitte vor dem Workshop und bring deinen Nachweis mit, zur Sicherheit aller überprüfen wir das.


  Hier unser Hygienekonzept: https://tanzschule-muenchen-dt.de/HYGIENEKONZEPT
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2Fbxaj6fMe8hgJtXlgRP18azMV3ve2%2Fd73c078e-ad18-4abc-b755-e2e6f59f4589?alt=media&token=2dce165a-9d31-4e8b-97aa-a14ff2594a46
duration: 60
createdAt: 1636469296093
watchersCount: 0
price: 12EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FGUXMnJUYG3wjkARrHbPQ.png?generation=1636474110351943&alt=media
commentsLast: ~
promoter: DT01
id: GUXMnJUYG3wjkARrHbPQ
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
international: No
views: 16
updatedAt: 1636469296093
website: https://tanzschule-muenchen-dt.de/
updatedBy: bxaj6fMe8hgJtXlgRP18azMV3ve2
visibility: Public
facebook: https://www.facebook.com/Tanzschule/
eventType: Workshop
confirmation: >-
  Komm zu unserer Schnupperstunde am Samstag, 27.11.2021 vorbei und triff andere
  Tanzbegeisterte, die auch gerne einen Tanzkurs machen möchten. Verabredet euch
  anschließend, und besucht unsere Tanzkurse! Dabei ist es nicht nötig, aber
  natürlich möglich, mit einem festen Tanzpartner zu tanzen. Du kannst dich
  genauso zu unterschiedlichen Stunden oder Kursen mit wechselnden Partnern
  anmelden.


  Mehr Infos und Anmelde Formular:


  https://tanzschule-muenchen-dt.de/Tanzsingle-Schnupperworkshop


  Wir freuen uns auf dich und alle anderen Tanzverrückten!


  Dein DT01 Team
organiser: DT01
form: No
createdBy: bxaj6fMe8hgJtXlgRP18azMV3ve2
commentsCount: 0
name: Tanzsingle-Schnupperworkshop
online: No
styles:
  Ballroom:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-27T13:30:00.000Z
username: DT01
viewsCount: 23
