endDate: 2021-07-31T18:00:00.000Z
link: https://www.sonlatino.de/tanzschule/courses.php?Salsa=info&cID=5788
description: >-
  Für alle, die in kubanische Rhythmen eintauchen wollen!

  Ein intensives dreistündiges Cuban Choreo Bootcamp mit Yoel und Alyona

  Sie haben die einzigartige Möglichkeit, an einem intensiven Tanztraining teilzunehmen, das euch nicht nur viel Spaß machen wird, sondern auch eure Tanzkenntnisse auf dem neuen Niveau bringt!

  Ihr lernt viele Elemente verschiedener kubanischer Tänze, die später individuell auf der Tanzfläche angewendet werden können. Und nebenbei arbeitet ihr an euren Körperbewegungen und Musikalität.
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FfPFOWINB1LNTCvLqLWxxgLuYhsX2%2F6acc2af5-df64-4134-ac28-dd1618982386?alt=media&token=f0cb9427-ba91-4a8c-92e2-bf7b99a0e5c6
duration: custom
createdAt: 1627384833390
watchersCount: 0
price: ab 39€
commentsLast: ~
place: ChIJCXjgokgGl0cRf-63THNV_LY
id: GveyrJWmeSqanDGQkCvV
views: 1
updatedAt: 1627384833390
address: Son Latino Tanzschule, Gablonzer Str. 9, 76185 Karlsruhe
updatedBy: fPFOWINB1LNTCvLqLWxxgLuYhsX2
visibility: Public
eventType: Workshop
form: Yes
createdBy: fPFOWINB1LNTCvLqLWxxgLuYhsX2
commentsCount: 0
name: CUBAN CHOREO BOOTCAMP
online: No
styles:
  RumbaGuaguanco:
    level: Intermediate
    highlighted: false
    selected: true
  Mambo:
    level: Intermediate
    highlighted: false
    selected: true
  Salsaton:
    level: Intermediate
    highlighted: false
    selected: true
  Casino:
    level: Intermediate
    highlighted: false
    selected: true
  Afro:
    level: Intermediate
    highlighted: false
    selected: true
region:
  name: Karlsruhe
  location:
    country: Germany
    latitude: 49.0068901
    locality: Karlsruhe
    usedGps: false
    place_id: ChIJCXjgokgGl0cRf-63THNV_LY
    longitude: 8.4036527
startDate: 2021-07-31T15:00:00.000Z
username: alyonadance
viewsCount: 28
