venue:
  website: http://www.studio1-muenchen.de/
  formatted_address: Rosa-Bavarese-Straße 1, 80639 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "1"
      short_name: "1"
    - types:
        - route
      long_name: Rosa-Bavarese-Straße
      short_name: Rosa-Bavarese-Straße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Neuhausen-Nymphenburg
      short_name: Neuhausen-Nymphenburg
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80639"
      short_name: "80639"
  url: https://maps.google.com/?cid=11723615964949206747
  name: Studio One Tanz & Yoga
  geometry:
    viewport:
      south: 48.1454465697085
      north: 48.1481445302915
      east: 11.5044284302915
      west: 11.5017304697085
    location:
      lng: 11.5028515
      lat: 48.14679410000001
  international_phone_number: +49 89 88906075
  place_id: ChIJS_JNfSt2nkcR21blEZumsqI
endDate:
  _seconds: 1634475600
  _nanoseconds: 0
description: >-
  Infos & Location:


  Studio One - Tanz & Yoga

  Rosa-Bavarese-Strasse 1,

  80639 München

  Nähe S-Bhf. Laim

  Anmeldung unter

  callthedancers@gmail.com


  Workshop kosten: 35.00€


  Bei einem Inzidenzwert über 35 gilt während der Veranstaltung die 3G Regel.


  Über Ian Salvador Lopéz


  Der gebürtige Filipino entdeckt seine Leidenschaft für das Tanzen bereits im zarten Alter von 5 Jahren. Als Jugendlicher kommt er mit 14 Jahren von Manila nach Deutschland, wo er seine erste Tanzgruppe MBS Dancers (Mind Body & Soul) 1990 gründet. 1998 spezialisiert er sich auf Salsa und lernt in Los Angeles die Vasquez Brüder kennen, die zu den Machern des Salsa L.A. Styles zählen. Durch die Teilnehme an ihren Workshops entwickelt er seine Kenntnisse immer weiter. Einige Zeit später entsteht dann sein unverwechselbarer eigener Stil in dem er klassische Salsa-Elemente mit anderen Styles, wie Streetdance, Breakdance, Tango, Contemporary und Hebefiguren mischt. Zurück in Berlin arbeitet der junge Tänzer weiter als Tanzlehrer und Choreograf und zieht 2004 schließlich nach München, wo er an allen namhaften Tanzschulen unterrichtet. Im Laufe seiner Karriere wird er Preisträger zahlloser nationaler und internationaler Tanzwettbewerbe. Nach jahrelanger Tanzerfahrung als Lehrer und als Showtänzer internationaler Stars, reicht sein heutiges Repertoire von Break,- und Streetdance hin zu Salsa und Bachata, Capoiera und Tango. Insgesamt beherrscht der Autodidakt und Stipendiat der Oxford Musical Dance Academy über 30 verschiedene Tanzrichtungen. Dieses unschätzbare Know-How, das er sich über die Jahre erworben hat, inspiriert ihn für seine Arbeit als Choreograf. Ian Salvador Lopez hat bis heute zahlreiche bekannte Tänzer ausgebildet. Seine Kurse sind ein einzigartiger Mix in dem er moderne Show-Elemente mit Bachata und Salsa verbindet.
type: event
duration: "120"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2F5e8e7fd0-c37f-4d3b-8353-394c6dfe8a92?alt=media&token=b7249730-219e-4df9-a038-88b164fbe6c9
createdAt: 1633361787494
watchersCount: 0
price: 35 EUR
commentsLast: ~
id: gYERJJxhtqZ7FquW3vsn
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 11
updatedAt: 1633361787494
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Workshop
organiser: LatinoDancer
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Bachata intensive basics
online: No
styles:
  Bachata:
    level: Beginner
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-17T11:00:00.000Z
username: Vitali
viewsCount: 14
