venue:
  website: http://www.antike-am-koenigsplatz.mwn.de/de/staatliche-antiken-sammlungen-muenchen.html
  formatted_address: Königsplatz 1, 80333 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/museum-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "1"
      short_name: "1"
    - types:
        - route
      long_name: Konigsplatz
      short_name: Königsplatz
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Maxvorstadt
      short_name: Maxvorstadt
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80333"
      short_name: "80333"
  url: https://maps.google.com/?cid=17662958789822015550
  name: Staatliche Antikensammlungen
  geometry:
    viewport:
      south: 48.1441349697085
      north: 48.1468329302915
      east: 11.5665336802915
      west: 11.5638357197085
    location:
      lng: 11.5650057
      lat: 48.14519769999999
  place_id: ChIJEYxtM2FynkcRPmi03W9vH_U
  international_phone_number: +49 89 59988830
endDate:
  _seconds: 1635714000
  _nanoseconds: 0
organisedBy: ""
claimed: No
description: Die Forro Gruppe trifft sich wieder spontan zum tanzen
type: event
duration: "120"
cover: ""
createdAt: 1635675155082
watchersCount: 0
price: FREE
commentsLast: ~
promoter: Vitali
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
id: HCReq3iejcX8HW8vTgH3
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 4
updatedAt: 1635675155082
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Party
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Forro Outdoor @ Antikensammlung
online: No
styles:
  ForroLove:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-31T19:00:00.000Z
username: Vitali
viewsCount: 11
