venue:
  formatted_address: Sonnenstraße 7, 80331 München, Germany
  website: http://www.tanzschuleamstachus.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "7"
      short_name: "7"
    - types:
        - route
      long_name: Sonnenstraße
      short_name: Sonnenstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Altstadt-Lehel
      short_name: Altstadt-Lehel
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80331"
      short_name: "80331"
  url: https://maps.google.com/?cid=7618752569010268631
  name: Tanzschule am Stachus
  geometry:
    viewport:
      south: 48.13684386970849
      north: 48.13954183029149
      east: 11.5668774802915
      west: 11.5641795197085
    location:
      lng: 11.56564
      lat: 48.13818409999999
  international_phone_number: +49 1590 1227277
  place_id: ChIJCxXM5ZV1nkcR16lzexg_u2k
endDate:
  _seconds: 1635638400
  _nanoseconds: 0
claimed: Yes
organisedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
link: https://www.eventbrite.de/e/halloween-timbero-tickets-197929270777
description: >-
  Rumber@s


  After stunning first parties, we will bring you a Halloween special of our Timba parties with a dance practice at one of the most beautiful dance rooms in Munich at Tanzschule am Stachus.


  The best of Salsa Cubana, Timba, Songo, Timbaton, Son and the great dancers you know from our parties with cool drinks to fair prices in a scary and amazing atmosphere. Come in a scary costume and awe us with your dance.


  Later at night, one of our favourite dancers will heat up the dance floor: Emi Lederer.


  - Date: 30 October 2021

  - Time: 21:00 - 02:00

  - Place: Tanzschule am Stachus

  - Cover: 10 Euro normal

  - 7 Euros students


  3G-Rules apply. You will have to show a certificate of vaccination, recovery, or negative testing.


  A vacunar!!!
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2Fb2370fb5-3a83-4a9b-b1ff-75ab73ba72d6?alt=media&token=e1f00707-ad06-43a8-a4b1-f17147d79576
duration: "300"
promo: Yes
createdAt: 1635150153876
watchersCount: 0
price: 10EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2Fhe8RxKcOzfmENgqx0nEQ.png?generation=1635150216064597&alt=media
commentsLast: ~
promoter: PapiAlek
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: he8RxKcOzfmENgqx0nEQ
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
international: No
views: 57
updatedAt: 1635150153876
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
visibility: Public
facebook: https://www.facebook.com/events/1989313394576616/
eventType: Party
organiser: salsa.cubana.munich
form: Yes
createdBy: N2N8hjGOw0dU0k0u1mpp0DlGJv93
commentsCount: 0
name: Salsa Cubana - Halloween Timbero
online: No
styles:
  Timba:
    level: Interested
    highlighted: true
    selected: true
  Son:
    level: Interested
    highlighted: true
    selected: true
  Casino:
    level: Intermediate
    highlighted: true
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-30T19:00:00.000Z
username: salsa.cubana.munich
viewsCount: 88
