endDate: 2021-07-23T21:00:00.000Z
description: Reunion Timbera
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FN2N8hjGOw0dU0k0u1mpp0DlGJv93%2F03349638-ebef-4ff7-a68d-286bed5961bf?alt=media&token=e8a25025-2d1a-4700-8b5b-a0c101b30251
duration: custom
createdAt: 1625667907270
watchersCount: 0
price: FREE
commentsLast: ~
id: hFyFnPpszwGATL6n0GVP
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 4
updatedAt: 1625667907270
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
address: Pinakothek der Moderne
visibility: Public
eventType: Party
form: No
createdBy: N2N8hjGOw0dU0k0u1mpp0DlGJv93
commentsCount: 0
name: Reunion Timbera
online: No
styles:
  Casino:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-07-23T17:00:00.000Z
username: salsa.cubana.munich
viewsCount: 5
