venue:
  website: http://www.iwanson.de/
  formatted_address: Adi-Maislinger-Straße 12, 81373 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "12"
      short_name: "12"
    - types:
        - route
      long_name: Adi-Maislinger-Straße
      short_name: Adi-Maislinger-Straße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Sendling-Westpark
      short_name: Sendling-Westpark
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81373"
      short_name: "81373"
  url: https://maps.google.com/?cid=5492811770859622788
  name: Iwanson International School of Contemporary Dance
  geometry:
    viewport:
      south: 48.12758666970849
      north: 48.13028463029149
      east: 11.5369510302915
      west: 11.5342530697085
    location:
      lng: 11.5359317
      lat: 48.12880579999999
  place_id: ChIJG-zlKa7YnUcRhBEsFDRjOkw
  international_phone_number: +49 89 7606085
endDate:
  _seconds: 1637501400
  _nanoseconds: 0
organisedBy: ""
claimed: No
link: ""
description: >+
  SALSA TIMBA FUSION WORKSHOP


  LADIES & GENTS


  ich freu mich Euch diesem Workshop zusammen mit ENERIS MULGADO präsentieren zu dürfen.


  Bei diesem Workshop-Konzept geht es nicht nur um coole Moves.


  Ausdruck und Ausstrahlung ist das Thema... sich in den Bewegungen wohl zu fühlen und dieses Gefühl auf spielerische Art nach außen zu bringen. 


  Egal ob Mann oder Frau. Nutzt diese Möglichkeit und den gegeben Rahmen um Euch auszuprobieren und neu zu entdecken.


  INHALT:


  Die ersten beiden Stunden arbeiten die Jungs und Mädels getrennt.


  Zur dritten Stunden kommen wir zusammen.  Zum letzten Workshop ist aber nicht unbedingt ein Partner erforderlich. Wenn du allerdings einen passenden Tanzpartner hast.... bring ihn mit.


  Die Workshops bauen zum Teil aufeinander auf und einige Elemente finden sich in dem abschließenden PARTNERWORK wieder. Somit ist es zu empfehlen den Workshop von Anfang bis zum Ende zu genießen und die einzelnen Stilelemente zu verinnerlichen.


  ### LOCATION


  Iwanson International School of Contemporary Dance


  ### Adresse


  Adi-Maislinger-Straße 12

  81373 München 


  ### TIMELINE


  10.30 - 11.00    Registrierung


  LADIES


  11.00 - 12.00    REGGAETON

  12.05 - 13.05    LADYSTYLING


  GENTS


  11.00 - 12.00    BODYMOVEMENT/ FOOTWORK 

  12.05 - 13.05    SALSA / RUMBA


  PARTNERWORK (kein Partner dringend erforderlich)


  13.10 - 14.30    SALSA TIMBA FUSION PARTNERWORK


  ### PREIS


  70 Euro    Fullpass (FP)


  25 Euro   1 Workshop


  50 Euro   2 Workshops


  Anmeldung erforderlich unter:


  info@emanuel-lederer.de


  +49 176 82 13 88 90


  PN


  Ich freu mich auf Euer kommen.


  gschmeidig bleiben.

  Euer Emi




type: event
duration: "240"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2Fda6d6aba-bdb4-4c20-b907-54ec753014e5?alt=media&token=132c58ec-c3ac-4c98-9d0f-0f45e7881e05
promo: Yes
createdAt: 1637425211158
watchersCount: 0
price: 25-70EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FhGfnwVHCbEtpRzAqCatX.png?generation=1637425362208102&alt=media
commentsLast: ~
promoter: alejito
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
id: hGfnwVHCbEtpRzAqCatX
international: No
views: 12
updatedAt: 1637425211158
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
visibility: Public
facebook: https://facebook.com/events/s/salsa-timba-fusion/623395768796308/
eventType: Workshop
confirmation: |
  Anmeldung erforderlich unter:

  info@emanuel-lederer.de

  +49 176 82 13 88 90
organiser: ""
form: No
createdBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
commentsCount: 0
name: Salsa Timba Fusion Workshop
online: No
styles:
  Timba:
    level: Intermediate
    highlighted: false
    selected: true
  Reggaeton:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Intermediate
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-21T09:30:00.000Z
username: alejito
viewsCount: 14
