endDate:
  _seconds: 1624131000
  _nanoseconds: 0
description: >-
  Cabaret de Elysion – sinnlich burlesques Programm


  Wir sind die vier Künstlerinnen Poppi Four, Madame Lenè Piuma, Aurora Elysion und Lola Spice und zusammen bilden wir das Cabaret de Elysion.



  Am 19. Juni um 20 Uhr möchten wir euch eine Auswahl aus unserem sinnlich und burlesquen Programms in einem Live Stream und Liveprogramm präsentieren.


  Zur Zeit können wir 20 Leute im Haus der Sinne zulassen.

  Die Vorschriften und Regeln kennt jeder, sie sind bei uns nicht anders. Eine Maske mit bekannten Standard und mit Negativ-Test oder geimpft ist Pflicht.


  Anmelden bitte unter info@hausdersinne-berlin.dehttps://hausdersinne-berlin.de/event/cabaret-de-elysion-sinnlich-burlesques-programm/
type: event
duration: "90"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FKxn6Gu557PawJFIrF6AKpcnSbM12%2Fe85b35e5-63c3-42e9-a1c2-a3ba8d8a8215?alt=media&token=d1ae7207-6e10-476b-8169-d81952e5600f
createdAt: 1622703346047
watchersCount: 0
price: 30- 35 Euro
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FhNIS9jK4l8OCr3PLqdsH.png?generation=1622704914496916&alt=media
commentsLast: ~
place: ChIJAVkDPzdOqEcRcDteW0YgIQQ
id: hNIS9jK4l8OCr3PLqdsH
views: 4
updatedAt: 1622703346047
updatedBy: Kxn6Gu557PawJFIrF6AKpcnSbM12
address: Haus der Sinne Ystader Str. 10
visibility: Public
eventType: Show
form: No
createdBy: Kxn6Gu557PawJFIrF6AKpcnSbM12
commentsCount: 0
name: Cabaret de Elysion
styles:
  Burlesque:
    level: Advanced
    highlighted: false
    selected: true
region:
  name: Berlin
  location:
    country: Germany
    latitude: 52.52000659999999
    locality: Berlin
    usedGps: false
    place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
    longitude: 13.404954
startDate: 2021-06-19T18:00:00.000Z
username: Aurora_Elysion
viewsCount: 56
