endDate:
  _seconds: 1628100000
  _nanoseconds: 0
description: >-
  Song name: Keep it moving

  Artist name: Godzilla a.k.a Nicky Trice

  Dance routine: keepit moving


  Wednesday 4th August we will be doing a professional video shoot of the new Dancehall song by🎤 @godzillaboss_ogs


  All dancers who can come to Munich from 6 to 8 pm are welcome to take part in the shoot.

  Support of each of you is very much appreciated.


  There is the small routine for the song which you all can catch easily:


  <w-instagram url="https://www.instagram.com/p/CR6wlkfiNjg/"></w-instagram>




  And also we would do freestyle videos. So even if you can't catch it you still can participate in it.


  🎬The video shoot will be done by @fabirinho88

  🔊Supported by @wedancemunich
type: event
duration: "120"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FzPEdeDTnNBZwTdhFyRrvCBTMUd52%2Fbecf4796-efec-417c-adbe-6cabe9144dee?alt=media&token=fae6aefb-5a65-4bcd-a77c-9260d1e36a2d
createdAt: 1627827499497
watchersCount: 0
price: FREE
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FhoZu9LnrsN3F7wYeVWMM.png?generation=1627997103440675&alt=media
commentsLast: ~
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: hoZu9LnrsN3F7wYeVWMM
views: 1
updatedAt: 1627827499497
address: Pinakotheken der Moderne
updatedBy: zPEdeDTnNBZwTdhFyRrvCBTMUd52
visibility: Public
eventType: Other
form: No
createdBy: zPEdeDTnNBZwTdhFyRrvCBTMUd52
commentsCount: 0
name: "Professional video shoot (Jamaican Artist) "
online: No
styles:
  StreetDance:
    level: Interested
    highlighted: false
    selected: true
  HipHop:
    level: Interested
    highlighted: false
    selected: true
  UrbanTarraxa:
    level: Interested
    highlighted: false
    selected: true
  Afrobeats:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Commercial:
    level: Interested
    highlighted: false
    selected: true
  Dancehall:
    level: Interested
    highlighted: false
    selected: true
  Reggaeton:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
  Breakdance:
    level: Interested
    highlighted: false
    selected: true
  Breaking:
    level: Interested
    highlighted: false
    selected: true
  Popping:
    level: Interested
    highlighted: false
    selected: true
  Zumba:
    level: Interested
    highlighted: false
    selected: true
  Twerking:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-08-04T16:00:00.000Z
username: oxy
viewsCount: 67
