venue:
  website: http://www.salsabor.de/
  formatted_address: Heßstr. 48b-UG, 80798 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Maxvorstadt
      short_name: Maxvorstadt
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80798"
      short_name: "80798"
  url: https://maps.google.com/?cid=13068910098957006739
  name: Salsabor Dance Academy
  geometry:
    viewport:
      south: 48.1506543197085
      north: 48.1533522802915
      east: 11.5672969802915
      west: 11.5645990197085
    location:
      lng: 11.5659788
      lat: 48.1520512
  place_id: ChIJneG5QOZ1nkcRk_fYMX4YXrU
  international_phone_number: +49 89 52059610
endDate:
  _seconds: 1636498800
  _nanoseconds: 0
organisedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
description: >-
  Jeden Dienstag in der Salsabor Dance Academy:


  ★★★ THE LEGENDARY SOCIAL DANCE PARTY ★★★


  ► SALSA & BACHATA SCHNUPPERKURS für Beginner

  19:00 - 20:00 Uhr mit Rafael, Salsabor Team & Live Percussion


  - RUEDA CLUB

  19:00 - 20:00 Uhr mit Carlos


  - SALSA / MAMBO / BACHATA PARTY

  20:15 - 24:00 Uhr mit DJ


  - ÜBUNGSSTUNDE mit BETREUUNG

  20:15 - 21:15 Uhr mit Carlos


  ## EINTRITT

  - Standard: 10,- €

  - Studenten: 7,- €

  - Im Eintrittspreis ist die Teilnahme am gesamten Programm der Party enthalten.


  ## ANMELDUNG


  - Eine Voranmeldung ist nicht mehr notwendig!

  - Es gilt die 2G Regel (genesen, geimpft). Nachweis bitte am Eingang vorzeigen.

  - Damen bitte keine Schuhe mit „Pfennigabsätzen“ tragen, um unseren Parkettboden zu schonen.

  - Bitte ein zweites Paar saubere Schuhe mitnehmen, am besten nicht mit Gummisohle sondern mit Ledersohle.


  ## ÜBUNGSSTUNDE mit BETREUUNG


  (Für alle Levels, während der Social Dance Party)


  Parallel zu unserer Social Dance Party bieten wir jeden Dienstag von 20:15 bis 21:15 Uhr allen Schülern die Möglichkeit mit einer zusätzlichen Betreuung, das im Kurs Erlernte selbständig zu üben und so sicherer in den Schritten und Figuren zu werden.


  Der Sinn der Übungsstunde ist, dass unsere Schüler in der gewohnten Umgebung mit nicht zu schneller Musik die Figuren anwenden. Des Weiteren steht unser Lehrer Carlos als Hilfestellung zur Verfügung, der euch entsprechend korrigiert und nützliche Tipps gibt
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2F2b23a39a-7938-418d-a283-9d734608d38d?alt=media&token=84de2bb9-103d-47d7-8d1c-2ee1fed03265
duration: "300"
createdAt: 1633176908121
watchersCount: 0
price: 7-10 EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FhRcBzfu1hiPSW55ekhAt.png?generation=1636472460686465&alt=media
commentsLast: ~
id: hRcBzfu1hiPSW55ekhAt
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
views: 35
updatedAt: 1633176908121
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
facebook: https://www.facebook.com/events/619709492810689
eventType: Party
organiser: LatinoDancer
form: No
createdBy: 6J1CzSRNBZbmuKb2J5E0YZRLC0k2
commentsCount: 0
name: THE LEGENDARY SOCIAL DANCE PARTY
online: No
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  SalsaLA:
    level: Interested
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
  RuedaDeCasino:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-09T18:00:00.000Z
username: Carlos
viewsCount: 61
