venue:
  formatted_address: Haager Str. 10A, 81671 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: 10A
      short_name: 10A
    - types:
        - route
      long_name: Haager Straße
      short_name: Haager Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Berg am Laim
      short_name: Berg am Laim
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81671"
      short_name: "81671"
  url: https://maps.google.com/?q=Haager+Str.+10A,+81671+M%C3%BCnchen,+Germany&ftid=0x479ddf8675b6f9ef:0x5bc20b56d9ab355a
  name: Haager Str. 10A
  geometry:
    viewport:
      south: 48.1250709197085
      north: 48.1277688802915
      east: 11.6096432302915
      west: 11.6069452697085
    location:
      lng: 11.6082717
      lat: 48.12640520000001
  place_id: ChIJ7_m2dYbfnUcRWjWr2VYLwls
endDate:
  _seconds: 1635030000
  _nanoseconds: 0
link: https://www.salsa-onstage.de/events-1/
description: >-
  SALSA ON SATURDAY - Übungsabend" 


  1 x im Monat haben wir für euch einen "SALSA ÜBUNGSABEND"

  mit den besten Salsa Hits!

  ═════════════

  ZEIT

  ═════════════

  Samstag, 18.09.2021 

  20:00-21:00 Uhr Workshop "Salsa Social Moves" zur Einstimmung im Intermediate Level. Nur paarweise Anmeldung möglich. 

  ab 21:00-01:00 Uhr

  mit den besten Hits aus Salsa (80%) & Bachata (20%)

  ═════════════

  PREIS

  ═════════════

  Übungsabend: 10 € regulär pro Person

  + Workshop 10 € pro Person 

  ═════════════

  ORT

  ═════════════

  ONSTAGE LOFT 4.0

  Haagerstr.10a

  81671 München

  Das Studio ist direkt am Ostbahnhof in der Haagerstr.10a. Wir sind allerbestens mit dem MVV erreichbar. 

  ═════════════

  Wir freuen uns auf Euch! 
type: event
cover: ""
duration: "240"
createdAt: 1633486147538
watchersCount: 0
price: 10 EUR
commentsLast: ~
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: hsiT6XU64pPvgCWnUZsi
views: 24
updatedAt: 1633486147538
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Party
organiser: LatinoDancer
form: Yes
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Salsa Übungsabend im OneStage
online: No
styles:
  SensualBachata:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
  SalsaLA:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-23T19:00:00.000Z
username: Vitali
viewsCount: 28
