venue:
  formatted_address: Westenriederstraße 41, 80331 München, Germany
  website: http://www.salsaclub-munich.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "41"
      short_name: "41"
    - types:
        - route
      long_name: Westenriederstraße
      short_name: Westenriederstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Altstadt-Lehel
      short_name: Altstadt-Lehel
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80331"
      short_name: "80331"
  url: https://maps.google.com/?cid=17999243784988121499
  name: Salsa Club Munich by Hakan
  geometry:
    viewport:
      south: 48.13373901970849
      north: 48.13643698029149
      east: 11.5813456802915
      west: 11.5786477197085
    location:
      lng: 11.5800076
      lat: 48.1351427
  place_id: ChIJU60HW-F1nkcRm9nfvdsoyvk
  international_phone_number: +49 172 8533891
endDate:
  _seconds: 1633719600
  _nanoseconds: 0
description: >-
  Before Bachata Sensual night you can attend Bachata Sensual intermediate
  workshop with Anna and Paolo


  Costs 15 EUR Workshop+Party
type: event
duration: 60
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2Fe43bbe0e-b49d-4186-a7f5-807db93254a5?alt=media&token=5e09bd67-615c-4ead-99bb-6c8ae3e735de
createdAt: 1633359728933
watchersCount: 0
price: 15 EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FI2av4rgVBwOlJWXCE7Dk.png?generation=1633434940733990&alt=media
commentsLast: ~
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: I2av4rgVBwOlJWXCE7Dk
views: 2
updatedAt: 1633359728933
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Workshop
organiser: LatinoDancer
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Pre-Party Bachata Workshop with Anna and Paolo
online: No
styles:
  SensualBachata:
    level: Intermediate
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-08T18:00:00.000Z
username: Vitali
viewsCount: 8
