venue:
  website: http://www.salsaclub-munich.de/
  formatted_address: Westenriederstraße 41, 80331 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "41"
      short_name: "41"
    - types:
        - route
      long_name: Westenriederstraße
      short_name: Westenriederstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Altstadt-Lehel
      short_name: Altstadt-Lehel
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80331"
      short_name: "80331"
  url: https://maps.google.com/?cid=17999243784988121499
  name: Salsa Club Munich by Hakan
  geometry:
    viewport:
      south: 48.13373901970849
      north: 48.13643698029149
      east: 11.5813456802915
      west: 11.5786477197085
    location:
      lng: 11.5800076
      lat: 48.1351427
  place_id: ChIJU60HW-F1nkcRm9nfvdsoyvk
  international_phone_number: +49 172 8533891
organisedBy: GOiMAEyBEZXKlHSYBAhfAg3RfDB3
claimed: Yes
link: https://www.tickettailor.com/events/bachatasensualnight/596579
type: event
promo: Yes
createdAt: 1635160907512
watchersCount: 0
price: 10EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FI5dJz4Ezb7XRXaqQPMV8.png?generation=1635161046077529&alt=media
commentsLast: ~
promoter: Djobi_bachata
id: I5dJz4Ezb7XRXaqQPMV8
promotedBy: GOiMAEyBEZXKlHSYBAhfAg3RfDB3
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 17
updatedAt: 1635160907512
website: http://www.bachata-sensual.party
updatedBy: GOiMAEyBEZXKlHSYBAhfAg3RfDB3
visibility: Public
eventType: Party
confirmation: |-
  Dear Bachataero, dear Bachatera,

  thank you for coming to our party.

  Bachata Sensual Nights Team
organiser: Djobi_bachata
form: Yes
createdBy: GOiMAEyBEZXKlHSYBAhfAg3RfDB3
commentsCount: 0
online: No
styles:
  Bachata:
    level: Interested
    selected: true
  Salsa:
    level: Interested
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
username: Djobi_bachata
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FGOiMAEyBEZXKlHSYBAhfAg3RfDB3%2F7b90a279-02fe-4e1c-947f-a15f0a8bc27e?alt=media&token=0c0b56e4-cc42-4737-b502-9f4f8116a75c
name: Bachata Sensual Night Dj Obi
startDate: 2022-03-18T20:00
org:
  youtube: ""
  facebook: ""
  bio: Best Bachata DJ In Town 😎🎛️
  photo: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FGOiMAEyBEZXKlHSYBAhfAg3RfDB3%2F2b02213c-5a3b-4fa8-a5ed-f43b4b2c3deb?alt=media&token=e633e9a5-89ee-45ef-9ec6-7476e6560576
  instagram: djobi_bachata
  tiktok: ""
  name: Dj Obi
  id: GOiMAEyBEZXKlHSYBAhfAg3RfDB3
  username: Djobi_bachata
description: >+
  Vamos a dentro, chicos!


  ACHTUNG DAS IST EINE PRIVATE VERANSTALTUNG!


  Vamos a dentro, chicos!


  Langsam aber sicher haben wir auch die letzte Corona Welle hinter uns gelassen. Es ist wieder Zeit raus zu gehen, spaß zu haben und zu feiern. Das lässt sich am besten zur gute Musik und mit den besten Tänzern der Stadt. Wir laden euch herzlich wieder zu unserem Bachata Sensual Nights ein.


  Join us for the best Bachata Sensual Event In Munich! 


  ![](https://uploads.tickettailor.com/c_limit,w_630/v1/production/userfiles/event_description_image_105946_1645364364_11790.jpg)


  Der Salsa Club Munich, einer der schönsten Locations im Herzen Münchens, wartet auf Euch. Vorbei sind die Zeiten mit Steinboden, Regen und Non-Tänzer, wir sagen: hallo Tanzparkett! Wir bewegen uns gemeinsam zu Bachata Sensual, über Dominicana bis hin zu Bachata Moderna (und vielleicht sogar etwas Salsa).


  Wir haben haben einen ganz besonderen Special für euch Vorbereitet:


  Wir starten den Abend mit einem tollen Lady Styling Workshop!!! 


  Eine der besten Lady Styling Artistin aus München zeigt euch neue Moves und wie Ihr eure Lady Styling aufs nächste Level bringt👩🏼‍🚒🔥🔥. 


  BACHATA SENSUAL NIGHTS BY DJ OBI PRESENTS:


  ![](https://uploads.tickettailor.com/c_limit,w_630/v1/production/userfiles/event_description_image_105946_1647167343_6a39c.jpg)


  Preis: 20 € inkl. 2,50 € Getränkegutschein

  Level: Beginner / Intermediate

  Zeit: 19:00 - 20:00


  After the Lady Styling Workshop you can enjoy the current choreo created by Vero herself with the OnStagy Lady Styling Group:


  ![](https://uploads.tickettailor.com/c_limit,w_630/v1/production/userfiles/event_description_image_105946_1647169221_05369.png)



  Übungsabend:


  Start: 20:00 bis 23:45


  Preis: 10 € + 2,50 € Getränkegutschein


  COVID INFO:


  DE


  Solltest du weder geimpft , genesen oder negativ getestet sein, ist der Einlass nicht gestattet, wir bitten um dein Verständnis.


  Aufgrund des Corona-Hygienekonzepts & der laufenden Verordnungen sind limitierte Tickets verfügbar.


  Wir freuen uns über deinen Ausweis/Reisepass und die notwendigen Dokumente, die deine Impfung / Genesung / negativ Test belegen.


  EN


  If you are not vaccinated , recovered or tested there is no entry permitted, we appreciate your understanding.


  Limited tickets available due to the corona hygiene concept & ongoing regulations.


  We would appreciate your ID, passport, and necessary documents that prove your vaccination & recovery or tested ready at the door.




  <w-youtube url="https://www.youtube.com/watch?v=LU6wymgFAWU&feature=emb_title"></w-youtube>


  ![](https://uploads.tickettailor.com/c_limit,w_630/v1/production/userfiles/event_description_image_105946_1633263046_91f33.jpg)


  ![](https://uploads.tickettailor.com/c_limit,w_630/v1/production/userfiles/event_description_image_105946_1633263642_62f1a.jpg)


  <w-teaser

  title="Bachata Sensual Night by DJ Obi"

  description="Best Bachata Party in Munich"

  button="GET TICKET"

  href="https://www.tickettailor.com/events/bachatasensualnight/596579"></w-teaser>


duration: custom
endDate: 2022-03-19T02:00
viewsCount: 31
