venue:
  formatted_address: Zenettistraße 7, 80337 München, Germany
  website: https://www.salsa-y-corazon.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "7"
      short_name: "7"
    - types:
        - route
      long_name: Zenettistraße
      short_name: Zenettistraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Ludwigsvorstadt-Isarvorstadt
      short_name: Ludwigsvorstadt-Isarvorstadt
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80337"
      short_name: "80337"
  url: https://maps.google.com/?cid=8616399599048238742
  name: Salsa Y Corazon - dance school
  geometry:
    viewport:
      south: 48.12187606970849
      north: 48.12457403029149
      east: 11.5593379802915
      west: 11.5566400197085
    location:
      lng: 11.557894
      lat: 48.12314479999999
  place_id: ChIJ7SAJ9Rd3nkcRlqYWoMiZk3c
  international_phone_number: +49 172 9659579
endDate:
  _seconds: 1639850400
  _nanoseconds: 0
claimed: No
organisedBy: ""
description: >-
  

  *👉🏾ES WERDEN KEINE ANTIGEN TEST MEHR BEI UNS ZUR VERFÜGUNG GESTELLT!!👈🏾*


  *TESTSTATION AN DER TUMBLINGERSTR.29 / ECKE ZENETTISTR. BIS 20:00 UHR GEÖFFNET!!*

  *Maske von Eingang bis zur Kasse tragen*

  *Bitte das Impf- oder Genesen Zertifikat mit PCR oder Antigen Test an der Tür, mit Ausweis, vorzeigen.*

  PCR (< 48 Std.) oder Antigen Test (< 24 Std.) 
          🌴 🌴 🌴 🌴 🌴
  *WORKSHOP:*

  *SALSA L.A. Style Mittelstufe mit *MARION* 

  Möglichst paarweise anmelden

  18 - 19 Uhr Workshop: 10€
         🌴 🌴 🌴 🌴 🌴


  Veranstalter: *SALSAFREAKS* 



  Registrierung für *den L.A. Style SALSA Workshop mit Marion*:👇🏿

  Info@salsa-y-corazon.de
type: event
cover: ""
duration: 60
createdAt: 1639690541321
watchersCount: 0
price: 10 EUR
commentsLast: ~
promoter: Vitali
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: IfSHfrMIXqiFl3Su1Dz6
international: No
views: 4
updatedAt: 1639690541321
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Workshop
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: L.A. Style SALSA Workshop mit Marion
online: No
styles:
  SalsaLA:
    level: Intermediate
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-12-18T17:00:00.000Z
username: Vitali
viewsCount: 6
