endDate: 2021-09-18T22:00:00.000Z
link: https://forms.gle/YWbChCYn4PFhyfSo6
description: |-
  😍 NEW CONCEPT !

  📍 MÜNCHEN 🗓 19.09.2021 / SONNTAG

  ••••••••••••••••••••••••••••••

  ### ⭐️ Bootcamp [B]: Sergio & Marichu 

  👉🏾 aus SPANIEN 

  🗣 2 Stunden 

  ➡️ Intermediate-Advance 
   
  ••••••••••••••••••••••••••••••

  ### ⭐️ Bootcamp [B]: Migo & Rebecca

  🗣 2 Stunden 

  ➡️ Open Level 

  ••••••••••••••••••••••••••••••

  ### ⭐️ Party [P]: DJ MIGO 

  ••••••••••••••••••••••••••••••

  💶 1 B + P = 35€ 

  💶 1 B = 20€

  💶 P = 20€ 

  ••••••••••••••••••••••••••••••

  🆘 Hier anmelden : 

  https://forms.gle/YWbChCYn4PFhyfSo6
type: event
duration: custom
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F8yp79cUd0jZtnVn34NxhBuMpxrx1%2Fced87774-887b-464e-8349-af2b5acce1db?alt=media&token=6a4b6db6-2a2b-4ea0-b768-8887bd7c312e
createdAt: 1631172651270
watchersCount: 0
price: 20 - 35 EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FIqEDFXUYZcANGplos7pq.png?generation=1631175850083507&alt=media
commentsLast: ~
id: IqEDFXUYZcANGplos7pq
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 12
updatedAt: 1631172651270
updatedBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
visibility: Public
eventType: Workshop
organiser: AnnaMil
form: Yes
createdBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
commentsCount: 0
name: Dansecrecy Bachata
online: No
styles:
  SensualBachata:
    level: Intermediate
    highlighted: false
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-09-19T15:30:00.000Z
username: AnnaMil
viewsCount: 21
