endDate:
  _seconds: 1628287200
  _nanoseconds: 0
description: "Kizomba Bacata Salsa und Regaton "
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2Fn5MNiqrsocfZBDNVx1GlIIfeiiK2%2Fd82852d5-7ddf-4bbd-b1c0-d41719668037?alt=media&token=ec0c91c1-cdc4-4518-80a4-2f3ac600864e
duration: "300"
createdAt: 1627661037137
watchersCount: 0
price: 10,00 €
commentsLast: ~
id: IvmhlcDMTArT77ZWuwqs
place: ChIJCXjgokgGl0cRf-63THNV_LY
views: 3
updatedAt: 1627661037137
updatedBy: n5MNiqrsocfZBDNVx1GlIIfeiiK2
address: "Max Garden Karlsruhe "
visibility: Public
eventType: Party
form: No
createdBy: n5MNiqrsocfZBDNVx1GlIIfeiiK2
commentsCount: 0
name: Kibasa
online: No
region:
  name: Karlsruhe
  location:
    country: Germany
    latitude: 49.0068901
    locality: Karlsruhe
    usedGps: false
    place_id: ChIJCXjgokgGl0cRf-63THNV_LY
    longitude: 8.4036527
startDate: 2021-08-06T17:00:00.000Z
username: KiBaSa
viewsCount: 5
