endDate:
  _seconds: 1613676600
  _nanoseconds: 0
city: Munich
description: |-
  Content:
  Technique men and women + Figures and Sequences! 

  Bachata Basics necessary

  only 10€ per course!
type: event
duration: "60"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F8yp79cUd0jZtnVn34NxhBuMpxrx1%2F75c08b01-5f8e-4780-b510-5f7d0905483d?alt=media&token=a27e34f6-72ba-4580-899a-3a3a825e5e26
createdAt: 1611436038645
watchersCount: 0
commentsLast: ~
id: ixF5Mknuz1P1VzNOFZDC
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 1
updatedAt: 1617065902046
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
address: Online
visibility: Public
eventType: Course
organiser: Salsa y Corazon
form: No
createdBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
commentsCount: 0
name: Bachata Sensual Style
styles:
  Bachata:
    level: Interested
    selected: true
  SensualBachata:
    level: Interested
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-02-18T18:30:00.000Z
username: AnnaMil
viewsCount: 2
