endDate: 2022-01-01T03:00:00.000Z
organisedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
claimed: Yes
link: http://www.bachata-sensual.party
description: >-
  Dear lovely community,


  due to the new Corona regulations and rules we have to cancel our Silvester Event. From 28th of  December only 10 people are allowed to come together and meet if they are vaccinated and 2 if they are not. Since we have to follow these rules we will cancel all events until further notice. 


  **All the tickets have been refunded already.** We all hope this will be over soon and that we can come together and dance together again. If there are any news regarding our parties we will keep you updated.
type: event
promo: Yes
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2F9ab8d608-0841-4670-9db3-05a0af371cbb?alt=media&token=195506ac-1db4-4b99-b7ba-87f487ae29d5
createdAt: 1634544361668
watchersCount: 0
price: 35EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2Fj0AiNl0Nj3IUvVGxpjNm.png?generation=1639129695720641&alt=media
commentsLast: ~
promoter: Djobi_bachata
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
id: j0AiNl0Nj3IUvVGxpjNm
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 72
updatedAt: 1634544361668
website: https://www.bachata-sensual.party
updatedBy: GOiMAEyBEZXKlHSYBAhfAg3RfDB3
visibility: Public
eventType: Party
confirmation: "Thank you for registering. "
organiser: Djobi_bachata
form: No
createdBy: GOiMAEyBEZXKlHSYBAhfAg3RfDB3
commentsCount: 0
name: Bachata White Silvester Gala By DJ Obi (Cancelled)
online: No
styles:
  Bachata:
    level: Interested
    selected: true
  Salsa:
    level: Interested
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-12-31T20:00:00.000Z
username: Djobi_bachata
viewsCount: 81
