venue:
  website: http://www.salsa-onstage.de/
  formatted_address: Haager Str. 10a, 81671 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: 10a
      short_name: 10a
    - types:
        - route
      long_name: Haager Straße
      short_name: Haager Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Berg am Laim
      short_name: Berg am Laim
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81671"
      short_name: "81671"
  url: https://maps.google.com/?cid=3637923077162623314
  name: Salsa OnStage
  geometry:
    viewport:
      south: 48.1251639197085
      north: 48.12786188029149
      east: 11.6095120802915
      west: 11.6068141197085
    location:
      lng: 11.6082717
      lat: 48.1264051
  international_phone_number: +49 178 3034004
  place_id: ChIJEx0xXYXfnUcRUmF5nsN_fDI
endDate:
  _seconds: 1639864800
  _nanoseconds: 0
claimed: No
organisedBy: ""
link: https://www.salsa-onstage.de/%C3%BCbungsabend/
description: >-
  Liebe OnStage Freunde,


  am Samstag, den 18.12.21 feiern wir unsere Weihnachtsfeier in etwas kleineren Rahmen. 


  Ab 18:30 Uhr habt hier die Möglichkeit in die Salsa & Bachata Tänze einzutauchen! 


  ab 19:30 Uhr dann auf einer Salsa  und einer Bachata Tanzfläche eure Skills anwenden!


  Höhepunkt ist um 21:00 Uhr die Premiere unserer Choreoprojects :) 


  ## ZEIT:


  - 18:00 Uhr:  Einlass 


  - 18:30 Uhr: Salsa Schnupperkurs


  - 19:00 Uhr: Bachata Schnupperkurs


  - ab 19:30 Uhr: Salsa & Bachata zum Tanzen und genießen


  - 21:00 Uhr: Showpremieren der Choreogruppen


  - 23:00 Uhr: Ende


  ## EINTRITT: (limitierte Teilnehmerzahl)


  aufgrund der aktuellen Corona-Regelungen für Bayern gilt Einlass nur


  für 2G+ (Geimpft, Genesen + Schnelltest).


  Hier eine Übersicht über kostenlose Schnelltest-Stationen:  https://www.testen-muenchen.de


  Wir freuen uns auf Euch
type: event
promo: No
duration: "300"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2F114930d5-0d7f-458f-b514-784e0bf8d8d7?alt=media&token=fce24544-cd55-4ea5-88c3-813fe26a3178
createdAt: 1639847759436
watchersCount: 0
price: 10 EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FJ1W25iaCtsB7nMYXzW4a.png?generation=1639850415948987&alt=media
commentsLast: ~
promoter: alejito
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: J1W25iaCtsB7nMYXzW4a
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
international: No
views: 5
updatedAt: 1639847759436
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
visibility: Public
eventType: Party
organiser: ""
form: No
createdBy: 5hkUljYCTSPJwsDqNqgGYRe1Tok2
commentsCount: 0
name: Weihnachtsfeier Salsa/Bachata
online: No
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-12-18T17:00:00.000Z
username: Promoter
viewsCount: 14
