venue:
  website: http://www.tanzschule-tanzraum.de/
  formatted_address: Salierring 33, 50677 Köln, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "33"
      short_name: "33"
    - types:
        - route
      long_name: Salierring
      short_name: Salierring
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Innenstadt
      short_name: Innenstadt
    - types:
        - locality
        - political
      long_name: Köln
      short_name: Köln
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Köln
      short_name: Kreisfreie Stadt Köln
    - types:
        - administrative_area_level_2
        - political
      long_name: Köln
      short_name: K
    - types:
        - administrative_area_level_1
        - political
      long_name: Nordrhein-Westfalen
      short_name: NRW
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "50677"
      short_name: "50677"
  url: https://maps.google.com/?cid=8536046700639217950
  name: Tanzschule tanzraum Köln Zentrum
  geometry:
    viewport:
      south: 50.9259685197085
      north: 50.9286664802915
      east: 6.945530880291503
      west: 6.942832919708498
    location:
      lng: 6.944104800000001
      lat: 50.927315
  international_phone_number: +49 221 233233
  place_id: ChIJjVZ9yVUkv0cRHum-kT8hdnY
endDate: 2021-10-18T17:00:00.000Z
link: https://www.eventbrite.de/e/pure-bachata-weekend-i-melvin-gatica-i-emerson-alara-i-dj-fran-tickets-164370266893?aff=ebdssbdestsearch
description: >-
  Mit Melvin & Gatica 🔥🔥🔥 Das erste mal in Deutschland!


  Tanzraum präsentiert das nächste Pure Bachata Weekend! 3 Tage gefüllt mit Workshops, Practice Nights sowie wundervollen Tänzen und Menschen.


  https://www.facebook.com/events/s/pure-bachata-weekend-i-melvin-/376198383912794/
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F5hkUljYCTSPJwsDqNqgGYRe1Tok2%2Fd444f6b9-47f0-42fc-8932-a00cc08a6df1?alt=media&token=ee342eee-20a1-4a97-a538-2fad2b4f5e61
duration: custom
promo: ""
createdAt: 1632144624859
watchersCount: 0
price: TICKETS
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2Fj6dsWrUWg2XODT0BHuoG.png?generation=1632144650439043&alt=media
commentsLast: ~
place: ""
id: j6dsWrUWg2XODT0BHuoG
views: 21
updatedAt: 1632144624859
updatedBy: 5hkUljYCTSPJwsDqNqgGYRe1Tok2
visibility: Public
eventType: Festival
organiser: Promoter
form: Yes
createdBy: 5hkUljYCTSPJwsDqNqgGYRe1Tok2
commentsCount: 0
name: Pure Bachata Weekend
online: No
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
startDate: 2021-10-15T16:00:00.000Z
username: Promoter
viewsCount: 27
