venue:
  website: http://www.sonlatino.de/
  formatted_address: Gablonzer Str. 9, 76185 Karlsruhe, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "9"
      short_name: "9"
    - types:
        - route
      long_name: Gablonzer Straße
      short_name: Gablonzer Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Mühlburg
      short_name: Mühlburg
    - types:
        - locality
        - political
      long_name: Karlsruhe
      short_name: Karlsruhe
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Karlsruhe
      short_name: Kreisfreie Stadt Karlsruhe
    - types:
        - administrative_area_level_2
        - political
      long_name: Karlsruhe
      short_name: KA
    - types:
        - administrative_area_level_1
        - political
      long_name: Baden-Württemberg
      short_name: BW
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "76185"
      short_name: "76185"
  url: https://maps.google.com/?cid=8926798613940117231
  name: Son Latino Dance Studio
  geometry:
    viewport:
      south: 49.02229426970851
      north: 49.02499223029151
      east: 8.354233980291502
      west: 8.351536019708497
    location:
      lng: 8.352825700000002
      lat: 49.0236634
  international_phone_number: +49 721 6638886
  place_id: ChIJ12tDlScHl0cR755ZDQtc4ns
endDate: 2021-09-19T01:00:00.000Z
link: https://forms.gle/24w1Gs8RsV7Xdtfc8
description: >-
  18:30 - 20:30 - 2h Bachata-Bootcamp mit Sergio und Marichu aus Spanien - ⚠️
  Level: Intermediate/Advanced ⚠️


  21:00 - Party mit DJ Dimen5ions aus London/UK


  Eintritt: 

  Bootcamp + Party: 35 EUR

  Party: 15 EUR


  Bewährtes und durchdachtes Hygienekonzept unter Befolgung der aktuellsten Richtlinien (CoronaVO BW). Einlass nur unter Beachtung von 3G (Getestet, geimpft oder genesen).
type: event
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FTv49tJF9gQbN5et4IAsF4Hlg8V63%2Fae7bb185-e8c7-41a8-a9bf-d7cea8a67138?alt=media&token=64df37cb-0a81-4a60-b342-1b9e54871c84
duration: custom
createdAt: 1629828467217
watchersCount: 0
price: 15 - 35 EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FjKE3RJIfT9IU78DToTYf.png?generation=1629828499227065&alt=media
commentsLast: ~
id: jKE3RJIfT9IU78DToTYf
place: ChIJCXjgokgGl0cRf-63THNV_LY
views: 1
updatedAt: 1629828467217
updatedBy: Tv49tJF9gQbN5et4IAsF4Hlg8V63
visibility: Public
eventType: Party
organiser: Flo.Oteca
form: Yes
createdBy: Tv49tJF9gQbN5et4IAsF4Hlg8V63
commentsCount: 0
name: Dansecrecy Bachata
online: No
styles: {}
region:
  name: Karlsruhe
  location:
    country: Germany
    latitude: 49.0068901
    locality: Karlsruhe
    usedGps: false
    place_id: ChIJCXjgokgGl0cRf-63THNV_LY
    longitude: 8.4036527
startDate: 2021-09-18T16:30:00.000Z
username: Flo.Oteca
viewsCount: 16
