venue:
  website: http://www.hayal-orientalmoves.de/
  formatted_address: Körtestraße 10, 10967 Berlin, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "10"
      short_name: "10"
    - types:
        - route
      long_name: Körtestraße
      short_name: Körtestraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Bezirk Friedrichshain-Kreuzberg
      short_name: Bezirk Friedrichshain-Kreuzberg
    - types:
        - locality
        - political
      long_name: Berlin
      short_name: Berlin
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Berlin
      short_name: Kreisfreie Stadt Berlin
    - types:
        - administrative_area_level_1
        - political
      long_name: Berlin
      short_name: BE
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "10967"
      short_name: "10967"
  url: https://maps.google.com/?cid=16554958696186229049
  name: Hayal Oriental Moves
  geometry:
    viewport:
      south: 52.48985896970851
      north: 52.49255693029151
      east: 13.41249738029151
      west: 13.4097994197085
    location:
      lng: 13.4110381
      lat: 52.4912961
  place_id: ChIJzTjeT85PqEcRObFx5TgHv-U
  international_phone_number: +49 1523 3816766
endDate:
  _seconds: 1639846800
  _nanoseconds: 0
organisedBy: KWqY4P1fsaOxPLVjG4mf9V7lqJG3
claimed: Yes
link: bachatadominicana.berlin@gmail.com
description: >-
  Wir bekommen Besuch von Becky Díaz aus der Tanzschule „ANIMO“ in Mannheim.
  Zusammen haben wir tolle Workshops für euch vorbereitet, die es sonst so in
  Berlin nicht gibt.


  https://www.facebook.com/becky.diaz.98


  Becky Díaz, eine Tänzerin, die mit ihrer Energie alle ansteckt. Sie ist bekannt für ihre Technik, ihr cleanes Footwork und besonderes Styling.


  Als halb Spanierin startet sie dort ihre Tanzkarriere mit einer Grundlagenausbildung in Salsa, Bachata und Kizomba. In Deutschland beendet sie ihre Ausbildung als Tanzlehrerin unter der Leitung von Inaki Fernandez in der Tanzschule Animo – Mannheim. Aktuell unterrichtet sie deutschlandweit und trainiert und performt mit ihrer Showgruppe „Las Soneras“ auf Events und Festivals.

  Sie ist stetig am Wachsen und liebt es, ihr Wissen und ihre Leidenschaft zu teilen.


  ## Programm:


  ### 14:00 – 15:15: LadyStyling Bachata Dominicana mit Nora


  *(Open Level, Grundlagen und Basics sind Voraussetzung)*


  In diesem Workshop wollen wir uns voll und ganz auf die Essenz der traditionellen Bachata fokussieren und an unserem Bodymovement von Kopf bis Fuß arbeiten. Wir werden an verschiedene Stylingelemente arbeiten, die für die gewisse Würze in unseren Basics sorgen. In Form einer kleinen Kombination lernt ihr euer neues Wissen anzuwenden und euch selbst beim Tanzen zu genießen.


  ### 15:15 – 16:30: LadyStyling Bachata Fusion mit Becky


  *(Open Level, Grundlagen und Basics sind Voraussetzung)*


  In diesem Workshop erarbeiten wir eine Kombination, bestehend aus verschiedenen Elementen aus Dominican Bachata und Sensual Bachata. Der Fokus liegt hier auf dem Bodymovement und dem Armstyling, vor allem aber auf der richtigen Technik.


  ### 16:30 – 17:45: Footwork Bachata Dominicana mit Becky


  *(Level Intermediate)*


  In diesem Workshop konzentrieren wir uns auf Fußarbeit und Musikalität. Hier lernt ihr die richtige Technik für Balance und Gewichtswechsel, sowie den coolen Flow.


  ## Preise:


  - Workshops einzeln: 20 € / Person

  - Workshop Paket (alle drei Workshops): 50 € / Person


  ## Anmeldung und Infos unter:


  Bachatadominicana.berlin@gmail.com


  ## Location:


  Tanzstudio Hayal – Körtestraße. 10, 10967 Berlin


  **Achtung:** Straßenschuhe sind im Studio nicht erlaubt, bitte bringt euch Wechselschuhe mit. Umkleiden befinden sich in der Tanzschule. Bitte kommt pünktlich.


  Diese Veranstaltung läuft nach den aktuellen Corona Bestimmungen als 2G Plus Veranstaltung (geimpft / genesen plus einen tagesaktuell Schnelltest, bitte einen Nachweise mitbringen). Alle Workshops sind Solo Kurse und die Teilnehmerzahl ist begrenzt. Wir werden regelmäßig Lüften und Abstand einhalten. Weniger anzeigen
type: event
duration: "240"
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FKWqY4P1fsaOxPLVjG4mf9V7lqJG3%2Fca0c64c1-5b8c-4eb4-af76-8e4ba7e510e2?alt=media&token=ce836916-d2c9-42b5-84e5-887579c439b8
createdAt: 1638969373529
watchersCount: 0
price: 1x Workshop 20 € / Workshop Paket 50 €
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FjpRU4XDmedQAu53ZLklU.png?generation=1638991079589612&alt=media
commentsLast: ~
promoter: Nora_Berlin
promotedBy: KWqY4P1fsaOxPLVjG4mf9V7lqJG3
id: jpRU4XDmedQAu53ZLklU
place: ChIJAVkDPzdOqEcRcDteW0YgIQQ
international: No
views: 5
updatedAt: 1638969373529
updatedBy: KWqY4P1fsaOxPLVjG4mf9V7lqJG3
visibility: Public
facebook: https://fb.me/e/1mHWduFTj
eventType: Workshop
organiser: Nora_Berlin
form: Yes
createdBy: KWqY4P1fsaOxPLVjG4mf9V7lqJG3
commentsCount: 0
name: Bachata Day - Dominican Vibes
online: No
styles:
  Bachata:
    level: Intermediate
    highlighted: false
    selected: true
  DominicanBachata:
    level: Intermediate
    highlighted: false
    selected: true
region:
  name: Berlin
  location:
    country: Germany
    latitude: 52.52000659999999
    locality: Berlin
    usedGps: false
    place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
    longitude: 13.404954
startDate: 2021-12-18T13:00:00.000Z
username: Nora_Berlin
viewsCount: 19
