venue:
  website: http://www.dance-station.com/
  formatted_address: Humboldtstraße 29, 81543 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "29"
      short_name: "29"
    - types:
        - route
      long_name: Humboldtstraße
      short_name: Humboldtstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Au-Haidhausen
      short_name: Au-Haidhausen
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81543"
      short_name: "81543"
  url: https://maps.google.com/?cid=2688866178684697913
  name: Dance School DANCE STATION
  geometry:
    viewport:
      south: 48.1182934197085
      north: 48.1209913802915
      east: 11.5764630802915
      west: 11.5737651197085
    location:
      lng: 11.575148
      lat: 48.11968
  place_id: ChIJrQnEp27fnUcROT0QFYvFUCU
  international_phone_number: +49 89 65114404
endDate:
  _seconds: 1637427600
  _nanoseconds: 0
organisedBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
claimed: Yes
link: https://jonsky-la-kossa.eventbrite.com
description: >-
  Gezwungen früher einen Ringer zu sein ist er heute ein großartiger Tänzer und
  Lehrer, der in Brooklyn gelernt hat.. Jon Sky...

  In diesem Workshop erlebst Tanz mit Kultur. Wir legen Fokus auf Geschichte, Interkation, Gemeinschaft. Eine Choreo wir aber nicht fehlen. Sei gespannt!
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FqTPAP7OhWMYjtoPXtpUJavNz5Fr2%2F63249286-711c-4d0d-9aef-1f53c6ff2601?alt=media&token=2cc3c6f9-c79e-465c-aea3-f6a16b8514ee
promo: Yes
duration: "180"
createdAt: 1635636394006
watchersCount: 0
price: ""
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FjsBct3xY58MGZs68XrXs.png?generation=1635853962945051&alt=media
commentsLast: ~
promoter: lakossa
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: jsBct3xY58MGZs68XrXs
promotedBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
international: No
views: 8
updatedAt: 1635636394006
website: http://www.la-kossa.de
updatedBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
visibility: Public
facebook: https://www.facebook.com/lakossa.fitness
eventType: Workshop
organiser: la.kossa
form: No
createdBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
commentsCount: 0
name: Hip Hop meets Afrobeats
online: No
styles:
  HipHop:
    level: Interested
    highlighted: false
    selected: true
  Afrobeats:
    level: Advanced
    highlighted: false
    selected: true
  Breakdance:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-20T14:00:00.000Z
username: lakossa
viewsCount: 69
