venue:
  formatted_address: Kolonnenstraße, Berlin, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png
  html_attributions: []
  address_components:
    - types:
        - route
      long_name: Kolonnenstraße
      short_name: Kolonnenstraße
    - types:
        - locality
        - political
      long_name: Berlin
      short_name: Berlin
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Berlin
      short_name: Kreisfreie Stadt Berlin
    - types:
        - administrative_area_level_1
        - political
      long_name: Berlin
      short_name: BE
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
  url: https://maps.google.com/?q=Kolonnenstra%C3%9Fe,+Berlin,+Germany&ftid=0x47a8503e72662a1d:0xe292c0697ea26ebe
  name: Kolonnenstraße
  geometry:
    viewport:
      south: 52.4837413197085
      north: 52.4864392802915
      east: 13.3656237802915
      west: 13.3629258197085
    location:
      lng: 13.3642748
      lat: 52.4850903
  place_id: EiBLb2xvbm5lbnN0cmHDn2UsIEJlcmxpbiwgR2VybWFueSIuKiwKFAoSCR0qZnI-UKhHEb5uon5pwJLiEhQKEgkBWQM_N06oRxFwO15bRiAhBA
endDate:
  _seconds: 1636750800
  _nanoseconds: 0
claimed: No
organisedBy: ""
link: ""
description: |-
  Schedule for next Friday party: (12-Nov)
  ❥ 21:00 - 22:00 Pre-social Workshop by Hari & Lilien
  ❥ 22:00 - 03:00 Non-stop Bachata Social with music from DJ DennisS
  ❥ ENTRANCE FEE: 6 € without Workshop, 8 € with Workshop
  ❥ LOCATION: Tanzschule Mambita Etage
  Kolonnenstraße 29, 10829 Berlin
  Join us to set the dance floor on 🔥🔥🔥!
  😷😷 SAFETY FOR ALL: Entrance only with 2G (recovered, vaccinated)!
type: event
promo: No
duration: 60
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FdRipXa4eZJVowvrrUWYYeyZvGnI3%2Fc8f1daea-64c3-4cab-99c4-776e62c12df2?alt=media&token=c478e761-3b65-46ba-a726-40f601ee4be3
createdAt: 1636368316820
watchersCount: 0
price: 8 EUR including party
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2Fk8k5KShakeZGV2F2fjCP.png?generation=1636715999921856&alt=media
commentsLast: ~
promoter: Bachata_Hari
promotedBy: dRipXa4eZJVowvrrUWYYeyZvGnI3
id: k8k5KShakeZGV2F2fjCP
place: ChIJAVkDPzdOqEcRcDteW0YgIQQ
international: No
views: 6
updatedAt: 1636368316820
updatedBy: dRipXa4eZJVowvrrUWYYeyZvGnI3
visibility: Public
facebook: https://facebook.com/events/s/fuego-100-bachata-on-fire/572850093996450/
eventType: Workshop
organiser: ""
form: No
createdBy: dRipXa4eZJVowvrrUWYYeyZvGnI3
commentsCount: 0
name: FUEGO bachata party
online: No
styles:
  SensualBachata:
    level: Intermediate
    highlighted: false
    selected: true
  Bachata:
    level: Beginner
    highlighted: false
    selected: true
region:
  name: Berlin
  location:
    country: Germany
    latitude: 52.52000659999999
    locality: Berlin
    usedGps: false
    place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
    longitude: 13.404954
startDate: 2021-11-12T20:00:00.000Z
username: Bachata_Hari
viewsCount: 59
