venue:
  website: https://fitnessanddance.center/
  formatted_address: Kurfürstenstraße 8, 80799 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "8"
      short_name: "8"
    - types:
        - route
      long_name: Kurfürstenstraße
      short_name: Kurfürstenstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Maxvorstadt
      short_name: Maxvorstadt
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80799"
      short_name: "80799"
  url: https://maps.google.com/?cid=4968408430539880362
  name: Fitness and Dance Munich
  geometry:
    viewport:
      south: 48.1529793197085
      north: 48.15567728029149
      east: 11.5777645802915
      west: 11.5750666197085
    location:
      lng: 11.5764797
      lat: 48.154286
  international_phone_number: +49 172 7328816
  place_id: ChIJfUVB3L11nkcRqrdi0SRV80Q
endDate:
  _seconds: 1638720000
  _nanoseconds: 0
claimed: Yes
organisedBy: XvsfaoTDLsWQoEInXA1DDTrNQNM2
description: >-
  🔥💃🏻 Registration open!


  🗓 SUN 05.12 🕚 14:00-17:00


  ✨Salsa Feminine Fusion Bootcamp ✨ with Yulia Ventum & Federica Caruso


  Ladies, we are back with our 2nd Bootcamp

  and looking forward to share with you our NEW fusion of femeninity, elegance and spice ♥️ 


  In our Bootcamp we will work on these elements:


  ➡️ Feminine Ladystyle - you will learn how to add to your dance elegance & femininity, esthetics, how to be natural & sexy while dancing. We will work on: bodymovement, fluidity, lines, techniques of hands, arms, shoulders, upper-body & hips.


  ➡️ Energy - you will learn how to feel the music, how to connect with the music, how to bring your character and soul into the dance.


  ➡️ Fusion - you will learn how to combine different elements & techniques.


  ➡️ Musicality - you will learn how to listen to the music & how to build harmonic moves on the music.


  Level: Open Level

  Price: 60€


  🗓 SUN 05.12 🕚 14:00-17:00

  📍 Fitness & Dance München, Kurfürstenstraße 8, 80799 München 


  ‼️ COVID rules will have to be observed. We except event to be subject to 2G rule.


  ‼️ Number of participants is limited. Participation is possible only with registration.
type: event
duration: "180"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FXvsfaoTDLsWQoEInXA1DDTrNQNM2%2F1aa56f32-6082-40f1-a3cb-9e9364bb0cd1?alt=media&token=4bbbd3ab-0656-4d6d-8cac-6be4e37b9274
promo: Yes
createdAt: 1636725923843
watchersCount: 0
price: 60€
commentsLast: ~
promoter: yulia_ventum
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: K91AbSCJQmm8gP9Yzcq1
promotedBy: XvsfaoTDLsWQoEInXA1DDTrNQNM2
international: No
views: 11
updatedAt: 1636725923843
updatedBy: XvsfaoTDLsWQoEInXA1DDTrNQNM2
visibility: Public
eventType: Workshop
organiser: ""
form: No
createdBy: XvsfaoTDLsWQoEInXA1DDTrNQNM2
commentsCount: 0
name: Salsa Feminine Fusion Bootcamp
online: No
styles:
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-12-05T13:00:00.000Z
username: yulia_ventum
viewsCount: 47
