endDate:
  _seconds: 1630090800
  _nanoseconds: 0
description: |-
  ## Salsa on2 Ws am Gottesaueschloß
   
  - Niveau: Mittelstufe 

  - Auf Spendenbasis 

  <w-instagram url="https://www.instagram.com/p/CSC0_3QiC4r/">
type: event
duration: "60"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FSxx9Y1rMeEh8vmaIhFsWRWzeooA2%2F66cb6968-ac75-4a8c-82dd-076f99f023be?alt=media&token=59c31689-6bce-403a-a72a-a0b365124f78
createdAt: 1628316214008
watchersCount: 0
price: "Donation-based "
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FkSlvrB2xph9u3Uwsrlzw.png?generation=1628338351032330&alt=media
commentsLast: ~
id: kSlvrB2xph9u3Uwsrlzw
place: ChIJCXjgokgGl0cRf-63THNV_LY
views: 2
updatedAt: 1628316214008
address: 49°00'17.4"N 8°25'33.3"E
updatedBy: Sxx9Y1rMeEh8vmaIhFsWRWzeooA2
visibility: Public
eventType: Workshop
form: No
createdBy: Sxx9Y1rMeEh8vmaIhFsWRWzeooA2
commentsCount: 0
name: Nico - Open Air Salsa WS on2
online: No
styles:
  SalsaNewYork:
    level: Interested
    highlighted: false
    selected: true
  Mambo:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Karlsruhe
  location:
    country: Germany
    latitude: 49.0068901
    locality: Karlsruhe
    usedGps: false
    place_id: ChIJCXjgokgGl0cRf-63THNV_LY
    longitude: 8.4036527
startDate: 2021-08-27T18:00:00.000Z
username: prinhony
viewsCount: 43
