venue:
  formatted_address: Am Einlaß 2A, 80469 München, Germany
  website: http://buena-vista-bar.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: 2A
      short_name: 2A
    - types:
        - route
      long_name: Am Einlaß
      short_name: Am Einlaß
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Altstadt-Lehel
      short_name: Altstadt-Lehel
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80469"
      short_name: "80469"
  url: https://maps.google.com/?cid=10819607444887102927
  name: Bar Buena Vista
  geometry:
    viewport:
      south: 48.1323055697085
      north: 48.1350035302915
      east: 11.5760210802915
      west: 11.5733231197085
    location:
      lng: 11.5746203
      lat: 48.1336406
  place_id: ChIJ6dF5E2DfnUcRz-WqeaX3JpY
  international_phone_number: +49 89 26022811
endDate:
  _seconds: 1634515200
  _nanoseconds: 0
organisedBy: ""
claimed: No
description: Noche Latina Party With Changing DJs
type: event
promo: ""
cover: ""
duration: "240"
createdAt: 1633767864774
watchersCount: 0
price: FREE
commentsLast: ~
promoter: Vitali
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
id: kyWDL5bEOTABqazBDwnD
international: No
views: 10
updatedAt: 1633767864774
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Party
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Cuba Party @ Buena Vista Bar
online: No
styles:
  Timba:
    level: Interested
    highlighted: false
    selected: true
  RumbaColumbia:
    level: Interested
    selected: true
  Merengue:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Intermediate
    highlighted: false
    selected: true
  DominicanBachata:
    level: Interested
    selected: true
  Cubaton:
    level: Interested
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-17T20:00:00.000Z
username: Vitali
viewsCount: 16
