venue:
  formatted_address: 81243 Munich, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/shopping-71.png
  html_attributions: []
  address_components:
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Pasing-Obermenzing
      short_name: Pasing-Obermenzing
    - types:
        - locality
        - political
      long_name: Munich
      short_name: Munich
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Upper Bavaria
      short_name: Upper Bavaria
    - types:
        - administrative_area_level_1
        - political
      long_name: Bavaria
      short_name: BY
    - types:
        - postal_code
      long_name: "81243"
      short_name: "81243"
  url: https://maps.google.com/?cid=10140352089264226498
  name: Mercedes-Benz
  geometry:
    viewport:
      south: 48.1443810697085
      north: 48.1470790302915
      east: 11.4468578802915
      west: 11.4441599197085
    location:
      lng: 11.4455475
      lat: 48.1456026
  place_id: ChIJP0zYmP_XnUcRwgD80X_EuYw
endDate: 2021-10-31T03:00:00.000Z
organisedBy: ""
claimed: No
link: https://bit.ly/3vfeoJ6
description: >-
  Bienvenido al infierno! 🎃 Munich de Noche lädt ein zur Halloween Party à lo
  Latino. Am Sa, den 30.10.21 zelebrieren wir im Headquarter vom Mercedes Benz
  Haus in München den "Día de los Muertos" mit einer gespenstigen Dekoration und
  einer geballten Power Latinbeats.


  ▶️ Ticketlink: https://bit.ly/3vfeoJ6


  Die Location ist an Exklusivität kaum zu überbieten. Wir feiern i 13 Stock in 65 Meter Höhe der Mercedes Benz Niederlassung die gruseligste Halloween Party der Stadt. DJ Javier & DJ Deli verwandeln die Tanzfläche mit den besten Latin Beats aus Reggaeton / Merengue / Bachata / Dembow in ein gespenstiges Fest. Weitere Specials, farbenprächtige und gespenstige Halloween Dekoration werden nicht fehlen.


  ❌ WICHTIGE INFO ❌

  Dieses Event findet gemäß der aktuellen Coronaverordnung statt. 

  • Zutritt zur Veranstaltung nach dem 2G-Prinzip nur für Geimpfte oder Genesene. Impfausweis / Genesenennachweis muss am Einlass vorgezeigt werden.

  • Keine Maskenpflicht

  • Es darf getanzt werden 💃

  • Die Eintrittskarten für diese Veranstaltung sind sehr limitiert. Wir empfehlen daher unbedingt den Vorverkauf zu nutzen. Link: https://bit.ly/3vfeoJ6
type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2Fffa5c89a-ba0b-4310-8060-6a2e2c3d7e4c?alt=media&token=4e3637a7-6b41-43e1-b04b-63367a49395c
createdAt: 1634181292081
watchersCount: 0
price: 15 EUR
commentsLast: ~
promoter: Vitali
id: L5I3jZH2MAhLwtHepWPY
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 14
updatedAt: 1634181292081
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
facebook: https://facebook.com/events/s/halloween-latino-secret-locati/346788703802090/
viewsCount: 14
eventType: Party
organiser: ""
form: Yes
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Halloween Latino Party@ Secret Location
online: No
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Reggaeton:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-30T20:00:00.000Z
username: Vitali
