endDate:
  _seconds: 1625508000
  _nanoseconds: 0
link: https://forms.gle/ethSxksUmifSe5G8A
description: >-
  Dear lovely Dancers in our Community, 


  Last year we presented you BachaKizZouk Mondays where we offered 3 workshops in 3 dance styles every Monday for over 2 Months to help you discover new dance styles that you are not used to dance.


  The event was a big success 😍 


  This year we improved the Idea and made it Bigger!! 🤩 


  This year & starting this coming *Monday 05.07.2021*, we are proud to present to you:


  🤯 **MOADC All-Dance Mondays** 🤯 


  **Bachata - Salsa - Kizomba - Zouk - Forró** 


  5 Dance Styles 5 Paralel Workshops for Free  5 Times more Fun!! **ONE Dance Community** 💃🕺 


  Limited Number of Participants per workshop, 1st come 1st served concept apply, so make sure to register fast.


  **Important**


  This event is completely **For Free** and is **not getting any money** from any Donation **Money Pool** made by any one from the dance Community.


  The registration for this coming MOADC All-Dance Monday's Workshops is *now open!!* 


  This Monday we have the Following Workshops: 


  - Bachata Basics by Migo & Rebecca

  - UrbanKiz by Sandra & Sabine

  - Salsa Casino by Alex & Valentina

  - Brasilian Zouk by Henning & Sigrid

  - Forró by Sami 


  All Workshops are Beginners Friendly 

  From 19:00 till 20:00 O'clock 


  **!! Please Note !!**


  MOADC All-Dance Monday Event *does NOT* include any Parties after the workshops.

  And is 100% Free Event.


  We *do NOT* receive any money or any Donation from any *Money-Pool* done by any Community member. 


  Please register yourself *only one time* and if you have any problems please let me know :) 


  *Registration Formular:* 


  https://forms.gle/ethSxksUmifSe5G8A 


  **Registration closes Saturday at 23 Uhr unless it is over booked before this, so please be fast 😊**


  **Please notice the following Rules during the Workshops:** 


  1. We start exactly at 19Uhr and end at 20Uhr, so please come on Time between 18:30 and 18:45 


  2. If you come alone, you will be assigned a partner before the beginning of the workshop. 


  3. If you are planning to come with a partner, please tell your partner to register him/her self as well online. 


  4. There is only places for 9 leaders and 9 followers in each workshop. 


  5. There will not be any partner change during the workshop. 


  6. Please keep 1.5m distance between yourself and the couple dancing next to you at the workshop. 


  7. Your registration doesn't guarantee that you will get a place in the workshop.. the 1st 18 people to come for each workshop to the location between 18:30 and 19:00 will get the place and of course they have to be pre-registered online. 


  8. If the workshop you registered for got full, you can switch to another workshop as long as they still have space. 


  9. There is no switching workshops after the workshop start. 


  10. All 5 workshops are for free 😉✌🏻 


  See you on Monday 05.July 💃🕺


  Be Ready tonight 😉


  Your **MOADC All-Dance** Team
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2F9c744bdc-871d-4611-811f-65fbca6f3341?alt=media&token=ed9a5d06-0c0c-470b-a811-f8d14e0cd9f7
duration: "60"
createdAt: 1625160599754
watchersCount: 0
price: FREE
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FLM8H7P95VJitpFnq9IHi.png?generation=1625161977310894&alt=media
commentsLast: ~
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: LM8H7P95VJitpFnq9IHi
views: 12
updatedAt: 1625160599754
updatedBy: mbBRluXxyeg1983QPK8wNgl0sO52
address: Pinakothek der Moderne
visibility: Public
eventType: Workshop
form: Yes
createdBy: mbBRluXxyeg1983QPK8wNgl0sO52
commentsCount: 0
name: MOADC All-Dance Mondays
styles:
  UrbanKizz:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  ForroLove:
    level: Interested
    highlighted: false
    selected: true
  BrazilianZouk:
    level: Interested
    highlighted: false
    selected: true
  RuedaDeCasino:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-07-05T17:00:00.000Z
username: Munich
viewsCount: 191
