venue:
  website: http://www.delmenhorst.de/
  formatted_address: Delmenhorst, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png
  html_attributions: []
  address_components:
    - types:
        - locality
        - political
      long_name: Delmenhorst
      short_name: DEL
    - types:
        - administrative_area_level_3
        - political
      long_name: Delmenhorst
      short_name: Delmenhorst
    - types:
        - administrative_area_level_1
        - political
      long_name: Lower Saxony
      short_name: NDS
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
  room: Test 2
  url: https://maps.google.com/?q=Delmenhorst,+Germany&ftid=0x47b0d50e13957643:0x34ca4f544513871b
  name: Delmenhorst
  geometry:
    viewport:
      south: 52.98676568181241
      north: 53.10910143602285
      east: 8.711392684286144
      west: 8.578763001455648
    location:
      lng: 8.635593199999999
      lat: 53.0521886
  map: ""
  place_id: ChIJQ3aVEw7VsEcRG4cTRVRPyjQ
organisedBy: U3J34xyfYLcaTMH6tRYg0mMPg4x2
claimed: Yes
description: A test event
type: event
cover: ""
duration: 60
createdAt: 1638964427307
watchersCount: 0
price: 0 EUR
commentsLast: ~
promoter: iDance
place: ""
promotedBy: U3J34xyfYLcaTMH6tRYg0mMPg4x2
id: McL52cxZYW7l1OxZFH9I
international: No
views: 2
updatedAt: 1638964427307
updatedBy: U3J34xyfYLcaTMH6tRYg0mMPg4x2
visibility: Public
eventType: Party
organiser: iDance
form: No
createdBy: U3J34xyfYLcaTMH6tRYg0mMPg4x2
commentsCount: 0
name: test
online: No
styles:
  Afrobeats:
    level: Interested
    highlighted: false
    selected: true
  Afro:
    level: Interested
    highlighted: false
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
username: iDance
viewsCount: 3
