venue:
  formatted_address: Barer Str. 40, 80333 München, Germany
  website: https://www.pinakothek-der-moderne.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/museum-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "40"
      short_name: "40"
    - types:
        - route
      long_name: Barer Straße
      short_name: Barer Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Maxvorstadt
      short_name: Maxvorstadt
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80333"
      short_name: "80333"
  url: https://maps.google.com/?cid=14384342178029021798
  room: Area 3
  name: Pinakothek der Moderne
  geometry:
    viewport:
      south: 48.1457500697085
      north: 48.1484480302915
      east: 11.5730605802915
      west: 11.5703626197085
    location:
      lng: 11.5723021
      lat: 48.1471559
  map: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2F54d1467f-62f9-4002-a37d-7e6e37ed0420?alt=media&token=676da4ef-b6c3-4a92-8de0-42370c700d71
  place_id: ChIJW8LuYO51nkcRZqoW2f9yn8c
  international_phone_number: +49 89 23805360
endDate:
  _seconds: 1628953200
  _nanoseconds: 0
description: >-
  Learn Casino (Salsa Cubana) basics in 1 month.


  - **Price:** free, optional donation

  - **Duration:** course includes 4 lessons, 1h every Saturday


  ### Course Program


  - Lesson 1. Introduction to rhythm and basic steps

  - **Lesson 2. Partner work and turns**

  - Lesson 3. Cross-body lead

  - Lesson 4. First choreography



  ### Instructor


  <w-profile username="alexrazbakov"></w-profile>



  ### Reviews


  > Viktoria: Alex gives a great Salsa lesson for very beginners. I can highly recommend it, because he teaches not only basic steps, but gives a lot of information about Salsa. The atmosphere is very friendly and relaxing. 

  I will definitely take more lessons with Alex as soon as I am back in Munich.


  > Masha: Montuno Club is the perfect place to start learning salsa - even for the real beginners with no dancing skills. Alexey is giving as much staff as needed so that you don't get bored, but also don't get overwhelmed. It's a very nice and friendly atmosphere here. As a nice bonus, Alex gives his best not only to teach you salsa, but also to introduce the salsa/dance world of Munich to you and connect all dancers together within a community. He also arranges rueda evenings where people with different knowledge and skills get togetger and enjoy dancing. As a bonus #2, you learn a bit of Spanish 🙂 I strongly recommend Montuno club for everyone who would like to start dancing/keep dancing 🙂


  [See all reviews on Facebook](https://www.facebook.com/montunoclub/reviews/)
type: event
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2Fef717276-b15e-4b8f-a3c6-395de9fce30b?alt=media&token=51f72e98-29e1-431e-a413-217f974d6a6e
duration: "60"
createdAt: 1627228515311
watchersCount: 0
price: FREE
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FmfguKeTWYc17eje9ZRdv.png?generation=1628602467883732&alt=media
commentsLast: ~
id: mfguKeTWYc17eje9ZRdv
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 2
updatedAt: 1627228515311
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
address: Pinakothek der Moderne
visibility: Public
eventType: Course
form: No
createdBy: ICpCp7IBpMe30vAHqYfw4FmQp382
commentsCount: 0
name: Salsa Cubana from Zero 2/4 (Cancelled)
online: No
styles:
  Salsa:
    level: Interested
    highlighted: false
    selected: true
  Casino:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-08-14T14:00:00.000Z
username: MontunoClub
viewsCount: 51
