venue:
  website: http://www.isarpost-eventlocation.de/
  formatted_address: Sonnenstraße 24-26, 80331 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: 24-26
      short_name: 24-26
    - types:
        - route
      long_name: Sonnenstraße
      short_name: Sonnenstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Ludwigsvorstadt-Isarvorstadt
      short_name: Ludwigsvorstadt-Isarvorstadt
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80331"
      short_name: "80331"
  url: https://maps.google.com/?cid=14604975425998091393
  name: ISARPOST Eventlocation
  geometry:
    viewport:
      south: 48.1337302197085
      north: 48.1364281802915
      east: 11.5665639302915
      west: 11.5638659697085
    location:
      lng: 11.5650711
      lat: 48.13503660000001
  place_id: ChIJg2EMgljfnUcRgfTs-8RLr8o
  international_phone_number: +49 89 1499037894
endDate:
  _seconds: 1636851600
  _nanoseconds: 0
claimed: No
organisedBy: ""
description: >-
  Kommt und feiert mit uns auf der beste REGGAETON / LATIN Party der Stadt


  #MÜNCHENTANTZWIEDER ❤️


  Wann: SA 13.11.2021 ab 21 Uhr bis 02 Uhr (Aufgrund des Tanzverbotes)

  Wo: ISARPOST - Sonnenstr. 24 - 26

  Eintritt: 12€ / 2 G REGEL +: geimpft, genesen

  Musik: REGGAETON, modern merengue & bachata, dembow, brazil vibes. DJ YENNY & TORI SEGURA 🎧 💯


  Ven a bailar, que comience la fiesta!


  🌴🍍☀️ 


  🇪🇸 Español:

  🥂 🎉 Te invitamos a la fiesta latina mas buena de Munich 💃🏽🕺🏽❤️

  El sábado 13.11. desde las 22 horas en el ISARPOST - Sonnenstrasse 24-26

  Entrada: 12€ y con las 2 G

  Nos vemos! 😍
type: event
promo: ""
duration: "240"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2F15f99bef-9ad3-42b5-88ff-c66392f7e444?alt=media&token=e77db550-2135-4996-a6bb-16b71d4d183e
createdAt: 1636533080013
watchersCount: 0
price: 12 EUR
commentsLast: ~
promoter: Vitali
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: MhkRDLqfdSX0LrALA5Vm
international: No
views: 10
updatedAt: 1636533080013
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Party
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Munich Reggaeton Party @Isarpost
online: No
styles:
  RumbaGuaguanco:
    level: Interested
    selected: true
  BachataModerna:
    level: Intermediate
    highlighted: false
    selected: true
  Salsaton:
    level: Interested
    selected: true
  SalsaCalena:
    level: Interested
    selected: true
  RumbaColumbia:
    level: Interested
    selected: true
  Bachata:
    level: Intermediate
    highlighted: false
    selected: true
  Merengue:
    level: Interested
    selected: true
  SensualBachata:
    level: Interested
    selected: true
  DominicanBachata:
    level: Interested
    selected: true
  Salsa:
    level: Intermediate
    highlighted: false
    selected: true
  SalsaLA:
    level: Interested
    selected: true
  Cubaton:
    level: Interested
    selected: true
  Bachatango:
    level: Interested
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-13T21:00:00.000Z
username: Vitali
viewsCount: 91
