endDate:
  _seconds: 1625929200
  _nanoseconds: 0
city: Munich
link: ""
description: >
  Learn Salsa Casino basics in 1 month.


  Course includes 4 lessons, 1h every Saturday.


  ### Course Program


  - **Lesson 1. Introduction to rhythm and basic steps (clave, son montuno, casino basico)**

  - Lesson 2. Partner work and turns (giro, vuelta)

  - Lesson 3. Cross-body lead (dile que si, dile que no)

  - Lesson 4. Walk around (enchufla)


  ### Price


  - free, optional donation


  ### Teacher


  <w-profile username="Guantanamero"></w-profile>
type: event
duration: "60"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2F0f0f41be-1069-4e69-bf4f-2a869b336156?alt=media&token=d2a76909-957b-48d4-aab6-f9ac02179c6a
createdAt: 1601376998962
watchersCount: 0
price: FREE
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FMtthszDeW66ocIwofqoL.png?generation=1625745581466494&alt=media
commentsLast: ~
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: MtthszDeW66ocIwofqoL
views: 2
updatedAt: 1617065896502
address: Pinakothek der Moderne
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
visibility: Public
eventType: Course
organiser: MontunoClub
form: No
createdBy: ICpCp7IBpMe30vAHqYfw4FmQp382
commentsCount: 0
name: Salsa From Zero 1/4
online: No
styles:
  Salsa:
    level: Interested
    highlighted: false
    selected: true
  Casino:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-07-10T14:00:00.000Z
username: MontunoClub
viewsCount: 54
