venue:
  formatted_address: Rue de Wittelsheim, 68950 Reiningue, France
  website: http://www.cvmulhouse.asso.fr/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png
  html_attributions: []
  address_components:
    - types:
        - route
      long_name: Rue de Wittelsheim
      short_name: Rue de Wittelsheim
    - types:
        - locality
        - political
      long_name: Reiningue
      short_name: Reiningue
    - types:
        - administrative_area_level_2
        - political
      long_name: Haut-Rhin
      short_name: Haut-Rhin
    - types:
        - administrative_area_level_1
        - political
      long_name: Grand Est
      short_name: Grand Est
    - types:
        - country
        - political
      long_name: France
      short_name: FR
    - types:
        - postal_code
      long_name: "68950"
      short_name: "68950"
  url: https://maps.google.com/?cid=193638286809435818
  name: Club de Voile Mulhouse
  geometry:
    viewport:
      south: 47.7683856697085
      north: 47.7710836302915
      east: 7.238918730291501
      west: 7.236220769708496
    location:
      lng: 7.237683
      lat: 47.769697
  international_phone_number: +33 3 89 55 40 15
  place_id: ChIJN6LA426EkUcRqg4x9P7wrwI
endDate: 2021-08-23T09:00:00.000Z
link: https://facebook.com/events/s/djamka-beach-social-day/224942052839309/
type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2Fi5jK4FKAJZbFoxYoQAMM0Llifho2%2Fd4b00b9a-13cf-4410-b78c-f64934839cd4?alt=media&token=c4d41c82-38c9-4d57-81a6-be0ee6d574a6
createdAt: 1628621115161
watchersCount: 0
price: 15€
commentsLast: ~
id: NayqR9nUcsfvzLUuf1IO
place: ""
views: 1
updatedAt: 1628621115161
updatedBy: i5jK4FKAJZbFoxYoQAMM0Llifho2
visibility: Public
eventType: Party
organiser: SwetlanaK
form: Yes
createdBy: i5jK4FKAJZbFoxYoQAMM0Llifho2
commentsCount: 0
name: Djamka Beach Social Day
online: Yes
styles:
  UrbanKizz:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
startDate: 2021-08-15T08:00:00.000Z
username: SwetlanaK
viewsCount: 2
