venue:
  formatted_address: Helfenrieder Straße 12, 81379 München, Germany
  website: http://www.sugarmountain-munich.com/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "12"
      short_name: "12"
    - types:
        - route
      long_name: Helfenrieder Straße
      short_name: Helfenrieder Straße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Thalkirchen-Obersendling-Forstenried-Fürstenried-Solln
      short_name: Thalkirchen-Obersendling-Forstenried-Fürstenried-Solln
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81379"
      short_name: "81379"
  url: https://maps.google.com/?cid=3343453655232852903
  name: Sugar Mountain
  geometry:
    viewport:
      south: 48.0958116697085
      north: 48.0985096302915
      east: 11.5200816802915
      west: 11.5173837197085
    location:
      lng: 11.5187217
      lat: 48.0971913
  place_id: ChIJ2-pVNOrZnUcRp7Mik2JVZi4
endDate:
  _seconds: 1633813200
  _nanoseconds: 0
description: |-
  Tango-Live-Musik mit QUINTETO GARUFA
  und LO DE LAURA

  Eintritt: 15,-

  ​

  Abendkasse + Vorverkauf möglich (empfohlen!!)

  KAYMY LLAQTAY e.V.
  IBAN: DE40 7115 2570 0012 1948 82
  Kreissparkasse Miesbach-Tegernsee
  Verwendungszweck: Name, Tag, Event (Milonga/Musical/Konzert
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2F2f3ac194-eecc-459c-a8c4-d9fc3e823600?alt=media&token=1727bfda-bb68-4d77-9db8-a19fefa94b81
duration: "240"
createdAt: 1633508349282
watchersCount: 0
price: 15 EUR
commentsLast: ~
id: NDID5A3K1WA87fMgV4GK
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 6
updatedAt: 1633508349282
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Party
organiser: LatinoDancer
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Milonga in Sougar Mountain
online: No
styles:
  Tango:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-09T17:00:00.000Z
username: Vitali
viewsCount: 61
