endDate: 2021-04-17T19:30:00.000Z
link: http://shumdesalsa.com/workshops
description: >-
  Die Tanzschulen  "Shumdesalsa" (Toronto) und "Son Latino" (Karlsruhe)
  präsentieren:

   Workshops per Zoom mit Yoel und Alyona Dance 

  Samstag, 10. April 2021


  Cuban Salsa Ladystyle


  19:30 Uhr (Berlin)

  14:30 Uhr (Toronto)




  Salsa Casino (Partnerwork)


  20:30 Uhr (Berlin)

  15:30 Uhr (Toronto)
   

  Samstag, 17. April 2021


  Cuban Salsa Men Style


  19:30 Uhr (Berlin)

  14:30 Uhr (Toronto)



  Salsa Casino (Partnerwork)


  20:30 Uhr (Berlin)

  15:30 Uhr (Toronto)


  Für mehr Informationen... 

  https://www.shumdesalsa.com/workshops





  <w-youtube url="https://www.youtube.com/watch?v=1RwEBDkhnOQ&ab_channel=YoelandAlyonaDance"></w-youtube>
type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FfPFOWINB1LNTCvLqLWxxgLuYhsX2%2F01b374b2-9a89-4816-81e8-fc43396ef38a?alt=media&token=aa6d810c-14d4-4494-83b2-57ba38bea704
createdAt: 1617694379067
watchersCount: 0
price: ab (from) 20$
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FNi0PZX0iVn6ONyMxkYEX.png?generation=1617695131388268&alt=media
commentsLast: ~
id: Ni0PZX0iVn6ONyMxkYEX
views: 1
updatedAt: 1617694379067
updatedBy: fPFOWINB1LNTCvLqLWxxgLuYhsX2
address: Online (Zoom)
visibility: Public
viewsCount: 1
eventType: Workshop
form: Yes
createdBy: fPFOWINB1LNTCvLqLWxxgLuYhsX2
commentsCount: 0
name: Cuban Salsa Online Workshops
styles:
  Timba:
    level: Interested
    highlighted: false
    selected: true
  Casino:
    level: Interested
    highlighted: false
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
startDate: 2021-04-10T17:30:00.000Z
username: alyonadance
