endDate:
  _seconds: 1633730400
  _nanoseconds: 0
organisedBy: ""
claimed: No
type: event
duration: "300"
cover: ""
createdAt: 1633720075931
watchersCount: 0
price: FREE
commentsLast: ~
promoter: alexrazbakov
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
id: NjPiLkkjImW8RsBPIcIH
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 2
updatedAt: 1633720075931
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
visibility: Public
eventType: Party
organiser: ""
form: No
createdBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
commentsCount: 0
name: Bachata Freaks
online: No
styles:
  SensualBachata:
    level: Interested
    highlighted: true
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-08T17:00:00.000Z
username: alejito
viewsCount: 3
