venue:
  formatted_address: 2nd backyard - only by elevator, Reichenberger Str. 113A,
    10999 Berlin, Germany
  website: http://ashtangahouse.com/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - point_of_interest
        - establishment
      long_name: 2nd backyard - only by elevator
      short_name: 2nd backyard - only by elevator
    - types:
        - street_number
      long_name: 113A
      short_name: 113A
    - types:
        - route
      long_name: Reichenberger Straße
      short_name: Reichenberger Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Bezirk Friedrichshain-Kreuzberg
      short_name: Bezirk Friedrichshain-Kreuzberg
    - types:
        - locality
        - political
      long_name: Berlin
      short_name: Berlin
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Berlin
      short_name: Kreisfreie Stadt Berlin
    - types:
        - administrative_area_level_1
        - political
      long_name: Berlin
      short_name: BE
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "10999"
      short_name: "10999"
  url: https://maps.google.com/?cid=2711764098885099617
  name: Ashtanga House Berlin
  geometry:
    viewport:
      south: 52.4930803697085
      north: 52.49577833029149
      east: 13.4358690302915
      west: 13.4331710697085
    location:
      lng: 13.4345947
      lat: 52.4945219
  place_id: ChIJ0fN6fQpPqEcRYSC0lBQfoiU
endDate: 2021-10-01T20:00:00.000Z
type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FEUuKwggiZjcEiZMOzXV5P8U6lQh2%2F3d4d16bc-4dca-4e03-854b-367bd4bae0fa?alt=media&token=35327476-3021-47c8-8ce9-fc7af0051d32
promo: Yes
createdAt: 1633111155062
watchersCount: 0
price: 55€
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FnTndBKOGhDc0LypzX8kR.png?generation=1633113916780165&alt=media
commentsLast: ~
id: nTndBKOGhDc0LypzX8kR
place: ChIJAVkDPzdOqEcRcDteW0YgIQQ
views: 6
updatedAt: 1633111155062
updatedBy: EUuKwggiZjcEiZMOzXV5P8U6lQh2
visibility: Public
eventType: Workshop
organiser: Julchik
form: No
createdBy: EUuKwggiZjcEiZMOzXV5P8U6lQh2
commentsCount: 0
name: West Coast Swing Crash Course
online: No
styles:
  WestCoastSwing:
    level: Beginner
    highlighted: false
    selected: true
region:
  name: Berlin
  location:
    country: Germany
    latitude: 52.52000659999999
    locality: Berlin
    usedGps: false
    place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
    longitude: 13.404954
startDate: 2021-10-09T14:00:00.000Z
username: Julchik
viewsCount: 64
