endDate:
  _seconds: 1642795200
  _nanoseconds: 0
claimed: Yes
organisedBy: 6dTh2GAJnkb5YXqwyOoQ34Dyi9d2
type: event
promo: No
duration: 60
cover: ""
createdAt: 1640018421802
watchersCount: 0
price: 0 EUR
commentsLast: ~
promoter: smile170
promotedBy: 6dTh2GAJnkb5YXqwyOoQ34Dyi9d2
place: ""
id: NvAdzIPSB962YeAedAzZ
international: No
views: 3
updatedAt: 1640018421803
updatedBy: 6dTh2GAJnkb5YXqwyOoQ34Dyi9d2
visibility: Unlisted
viewsCount: 3
eventType: Party
organiser: smile170
form: No
createdBy: 6dTh2GAJnkb5YXqwyOoQ34Dyi9d2
commentsCount: 0
name: Test event
online: No
styles: {}
region:
  placeId: ""
  loaded: true
  name: Anywhere
startDate: 2022-01-21T19:00:00.000Z
username: smile170
