endDate: 2021-06-24T18:15:00.000Z
description: >-
  🏴󠁧󠁢󠁥󠁮󠁧󠁿English - German below:


  !!InPerson as well as Online possible!!!


  🔥Our dates in June💃

  17.06.2021 / 24.06.2021 / 30.06.2021


  The classes are designed for all levels.

  We will work on technique, styling and soft movements.


  Duration & Price:

  1.15 hour = 10 €

  15 Min = Welcome, WarmUp, CoolDown


  When booking all classes, 15% discount


  🖥️For Zoom Online:

  In order to receive the online link, payment via PayPal or Bank is required in advance.


  🏠 For Presence:

  Location will be announced after registration!


  During the course , you have not to wear a Mask. Limited Spots available!


  📲Registration via private message or at an.milite@gmail.com


  🇩🇪German:


  !!Präsenz sowie Online möglich!!!


  🔥Unsere Termine im Juni💃
   17.06.2021 / 24.06.2021 / 30.06.2021

  Die Kurse sind für alle Niveaus ausgelegt.  Wir arbeiten an Technik, Styling und sanften Bewegungen.


  Dauer & Preis:

  1,15 Stunde = 10 €

  15 Min = Willkommen, WarmUp, CoolDown


  Bei Buchung aller Klassen 15% Rabatt


  🖥️Für Zoom Online:

  Um den Online-Link zu erhalten, ist eine Vorauszahlung per PayPal oder Bank erforderlich.


  🏠 Für Präsenz:

  Ort wird nach Anmeldung bekannt gegeben!


  Während des Kurses kein Maskenpflicht.

  Begrenzte Plätze verfügbar!


  📲Anmeldung per Nachrichtoder an.milite@gmail.com


  💃🦋 Can't wait 💥✨
type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FBopC3kiIMISXYYdn3deq6MLv7152%2F46fa950e-06c4-4266-aad8-a5573b705a2d?alt=media&token=9c01dbcf-6977-437b-9e16-20d8362d346a
createdAt: 1622471780844
watchersCount: 0
price: "10"
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FNZoHJjbMuRM05Jqzg7xi.png?generation=1624371955430574&alt=media
commentsLast: ~
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: NZoHJjbMuRM05Jqzg7xi
views: 1
updatedAt: 1622471780844
address: Munich
updatedBy: BopC3kiIMISXYYdn3deq6MLv7152
visibility: Public
viewsCount: 1
eventType: Course
createdBy: BopC3kiIMISXYYdn3deq6MLv7152
commentsCount: 0
name: Bachata LadyStyling Class
styles:
  SensualBachata:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-06-24T17:00:00.000Z
username: DELETED
