venue:
  formatted_address: Speicherstraße 26, 81671 München, Germany
  website: http://www.eventfabrik-muenchen.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "26"
      short_name: "26"
    - types:
        - route
      long_name: Speicherstraße
      short_name: Speicherstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Berg am Laim
      short_name: Berg am Laim
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81671"
      short_name: "81671"
  url: https://maps.google.com/?cid=597769398143220767
  name: Technikum
  geometry:
    viewport:
      south: 48.1221433697085
      north: 48.1248413302915
      east: 11.6080984302915
      west: 11.6054004697085
    location:
      lng: 11.6066841
      lat: 48.1234532
  international_phone_number: +49 89 628344411
  place_id: ChIJ7Ukks77fnUcRH_zsuRm0Swg
endDate:
  _seconds: 1635451200
  _nanoseconds: 0
claimed: No
organisedBy: ""
link: https://www.ticketbu.de/produkte/201-tickets-salsa-konzert-technikum-muenchen-am-28-10-2021
description: >
  Die meisten von Euch werden es schon wissen und viele haben sich längst ihr
  Ticket gesichert. Nach 1,5 Jahren warten kommt er endlich nach München:
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2F92686fe7-9b70-40b1-9529-f4d284d91cd3?alt=media&token=44b94ace-34c6-471d-a164-dd91ac128f20
duration: "180"
promo: ""
createdAt: 1633115384665
watchersCount: 0
price: 35EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FofttGncFtCJdl8aAsqSy.png?generation=1635345299172751&alt=media
commentsLast: ~
id: ofttGncFtCJdl8aAsqSy
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
views: 20
updatedAt: 1633115384665
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
visibility: Public
facebook: https://www.facebook.com/events/1410807992620441/
eventType: Concert
organiser: ""
form: Yes
createdBy: 5hkUljYCTSPJwsDqNqgGYRe1Tok2
commentsCount: 0
name: Alexander Abreu & Havana D'Primera
online: No
styles:
  Casino:
    level: Intermediate
    highlighted: true
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-28T17:00:00.000Z
username: Promoter
viewsCount: 28
