endDate:
  _seconds: 1641132000
  _nanoseconds: 0
claimed: Yes
organisedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
link: https://fb.me/e/1DDKsCsgv
description: >
  Hi Ladies in Munich & around  ✨⁣


  I would like to invite you to be part of the World Team Project:


  WOMEN MOVEMENT by Gatica - Team Munich ✨💃🏻✨


  We are going to learn the World Choreo of Gatica and perform it on stage! 🔥⁣💥


  💃🔸💃🔸💃🔸💃🔸💃🔸💃🔸

  WOMEN MOVEMENT by Gatica

  --> worldwide dance project <--


  Start: 02.01.22 - 2pm - Online


  Due to the holidays and Corona rules, we are going to meet the first time and go over all the things on Zoom-online

  (Text me to have the Link to join)


  What to bring:

  Good Energy, Smiles, clothes that you are comfortable dancing in + high heels.

  -- make sure u have space to move in front of your Computer --


  IMPORTANT:

  -you do not need to be a professional dancer to attend / or to join the Team.

  --we search for WOMEN with great energy, positive mind & attitude 💥


  ▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️

  Let’s create a team of power women who are supporting each other and will work to lift each other up💕

  ▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️


  For questions, please send me a DM 💌


  Much Love

  Anna🦋


  **FB Link: https://fb.me/e/1DDKsCsgv
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FYIbvg9vcOXbRapL8CqODDE5rQcg2%2Fcdd6f2f4-4faa-4540-b197-9d3636c20411?alt=media&token=d52f970a-5096-46b4-b50e-427af81f9a5a
promo: No
duration: 60
createdAt: 1640024779755
watchersCount: 0
price: 0 EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FOglp3aBx22y1t6HAPE7b.png?generation=1640083303064734&alt=media
commentsLast: ~
promoter: Lakkana
place: ""
id: Oglp3aBx22y1t6HAPE7b
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
international: Yes
views: 8
updatedAt: 1640024779755
updatedBy: YIbvg9vcOXbRapL8CqODDE5rQcg2
visibility: Members
eventType: Workshop
organiser: ""
form: Yes
createdBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
commentsCount: 0
name: Women Movement by Gatica - Team Munich ✨💃🏻✨
online: Yes
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
startDate: 2022-01-02T13:00:00.000Z
username: AnnaMil
watch:
  count: 0
  list: {}
viewsCount: 21
