endDate: 2021-11-27T23:00:00.000Z
organisedBy: ""
claimed: No
link: www.timbalemania.de
description: >-
  For almost 2 years there were hardly any events and joyful get-togethers... We
  want to change that! If we have learned anything during this time, it is how
  valuable and important community and friendship are, how we should be braver
  and enjoy every single moment more! 💪😊


  We want to invite the Salsa & Timba community from all over Germany to come to Augsburg, so we can all finally meet again and of course dance, party and experience a special weekend together. We have decided to organise a different kind of festival by combining tourism, community and dance! 💜💙

  We offer you 3 days full programme: 10 hours of workshops, 3 parties, 2 excursions, bus ride & gondola ride Zugspitze, 2 dinners (water flatrate) for 230 €!


  - Very limited places (50 in total)

  - family atmosphere & activities

  - joint excursions (Augsburg City Tour & Zugspitze excursion)

  - joint dinner before the parties

  - DJ LA PANTERA from Barcelona & DJ LUIS with finest Cuban music selection

  - 2 levels (Intermediate & Advanced)

  - Intensive 90-minute workshops focusing on both dance roles, technique, musicality & more

  - dedicated teaching team:


  YOHAN CORRIOSO

  YAILEN SERRANO

  LUIS DUARTE

  SASSAN & BERLIN RUEDA

  ARIEL LOPEZ 

  SOFIA DE ENDAYA


  The current COVID rules for Bavaria, Germany apply for the entire weekend.


  We are really looking forward to our first TIMBALEMANIA with all of you together! 🎉


  All info & registration at www.timbalemania.de


  Questions and/or paypal payment to mail@timbalemania.de
type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2F67200fad-56bf-4ba0-9e94-34c9e1bedf71?alt=media&token=bbb6b1fd-572c-4be0-ad64-9497c09ab1fd
createdAt: 1636535413100
watchersCount: 0
price: 230€
commentsLast: ~
promoter: Vitali
id: OGUTjh2YDckMurYN9dnY
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 10
updatedAt: 1636535413100
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
facebook: https://facebook.com/events/s/timbalemania-cuban-family-danc/704228047203279/
eventType: Party
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: TIMBAALEMANIA [POSTPONED]
online: No
styles:
  Timba:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Intermediate
    highlighted: false
    selected: true
  Salsa:
    level: Intermediate
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-26T08:00:00.000Z
username: Vitali
viewsCount: 12
