updatedBy: ErP9WITL4eMyf36LQ5iR9nCAIJ82
visibility: Public
endDate: 2021-08-08T20:30:00.000Z
eventType: Festival
type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FErP9WITL4eMyf36LQ5iR9nCAIJ82%2F360e07f8-a9d8-4997-a132-adcec7be27af?alt=media&token=ecdede70-0097-4e29-8c67-320cba7a1966
createdAt: 1619967245169
watchersCount: 0
form: No
createdBy: ErP9WITL4eMyf36LQ5iR9nCAIJ82
commentsCount: 0
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FOHlYaB7Mfq1m45thxg3K.png?generation=1619967259026442&alt=media
name: Bachata Idol
commentsLast: ~
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
place: ChIJybDUc_xKtUYRTM9XV8zWRD0
id: OHlYaB7Mfq1m45thxg3K
region:
  name: Moscow
  location:
    country: Russia
    latitude: 55.755826
    locality: Moscow
    usedGps: false
    place_id: ChIJybDUc_xKtUYRTM9XV8zWRD0
    longitude: 37.6172999
views: 2
startDate: 2021-08-07T07:00:00.000Z
updatedAt: 1619967245169
username: MaryRys
viewsCount: 4
