venue:
  website: http://www.groovedance.de/
  formatted_address: Wächtersbacher Str. 76, 60386 Frankfurt am Main, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "76"
      short_name: "76"
    - types:
        - route
      long_name: Wächtersbacher Straße
      short_name: Wächtersbacher Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Frankfurt am Main Ost
      short_name: Frankfurt am Main Ost
    - types:
        - locality
        - political
      long_name: Frankfurt am Main
      short_name: Frankfurt am Main
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Frankfurt am Main
      short_name: Kreisfreie Stadt Frankfurt am Main
    - types:
        - administrative_area_level_2
        - political
      long_name: Darmstadt
      short_name: DA
    - types:
        - administrative_area_level_1
        - political
      long_name: Hessen
      short_name: HE
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "60386"
      short_name: "60386"
  url: https://maps.google.com/?cid=8316037561201953830
  name: Groove Dance Classes
  geometry:
    viewport:
      south: 50.1310269197085
      north: 50.1337248802915
      east: 8.749177930291502
      west: 8.746479969708497
    location:
      lng: 8.74781
      lat: 50.13249
  place_id: ChIJdeymqUgOvUcRJow_BhqAaHM
  international_phone_number: +49 69 40897551
endDate:
  _seconds: 1638028800
  _nanoseconds: 0
organisedBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
claimed: Yes
link: https://la-kossa-frankfurt.eventbrite.com
description: |-
  3 Workshops mit verschiedenen Styles
  Coupé Décalé
  Afrobeats Dance
  Afro Contemporary
type: event
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FqTPAP7OhWMYjtoPXtpUJavNz5Fr2%2Fc2606164-e749-403d-a228-bfd173590f2a?alt=media&token=19e402e9-098a-4040-a110-20167046fe9d
duration: "300"
createdAt: 1635636129978
watchersCount: 0
price: ""
commentsLast: ~
promoter: lakossa
promotedBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
place: ChIJxZZwR28JvUcRAMawKVBDIgQ
id: oHtTohVTYTtSREXVLRiF
international: No
views: 7
updatedAt: 1635636129978
website: http://www.la-kossa.de
updatedBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
visibility: Public
facebook: https://www.facebook.com/lakossa.fitness
eventType: Party
organiser: la.kossa
form: Yes
createdBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
commentsCount: 0
name: Afro Dance Day in Frankfurt
online: No
styles:
  Afrobeats:
    level: Advanced
    highlighted: false
    selected: true
  Contemporary:
    level: Interested
    highlighted: false
    selected: true
  AfroHouse:
    level: Advanced
    highlighted: false
    selected: true
region:
  name: Frankfurt am Main
  location:
    country: Germany
    latitude: 50.1109221
    locality: Frankfurt
    usedGps: false
    place_id: ChIJxZZwR28JvUcRAMawKVBDIgQ
    longitude: 8.6821267
startDate: 2021-11-27T11:00:00.000Z
username: lakossa
viewsCount: 44
