venue:
  website: http://www.salsacubaclub.de/
  formatted_address: Landsberger Str. 18, 80339 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "18"
      short_name: "18"
    - types:
        - route
      long_name: Landsberger Straße
      short_name: Landsberger Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Schwanthalerhöhe
      short_name: Schwanthalerhöhe
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80339"
      short_name: "80339"
  url: https://maps.google.com/?cid=13465701088836487314
  name: Salsa Cuba Club
  geometry:
    viewport:
      south: 48.13810136970851
      north: 48.14079933029151
      east: 11.5472657802915
      west: 11.5445678197085
    location:
      lng: 11.5459098
      lat: 48.13950500000001
  international_phone_number: +49 179 5456322
  place_id: ChIJKTBBsgF2nkcRkoiww8vH37o
endDate:
  _seconds: 1635460200
  _nanoseconds: 0
claimed: No
organisedBy: ""
link: https://salsaclub-munich.de/course.php?kid=119
description: |-
  Salsa & Bachata Party für Schüler, Mitglieder und Gäste!

  - 20.30 Salsa On2 Einführungskurs
  - Cocktails & Longdrings
  - NYC Salsa, Mambo, Bachata sounds by Hakan


  Veranstaltung vom Siempre Salsa e.V.
  Es gelten die aktuellen 3G Regeln.
type: event
cover: ""
duration: "240"
createdAt: 1633789902994
watchersCount: 0
price: 5-10 EUR
commentsLast: ~
promoter: Vitali
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: oLElMcM7r9gxfbzmMxNt
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
international: No
views: 14
updatedAt: 1633789902994
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Party
organiser: ""
form: Yes
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Mambo Social @ Salsa Club Munich
online: No
styles:
  SalsaNewYork:
    level: Interested
    highlighted: false
    selected: true
  Mambo:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Intermediate
    highlighted: false
    selected: true
  SalsaLA:
    level: Interested
    selected: true
  Salsa:
    level: Intermediate
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-28T18:30:00.000Z
username: Vitali
viewsCount: 19
