endDate:
  _seconds: 1628377200
  _nanoseconds: 0
link: https://docs.google.com/forms/d/e/1FAIpQLSf8CLqrwmwTtKj-mKpi9F8hY0wAYs-ZprvL_YochLMSeHSwkA/viewform
description: Everybody can come but please registrate ❤️
type: event
duration: "300"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F53RIv65ORyVgTf99Mrvef8gyGVr2%2F08aaa9aa-70da-4272-99d2-672091b3ddc7?alt=media&token=67888417-d4f2-4354-90b0-9e36d24c4ab2
createdAt: 1627448777327
watchersCount: 0
price: 10,-
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FOpLafaTgSXwUayL8pngx.png?generation=1627451308498094&alt=media
commentsLast: ~
place: ChIJCXjgokgGl0cRf-63THNV_LY
id: OpLafaTgSXwUayL8pngx
views: 1
updatedAt: 1627448777327
updatedBy: 53RIv65ORyVgTf99Mrvef8gyGVr2
address: Sonlatino Gablonzerstrasse 9
visibility: Public
eventType: Party
form: Yes
createdBy: 53RIv65ORyVgTf99Mrvef8gyGVr2
commentsCount: 0
name: Linda‘s birthday party in Son Latino
online: No
styles:
  SalsaNewYork:
    level: Interested
    highlighted: false
    selected: true
  SalsaCalena:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Karlsruhe
  location:
    country: Germany
    latitude: 49.0068901
    locality: Karlsruhe
    usedGps: false
    place_id: ChIJCXjgokgGl0cRf-63THNV_LY
    longitude: 8.4036527
startDate: 2021-08-07T18:00:00.000Z
username: Innerpeaceaakademy
viewsCount: 2
