venue:
  website: http://www.sonlatino.de/
  formatted_address: Gablonzer Str. 9, 76185 Karlsruhe, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "9"
      short_name: "9"
    - types:
        - route
      long_name: Gablonzer Straße
      short_name: Gablonzer Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Mühlburg
      short_name: Mühlburg
    - types:
        - locality
        - political
      long_name: Karlsruhe
      short_name: Karlsruhe
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Karlsruhe
      short_name: Kreisfreie Stadt Karlsruhe
    - types:
        - administrative_area_level_2
        - political
      long_name: Karlsruhe
      short_name: KA
    - types:
        - administrative_area_level_1
        - political
      long_name: Baden-Württemberg
      short_name: BW
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "76185"
      short_name: "76185"
  room: Studio 1
  url: https://maps.google.com/?cid=8926798613940117231
  name: Son Latino Dance Studio
  geometry:
    viewport:
      south: 49.02229426970851
      north: 49.02499223029151
      east: 8.354233980291502
      west: 8.351536019708497
    location:
      lng: 8.352825700000002
      lat: 49.0236634
  map: ""
  international_phone_number: +49 721 6638886
  place_id: ChIJ12tDlScHl0cR755ZDQtc4ns
endDate: 2021-11-01T03:00:00.000Z
link: https://www.sonlatino-events.de/booking/12?fbclid=IwAR3UKxQkmtfsUMZCl-1VA7S-E5ank8KxoknG70P62NVcpABeVXCWdMiKFRE
description: >-
  Son Latino Events proudly presents

  🎃HALLOWEEN LATINO 🎃.

  💥Sonntag 31 Oktober ☠ 20H ☠ Son Latino Karlsruhe 💥

  Kommt und genießt einer der berühmtesten Nächte der Welt. HALLOWEEN LATINO - Die gruseligste Practica des Jahres.

  Eine Nacht voller gruseligen Emotionen und vielen Überraschungen.

  Wir verwandeln unser Studio in ein Landjenseits dieser Welt! Erlebt die aufwändigste Halloween Party in der Latino-Szene, mit gigantischer Dekoration, eine Special-Programm und der gruseligste Atmosphäre des Jahres!

  Thriller Show, Video-Show und Projektionen, Preise für das beste Kostüm, Tombola, Animationen und viele gruselige Sachen warten auf euch!!

  _____________________________

  🎃 HALLOWEEN ☠ SPECIALS🎃

  🕷 Latin Nacht. Salsa, Bachata, Kizomba, Merengue, Reggaeton ( alle Stile) mit Videoprojektion

  🕷 Frankenstein Tombola:

  Teste dein Glück und gewinne tolle gruselige Preise!

  💥 Preise der Tombola 💥

  * Workshop-Gutschein

  * Eintritt frei für die nächste Party

  * Flasche Sekt

  💥Preise für das beste Kostüm💥

  Ein Tanzkurs in Son Latino Karlsruhe oder Baden-Baden

  🕷 Dracula Willkommens-Cocktail

  Begrüßungscocktail nur für kostümierte oder geschminkte Besucher

  🕷 Zombies Cocktail Happy Hour

  Ab 20:00H bis 21:00H (Alle Cocktails zum halben Preis)

  🕷 Animation jede Stunde

  Genießt mit unseren Tanzlehrern unterhaltsame Tänze der Animation

  21H - Merengue ☠ 22H - Bachata ☠ 23H - Arrebatate ☠ 24H - Tombola, Preise und Show Time ☠ 01H - Rueda de Casino ( Special und Speed Crash Kurs) ☠ 02H - La Cura (Jerusalema) ☠ 03H - Reggaeton

  🕷 Show Ab 24H Thriller Salsa Show (Premiere Son Latino Showgruppe)

  _____________________________

  🎃 3G-REGELUNG ☠

  3G Geimpft, Genesen oder Getestet ( alle Tests ) PCR Test oder Schnelltest im Sinne der aktuellen CoronaSchVO.

  _____________________________

  🎃 HALLOWEEN ☠ DRESSCODE 🎃

  Dresscode (Mit Kostüm oder geschminkt)

  _____________________________

  🎃 EINTRITT ☠

  15€/13€ für SL-Clubmitglieder mit Mitglieder-Ausweis (Vorregistrierung erforderlich. Limitierte Plätze)
type: event
duration: custom
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FfPFOWINB1LNTCvLqLWxxgLuYhsX2%2F1cdcde01-ca42-4eb5-aea8-eea678521f79?alt=media&token=314e130b-1b63-4460-813c-095b0105048c
createdAt: 1632074329121
watchersCount: 0
price: ab 13€
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2Fp1I3UBfGeigbKyuNialj.png?generation=1635371202091467&alt=media
commentsLast: ~
place: ChIJCXjgokgGl0cRf-63THNV_LY
id: p1I3UBfGeigbKyuNialj
views: 16
updatedAt: 1632074329121
updatedBy: fPFOWINB1LNTCvLqLWxxgLuYhsX2
visibility: Public
eventType: Party
organiser: alyonadance
form: Yes
createdBy: fPFOWINB1LNTCvLqLWxxgLuYhsX2
commentsCount: 0
name: HALLOWEEN LATINO
online: No
styles:
  Merengue:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Reggaeton:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Karlsruhe
  location:
    country: Germany
    latitude: 49.0068901
    locality: Karlsruhe
    usedGps: false
    place_id: ChIJCXjgokgGl0cRf-63THNV_LY
    longitude: 8.4036527
startDate: 2021-10-31T19:00:00.000Z
username: alyonadance
viewsCount: 34
