venue:
  formatted_address: Adi-Maislinger-Straße 12, 81373 München, Germany
  website: http://www.iwanson.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "12"
      short_name: "12"
    - types:
        - route
      long_name: Adi-Maislinger-Straße
      short_name: Adi-Maislinger-Straße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Sendling-Westpark
      short_name: Sendling-Westpark
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81373"
      short_name: "81373"
  url: https://maps.google.com/?cid=5492811770859622788
  name: Iwanson International School of Contemporary Dance
  geometry:
    viewport:
      south: 48.12758666970849
      north: 48.13028463029149
      east: 11.5369510302915
      west: 11.5342530697085
    location:
      lng: 11.5359317
      lat: 48.12880579999999
  place_id: ChIJG-zlKa7YnUcRhBEsFDRjOkw
  international_phone_number: +49 89 7606085
endDate: 2021-10-31T13:30:00.000Z
organisedBy: ""
claimed: No
description: >+
  Beschreibung

  GERMAN / ENGLISH


  AFRO CUBAN WEKEND

  ALFREDO GARCIA BACK IN MUNICH AGAIN


  Programm:


  Samstag 30.10

  10.30 - 11.00 Registration

  11.00 - 14.00 Afro Cuban (Basics) 3 Std.


  Sonntag 31.10

  10.30 - 11.00 Registration

  11.00 - 12.30 Afro Cuban (Advanced) 1,5 Std

  12.45 - 14.15 Afro Contemporary Fusion 1,5 Std ______________________________________ 

  LOCATION:


  Iwanson International School of Contemporary Dance


  Adresse: 

  Adi-Maislinger-Straße 12, 81373 München  ACHTUNG -> (STIFTUNGSSTUDIO) siehe in Event Feed

  ____________________________________


  Preis:


  FULLPASS                                         129 €


  1 DAY PASS                                         69 €


  1 CLASS 1,5 h (only on Sunday)       39 €

  _______________________________________


  ANMELDUNG: (erforderlich) unter:


  +176 82 13 88 90


  info@emanuel-lederer


  BEZAHLUNG via:


  PayPal: emanuel-lederer@gmx.de


  oDER


  Bank Überweisung:  IBAN: DE74 7009 3400 0000 0574 01 BIC:	   GENODEF	

  _______________________________________


  Beschreibung:


  Afro Cuban Bacics


  Egal aus welcher Tanzrichtung du kommst,… DU wirst so viel mitnehmen können!!!

  In diesem 3 Std. beschäftigen wir uns mit den Basics aus Afro Cuban Yoruba und Palo. Für jeden der schon mal mit Alfredo gearbeitet hat, weiß wie viel Wert er auf tiefe in seinen Stunden legt. Wir haben mit Absicht keine Stundenweise Unterteilung gemacht um fließende Übergänge zu schaffen. So sind die Basics, sowohl für Anfänger als auch für Fortgeschrittene,  super gut geeignet damit sich jeder auf  seinen Individuellen Level steigern und die Bewegungen in sein schon vorhandenes Movement integrieren kann.


  Afro Cuban Advanced


  Hier wird richtig gelevelt und Gas gegeben. Für diejenigen die bereit dazu sind die Challenge anzunehmen!

  Wenn du an Tag 1 schon mit  dabei warst und Lust auf mehr hast, dann nimm es mit.


  Afro-Contemporary Fusion 


  Alfredo ist nicht nur ein absoluter Guru was Afro angeht sondern auch eine Ikone in Ballett und Contemporary. 

  Die Kombination aus zeitgenössischem Tanz und Afro Cuban ergibt eine schöne Symbiose aus unterschiedlichen Tanzstilen die geprägt sind von Gegensätzen. Genau diese Gegensätze verbessern deine Dynamik, Ausdruck und Vielseitigkeit in deinem Tanz.



  Wir freuen uns auf DEIN Kommen und DEINE Energie. Zöger nicht und schreib mir einfach, wenn du dabei sein möchtest.


  DEIN EMANUEL



  Afro Cuban WEEKEND

  ALFREDO GARCIA BACK IN MUNICH AGAIN

  ________________________________________


  ENGLISH


  Description:


  Afro Cuban Bacics


  No matter what dance style you come from, you will take away so much. 

  In this 3 hour class we will cover the basics of Afro Cuban Yoruba and Palo. For anyone who has worked with Alfredo knows how much emphasis he places on depth in his lessons. We have intentionally not divided the lessons into hours to create smooth transitions. So the basics, both for beginners and advanced, are super well suited to increase to his individual level and to integrate the movements into his already existing movement.


  Afro Cuban Advanced


  This is where you really level up and step on the gas. For those who feel ready for a challenge, feel free to take it. If you already participated on day 1 and feel like doing more, then take it.


  Afro-Contemporary Fusion 


  Alfredo is not only an absolute guru when it comes to Afro but also an icon in Ballet and Contemporary. 

  The combination of contemporary dance and Afro Cuban results in a beautiful symbiosis of different dance styles that are characterized by contrasts. Exactly these contrasts improve your dynamics, expression and versatility in your dance.



  We are looking forward to YOUR coming and YOUR energy. Do not hesitate and just write me if you want to be there.


  YOUR EMANUEL



type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2Faaba125b-178b-4759-bb6c-3e340d4129f8?alt=media&token=bcaf55ab-be9f-4cea-8c4a-d0272566eb35
createdAt: 1633977949732
watchersCount: 0
price: 39-128 EUR
commentsLast: ~
promoter: Vitali
id: PFIelCk5TM65ixPJ20yT
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
international: No
views: 21
updatedAt: 1633977949732
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
facebook: https://facebook.com/events/s/afro-cuban-contemporary-fusion/1233233440514225/
eventType: Workshop
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: AFRO CUBAN WEKEND ALFREDO GARCIA BACK IN MUNICH AGAIN
online: No
styles:
  Contemporary:
    level: Advanced
    highlighted: false
    selected: true
  Afro:
    level: Advanced
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-31T09:30:00.000Z
username: Vitali
viewsCount: 24
