venue:
  formatted_address: Geretsrieder Str. 6, 81379 München, Germany
  website: http://www.dilly-dance.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "6"
      short_name: "6"
    - types:
        - route
      long_name: Geretsrieder Straße
      short_name: Geretsrieder Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Thalkirchen-Obersendling-Forstenried-Fürstenried-Solln
      short_name: Thalkirchen-Obersendling-Forstenried-Fürstenried-Solln
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81379"
      short_name: "81379"
  url: https://maps.google.com/?cid=6143705177948861557
  name: Ballett- und Tanzschule Dilly-Dance
  geometry:
    viewport:
      south: 48.09932636970851
      north: 48.10202433029151
      east: 11.5345753302915
      west: 11.5318773697085
    location:
      lng: 11.533212
      lat: 48.100572
  international_phone_number: +49 176 19710400
  place_id: ChIJX8e94rXYnUcRdbReAE_TQlU
endDate:
  _seconds: 1636837200
  _nanoseconds: 0
organisedBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
claimed: Yes
description: Nothing needed - just you and the desire to dance with us - join us
  !! See you on the Dancefloor!
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F8yp79cUd0jZtnVn34NxhBuMpxrx1%2F01cfb4e8-7827-446d-ab2a-0b165e31e2ab?alt=media&token=8e11681b-aaf2-4e50-8969-1d4805cffc4d
promo: Yes
duration: 60
createdAt: 1636524997550
watchersCount: 0
price: 10EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FpMeDmACM6xzAAyOirArA.png?generation=1636525163447473&alt=media
commentsLast: ~
promoter: AnnaMil
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
id: pMeDmACM6xzAAyOirArA
international: No
views: 20
updatedAt: 1636524997550
updatedBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
visibility: Public
eventType: Party
organiser: AnnaMil
form: No
createdBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
commentsCount: 0
name: Saturday Pre - Party mit Gatica
online: No
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-13T20:00:00.000Z
username: AnnaMil
viewsCount: 24
