venue:
  website: http://www.facebook.com/cafebar.maracas
  formatted_address: Nekázanka 8, Nové Město, 110 00 Praha-Praha 1, Czechia
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "8"
      short_name: "8"
    - types:
        - route
      long_name: Nekázanka
      short_name: Nekázanka
    - types:
        - neighborhood
        - political
      long_name: Nové Město
      short_name: Nové Město
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Praha 1
      short_name: Praha 1
    - types:
        - administrative_area_level_2
        - political
      long_name: Hlavní město Praha
      short_name: Hlavní město Praha
    - types:
        - administrative_area_level_1
        - political
      long_name: Hlavní město Praha
      short_name: Hlavní město Praha
    - types:
        - country
        - political
      long_name: Czechia
      short_name: CZ
    - types:
        - postal_code
      long_name: 110 00
      short_name: 110 00
  url: https://maps.google.com/?cid=4567179202943258383
  name: Café Bar Maracas
  geometry:
    viewport:
      south: 50.0838506697085
      north: 50.0865486302915
      east: 14.4290272302915
      west: 14.4263292697085
    location:
      lng: 14.4276184
      lat: 50.08516760000001
  international_phone_number: +420 734 141 712
  place_id: ChIJf6kboeyUC0cRDw_8gEnhYT8
endDate:
  _seconds: 1636671600
  _nanoseconds: 0
organisedBy: GEYBE2nFRAPu2y7Ie7dKF2bZPKk1
description: |-
  ✪ Latino mix: Salsa, bachata, kizomba, reggaeton, latin pop... ✪

  ✪ Dj Lole 🎧 ✪

  + Vstup zdarma / Free entry +

  Reservace: 734 141 712
type: event
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FGEYBE2nFRAPu2y7Ie7dKF2bZPKk1%2Fd905d51b-7f35-4060-ae8e-204f42371140?alt=media&token=4df10e73-338b-46f4-84f8-cc52db58220b
duration: "180"
createdAt: 1629964969652
watchersCount: 0
price: FREE
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FpSvJKRIMQBZHOZT4CLJ8.png?generation=1636642488379070&alt=media
commentsLast: ~
id: pSvJKRIMQBZHOZT4CLJ8
place: ""
promotedBy: GEYBE2nFRAPu2y7Ie7dKF2bZPKk1
views: 13
updatedAt: 1629964969652
updatedBy: GEYBE2nFRAPu2y7Ie7dKF2bZPKk1
visibility: Public
eventType: Party
organiser: DjLole
form: No
createdBy: GEYBE2nFRAPu2y7Ie7dKF2bZPKk1
commentsCount: 0
name: Locura Cubana en Las Maracas ★
online: No
styles:
  Timba:
    level: Interested
    selected: true
  UrbanKizz:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Reggaeton:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
startDate: 2021-11-11T20:00:00.000Z
username: DjLole
viewsCount: 17
