venue:
  website: http://www.waldorfschule-msw.de/
  formatted_address: Züricher Str. 9, 81476 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "9"
      short_name: "9"
    - types:
        - route
      long_name: Züricher Straße
      short_name: Züricher Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Thalkirchen-Obersendling-Forstenried-Fürstenried-Solln
      short_name: Thalkirchen-Obersendling-Forstenried-Fürstenried-Solln
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81476"
      short_name: "81476"
  url: https://maps.google.com/?cid=17638280745153986554
  name: Free Waldorf School Munich Southwest
  geometry:
    viewport:
      south: 48.0925519697085
      north: 48.09524993029149
      east: 11.5036682302915
      west: 11.5009702697085
    location:
      lng: 11.5021447
      lat: 48.093345
  place_id: ChIJ7d5mwLZ3nkcR-v-D1-LCx_Q
  international_phone_number: +49 89 72406380
endDate:
  _seconds: 1634068800
  _nanoseconds: 0
claimed: No
organisedBy: ""
link: https://docs.google.com/forms/d/e/1FAIpQLSd9GsNP9a2mxK0XjH_a-wo4T0DBzSh3gDT5zPxKHOIQI22czQ/viewform?usp=sf_link
description: >+2
   Schupperkurs für alle, die noch nie getantzt haben, um etwas neues auszuprobieren und für diejenigen die bereits Forro tanzen Ähnlichkeiten zum Samba zu entdecken oder umgekehrt. 

  WANN?    12.Oktober
                   19:00-20:30 Uhr Forró/Samba 
                   20:30-22:00 Uhr freies Tanzen 

   

  Alle Teilnehmer - müssen die 3G-Regel befolgen. Und davor sich über den Link Anmelden

type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2Fa6b35022-b2be-45f7-88c7-2954ec191b3d?alt=media&token=3b7b7159-b6b0-4656-b1a0-13e88c23546f
duration: "180"
promo: ""
createdAt: 1633852628637
watchersCount: 0
price: FREE
commentsLast: ~
promoter: Vitali
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
id: QiWFG3ByV0EUXE2ygvtD
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 4
updatedAt: 1633852628637
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
facebook: https://facebook.com/events/s/schnupperkurs-sambaforro-und-f/268063975233364/
eventType: Party
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: "Schnupperkurs Forro/Samba und freies tanzen "
online: No
styles:
  Samba:
    level: Interested
    highlighted: false
    selected: true
  ForroLove:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-12T17:00:00.000Z
username: Vitali
viewsCount: 59
