endDate:
  _seconds: 1638298800
  _nanoseconds: 0
organisedBy: ""
claimed: No
link: joycceedancer@gmail.com
description: |
  Every Tuesday: 

  19:30 Uhr: Reggaeton (Open Level)

  20: 15 Uhr: Salsa Suelta (Open Level)

  21 Uhr: Son tradicional cubano (Beginner)

  Duration/Course (Dauer/Kurs): 30 Minuten

  5€/Course

  Pay Information

  Joycce Vasallo Martinez

  IBAN: Auf Anfrage

  PayPal: joyccedancer@gmail.com

  Registration Email to:

  joyccedancer@gmail.com

  or

  diamaryssarabaza@yahoo.es

  <w-youtube url="https://www.youtube.com/watch?v=m0qDGZJTaJo"></w-youtube>
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FdTkY7Qsrz8OxZQ3GW2ShP5BFV282%2F3507d243-6bd1-42fd-9457-1bc7cee3cd9b?alt=media&token=740c3c13-1d1d-44f1-9e20-14b566bfbdc2
promo: Yes
duration: "30"
createdAt: 1638116026062
watchersCount: 0
price: 5EUR
commentsLast: ~
promoter: VladimirCuba
id: qrV1DlF6J86mhCmlzQTh
place: ""
promotedBy: dTkY7Qsrz8OxZQ3GW2ShP5BFV282
international: Yes
views: 6
updatedAt: 1638116026062
updatedBy: dTkY7Qsrz8OxZQ3GW2ShP5BFV282
visibility: Public
facebook: https://fb.watch/9z2GjBKflU/
eventType: Course
organiser: ""
form: No
createdBy: dTkY7Qsrz8OxZQ3GW2ShP5BFV282
commentsCount: 0
name: Joycce Salsa Cubana Clubs (online via invitation)
online: Yes
styles:
  Reggaeton:
    level: Interested
    highlighted: false
    selected: true
  Son:
    level: Beginner
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
startDate: 2021-11-30T18:30:00.000Z
username: VladimirCuba
viewsCount: 9
