venue:
  formatted_address: St.-Martin-Straße 58-68, 81541 München, Germany
  website: https://suhag.restaurant/menu/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: 58-68
      short_name: 58-68
    - types:
        - route
      long_name: St.-Martin-Straße
      short_name: St.-Martin-Straße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Obergiesing-Fasangarten
      short_name: Obergiesing-Fasangarten
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81541"
      short_name: "81541"
  url: https://maps.google.com/?cid=12885342734864249841
  name: Restaurant Suhag
  geometry:
    viewport:
      south: 48.1166701197085
      north: 48.11936808029149
      east: 11.5959340802915
      west: 11.5932361197085
    location:
      lng: 11.5945851
      lat: 48.1180191
  place_id: ChIJfT4a5J3fnUcR8XO-qPLu0bI
  international_phone_number: +49 89 64945050
endDate:
  _seconds: 1635544800
  _nanoseconds: 0
claimed: No
organisedBy: ""
link: https://suhag-events.yapsody.com/event/index/688246/diwali-party-2021
description: >+
  Dear all, Suhag invites you to join us in celebrating the festival of lights
  on 29.11.2021. DINE | DJ| LIVE MUSIC | DANCE .

  Looking forward to welcoming you all.

  Hurry BOOK your Tickets now!




type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2F5178121a-6f5d-4e93-b48a-9991e60baa46?alt=media&token=ad03761c-5265-4f68-878b-3a977a33fa88
duration: "300"
createdAt: 1634053610706
watchersCount: 0
price: 20-35 EUR
commentsLast: ~
promoter: Vitali
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
id: R7QomvdIoysBXK5rsBH5
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 19
updatedAt: 1634053610706
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
facebook: https://facebook.com/events/s/diwali-party-suhag-indisches-r/717472722513042/
eventType: Party
organiser: ""
form: Yes
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Diwali Party 2021 Dine DJ Dance Diwali 2021
online: No
styles:
  Bollywood:
    level: Interested
    highlighted: false
    selected: true
  Indian:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-29T17:00:00.000Z
username: Vitali
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FR7QomvdIoysBXK5rsBH5.png?generation=1665499687996780&alt=media
viewsCount: 82
