venue:
  formatted_address: Westenriederstraße 41, 80331 München, Germany
  website: http://www.salsaclub-munich.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "41"
      short_name: "41"
    - types:
        - route
      long_name: Westenriederstraße
      short_name: Westenriederstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Altstadt-Lehel
      short_name: Altstadt-Lehel
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80331"
      short_name: "80331"
  url: https://maps.google.com/?cid=17999243784988121499
  name: Salsa Club Munich by Hakan
  geometry:
    viewport:
      south: 48.1337395197085
      north: 48.1364374802915
      east: 11.5813472302915
      west: 11.5786492697085
    location:
      lng: 11.5800107
      lat: 48.1351437
  international_phone_number: +49 172 8533891
  place_id: ChIJU60HW-F1nkcRm9nfvdsoyvk
endDate: 2021-09-17T17:15:00.000Z
link: https://salsaclub-munich.de/course.php?kid=124
description: >-
  Bachata absolute Einsteiger!


  Mit und ohne Partner möglich.

  Hier unterrichten wir die Grundlagen für den schönen Tanz aus der Dom. Republik.


  Dauer = 4 x 75 Min. (Jeden Freitag)

  Schwierigkeitsgrad = BA-1


  Preise:

  Mitglieder 60 € (Mitglieder)

  Regulär    80 €

  Studenten  75 €
type: event
duration: custom
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F8yp79cUd0jZtnVn34NxhBuMpxrx1%2F25b7c875-5dda-4713-8a04-6367b62eb6c8?alt=media&token=f634e45d-d90a-4525-99d1-d22ddedbffb3
createdAt: 1628689193538
watchersCount: 0
price: 80EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FRCh1pUql0N5iY0Y6cfRs.png?generation=1628689523642862&alt=media
commentsLast: ~
id: RCh1pUql0N5iY0Y6cfRs
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 1
updatedAt: 1628689193538
updatedBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
visibility: Public
eventType: Course
organiser: AnnaMil
form: Yes
createdBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
commentsCount: 0
name: BACHATA - Beginner Course
online: No
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-09-17T16:00:00.000Z
username: AnnaMil
viewsCount: 31
