endDate:
  _seconds: 1613672100
  _nanoseconds: 0
city: Munich
description: >-
  Every Thursday !!! Improver Level - Focusing on Sensual Body Movement +
  Partnerwork suitable styling


  only 10€ per course!
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F8yp79cUd0jZtnVn34NxhBuMpxrx1%2F74b6a90d-c5d2-4131-9eaa-c149394b8329?alt=media&token=4906c82c-3295-4378-85a2-a2f9363f4523
duration: 60
createdAt: 1611434603146
watchersCount: 0
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FrE4YyLHvhBuEMy7rxFQm.png?generation=1613416296374452&alt=media
commentsLast: ~
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: rE4YyLHvhBuEMy7rxFQm
views: 1
updatedAt: 1617065904055
address: Online
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
visibility: Public
eventType: Course
organiser: Salsa y Corazon
form: No
createdBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
commentsCount: 0
name: Bachata Sensual LadyStyling
styles:
  SensualBachata:
    level: Interested
    selected: true
  Bachata:
    level: Interested
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-02-18T17:15:00.000Z
username: AnnaMil
viewsCount: 5
