venue:
  formatted_address: Im Annahof 4, 86150 Augsburg, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "4"
      short_name: "4"
    - types:
        - route
      long_name: Im Annahof
      short_name: Im Annahof
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Augsburg-Innenstadt
      short_name: Augsburg-Innenstadt
    - types:
        - locality
        - political
      long_name: Augsburg
      short_name: A
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Augsburg
      short_name: Kreisfreie Stadt Augsburg
    - types:
        - administrative_area_level_2
        - political
      long_name: Schwaben
      short_name: Schwaben
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "86150"
      short_name: "86150"
  url: https://maps.google.com/?q=Im+Annahof+4,+86150+Augsburg,+Germany&ftid=0x479ebd522db11249:0x35e5a71b52e0e4f8
  name: Im Annahof 4
  geometry:
    viewport:
      south: 48.3664480697085
      north: 48.3691460302915
      east: 10.8957449802915
      west: 10.8930470197085
    location:
      lng: 10.894701
      lat: 48.367757
  place_id: ChIJSRKxLVK9nkcR-OTgUhun5TU
endDate:
  _seconds: 1642892400
  _nanoseconds: 0
organisedBy: ""
claimed: No
link: https://copacaribe.sumup.link/produkt/dani-j-concert-sabor-de-caribe-party-sa-22-01-2022
description: >
  Vor sowie nach dem Konzert darf auf 3 Areas ausgiebig getanzt werden. 

  Die Raumaufteilung sieht wie folgt aus: 

  Area 1 = Bachata, 

  Area 2 = Salsa, 

  Area 3 = Kizomba.


  Ticketkauf: 

  https://copacaribe.sumup.link/produkt/dani-j-concert-sabor-de-caribe-party-sa-22-01-2022


  Location:

  Augustensaal, Im Annahof 4, 86150 Augsburg


  Veranstalter:

  Copa Caribe - Latin Events since 2018


  Facebook:

  https://www.facebook.com/copacaribe.augsburg
type: event
duration: "300"
promo: No
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FMeIdCU0HjEUjBY1qdU1ExxBmGth2%2F679ced87-aa43-4d60-aa25-9c9e2ccdd00c?alt=media&token=dc08fb19-78ed-4bce-a57e-2884d079b0b1
createdAt: 1640366777197
watchersCount: 0
price: 25-30 EUR
commentsLast: ~
promoter: Deniz
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: RJ8axMeFxMOgrRn2eXFl
promotedBy: MeIdCU0HjEUjBY1qdU1ExxBmGth2
international: No
views: 2
updatedAt: 1640366777197
updatedBy: MeIdCU0HjEUjBY1qdU1ExxBmGth2
visibility: Public
facebook: https://www.facebook.com/copacaribe.augsburg
eventType: Concert
organiser: ""
form: No
createdBy: MeIdCU0HjEUjBY1qdU1ExxBmGth2
commentsCount: 0
name: Concert Dani J + DJ Tronky in Augsburg + Party
online: No
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2022-01-22T18:00:00.000Z
username: Deniz
star:
  count: 1
  list:
    alejito: true
watch:
  count: 1
  list:
    Marcos: true
viewsCount: 57
