endDate:
  _seconds: 1618252200
  _nanoseconds: 0
link: an.milite@gmail.com
description: >-
  Mondays LadyStyling Class


  👤 Price: 1h = 10 EUR 👥 Other Classes available - Package prices when booking more than one class


  🛒 REGISTRATION: an.milite@gmail.com or message us directly 

  —————————————————————————————— 

  🌐 Fb Page: facebook.com/annamildance 

  📷 Instagram: instagram.com/milite_anna 

  💬 Whatsapp / SMS: +4917683366552
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F8yp79cUd0jZtnVn34NxhBuMpxrx1%2F1b2b52ce-79dd-4da2-ab44-2ea14761aebd?alt=media&token=2ac45cf7-3bc9-4874-842f-d3bb320e5d06
duration: "60"
createdAt: 1617476384961
watchersCount: 0
price: 10 €
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FRN1aCu7BgPa52uy1gzsu.png?generation=1618141171236922&alt=media
commentsLast: ~
id: RN1aCu7BgPa52uy1gzsu
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 2
updatedAt: 1617476384961
updatedBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
address: Online Zoom
visibility: Public
viewsCount: 2
eventType: Course
form: Yes
createdBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
commentsCount: 0
name: LIVE ONLINE *BACHATA LADYSTYLING CLASS*
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-04-12T17:30:00.000Z
username: AnnaMil
