venue:
  website: http://www.facebook.com/cafebar.maracas
  formatted_address: Nekázanka 8, Nové Město, 110 00 Praha-Praha 1, Czechia
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "8"
      short_name: "8"
    - types:
        - route
      long_name: Nekázanka
      short_name: Nekázanka
    - types:
        - neighborhood
        - political
      long_name: Nové Město
      short_name: Nové Město
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Praha 1
      short_name: Praha 1
    - types:
        - administrative_area_level_2
        - political
      long_name: Hlavní město Praha
      short_name: Hlavní město Praha
    - types:
        - administrative_area_level_1
        - political
      long_name: Hlavní město Praha
      short_name: Hlavní město Praha
    - types:
        - country
        - political
      long_name: Czechia
      short_name: CZ
    - types:
        - postal_code
      long_name: 110 00
      short_name: 110 00
  url: https://maps.google.com/?cid=4567179202943258383
  name: Café Bar Maracas
  geometry:
    viewport:
      south: 50.0838506697085
      north: 50.0865486302915
      east: 14.4290272302915
      west: 14.4263292697085
    location:
      lng: 14.4276184
      lat: 50.08516760000001
  place_id: ChIJf6kboeyUC0cRDw_8gEnhYT8
  international_phone_number: +420 734 141 712
endDate: 2021-11-21T03:00:00.000Z
organisedBy: GEYBE2nFRAPu2y7Ie7dKF2bZPKk1
description: |-
  Salsa - Bachata - Kizomba party ️♪♫

  ▷ Dj Lole

  ⭐️ Vstup zdarma / Free entry ️️⭐️

  (Reservace ☛ 734 141 712)
type: event
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FGEYBE2nFRAPu2y7Ie7dKF2bZPKk1%2F90b948fe-489f-4a95-acbc-db4d551e450d?alt=media&token=2969a61c-6905-43ed-8226-4a62c9b4be6a
duration: custom
createdAt: 1630404848702
watchersCount: 0
price: FREE
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2Fer32CIClR8lILWec4jXv.png?generation=1636833779165873&alt=media
commentsLast: ~
promotedBy: GEYBE2nFRAPu2y7Ie7dKF2bZPKk1
place: ChIJi3lwCZyTC0cRkEAWZg-vAAQ
id: rog2xUzMGh13tsuK62t2
views: 19
updatedAt: 1630404848702
updatedBy: GEYBE2nFRAPu2y7Ie7dKF2bZPKk1
visibility: Public
eventType: Party
organiser: DjLole
form: No
createdBy: GEYBE2nFRAPu2y7Ie7dKF2bZPKk1
commentsCount: 0
name: Salsa Bachata Kizomba party in Las Maracas ★
online: No
styles:
  Timba:
    level: Interested
    selected: true
  Bachata:
    level: Interested
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    selected: true
region:
  name: Prague
  location:
    country: Czechia
    latitude: 50.0755381
    locality: Prague
    usedGps: false
    place_id: ChIJi3lwCZyTC0cRkEAWZg-vAAQ
    longitude: 14.4378005
startDate: 2021-11-20T20:00:00.000Z
username: DjLole
viewsCount: 22
