venue:
  formatted_address: Sonnenstraße 7, 80331 München, Germany
  website: http://www.tanzschuleamstachus.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "7"
      short_name: "7"
    - types:
        - route
      long_name: Sonnenstraße
      short_name: Sonnenstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Altstadt-Lehel
      short_name: Altstadt-Lehel
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80331"
      short_name: "80331"
  url: https://maps.google.com/?cid=7618752569010268631
  name: Tanzschule am Stachus
  geometry:
    viewport:
      south: 48.13684386970849
      north: 48.13954183029149
      east: 11.5668774802915
      west: 11.5641795197085
    location:
      lng: 11.56564
      lat: 48.13818409999999
  place_id: ChIJCxXM5ZV1nkcR16lzexg_u2k
  international_phone_number: +49 1590 1227277
endDate:
  _seconds: 1634162400
  _nanoseconds: 0
description: |+
  Beautiful location with rooftop.

  - music from DJ Bubu
  - 3G Rules

  How to participate?
  1. Please write a message to DJ Bubu
  +61 412 564 562 - With your name+corona 
  certificate
  2. Pay the ticket via PayPal
  3. Enjoy the party

type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2F18a80a80-daa5-4e7b-96d0-3916b2b3e529?alt=media&token=91f4ff79-8a11-4a53-9b50-183a6e4a6743
duration: "180"
createdAt: 1633331066075
watchersCount: 0
price: 8 EUR
commentsLast: ~
id: RptNANB1wQ6TqFoeNQ9o
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 10
updatedAt: 1633331066075
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
viewsCount: 10
eventType: Party
organiser: LatinoDancer
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: "Bachata sensual party "
online: No
styles:
  SensualBachata:
    level: Interested
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-13T19:00:00.000Z
username: Vitali
