endDate: 2021-07-31T15:00:00.000Z
link: http://afrodanceday3107.eventbrite.de/
type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FqTPAP7OhWMYjtoPXtpUJavNz5Fr2%2Fa689cfbd-a1e1-4085-92e7-a1c74ef64a63?alt=media&token=7cce7656-6379-4756-a531-f348c14668dc
createdAt: 1626858932685
watchersCount: 0
price: 39EUR
commentsLast: ~
id: RqO48NObunrFKsVuPpVJ
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 4
updatedAt: 1626858932685
address: Habacherstr. 67
updatedBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
visibility: Public
eventType: Workshop
form: Yes
createdBy: qTPAP7OhWMYjtoPXtpUJavNz5Fr2
commentsCount: 0
name: Afro Dance Day
online: No
styles:
  Afrobeats:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-07-31T11:30:00.000Z
username: lakossa
viewsCount: 52
