venue:
  formatted_address: Gablonzer Str. 9, 76185 Karlsruhe, Germany
  website: http://www.sonlatino.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "9"
      short_name: "9"
    - types:
        - route
      long_name: Gablonzer Straße
      short_name: Gablonzer Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Mühlburg
      short_name: Mühlburg
    - types:
        - locality
        - political
      long_name: Karlsruhe
      short_name: Karlsruhe
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Karlsruhe
      short_name: Kreisfreie Stadt Karlsruhe
    - types:
        - administrative_area_level_2
        - political
      long_name: Karlsruhe
      short_name: KA
    - types:
        - administrative_area_level_1
        - political
      long_name: Baden-Württemberg
      short_name: BW
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "76185"
      short_name: "76185"
  url: https://maps.google.com/?cid=8926798613940117231
  name: Son Latino Dance Studio
  geometry:
    viewport:
      south: 49.02229426970851
      north: 49.02499223029151
      east: 8.354233980291502
      west: 8.351536019708497
    location:
      lng: 8.352825700000002
      lat: 49.0236634
  international_phone_number: +49 721 6638886
  place_id: ChIJ12tDlScHl0cR755ZDQtc4ns
endDate: 2021-10-09T17:00:00.000Z
organisedBy: fPFOWINB1LNTCvLqLWxxgLuYhsX2
link: https://www.sonlatino.de/tanzschule/courses.php?Bachata+und+Merengue=info&lID=168&ccID=99&osCsid=c9dfffce1aa80342e73c596fb5f30bdc
description: >-
  Son Latino proudly presents

  BACHATA DOMINICANA BOOTCAMP by EVELYN "LA NEGRA"

  FR.08.+SA.09.10.2021 ✱ SON LATINO KARLSRUHE

  Lerne von der energische und erfahrene Dozentin Evelyn "La Negra" Schritte, Body Flow & Moves, Musikalität und spaßigen Kombinationen dieses faszinierenden Tanzes. Evelyn ist eine sehr gern gesehene Trainerin bei allen Bachata-Festivals weltweit.

  In den zwei 3-Stündigen Bootcamps werden musikalische und tänzerische Grundlagen der Bachata Dominicana vermittelt.

  Voraussetzung für die Teilnahme sind gute Bachata Basics.

  Die Anzahl der Plätze ist limitiert.

  10% Ermäßigung bei Buchung beiden Bootcamps

  3G (Geimpft, Genessen, Getestet (jeder Test)

  Weitere Infos & Anmeldungen unter

  www.sonlatino.de
type: event
promo: Yes
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FfPFOWINB1LNTCvLqLWxxgLuYhsX2%2Ff320512c-c9e4-4cb4-96ac-b9456126b1d2?alt=media&token=0b6aae1b-5c04-488d-80c9-7ee112313669
createdAt: 1632075170244
watchersCount: 0
price: Ab 49 euro
commentsLast: ~
promotedBy: fPFOWINB1LNTCvLqLWxxgLuYhsX2
id: S2Msrr1jKvGwER87ZDDy
place: ChIJCXjgokgGl0cRf-63THNV_LY
views: 4
updatedAt: 1632075170244
updatedBy: fPFOWINB1LNTCvLqLWxxgLuYhsX2
visibility: Public
eventType: Workshop
organiser: alyonadance
form: Yes
createdBy: fPFOWINB1LNTCvLqLWxxgLuYhsX2
commentsCount: 0
name: Bachata Dominicana Bootcamp ✱ Evelyn La Negra ✱ 08.+09.10.21
online: No
styles:
  DominicanBachata:
    level: Intermediate
    highlighted: false
    selected: true
region:
  name: Karlsruhe
  location:
    country: Germany
    latitude: 49.0068901
    locality: Karlsruhe
    usedGps: false
    place_id: ChIJCXjgokgGl0cRf-63THNV_LY
    longitude: 8.4036527
startDate: 2021-10-08T16:00:00.000Z
username: alyonadance
viewsCount: 13
