endDate: 2021-07-13T21:00:00.000Z
type: event
duration: custom
createdAt: 1626178495513
watchersCount: 0
price: FREE
commentsLast: ~
id: s9a0o2I6j2KxtRIcl5UK
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 2
updatedAt: 1626178495513
updatedBy: N2N8hjGOw0dU0k0u1mpp0DlGJv93
address: Pinakothek der Moderne
visibility: Public
viewsCount: 2
eventType: Party
form: No
createdBy: N2N8hjGOw0dU0k0u1mpp0DlGJv93
commentsCount: 0
name: Reunión Timbera
online: No
styles:
  Casino:
    level: Interested
    highlighted: false
    selected: true
  Afro:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-07-14T17:00:00.000Z
username: salsa.cubana.munich
