venue:
  formatted_address: Stockholm, Sweden
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png
  html_attributions: []
  address_components:
    - types:
        - locality
        - political
      long_name: Stockholm
      short_name: Stockholm
    - types:
        - administrative_area_level_1
        - political
      long_name: Stockholm County
      short_name: Stockholm County
    - types:
        - country
        - political
      long_name: Sweden
      short_name: SE
  url: https://maps.google.com/?q=Stockholm,+Sweden&ftid=0x465f763119640bcb:0xa80d27d3679d7766
  name: Stockholm
  geometry:
    viewport:
      south: 59.22444299576489
      north: 59.42784094305499
      east: 18.19822899322501
      west: 17.76587601870478
    location:
      lng: 18.0685808
      lat: 59.32932349999999
  place_id: ChIJywtkGTF2X0YRZnedZ9MnDag
endDate: 2021-10-10T18:00:00.000Z
link: https://alocubano.se/alocubano-salsa-festival/
description: <w-youtube url="https://youtu.be/tC0k7mZxe2c"></w-youtube>
type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2F8208e06d-4a99-42a5-8163-8fda92ab7028?alt=media&token=563a1a2a-9eb9-4183-8aa8-4720ad966f75
createdAt: 1631881224614
watchersCount: 0
price: TICKETS
commentsLast: ~
place: ""
id: SdJhEI4kOME0L3sBCl5Y
views: 8
updatedAt: 1631881224614
updatedBy: 5hkUljYCTSPJwsDqNqgGYRe1Tok2
visibility: Public
viewsCount: 8
eventType: Festival
organiser: Promoter
form: Yes
createdBy: 5hkUljYCTSPJwsDqNqgGYRe1Tok2
commentsCount: 0
name: Alocubano Salsa Festival Stockholm
online: No
styles:
  Salsa:
    level: Interested
    highlighted: false
    selected: true
  Casino:
    level: Interested
    highlighted: false
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
startDate: 2021-10-07T17:00:00.000Z
username: Promoter
