venue:
  formatted_address: Mainlände 1, 97209 Veitshöchheim, Germany
  website: http://www.mainfrankensaele.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "1"
      short_name: "1"
    - types:
        - route
      long_name: Mainlände
      short_name: Mainlände
    - types:
        - locality
        - political
      long_name: Veitshöchheim
      short_name: Veitshöchheim
    - types:
        - administrative_area_level_3
        - political
      long_name: Würzburg
      short_name: WÜ
    - types:
        - administrative_area_level_2
        - political
      long_name: Unterfranken
      short_name: Unterfranken
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "97209"
      short_name: "97209"
  url: https://maps.google.com/?cid=8972513965889239211
  name: Mainfrankensäle
  geometry:
    viewport:
      south: 49.8292380197085
      north: 49.8319359802915
      east: 9.871176830291503
      west: 9.868478869708499
    location:
      lng: 9.8699279
      lat: 49.83059249999999
  place_id: ChIJxd-0fUWRokcRqzgP3-nFhHw
  international_phone_number: +49 931 7809000
endDate: 2021-12-11T19:00:00.000Z
link: https://www.saborlatinofestival.de/
description: https://www.facebook.com/events/930319687315782
type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F5hkUljYCTSPJwsDqNqgGYRe1Tok2%2Fcd3d0a23-11a6-4d9f-b75e-261a555cd9dc?alt=media&token=7ec8ad99-1eda-4ad8-a4c8-3dbce858850d
createdAt: 1631883821327
watchersCount: 0
price: TICKETS
commentsLast: ~
place: ""
id: sRkM2nYuvLbIh5rbRAAi
views: 13
updatedAt: 1631883821327
updatedBy: 5hkUljYCTSPJwsDqNqgGYRe1Tok2
visibility: Public
eventType: Festival
organiser: Promoter
form: Yes
createdBy: 5hkUljYCTSPJwsDqNqgGYRe1Tok2
commentsCount: 0
name: Sabor Latino Festival Würzburg
online: No
styles:
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
startDate: 2021-12-11T18:00:00.000Z
username: Promoter
viewsCount: 19
