venue:
  website: http://www.iwanson.de/
  formatted_address: Adi-Maislinger-Straße 12, 81373 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "12"
      short_name: "12"
    - types:
        - route
      long_name: Adi-Maislinger-Straße
      short_name: Adi-Maislinger-Straße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Sendling-Westpark
      short_name: Sendling-Westpark
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81373"
      short_name: "81373"
  url: https://maps.google.com/?cid=5492811770859622788
  name: Iwanson International School of Contemporary Dance
  geometry:
    viewport:
      south: 48.12758666970849
      north: 48.13028463029149
      east: 11.5369510302915
      west: 11.5342530697085
    location:
      lng: 11.5359317
      lat: 48.12880579999999
  place_id: ChIJG-zlKa7YnUcRhBEsFDRjOkw
  international_phone_number: +49 89 7606085
endDate: 2021-10-17T13:15:00.000Z
claimed: No
organisedBy: ""
description: >+
  LONG TIME NO SEE GUYS


  Lasst uns gemeinsam in den Herbst tanzen...!!!


  Programm:


  Sonntag 17.10


  10.30 - 11.00 Registration

  11.00 - 12.30 Men Movin Workshop

  12.45 - 15.15 Latin meets HipHop


  Beschreibung:



  MEN MOVIN WORKSHOP


  GENTS... in der gemeinsamen Zeit befassen wir uns mit Stilelementen aus Salsa, Rumba, Afro und Bodymovement und verleihen diesen eine männliche Ausrucksnote die Eurem Tanz das gewisse extra verleiht.



  LATIN MEETS HIPHOP


  Im ersten Teil schauen wir uns die Basics im Bereich HipHop, Salsa und Reggaeton an... kommen in das Gefühl und den Groove der Steps. 

  Zu späterer Stunde packen wir die unterschiedlichen Stilrichtungen zu Sequenzen zusammen und üben uns in Sachen Dynamik und Flow.


  Ich freu mich auf DEIN Kommen und DEINE Energie. Zöger nicht und schreib mir einfach, wenn du dabei sein möchtest.


  DEIN EMANUEL

  ______________________________________ 


  LOCATION:


  Iwanson International School of Contemporary Dance


  Adresse: 

  Adi-Maislinger-Straße 12, 81373 München

  STUDIO 1


  ____________________________________


  Preis:


  Men Movin Workshop     25€


  Latin meets HipHp          40€


  _______________________________________



  ANMELDUNG: (erforderlich) unter:


  +176 82 13 88 90


  info@emanuel-lederer


  BEZAHLUNG via:


  PayPal: emanuel-lederer@gmx.de


  oder


  Bank Überweisung:

    IBAN: DE74 7009 3400 0000 0574 01 

  BIC:	   GENODEF	


type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2Fa97c22cd-1492-419f-97dc-4a789e467fdd?alt=media&token=9668d343-d7bc-4f95-83fd-cda1bbee9f13
createdAt: 1634038944764
watchersCount: 0
price: 25-40 EUR
commentsLast: ~
promoter: Vitali
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: SZgXGBq7V3WdcE9k95yf
international: No
views: 10
updatedAt: 1634038944764
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
facebook: https://facebook.com/events/s/men-movin-latins-meets-hiphop/923458541594611/
eventType: Workshop
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Latin meets Hip-Hop
online: No
styles:
  HipHop:
    level: Intermediate
    highlighted: false
    selected: true
  Timba:
    level: Intermediate
    highlighted: false
    selected: true
  Reggaeton:
    level: Intermediate
    highlighted: false
    selected: true
  Salsa:
    level: Intermediate
    highlighted: false
    selected: true
  Afro:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-17T08:30:00.000Z
username: Vitali
viewsCount: 12
