venue:
  formatted_address: Westenriederstraße 41, 80331 München, Germany
  website: http://www.salsaclub-munich.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "41"
      short_name: "41"
    - types:
        - route
      long_name: Westenriederstraße
      short_name: Westenriederstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Altstadt-Lehel
      short_name: Altstadt-Lehel
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80331"
      short_name: "80331"
  url: https://maps.google.com/?cid=17999243784988121499
  name: Salsa Club Munich by Hakan
  geometry:
    viewport:
      south: 48.13373901970849
      north: 48.13643698029149
      east: 11.5813456802915
      west: 11.5786477197085
    location:
      lng: 11.5800076
      lat: 48.1351427
  place_id: ChIJU60HW-F1nkcRm9nfvdsoyvk
  international_phone_number: +49 172 8533891
endDate:
  _seconds: 1639785600
  _nanoseconds: 0
organisedBy: ""
claimed: No
link: https://www.tickettailor.com/events/bachatasensualnight/624220/
description: >-
  Dear lovely community,


  next Friday is our last weekly Bachata Sensual Fridays party for this year. Due to the current corona regulations, it will be a private event again, only for the bachata community Munich members. 

  These are the facts:

  Date: 17.12.2021

  Entry: 21:00

  COVID Rule: 2G+ (We cannot offer free tests, please bring your test/QR Code with you. Without rapid test we are not allowed to let you in)

  Price: 10 € + 2,50 € Voucher

  ONLINE 100 TICKETS ARE AVAILABLE 

  You can buy tickets as usually under:


  http://www.bachata-sensual.party
type: event
duration: "240"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2Fd892b2fc-5d88-437b-b565-9ff0e2d1dc42?alt=media&token=4c4c34e9-7ac6-48a3-a261-526626d92c02
createdAt: 1639555838061
watchersCount: 0
price: 10 EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FTFwaDGrdPLqXIVkLnJhq.png?generation=1639666084983534&alt=media
commentsLast: ~
promoter: Vitali
id: TFwaDGrdPLqXIVkLnJhq
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
international: No
views: 16
updatedAt: 1639555838061
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Members
eventType: Party
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: "Bachata sensual X-Mas party "
online: No
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-12-17T20:00:00.000Z
username: Vitali
viewsCount: 18
