endDate:
  _seconds: 1628100000
  _nanoseconds: 0
link: https://doo.net/veranstaltung/81683/buchung
description: >-
  The fireworks of classes and workshops won't stop! Let's face it - we didn't
  have international teachers here for a while now - let's learn from Anna as
  much as we can!


  This class is for improver/intermediate level.

  We will work on headmovements / axis control. Both Zouk basics and basic headmovements are a requirement to join this class.


  If you are a beginner, take a look at our Beginners' intensive class with Anna on Thursday - this is MADE for you to start your journey into Zouk. https://www.facebook.com/events/980797602680155


  REGISTER here for the intermediate level class: https://doo.net/veranstaltung/81683/buchung
type: event
duration: "90"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FG008dEeTZJcXLBzzL2krS0Ynumu2%2F0ee6c14a-71c2-4ad9-97d9-4e8e4d9534d4?alt=media&token=2d963522-aa94-4d54-8ce7-21d5fa170c1c
createdAt: 1627950646874
watchersCount: 0
price: 18€
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2Fti2InUeuExFZrf1fC2UD.png?generation=1627992974690145&alt=media
commentsLast: ~
id: ti2InUeuExFZrf1fC2UD
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 1
updatedAt: 1627950646874
address: Studio Rebecca - Studio white (3rd floor) - Anglerstraße 6, 80339
  München, Deutschland
updatedBy: G008dEeTZJcXLBzzL2krS0Ynumu2
visibility: Public
eventType: Course
form: Yes
createdBy: G008dEeTZJcXLBzzL2krS0Ynumu2
commentsCount: 0
name: Brazilian Zouk with Anna Hoekstra - "Axis Control" - Improver/Intermediate
online: No
styles:
  BrazilianZouk:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-08-04T16:30:00.000Z
username: Thomas
viewsCount: 5
