venue:
  formatted_address: Geretsrieder Str. 6, 81379 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "6"
      short_name: "6"
    - types:
        - route
      long_name: Geretsrieder Straße
      short_name: Geretsrieder Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Thalkirchen-Obersendling-Forstenried-Fürstenried-Solln
      short_name: Thalkirchen-Obersendling-Forstenried-Fürstenried-Solln
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81379"
      short_name: "81379"
  url: https://maps.google.com/?q=Geretsrieder+Str.+6,+81379+M%C3%BCnchen,+Germany&ftid=0x479dd8d532131c0d:0xf463e52cbecb2077
  name: Geretsrieder Str. 6
  geometry:
    viewport:
      south: 48.0993283197085
      north: 48.1020262802915
      east: 11.5346033302915
      west: 11.5319053697085
    location:
      lng: 11.533212
      lat: 48.10057159999999
  place_id: ChIJDRwTMtXYnUcRdyDLvizlY_Q
endDate: 2022-01-26T19:30:00.000Z
claimed: Yes
organisedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
description: >-
  Here you learn the basic steps as well as figures and step-combinations.


  The focus is on good dance posture as well as leadership and follow-up elements.



  ## Attention


  This is a 2G+. You should be vaccinated / recovered + need a negative test to come in.
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F8yp79cUd0jZtnVn34NxhBuMpxrx1%2F4a18f874-3fee-4903-8821-902bcfe7a5a0?alt=media&token=5348bb82-7e2c-4b19-b8bc-a682f2235043
promo: Yes
duration: custom
createdAt: 1639669802297
watchersCount: 0
price: 50 EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FtjYAbt1On17zSA3uAhgm.png?generation=1639669962873454&alt=media
commentsLast: ~
promoter: AnnaMil
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
id: tjYAbt1On17zSA3uAhgm
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 18
updatedAt: 1639669802297
updatedBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
visibility: Public
confirmation: >-
  Dear Guest,


  You are confirmed and almost done.


  You can do your payment via PayPal or Bank.


  For Bank-transfer the links:


  Registration without Partner = 50€

  https://buy.stripe.com/7sIg0D3VT6Z60Hm28a


  Registration CoupleSpecial (Leader&Follower) = 80€

  https://buy.stripe.com/4gw6q3cspabi3Ty145


  For PayPal - choose Family&Friends: an.milite@gmail.com


  – Attention – This is a 2G+. You should be vaccinated / recovered + need a negative test to come in.


  Thank you & See you soon Anna 🦋
eventType: Course
organiser: AnnaMil
form: No
createdBy: 8yp79cUd0jZtnVn34NxhBuMpxrx1
commentsCount: 0
name: Bachata B1
online: No
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2022-01-05T18:30:00.000Z
username: AnnaMil
viewsCount: 25
