venue:
  formatted_address: Dachauer Str., München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png
  html_attributions: []
  address_components:
    - types:
        - route
      long_name: Dachauer Straße
      short_name: Dachauer Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Moosach
      short_name: Moosach
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Dachau
      short_name: DAH
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
  url: https://maps.google.com/?q=Dachauer+Str.,+M%C3%BCnchen,+Germany&ftid=0x479e7655f53028e5:0x7504b206b2aa3a93
  name: Dachauer Straße
  geometry:
    viewport:
      south: 48.1810099197085
      north: 48.18370788029149
      east: 11.5110255802915
      west: 11.5083276197085
    location:
      lng: 11.5096766
      lat: 48.1823589
  place_id: EiBEYWNoYXVlciBTdHIuLCBNw7xuY2hlbiwgR2VybWFueSIuKiwKFAoSCeUoMPVVdp5HEZM6qrIGsgR1EhQKEgkr87lIBneeRxGApTkJpCUdBQ
endDate:
  _seconds: 1639425600
  _nanoseconds: 0
organisedBy: ""
claimed: No
description: "Der Hochzeits - Express Tanzkurs vermittelt Ihnen die wichtigsten
  Tänze. Er verfeinert und komplementiert zugleich Ihr Auftreten und zeigt Ihnen
  die wichtigsten Verhaltensregeln, um Sie an Ihrem großen und schönsten Tag im
  Leben präsentieren zu können. Dauer: 4 x 90 Minuten"
type: event
duration: "90"
cover: ""
createdAt: 1640362470584
watchersCount: 0
price: 75 EUR
commentsLast: ~
promoter: Vitali
id: tlDbBHplEGTdwCCH8hef
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 1
updatedAt: 1640362470584
website: http://tanzschule-proepster.de/component/option,com_seminar/Itemid,88/
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Course
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Tanzkurs Stufe 1
online: No
styles: {}
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-12-13T18:30:00.000Z
username: Vitali
hide:
  count: 0
  list: {}
viewsCount: 13
