venue:
  formatted_address: Barer Str. 40, 80333 München, Germany
  website: https://www.pinakothek-der-moderne.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/museum-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "40"
      short_name: "40"
    - types:
        - route
      long_name: Barer Straße
      short_name: Barer Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Maxvorstadt
      short_name: Maxvorstadt
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80333"
      short_name: "80333"
  url: https://maps.google.com/?cid=14384342178029021798
  room: Area 1
  name: Pinakothek der Moderne
  geometry:
    viewport:
      south: 48.1457500697085
      north: 48.1484480302915
      east: 11.5730605802915
      west: 11.5703626197085
    location:
      lng: 11.5723021
      lat: 48.1471559
  map: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2F54d1467f-62f9-4002-a37d-7e6e37ed0420?alt=media&token=676da4ef-b6c3-4a92-8de0-42370c700d71
  international_phone_number: +49 89 23805360
  place_id: ChIJW8LuYO51nkcRZqoW2f9yn8c
endDate:
  _seconds: 1634499000
  _nanoseconds: 0
claimed: Yes
organisedBy: 9GwaYZZIzkgWWeuHb63MejTPjAu2
type: event
duration: "120"
promo: ""
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F9GwaYZZIzkgWWeuHb63MejTPjAu2%2F7011ba6a-84f7-408f-8540-711f442c963a?alt=media&token=783150ae-e279-43bf-be21-ce8b2f65d8df
createdAt: 1634126660001
watchersCount: 0
price: Free
commentsLast: ~
promoter: Katja
promotedBy: 9GwaYZZIzkgWWeuHb63MejTPjAu2
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: TnlJx6teqbzO3554k6qz
international: No
views: 11
updatedAt: 1634126660001
updatedBy: 9GwaYZZIzkgWWeuHb63MejTPjAu2
visibility: Public
eventType: Party
organiser: Katja
form: No
createdBy: 9GwaYZZIzkgWWeuHb63MejTPjAu2
commentsCount: 0
name: "Kleine Cubana Party "
online: No
styles: {}
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-17T17:30:00.000Z
username: Katja
viewsCount: 43
