venue:
  formatted_address: Ellispontou, Kallithea 630 77, Greece
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png
  html_attributions: []
  address_components:
    - types:
        - route
      long_name: Ellispontou
      short_name: Ellispontou
    - types:
        - locality
        - political
      long_name: Kallithea
      short_name: Kallithea
    - types:
        - administrative_area_level_3
        - political
      long_name: Chalkidiki
      short_name: Chalkidiki
    - types:
        - country
        - political
      long_name: Greece
      short_name: GR
    - types:
        - postal_code
      long_name: 630 77
      short_name: 630 77
  url: https://maps.google.com/?cid=7734401736766042688
  name: Sunway Beach Bar
  geometry:
    viewport:
      south: 40.0726495697085
      north: 40.0753475302915
      east: 23.4522220302915
      west: 23.4495240697085
    location:
      lng: 23.4511405
      lat: 40.0741698
  place_id: ChIJn8KdjPgrphQRQLIapmYdVms
endDate: 2021-09-27T17:00:00.000Z
link: https://fb.me/e/1w9540Adz
description: |
  Salsa Bachata Kizomba Dance Trip to Greece 
  15th - 27th September 2021 
type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FNdWULS1MNCbIwfn8Py2aR1tdHiz2%2Feeed58cc-48a9-4b1e-bf14-fdcdb0b5111e?alt=media&token=b496fa63-9b68-4dfe-ab61-30bc93c57ba3
createdAt: 1622141577364
watchersCount: 0
price: ""
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FTPn6u4EldvaYCBJWRiw2.png?generation=1631438528755521&alt=media
commentsLast: ~
place: ""
id: TPn6u4EldvaYCBJWRiw2
views: 6
updatedAt: 1622141577364
address: "Sunway Beach Kalithe/Chalkidiki Greece "
updatedBy: NdWULS1MNCbIwfn8Py2aR1tdHiz2
visibility: Public
eventType: Festival
form: Yes
createdBy: NdWULS1MNCbIwfn8Py2aR1tdHiz2
commentsCount: 0
name: "Dance Invasion Chalkidiki 2021 "
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
startDate: 2021-09-14T23:00:00.000Z
username: Melungeon
viewsCount: 9
