venue:
  formatted_address: Neusser Str. 216, 50733 Köln, Germany
  website: http://www.tanzschule-tanzraum.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "216"
      short_name: "216"
    - types:
        - route
      long_name: Neusser Straße
      short_name: Neusser Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Nippes
      short_name: Nippes
    - types:
        - locality
        - political
      long_name: Köln
      short_name: Köln
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Köln
      short_name: Kreisfreie Stadt Köln
    - types:
        - administrative_area_level_2
        - political
      long_name: Köln
      short_name: K
    - types:
        - administrative_area_level_1
        - political
      long_name: Nordrhein-Westfalen
      short_name: NRW
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "50733"
      short_name: "50733"
  url: https://maps.google.com/?cid=2981146820628674026
  name: Ballet School Annette Farber
  geometry:
    viewport:
      south: 50.96033351970851
      north: 50.96303148029151
      east: 6.955849630291502
      west: 6.953151669708498
    location:
      lng: 6.954593999999999
      lat: 50.9616923
  place_id: ChIJy85DyZwlv0cR6nXbEj0pXyk
  international_phone_number: +49 221 233233
endDate: 2022-04-03T16:00:00.000Z
organisedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
claimed: Yes
link: https://fb.me/e/iUhEfwWWe
description: >-
  You like urban kiz and want to start with it?

  - You dance at parties and festivals ... but you have the feeling that you are still missing something?

  - Are you still looking for the so-called "connection" to your partner?

  - Do you have trouble finding your balance when your partner leads you slowly or quickly?

  - Do you even know what makes the difference between “urban kiz” and “kizomba” in terms of dance?


  You are here at the right place!


  I am pleased to welcome you to my customized URBAN KIZ program. For the first time here in NRW! This series of workshops will be INTENSIVE and will challenge you 100% in URBAN KIZ.


  It doesn't matter if you are a beginner or not!


  It doesn't matter if you are a follower or not!


  Within 7 appointments you will get the elements, exercises, theory and practice time that you need to get the best out of yourself. As a highlight you will be assisted by 4 experienced international Kizomba and Urbankiz teachers.


  Under an international and high quality pedagogy, we will accompagne you in various dance topics and remove your obstacles.


  ---


  Head teacher:

  - Stone’s rock


  Guest teacher:

  - Ledoux Dianza

  - Danielle Dejong

  - Ramona


  - URBAN KIZ BASICS

  - SYNCOPATION 

  - ORIENTATIONS

  - POWERFUL SAIDAS

  - LEG LEADING 

  - CONNECTION-FOOTWORK

  - FEMALE KIZ ATTITUDE

  - MALE KIZ ATTITUDE

  - MUSICALITY 1-2-3


  ** A LOOOOT OF PRACTICE TIME **


  ** A LOOOOT OF PRACTICE TIME **


  7 DATES (January 2022-April 2022):

  - Date1: Sat. January 8, 2022

  - Date2: Sun. January 9, 2022

  - Date3: Sun. January 30, 2022

  - Date4: Sun. February 20, 2022

  - Date5: Sun. February 27, 2022

  - Date6: Sat. April 02, 2022

  - Date7: Su. April 03, 2022


  ---


  DANCE LEVEL AT EACH DATE (14:00 - 18:00):

  Urban kiz Open level / Foundamentals (2 hours)


  Urban kiz Intermediate to Advanced (2 hours)


  ---


  ## Tickets:

  - Large Pass: 210 euro  all 7 dates-28 hours-Foundamental- intermediate-advanced level 

  - Small pass: 120 euro  all 7 dates-14 hours-Foundamental level 


  ## Registration


  Contact rockyourdance@gmail.com or @ramona or @ stone’s rock


  ☝🏾☝🏾☝🏾☝🏾☝🏾😃☝🏾☝🏾☝🏾☝🏾☝🏾☝🏾☝🏾☝🏾


  The sessions are each time under strict respect of the Corona regulations. According to the current regulations, 2G + applies. So recovered or vaccinated and a negative Covid test
type: event
promo: Yes
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2Fm6ZLnWaUfCU1rfzcZuI93E1B1r43%2Fa0396882-46a7-4c1e-99e4-9e6f85e3c97a?alt=media&token=41e5fc19-7881-4c92-831e-cbf4996abaf4
createdAt: 1639524018526
watchersCount: 0
price: 120-210 EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FtRVVoJKwwfs85wArTjws.png?generation=1639524396002749&alt=media
commentsLast: ~
promoter: Stones
place: ChIJ5S-raZElv0cR8HcqSvxgJwQ
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
id: tRVVoJKwwfs85wArTjws
international: No
views: 4
updatedAt: 1639524018526
website: https://fb.me/e/iUhEfwWWe
updatedBy: m6ZLnWaUfCU1rfzcZuI93E1B1r43
visibility: Public
facebook: https://fb.me/e/iUhEfwWWe
eventType: Course
organiser: Stones rock & Tanzraum
form: No
createdBy: m6ZLnWaUfCU1rfzcZuI93E1B1r43
commentsCount: 0
name: INTENSIVE URBANKIZ CLASSES
online: No
styles:
  UrbanKizz:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Cologne
  location:
    country: Germany
    latitude: 50.937531
    locality: Cologne
    usedGps: false
    place_id: ChIJ5S-raZElv0cR8HcqSvxgJwQ
    longitude: 6.9602786
startDate: 2022-01-08T13:00:00.000Z
username: Stones
viewsCount: 36
