venue:
  website: http://www.fuerstenfeld.de/
  formatted_address: Fürstenfeld 12, 82256 Fürstenfeldbruck, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "12"
      short_name: "12"
    - types:
        - route
      long_name: Fürstenfeld
      short_name: Fürstenfeld
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Fürstenfeld
      short_name: Fürstenfeld
    - types:
        - locality
        - political
      long_name: Fürstenfeldbruck
      short_name: Fürstenfeldbruck
    - types:
        - administrative_area_level_3
        - political
      long_name: Fürstenfeldbruck
      short_name: FFB
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "82256"
      short_name: "82256"
  url: https://maps.google.com/?cid=17928312527415868035
  name: Veranstaltungsforum Fürstenfeld
  geometry:
    viewport:
      south: 48.1695734697085
      north: 48.1722714302915
      east: 11.2482031802915
      west: 11.2455052197085
    location:
      lng: 11.2468848
      lat: 48.1707451
  place_id: ChIJ3y7cL_5_nkcRg_rOYkEpzvg
  international_phone_number: +49 8141 6665140
endDate:
  _seconds: 1635894000
  _nanoseconds: 0
claimed: No
organisedBy: ""
description: "Karibikrhythmen, entspanntes Urlaubsfeeling, Lebensfreude! Die 30.
  Noche Latina verspricht nicht nur eingefleischten Latinos einen besonderen
  Abend mit Tanz, Musik und Show. Zu Beginn ist Gelegenheit, sich bei einem
  30-minütigen Salsa-Tanzkurs mit Tanzlehrer Ruben Chagas Diaz einzustimmen. Der
  bekannte DJ David Muñoz sorgt mit seinem Mix aus Salsa, Bachata, Merengue,
  Reggaeton und Latin-Rock für Partystimmung bis tief in die Nacht. Freuen darf
  man sich zudem auf eine packende Mitternachts-Show! Wer sich vor der Party
  noch mit Bachata-Schritten vertraut machen möchte, kann sich unter
  gloria@noche-latina.de informieren und anmelden: 19-21 Uhr, Preis (inkl.
  Noche-Latina-Eintritt): € 32,00.  Samstag06.11.202121:00 Uhr Kleiner
  Saal  VVK€ 12,00 AK€ 14,00 Veranstalter: Gloria Heep Veranstaltungsagentur"
type: event
cover: ""
duration: "300"
createdAt: 1633768609399
watchersCount: 0
price: 12-32 EUR
commentsLast: ~
promoter: Vitali
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: TSxaYp7ctpqlR6kNOgla
international: No
views: 11
updatedAt: 1633768609399
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Party
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Jubiläumsparty Noche Latina
online: No
styles:
  Timba:
    level: Interested
    highlighted: false
    selected: true
  RumbaColumbia:
    level: Interested
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Merengue:
    level: Interested
    highlighted: false
    selected: true
  DominicanBachata:
    level: Interested
    selected: true
  Reggaeton:
    level: Interested
    highlighted: false
    selected: true
  Cubaton:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-02T18:00:00.000Z
username: Vitali
viewsCount: 17
