venue:
  formatted_address: Kurfürstenstraße 3a, 10785 Berlin, Germany
  website: https://www.trybedancestudio.com/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: 3a
      short_name: 3a
    - types:
        - route
      long_name: Kurfürstenstraße
      short_name: Kurfürstenstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Mitte
      short_name: Mitte
    - types:
        - locality
        - political
      long_name: Berlin
      short_name: Berlin
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Berlin
      short_name: Kreisfreie Stadt Berlin
    - types:
        - administrative_area_level_1
        - political
      long_name: Berlin
      short_name: BE
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "10785"
      short_name: "10785"
  url: https://maps.google.com/?cid=1968106549161841524
  name: Trybe Dance Studio
  geometry:
    viewport:
      south: 52.49778706970849
      north: 52.50048503029149
      east: 13.3699006302915
      west: 13.3672026697085
    location:
      lng: 13.3686256
      lat: 52.4993133
  international_phone_number: +49 171 5652454
  place_id: ChIJ8_citTVRqEcRdFPpnnoeUBs
endDate: 2021-09-18T16:45:00.000Z
link: https://cspberlin.com/ladystyling/
description: >-
  Im Lady Styling geht es um schöne und ausdrucksstarke feminine Bewegungen in
  der kubanischen Salsa. In dem Intensivkurs lernt ihr verschiedene
  Basiselemente wie Armenbewegungen, Schrittkombinationen, Übergänge etc., die
  ihr im freien Tanz einsetzten könnt.

  Ziel ist es, euren Stil beim Tanzen für Solo-Tanz und Partnerwork zu optimieren und Kombinationen zu lernen, die typische kubanische Elemente enthalten (Pasitos, rumba cubana , Mambo, Cha-Cha-Cha, afrokubanische Elemente …). 
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FpH0880yoosdst2YzH0t6hvWMmi63%2F145829f1-757b-428f-b833-dcd8710ca5be?alt=media&token=755cac13-a3d5-4784-8106-bf618b9b7241
duration: custom
promo: Yes
createdAt: 1630275065371
watchersCount: 0
price: "15"
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FTUDKNP1SFgJVvKyLKxOi.png?generation=1630322313503241&alt=media
commentsLast: ~
place: ChIJAVkDPzdOqEcRcDteW0YgIQQ
id: TUDKNP1SFgJVvKyLKxOi
views: 2
updatedAt: 1630275065371
updatedBy: pH0880yoosdst2YzH0t6hvWMmi63
visibility: Public
eventType: Workshop
organiser: Juli
form: Yes
createdBy: pH0880yoosdst2YzH0t6hvWMmi63
commentsCount: 0
name: Ladystyling Basic Intensive
online: No
styles:
  Salsa:
    level: Advanced
    highlighted: false
    selected: true
  Casino:
    level: Advanced
    highlighted: false
    selected: true
region:
  name: Berlin
  location:
    country: Germany
    latitude: 52.52000659999999
    locality: Berlin
    usedGps: false
    place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
    longitude: 13.404954
startDate: 2021-09-04T15:30:00.000Z
username: Juli
viewsCount: 55
