venue:
  website: http://www.tanzhausemotion.de/
  formatted_address: Biberger Str. 91, 82008 Unterhaching, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "91"
      short_name: "91"
    - types:
        - route
      long_name: Biberger Straße
      short_name: Biberger Str.
    - types:
        - locality
        - political
      long_name: Unterhaching
      short_name: Unterhaching
    - types:
        - administrative_area_level_3
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "82008"
      short_name: "82008"
  url: https://maps.google.com/?cid=9015721869128002009
  name: Tanzschule München Tanzhaus emotion ADTV
  geometry:
    viewport:
      south: 48.0718735697085
      north: 48.0745715302915
      east: 11.6214237802915
      west: 11.6187258197085
    location:
      lng: 11.6200113
      lat: 48.0733528
  place_id: ChIJHS2vnMnYnUcR2WkYy0VHHn0
  international_phone_number: +49 89 74329895
endDate:
  _seconds: 1634421600
  _nanoseconds: 0
organisedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
claimed: Yes
description: >-
  The Party will include an entire Dance floor exclusively for live Kizomba
  Music by *DJ MixMillion* and a Dance floor for mixed Bachata by DJ Curly and
  Salsa by Elena (60% Bachata, 40% Salsa)


  Beforehand there will be a free, hour long introductory course for all interested in social dance. 

  It will include a survival guide for socials and a few basics for Bachata and Salsa.


  **⏰ When:** 16th October at 20:00 (Introduction course at 19:00)


  **📍 Where:** Dancehouse Emotion - Biberger Straße 91, 82008 Unterhaching -> 1. Stock, Hinterhaus -> Beschilderung folgen


  ❗️Plenty of Parking available❗️


  💰 Entrance fee: 6€


  ## IMPORTANT


  Due to the current situation we need to follow the current 3G rules which means that everyone who comes either needs a **geimpft** (vaccinated), **genesen** (recovered) status or a *test*.


  Please bring your own test in the original packaging if you can.


  We will offer tests directly at the entrance for 3€ to make entry simple for *everyone*!


  ### Please click "Going" to register for the event


  Please also write your 3G status and if you want to buy a test add: “I will buy a test for 3€”


  By signing up you and agree to pay the entrance fee of 6€
type: event
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2F01c43bc8-3028-407a-ac37-493c5d3a44ff?alt=media&token=36eb233e-c17e-4009-900e-257579b677f2
duration: "300"
createdAt: 1633360285047
watchersCount: 0
price: 6 EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FU0vODDewsVjdwZCsv8ea.png?generation=1633467358575567&alt=media
commentsLast: ~
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
id: U0vODDewsVjdwZCsv8ea
international: No
views: 287
updatedAt: 1633360285047
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Party
confirmation: |-
  Hallo,

  Vielen Dank für die Anmeldung zu Noche de emoción latina in Unterhaching

  Wir freuen uns auf euch!

  Liebe Grüße,
  Sandra, Elena, Daniel und Ugur
organiser: Sandrdida
form: No
createdBy: wtbRT0MKroNZF57oOvg9i8ZAjOV2
commentsCount: 0
name: Noche de emoción latina in Unterhaching
online: No
styles:
  UrbanKizz:
    level: Interested
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-16T17:00:00.000Z
username: Curly
viewsCount: 298
