venue:
  formatted_address: Berlin, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png
  html_attributions: []
  address_components:
    - types:
        - locality
        - political
      long_name: Berlin
      short_name: Berlin
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Berlin
      short_name: Kreisfreie Stadt Berlin
    - types:
        - administrative_area_level_1
        - political
      long_name: Berlin
      short_name: BE
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
  url: https://maps.google.com/?q=Berlin,+Germany&ftid=0x47a84e373f035901:0x42120465b5e3b70
  name: Berlin
  geometry:
    viewport:
      south: 52.33823404386677
      north: 52.67545420869131
      east: 13.76111748460941
      west: 13.08834600183454
    location:
      lng: 13.404954
      lat: 52.52000659999999
  place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
endDate: 2021-11-14T15:00:00.000Z
link: www.eventbrite.de/e/adicto-exclusive-weekend-with-pablo-y-raquel-tickets-175544286687
description: >-
  TICKETS:
  https://www.eventbrite.de/e/adicto-exclusive-weekend-with-pablo-y-raquel-tickets-175544286687?aff=eand


  🔥🔥🔥 We are back out of the ashes! Still addicted. 💪🏻


  🌟🌟🌟 WORLD BACHATA STARS IN BERLIN, GERMANY! 🌟🌟🌟


  ADICTO is honored to host World champions, Bachata stars, teachers, choreographers and performers, inventors of Smooth Bachata: Pablo y Raquel for the first time in Berlin, Germany as part of a purely Bachata Exclusive Weekend.


  This fantastic couple will be teaching 3 hours of Partnerwork, 1 hour of styling each, and 1 hour special Master Class.

  They will be accompanied by Erol & Martyna for another 3 hours of Partnerwork and 1 hour of Styling each.


  DJ DennisS will play the best Bachata tunes at the Saturday social, with a special performance by Pablo y Raquel and the opportunity to dance with them. We also have surprises and competitions planned for you.

  Due to Corona regulations, we may allow only a limited number of attendees.


  😷😷😷 SAFETY FIRST (3G RULE) 😷😷😷

  Unless otherwise stated, we need to comply with current German regulations of 3G (tested, recovered, vaccinated) to ensure the safety of our participants against COVID-19. Please present valid proof at entry. In case of not presenting valid proof, your ticket will be deemed invalid and you will not be entitled for a refund.


  📆📆📆 WORKSHOP SCHEDULE 📆📆📆


  13.11.2021 - SATURDAY


  12:00 - 13:00 Partnerwork with Erol & Martyna (INT)


  13:00 - 14:00 Partnerwork with Erol & Martyna (ADV)


  14:30 - 16:00 Partnerwork with Pablo y Raquel (INT)


  16:00 - 17:30 Partnerwork with Pablo y Raquel (ADV)


  14.11.2021 - SUNDAY


  13:00 - 14:00 Styling with Erol/Styling with Martyna (OPEN)


  14:00 - 15:00 Styling with Pablo/Styling with Raquel (OPEN)


  15:00 - 16:00 Masterclass with Pablo y Raquel (ADV/PRO)


  🎊🎊🎊 SOCIAL 🎊🎊🎊


  13.11.2021 - SATURDAY


  21:00 - 22:00 Partnerwork with Erol & Martyna (OPEN)


  22:00 - 03:00 Social with DJ DennisS, Pablo y Raquel and Erol & Martyna


  * Schedule is subject to change.


  The venue will be announced soon.


  ---

  PABLO Y RAQUEL BIO:


  Pablo Pérez started dancing the bachata in 2010 with Korke Escalona and Judith Cordero pioneers and precursors worldwide this style,(Bachata Sensual), and thank his Latin roots he started dancing Colombian folklore himself while developing skills in the Dominican bachata with renowned professionals. In 2012 gets his first place in the national championship "Bachatart Spain Edition" with his previous partner. Later he continues his training with international mambo dancers like Eddie Torres, Juan Pachanga Matos, or Adolfo Indacoechea among others. In May 2014 he reached first place at the "Footwork World Championship" competition - FWC in the category of groups held in Badajoz (Spain).

  Raquel Castro starts their training in several disciplines from contemporary and jazz to urban styles in his hometown Salamanca. But it was not until 2012 when she joined Adrian and Anita Salsa Company - World Salsa Champions - in Valladolid and began her career in Latin rhythms. At the same time, among several local dancers, creates her own team "Fusion Latina Salamanca" getting crowned champions of "Spain Bachata Masters Teams" for two consecutive years and qualified for the international competition "World Bachata Masters" in which they obtained a third and a second place in 2014 and 2015 respectively.


  Pablo & Raquel met as a couple in June 2014, since then, they have achieved great results in national and international competitions, are the current International Bachatart Fusion Champions, National Bachata Stars Improvisation Champions, and runners-up at the International Bachata Stars 2014 and 2015 qualifying for World Bachata Masters in their first year dancing together.

  Recently they reached 4th place at World Bachata Masters 2016, one of the most prestigious bachata couples competitions around the world.

  They travel teaching and sharing their style around Spain and Europe giving a different perspective of the current bachata background.

  Dancing is their job and passion and because of that, they continue their training being part of several professional salsa and bachata teams and learning from the greatest Dominican and sensual bachata instructors.

  Awards:

  - 1st place Bachata Stars Spain 2016

  - 1st place International Fusion Bachata Championship BACHTART 2015

  - 1st place BACHATART Fusion Bachata Championship Spanish Edition 2014

  - 2nd place Bachata Stars Spain 2015 and 2014

  - 2nd place International Bachata Stars 2014

  - 3rd place International Bachata Stars 2015

  - 4th place World Bachata Masters 2016
type: event
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F3ucRV7NCdPMWMf2mHXAutsuorhm2%2Ffe63156a-92f9-41ed-a739-b85c97e05dc7?alt=media&token=b8464549-f5c8-45bc-af41-635be3cad8e7
duration: custom
createdAt: 1633329371930
watchersCount: 0
price: VARIOUS
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FU90fR25XZpXzESKFIDmZ.png?generation=1633341960511873&alt=media
commentsLast: ~
id: U90fR25XZpXzESKFIDmZ
place: ""
views: 10
updatedAt: 1633329371930
updatedBy: 3ucRV7NCdPMWMf2mHXAutsuorhm2
visibility: Public
eventType: Festival
organiser: eNm
form: Yes
createdBy: 3ucRV7NCdPMWMf2mHXAutsuorhm2
commentsCount: 0
name: "ADICTO: Exclusive Weekend with Pablo y Raquel"
online: No
styles:
  BachataModerna:
    level: Interested
    highlighted: false
    selected: true
  SensualBachata:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  DominicanBachata:
    level: Interested
    highlighted: false
    selected: true
  HighHeels:
    level: Interested
    highlighted: false
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
startDate: 2021-11-13T11:00:00.000Z
username: eNm
viewsCount: 11
