venue:
  website: https://www.trybedancestudio.com/
  formatted_address: Kurfürstenstraße 3a, 10785 Berlin, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: 3a
      short_name: 3a
    - types:
        - route
      long_name: Kurfürstenstraße
      short_name: Kurfürstenstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Mitte
      short_name: Mitte
    - types:
        - locality
        - political
      long_name: Berlin
      short_name: Berlin
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Berlin
      short_name: Kreisfreie Stadt Berlin
    - types:
        - administrative_area_level_1
        - political
      long_name: Berlin
      short_name: BE
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "10785"
      short_name: "10785"
  url: https://maps.google.com/?cid=1968106549161841524
  name: Trybe Dance Studio
  geometry:
    viewport:
      south: 52.49778586970849
      north: 52.50048383029149
      east: 13.3699097302915
      west: 13.3672117697085
    location:
      lng: 13.3686256
      lat: 52.4993133
  international_phone_number: +49 171 5652454
  place_id: ChIJ8_citTVRqEcRdFPpnnoeUBs
endDate: 2021-10-23T17:30:00.000Z
link: https://cspberlin.com/ladystyling/
description: >-
  CUBAN SALSA LADYSTYLING mit Julia


  > BASIC INTENSIVE 17:00 - 18:15 Uhr

  > CHOREO INTENSIVE  18:15 - 19:30 Uhr



  Im Lady Styling geht es vor allem um schöne und ausdrucksstarke feminine Bewegungen in der kubanischen Salsa.


  Ziel ist es, euren Stil beim Tanzen für Solo-Tanz und Partnerwork zu optimieren und Kombinationen zu lernen, die typische kubanische Elemente enthalten (Pasitos, rumba cubana , Mambo, Cha-Cha-Cha, afrokubanische Elemente …). 



  >BASIC INTENSIVE


  In der ersten Stunde werden wir insbesondere anhand von Übungen zu Körperhaltung, Isolation sowie Stabilität und Drehtechniken trainieren, die ihr auch selbst zuhause zum üben nutzen könnt. Damit erweitert ihr zum einen euer Repertoire fürs Improvisieren und schult zum anderen eure Koordination, euer Körpergefühl und Weiblichkeit in der Bewegung.


  LEVEL (BASIC INTENSIVE): Für alle die den Grundschritt in Salsa Cubana beherrschen. Wenn ihr bereits Erfahrung im freien Tanzen habt, kann der Kurs auch als Vertiefung dienen.



  > CHOREO INTENSIVE


  In diesem Intensive erarbeiten wir eine Ladystyling Choreographie, die typische kubanische Elemente enthält (wie Pasitos, Elemente aus der rumba cubana , Mambo…).

  Der Fokus der Choreo liegt neben der femininen Körperbewegung in der kubanischen Salsa auf Musikalität.


  LEVEL (CHOREO INTENSIVE): Mittelstufe/ Fortgeschritten. Der Kurs richtet sich an alle, die den Grundschritt in Salsa Cubana beherrschen und erste Erfahrungen im freien Tanz haben.



  NUR Mit Voranmeldung über unsere Website !

  Begrenzte Teilnehmer*innenzahl !


  PREISE: 60 € / 4-Wochen-Kurs

  *Wenn ihr beide Kurse bucht erhaltet ihr  auf den zweiten Kurs 10 % Rabatt. 


  WICHTIGER HINWEIS:

  Im Studio sind Straßenschuhe nicht gestattet. Bitte bringt Wechselschuhe, gerne Absatzschuhe mit 🙂
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FpH0880yoosdst2YzH0t6hvWMmi63%2Fde5951f8-f927-4cae-bfb4-625d0a4552c5?alt=media&token=3254a87c-b383-473d-b2be-47abe82af23f
promo: Yes
duration: custom
createdAt: 1631713290346
watchersCount: 0
price: 60EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FUFh4qcjtcYHjFLXZZHTI.png?generation=1631713309165325&alt=media
commentsLast: ~
place: ChIJAVkDPzdOqEcRcDteW0YgIQQ
id: UFh4qcjtcYHjFLXZZHTI
views: 4
updatedAt: 1631713290346
updatedBy: pH0880yoosdst2YzH0t6hvWMmi63
visibility: Public
eventType: Course
organiser: Juli
form: Yes
createdBy: pH0880yoosdst2YzH0t6hvWMmi63
commentsCount: 0
name: Cuban Ladystyling Basic & Choreo Intensives
online: No
styles:
  Salsa:
    level: Beginner
    highlighted: false
    selected: true
  Casino:
    level: Beginner
    highlighted: false
    selected: true
region:
  name: Berlin
  location:
    country: Germany
    latitude: 52.52000659999999
    locality: Berlin
    usedGps: false
    place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
    longitude: 13.404954
startDate: 2021-10-02T15:00:00.000Z
username: Juli
viewsCount: 7
