venue:
  formatted_address: Sonnenstraße 8, 80331 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "8"
      short_name: "8"
    - types:
        - route
      long_name: Sonnenstraße
      short_name: Sonnenstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Ludwigsvorstadt-Isarvorstadt
      short_name: Ludwigsvorstadt-Isarvorstadt
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80331"
      short_name: "80331"
  url: https://maps.google.com/?q=Sonnenstra%C3%9Fe+8,+80331+M%C3%BCnchen,+Germany&ftid=0x479e75f7baaca45b:0xf222741d07de348d
  name: Sonnenstraße 8
  geometry:
    viewport:
      south: 48.13618106970849
      north: 48.13887903029149
      east: 11.5658509802915
      west: 11.5631530197085
    location:
      lng: 11.5644795
      lat: 48.1376562
  place_id: ChIJW6Ssuvd1nkcRjTTeBx10IvI
endDate:
  _seconds: 1635883200
  _nanoseconds: 0
organisedBy: J0mi8B2jsuVBNFIORdVyZ5aFvjm2
claimed: Yes
link: https://forms.gle/ztuQvHBoZRrRHF4r9
description: >-
  Друзья, приглашаю присоединиться к курсу по движению и танцам „Smart Dance“.


  Старт: 2 ноября  


  Для кого этот курс?


  🤸‍♀️тех, кто хочет развивать гибкость своего тела 


  💃🏻🕺новичков в танцах и тех, кто хочет научиться азам 


  🎶тех, кто хочет мягкую музыкальную тренировку после работы/учебы 


  ☯️тех, кто хочет настроить контакт со своим телом 


  Автор и тренер курса: Ольга Худошина @olka_hd: более 15 лет в танцах, 6 лет в социальных парных танцах, 2 года в сфере холистического здоровья, 1,5 года в умном фитнесе, в данный момент учится на натуропата и health-коуча.


  🗓Занятия будут проходить по вторникам с 19:30 до 21:00 

  📍Адрес: Sonnenstr. 8 (5й этаж), 80331 München


  Условия участия:


  ➡️ Чтобы получить максимум эффекта от курса, рекомендуем пройти минимум месячный цикл (ноябрь, например)


  ➡️ Если ты не можешь присутствовать все вторники в ноябре, твоё пропущенное занятие переносится на следующий месяц.


  👍Инвестиция за участие (в месяц): 15€ (для студентов 10€)


  ✅Всего 12 мест. Занимайте своё по ссылке
type: event
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FJ0mi8B2jsuVBNFIORdVyZ5aFvjm2%2Fcb413d1c-2426-46a5-b72d-3c6eb5ed4f00?alt=media&token=1a369569-618d-4d77-b1d8-dfb3c5691b0e
duration: "90"
createdAt: 1635351838711
watchersCount: 0
price: 15EUR / 4 Weeks
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FUFtwl2BxhTSqnKQZHtEG.png?generation=1635352105488812&alt=media
commentsLast: ~
promoter: olka_hd
id: UFtwl2BxhTSqnKQZHtEG
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: J0mi8B2jsuVBNFIORdVyZ5aFvjm2
international: No
views: 20
updatedAt: 1635351838711
updatedBy: J0mi8B2jsuVBNFIORdVyZ5aFvjm2
visibility: Public
confirmation: >-
  Дорогой друг, твое место для участие в курсе „Smart Dance“ забронировано. Жду
  тебя во вторник в 19:30.

  Ольга Худошина 
eventType: Course
organiser: olka_hd
form: Yes
createdBy: J0mi8B2jsuVBNFIORdVyZ5aFvjm2
commentsCount: 0
name: "Smart Dance (RU) "
online: No
styles:
  WestCoastSwing:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Beginner
    highlighted: false
    selected: true
  Salsa:
    level: Beginner
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-02T18:30:00.000Z
username: olka_hd
viewsCount: 25
