endDate: 2021-04-28T22:00:00.000Z
link: https://kizzafro.justclick.ru/order/bilet1/
description: >-
  🔥 Приглашаем вас на Regulyar'KA в среду, 28 апреля.

  Urban, Kizomba, Ghetto Zouk, Douceur, Tarraxinha, Semba, Tarraxo

  🎧 21.00 - 22.30 DJ MARIANNA

  🎧 22.30 - 00.00 DJ ARTY MONTE

  🎧 00.00 - 01.00 DJ K-Andy


  Мастер-классы:

  🕺 20.00-20.40 «Выход в соло и вариации комфортного обыгрывания соло» от Алексея Касаткина и Марины Мармур

  💃 20.40-21.00 Afro House (популярные степы из анимаций) от Marianna


  🏰 Место проведения: уютный лофт на Таганской.

  От метро 7-10 минут пешком. ул. Александра Солженицына 44/10

  Подробности здесь: https://vk.com/topic-97548216_46642134


  Вечеринка в среду на входе стоит - 500 рублей

  По предоплате и репосте этой новости стоимость - 450 рублей (https://kizzafro.justclick.ru/order/bilet1/)

  По предоплате парой и репосте этой новости стоимость 400 рублей (https://kizzafro.justclick.ru/order/bilet2/)

  Списки закрываются в среду в 17.00


  💡Хотите на вечеринку бесплатно, подробности здесь: https://vk.com/topic-97548216_47415279


  👉🏻 Москва. Regulyar'KA

  👉🏻 Среда, 28 апреля с 20.00 до 01.00

  👉🏻 ст.м. Таганская, ул. Александра Солженицына 44/10
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FErP9WITL4eMyf36LQ5iR9nCAIJ82%2Fc0db95e5-89d3-4570-8829-addea308d8ad?alt=media&token=d74bfdad-da1f-4e1b-b268-07da294733d8
duration: custom
createdAt: 1619436857520
watchersCount: 0
price: 400 - 500 руб.
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2Fug3hySmTwYTFBPVJc8w2.png?generation=1619436872950442&alt=media
commentsLast: ~
place: ChIJybDUc_xKtUYRTM9XV8zWRD0
id: ug3hySmTwYTFBPVJc8w2
views: 1
updatedAt: 1619436857520
address: уютный лофт на Таганской. От метро 7-10 минут пешком. ул. Александра
  Солженицына 44/10
updatedBy: ErP9WITL4eMyf36LQ5iR9nCAIJ82
visibility: Public
eventType: Party
form: Yes
createdBy: ErP9WITL4eMyf36LQ5iR9nCAIJ82
commentsCount: 0
name: Regulyar'KA
region:
  name: Moscow
  location:
    country: Russia
    latitude: 55.755826
    locality: Moscow
    usedGps: false
    place_id: ChIJybDUc_xKtUYRTM9XV8zWRD0
    longitude: 37.6172999
startDate: 2021-04-28T17:00:00.000Z
username: MaryRys
viewsCount: 6
styles:
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
  Tarraxinha:
    level: Interested
    highlighted: false
    selected: true
  Tarraxo:
    level: Interested
    highlighted: false
    selected: true
  UrbanKizz:
    level: Interested
    highlighted: false
    selected: true
  Douceur:
    level: Interested
    highlighted: false
    selected: true
  Semba:
    level: Interested
    highlighted: false
    selected: true
  BrazilianZouk:
    level: Interested
    highlighted: false
    selected: true
