venue:
  formatted_address: Mehringdamm 61, 10961 Berlin, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "61"
      short_name: "61"
    - types:
        - route
      long_name: Mehringdamm
      short_name: Mehringdamm
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Bezirk Friedrichshain-Kreuzberg
      short_name: Bezirk Friedrichshain-Kreuzberg
    - types:
        - locality
        - political
      long_name: Berlin
      short_name: Berlin
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Berlin
      short_name: Kreisfreie Stadt Berlin
    - types:
        - administrative_area_level_1
        - political
      long_name: Berlin
      short_name: BE
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "10961"
      short_name: "10961"
  url: https://maps.google.com/?q=Mehringdamm+61,+10961+Berlin,+Germany&ftid=0x47a85028803d8a4d:0xba1c7db9eee3901f
  name: Mehringdamm 61
  geometry:
    viewport:
      south: 52.4894093197085
      north: 52.4921072802915
      east: 13.3883985802915
      west: 13.3857006197085
    location:
      lng: 13.3872931
      lat: 52.4907257
  place_id: ChIJTYo9gChQqEcRH5Dj7rl9HLo
endDate:
  _seconds: 1636851600
  _nanoseconds: 0
organisedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
claimed: Yes
link: https://www.meetup.com/Internationals-in-Berlin/events/282040604
description: >-
  Welcome to the PACIFIC COAST PARTY art, dancing workshop, music and friends


  * Free bachata workshop

  * Dj Latin music

  * 2G Regel + Luca app

  * Photographer to capture the best moments

  * Entry fee €5


  Best cocktails!


  Feel free to dress the way and fun you find yourself.


  Bebo club also has a dj that will make you enjoy the best Latin rhythms of the moment to dance and enjoy with your friends.


  ### COVID-19 safety measures


  - COVID 19 vaccination required

  - Event will be indoors

  - 2G Regel
type: event
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F91wGbG4Kwaa2XmcEoEpKvwcfleL2%2Fa3458090-255a-4cbe-9268-4b7f57b33d31?alt=media&token=b3a835d3-8232-4604-9545-d1b887c9cd62
duration: "300"
createdAt: 1636727693847
watchersCount: 0
price: 5EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FUhueSxcjB7qMWF4lyZRJ.png?generation=1636728210217237&alt=media
commentsLast: ~
promoter: Latinvibes
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
id: UhueSxcjB7qMWF4lyZRJ
place: ChIJAVkDPzdOqEcRcDteW0YgIQQ
international: No
views: 7
updatedAt: 1636727693847
updatedBy: 91wGbG4Kwaa2XmcEoEpKvwcfleL2
visibility: Public
confirmation: Dear guest you are confirmed to our event.
eventType: Party
organiser: Latinvibes
form: Yes
createdBy: 91wGbG4Kwaa2XmcEoEpKvwcfleL2
commentsCount: 0
name: PACIFIC COAST PARTY dancing workshop, music and friends
online: No
styles:
  BachataModerna:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Merengue:
    level: Interested
    highlighted: false
    selected: true
  Reggaeton:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
  Casino:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Berlin
  location:
    country: Germany
    latitude: 52.52000659999999
    locality: Berlin
    usedGps: false
    place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
    longitude: 13.404954
startDate: 2021-11-13T20:00:00.000Z
username: Latinvibes
viewsCount: 69
