venue:
  website: http://www.tanzstudio-rebecca.com/
  formatted_address: Anglerstraße 6, 80339 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "6"
      short_name: "6"
    - types:
        - route
      long_name: Anglerstraße
      short_name: Anglerstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Schwanthalerhöhe
      short_name: Schwanthalerhöhe
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80339"
      short_name: "80339"
  room: orange
  url: https://maps.google.com/?cid=14332716633642345223
  name: Studio Rebecca | Tanzstudio Rebecca
  geometry:
    viewport:
      south: 48.1328691697085
      north: 48.1355671302915
      east: 11.5365322802915
      west: 11.53383431970849
    location:
      lng: 11.5350651
      lat: 48.1342039
  map: ""
  place_id: ChIJz0JxsqjYnUcRB6OVHtcJ6MY
  international_phone_number: +49 176 24414498
endDate:
  _seconds: 1640950200
  _nanoseconds: 0
claimed: Yes
organisedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
link: https://www.eventbrite.it/e/brazilian-zouk-basic-level-workshop-tickets-229765543927
description: >-
  This workshop is an introductory level workshop for the wonderful and rapidly
  growing partner dance Brazilian Zouk. Brazilian Zouk is characterized by fluid
  and sensual movements and dance techniques such as "contra-balance" and
  "out-of-axis" turns, which can be danced to a wide variety of music genres
  (e.g. contemporary, pop & hip-hop). The course is taught by Paula and
  Sebastian, two experienced teachers from Spain and Germany, who are trained in
  different dance techniques and styles.


  The main focuses of this course are:


  - Beginners steps and simple combinations

  - Basic technique

  - Leading & Following


  Registration is possible with or without a partner. 2G+ corona rules apply.
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FJSJpodNRDHakSXpOj2KkJMVDKFI2%2F5b683373-a743-47e6-86b3-162d2e016720?alt=media&token=ce94744a-b99e-421b-a2be-f3d21a4e13e8
promo: Yes
duration: "90"
createdAt: 1639946946957
watchersCount: 0
price: 8 EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FUju5IPQrKvFUakFZ5OjQ.png?generation=1639956868076811&alt=media
commentsLast: ~
promoter: Paulita
id: Uju5IPQrKvFUakFZ5OjQ
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
international: No
views: 6
updatedAt: 1639946946957
updatedBy: JSJpodNRDHakSXpOj2KkJMVDKFI2
visibility: Public
facebook: https://www.facebook.com/Bailadictos
eventType: Workshop
organiser: Paulita
form: Yes
createdBy: JSJpodNRDHakSXpOj2KkJMVDKFI2
commentsCount: 0
name: Brazilian Zouk Basic Level Workshop
online: No
styles:
  BrazilianZouk:
    level: Beginner
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-12-31T10:00:00.000Z
username: Paulita
viewsCount: 60
