endDate: 2021-04-02T15:00:00.000Z
link: https://vk.com/topic-199829687_46946453
description: >
  Дорогие танцоры! Если у вас еще нет планов на начало мая, то мы с радостью
  готовы предоставить вам железное алиби:


  В Москве с 30.04 по 03.05 от организаторов "Alibi Kizomba Festival" пройдет кизомба марафон! Вас ожидают:

  🔹 72 часа нонстоп музыки и танцев в главном зале, с 18:00 пятницы до 18:00 понедельника (Kizomba, Urbankiz, Tarraxa, Tarraxo)

  🔹18 часов традиционной музыки во втором зале во время вечеринок (Kizomba, Semba)

  🔹 Различные психологические практики для поиска формулы идеального удовольствия от танцев и снятия блоков!

  🔹 Возможность взять индивидуальные занятия у преподавателей по сниженным ценам


  В создании музыкальной атмосферы марафона примут участие лучшие диджеи Украины DJ NUO и DJ TEO! Ребята очень жаждут приехать, но если границы останутся закрытыми, они будут играть онлайн. А также представляем вам список наших диджеев:

  DJ Exponenta (Пенза)

  DJ Di (Ставрополь)

  DJ Gas (Краснодар)

  DJ Arty Monte (Москва)

  DJ Smart (Санкт-Петербург)

  DJ Korzh (Саратов)

  DJ Bur (Волгоград)

  DJ Marsel (Москва)

  DJ Marianna (Москва)

  DJ Uzhey (Санкт-Петербург)


  Подробности скоро! По вопросам сотрудничества и покупки пассов обращайтесь к Регине


  Купить билет https://vk.com/topic-199829687_46946453

  Проживание и место проведения https://vk.com/topic-199829687_46946456

  DJ https://vk.com/topic-199829687_46946454
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FErP9WITL4eMyf36LQ5iR9nCAIJ82%2F46222218-7379-4cf1-9bf4-d89483205cad?alt=media&token=25d855f3-afff-450b-860a-1e427261a7da
duration: custom
createdAt: 1619253774367
watchersCount: 0
price: 1300 - 2200 руб.
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FUNqX9oa65ducvzbyxQsk.png?generation=1619255137567442&alt=media
commentsLast: ~
place: ChIJybDUc_xKtUYRTM9XV8zWRD0
id: UNqX9oa65ducvzbyxQsk
views: 1
updatedAt: 1619253774367
address: г. Москва станция м. Пролетарская/Крестьянская застава ул. Симоновский вал, д.2
updatedBy: ErP9WITL4eMyf36LQ5iR9nCAIJ82
visibility: Public
eventType: Festival
form: Yes
createdBy: ErP9WITL4eMyf36LQ5iR9nCAIJ82
commentsCount: 0
name: Alibi Kizomba Festival
styles:
  Tarraxinha:
    level: Interested
    highlighted: false
    selected: true
  Tarraxo:
    level: Interested
    highlighted: false
    selected: true
  UrbanTarraxa:
    level: Interested
    highlighted: false
    selected: true
  UrbanKizz:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Moscow
  location:
    country: Russia
    latitude: 55.755826
    locality: Moscow
    usedGps: false
    place_id: ChIJybDUc_xKtUYRTM9XV8zWRD0
    longitude: 37.6172999
startDate: 2021-04-30T15:00:00.000Z
username: MaryRys
viewsCount: 18
