updatedBy: pzHj4sqTOkSOVnyiZK787r0hqoA3
address: "Hofgarten "
endDate: 2021-07-10T21:00:00.000Z
viewsCount: 2
description: Salsa all Styles & Bachata
eventType: Party
type: event
duration: custom
createdAt: 1625729111310
watchersCount: 0
createdBy: pzHj4sqTOkSOVnyiZK787r0hqoA3
commentsCount: 0
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FUrPUjVsKzyZMpNaBgSPy.png?generation=1625729343797666&alt=media
name: "Salsa in Hofgarten "
commentsLast: ~
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: UrPUjVsKzyZMpNaBgSPy
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-07-10T17:00:00.000Z
views: 2
updatedAt: 1625729111310
username: DELETED
