venue:
  website: http://www.tanzschuleamstachus.de/
  formatted_address: Sonnenstraße 7, 80331 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "7"
      short_name: "7"
    - types:
        - route
      long_name: Sonnenstraße
      short_name: Sonnenstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Altstadt-Lehel
      short_name: Altstadt-Lehel
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80331"
      short_name: "80331"
  url: https://maps.google.com/?cid=7618752569010268631
  name: Tanzschule am Stachus
  geometry:
    viewport:
      south: 48.13684386970849
      north: 48.13954183029149
      east: 11.5668774802915
      west: 11.5641795197085
    location:
      lng: 11.56564
      lat: 48.13818409999999
  place_id: ChIJCxXM5ZV1nkcR16lzexg_u2k
  international_phone_number: +49 1590 1227277
endDate:
  _seconds: 1637370000
  _nanoseconds: 0
claimed: Yes
organisedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
link: https://www.eventbrite.de/e/timba-party-by-salsa-cubana-munich-tickets-206730044127
description: >
  Rumber@s


  We continue our Timba parties with another dance practice at one of the most beautiful dance rooms in Munich at Tanzschule am Stachus.


  The best of Salsa Cubana, Timba, Songo, Timbaton, Son and the great dancers you know from our parties with cool drinks to fair prices in an amazing atmosphere. 


  Salsa Candela will prepare you for the night with a workshop from 21:00 - 21:30.


  Later at night, one of our favourite dancers will heat up the dance floor: Emi Lederer. 


  As a special guest Eneris Mulgado will join us at the party. 


  - Date: 19 November 2021

  - Workshop: 21:00 - 21:30

  - Party: 21:30 - 02:00

  - Place: Tanzschule am Stachus

  - Cover: 10 Euro normal, 7 Euros students


  The event will be subject to 2G+. Admission for vaccinated and recovered only. Additionally a negative rapid test will be required. As an alternative you can buy test-kit and do test at the entrance.


  A vacunar!!!


  ### Useful links


  - [COVID Tests Locations](https://www.muenchen.de/aktuell/2021/corona-schnelltest-muenchen-orte.html)
type: event
duration: "300"
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2Fa8bf1117-50d2-48a6-b18e-0f02870dcefd?alt=media&token=260b002c-f20d-4644-aa07-6bb93874330b
createdAt: 1636312476272
watchersCount: 0
price: 10EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FUscvbgfHmx2Xak9n9mBR.png?generation=1637325312401278&alt=media
commentsLast: ~
promoter: alejito
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: UscvbgfHmx2Xak9n9mBR
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
international: No
views: 24
updatedAt: 1636312476272
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
visibility: Public
facebook: https://www.facebook.com/events/451404446614007
eventType: Party
organiser: salsa.cubana.munich
form: No
createdBy: N2N8hjGOw0dU0k0u1mpp0DlGJv93
commentsCount: 0
name: Timba Party 2G+
online: No
styles:
  Son:
    level: Interested
    highlighted: true
    selected: true
  Casino:
    level: Interested
    highlighted: true
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-19T20:00:00.000Z
username: salsa.cubana.munich
viewsCount: 95
