venue:
  formatted_address: Zentnerstraße 39, 80798 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "39"
      short_name: "39"
    - types:
        - route
      long_name: Zentnerstraße
      short_name: Zentnerstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Schwabing-West
      short_name: Schwabing-West
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80798"
      short_name: "80798"
  url: https://maps.google.com/?q=Zentnerstra%C3%9Fe+39,+80798+M%C3%BCnchen,+Germany&ftid=0x479e75dc25efb82b:0xf086b65e449cb796
  name: Zentnerstraße 39
  geometry:
    viewport:
      south: 48.1577258697085
      north: 48.1604238302915
      east: 11.5660365802915
      west: 11.5633386197085
    location:
      lng: 11.5646014
      lat: 48.1590917
  place_id: ChIJK7jvJdx1nkcRlrecRF62hvA
endDate:
  _seconds: 1629554400
  _nanoseconds: 0
link: https://fb.me/e/2v24DyEzD
description: >
  For English, scroll down :) 

  In unserem Bachata Styling Day lernen wir Techniken aus vielen verschiedenen Tanzrichtungen, die unsere Bachata-Bewegungen eleganter und ausdrucksvoller machen. Folgende Inhalte werden angesprochen:

  - Kopfdrehungen, Schultern, Beugen des Oberkörpers, Cambrés in alle Richtungen, sowie Bodywaves und Bodyrolls, Armstylings

  - Hüft bewegungen im Sensual, Domenican und klassischen Bachata

  - Starke und schöne Beine und Fußhaltungen

  - Körperspannung während Figuren und Beugeübungen (Cambrés)

  - Musikalität und Musik anders hören lernen, Sicherheit in Bewegungen schaffen, verschiedene Charaktere darstellen

  Tipps und Tricks bei Socialdancing und Partnerwork. Wie man besser aussieht als Tänzerin und sich gut führen lässt.

  Am Ende wird eine Choreo eingeübt, in der die wichtigsten gelernten Techniken eingebaut sind.

  Der Kurs ist für alle, mit Basic Level Vorerfahrung geeignet!


  Über Marta findest du mehr Infos hier:

  https://www.instagram.com/martapihelgas/


  Anmeldung:

  DM or mymia.miamy@gmail.com


  Ablauf

  12:00 Bachata ABC + Musicality + History explained with movement

  12:30 Basic steps with technical explanation + Styling cherries

  14:00 Break

  14:30 until open end Choreography Study and Dominican Step combination

  Video Shooting, Photos


  English


  Bachata Styling Day


  Introduction:

  In our Bachata Ladies Styling Intensive Course we will study many different dance techniques, that will help us improve, spice up and smoothen our moves in bachata dancing.

  - practice of different head positions in turns and create illusions with help of zouk head flicks and head rolls

  - study body rolls and -waves in all directions

  - Learn to release your neck and shoulders while styling and learn correct techniques for cambrés and hip movements in Dominican, Sensual and classical styles. Work on isolations and become aware of your feet!

  You will get tips and tricks in social- and partnerwork-dancing as well as practice body manipulations and contact-dance, we will play with musicality and different attitudes while performing our movements.

  We will be fierce but soft, strong but confident!

  All levels, with or without dance and bachata style experience.

  In the end of every class we will learn a combination to practice what we have learned.


  Registration DM or mymia.miamy@gmail.xom


  About Marta https://www.instagram.com/martapihelgas/


  Schedule


  12:00 Bachata ABC + Musicality + History explained with movement

  12:30 Basic steps with technical explanation + Styling cherries

  14:00 Break

  14:30 until open end Choreography Study and Dominican Step combination


  Price: 35 EUR
type: event
duration: "240"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F2SiXeZreWTU11yK7B35E2ZL4c1v1%2Fed21be96-02ed-4103-8201-c77764de3b33?alt=media&token=5d803d6a-75f2-4c56-815f-b93afd4a8bd3
createdAt: 1628009000758
watchersCount: 0
price: 35EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FuUOkjjwUUNWjVV1w5KBi.png?generation=1628068248108094&alt=media
commentsLast: ~
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: uUOkjjwUUNWjVV1w5KBi
views: 1
updatedAt: 1628009000758
updatedBy: 2SiXeZreWTU11yK7B35E2ZL4c1v1
address: Zentnerstraße 39, Video Print Training
visibility: Public
eventType: Workshop
form: Yes
createdBy: 2SiXeZreWTU11yK7B35E2ZL4c1v1
commentsCount: 0
name: Bachata Styling Day
online: No
styles:
  SensualBachata:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  DominicanBachata:
    level: Interested
    highlighted: false
    selected: true
  Latin:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-08-21T10:00:00.000Z
username: marta
viewsCount: 65
