endDate: 2021-11-20T18:30:00.000Z
organisedBy: ""
claimed: No
description: >-
  Die Große Tänzerin und Lehrerin Alejandra Mantiñan erweitert unser Tango mit
  ihrer Zauberei!


  WORKSHOPS Samstag 20 November 


  14 bis 15.30 Uhr


  1)TECHNIK FÜR FOLLOWERS 
      Ladys Ornaments 
      Aktive Follower concept
                (  all Levels )
  ‐--‐-------------------------------------------------------------

  16 bis 17.30 Uhr


  2)TANGO 360° Concept of Creativity

                   (all Levels )
  -----------------------------------------------------------------
     18 bis 19.30 Uhr

    3)Ganchos/ Volcadas

          (Intermedia/Advance)

  --‐--------------------------------------------------------------

  Sonntag 21 November 


  12 bis 13.30 Uhr

  4) Musicality of Vals 
           (All Levels )
  ---‐-------------------------------------------------------------
   14 bis 15.30 Uhr

  5)Dynamik and Connection control of                                           the  Smooth movement 
           All Levels 
  -----------------------------------------------------------------

  18 30 bis 20 Uhr


  6) komplexe Enrrosques 
            ADVANCE
  -----------------------------------------------------------------


  preis


  Earlybird bis 15 November!!!!!


  6 Workshops 135€

  5 Workshops 115€

  4 Workshops 95€

  3 Workshops 75€

  2 Workshops  55€

  1 Workshop   30€


  Reguläre Preise 


  6 Workshops 165€

  5 Workshops 145€

  4 Workshops 115€

  3 Workshops 90€

  2 Workshops 65€

  1 Workshop 35€


  Bei Teilnahme an 4 Workshops 

  Eintritt in  Milonga  Loca Frei


  Workshops in Milonga Loca


  18 bis 19 Uhr All Levels 

  Torsions and their concepts 
   25€
  19 bis 20 Uhr Advance 


  little and big Planeos for both Roles

  25€


  Show vom Alejandra Mantiñan & Martha Giorgi 

  Milonga Loca 22 hs 



  Privatstunde mit Alejandra 120€


  Anmeldung und Kontakt 

  contact@tango-connection.de 
   Mobil & Whatsapp 
                 015751337705
type: event
duration: custom
promo: ""
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2F114dea6f-dfda-46dd-9f1b-bc22f2f9a2ce?alt=media&token=cd3be18f-21a0-4e51-87cc-4c25aef06aef
createdAt: 1635681664407
watchersCount: 0
price: 30-165 EUR
commentsLast: ~
promoter: Vitali
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
id: v3J7lyAygvWi7a0datnA
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 13
updatedAt: 1635681664407
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
facebook: https://facebook.com/events/s/alejandra-mantinan-in-munchen/200309345572132/
eventType: Party
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Alejandra Mantiñan in München
online: No
styles:
  Tango:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-20T13:00:00.000Z
username: Vitali
viewsCount: 71
