endDate: 2021-08-01T20:00:00.000Z
description: "Free Live-Musik, gutes Essen, grösse Tanzfläche  "
type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FR2uKbN7LNHdMThHxURcTwyb81rG2%2F920f7536-f9a0-4ce1-a6b2-c0747194f455?alt=media&token=3608a763-0420-4370-9bb7-39e0fa6b38a0
createdAt: 1627286160240
watchersCount: 0
price: Free
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FvBTs7Iv08yKeWVZ6iUQC.png?generation=1627286225285208&alt=media
commentsLast: ~
id: vBTs7Iv08yKeWVZ6iUQC
place: ChIJ04-twTTbmUcR5M-RdxzB1Xk
views: 4
updatedAt: 1627286160240
updatedBy: R2uKbN7LNHdMThHxURcTwyb81rG2
address: Berger Festplatz
visibility: Public
viewsCount: 4
eventType: Party
form: No
createdBy: R2uKbN7LNHdMThHxURcTwyb81rG2
commentsCount: 0
name: Peruanischer Unabhängigkeitstag Party
online: No
styles:
  Merengue:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Stuttgart
  location:
    country: Germany
    latitude: 48.7758459
    locality: Stuttgart
    usedGps: false
    place_id: ChIJ04-twTTbmUcR5M-RdxzB1Xk
    longitude: 9.1829321
startDate: 2021-07-31T10:00:00.000Z
username: Coco0288
