venue:
  formatted_address: Böckhstraße 21, 10967 Berlin, Germany
  website: http://www.caminada.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "21"
      short_name: "21"
    - types:
        - route
      long_name: Böckhstraße
      short_name: Böckhstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Bezirk Friedrichshain-Kreuzberg
      short_name: Bezirk Friedrichshain-Kreuzberg
    - types:
        - locality
        - political
      long_name: Berlin
      short_name: Berlin
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Berlin
      short_name: Kreisfreie Stadt Berlin
    - types:
        - administrative_area_level_1
        - political
      long_name: Berlin
      short_name: BE
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "10967"
      short_name: "10967"
  url: https://maps.google.com/?cid=2639942359527432436
  name: La Caminada Tanzstudio
  geometry:
    viewport:
      south: 52.49203981970851
      north: 52.49473778029151
      east: 13.4210531802915
      west: 13.4183552197085
    location:
      lng: 13.4197042
      lat: 52.49338880000001
  place_id: ChIJAwhy0ctPqEcR9KAjx5b1oiQ
  international_phone_number: +49 30 6949744
endDate:
  _seconds: 1634473800
  _nanoseconds: 0
claimed: Yes
organisedBy: 3ucRV7NCdPMWMf2mHXAutsuorhm2
description: >-
  We are back with two new amazing Bachata Workshops for YOU on *17th of
  October* in Berlin ☄️🔥💥

  On the menu:

  ☀️12:30-13:30 Bachata Styling with Martyna (open level)

  ☀️13:30-14:30 Bachata Partnerwork with Erol & Martyna (inter/adv)

  During Bachata Styling class, we will focus on musicality, footwork, beautiful arms, and useful tricks dancing with a partner 🌸 You don't need to have any prior experience, just COME as YOU ARE and take your 👠, if you like!

  During the partner work, we will teach you how to add a bit of sass to your bachata dancing ⚡. We will play with more advanced combinations of foundations so that you can begin creating your own combos and style, plus we will work on musicality, partner work, and social dancing skills, which you will be able to easily apply on the dancefloor.💃🏽 The level is intermediate/advance.

  YOU DON'T NEED A PARTNER, we will switch! The space is limited to 10 Leaders and 10 Followers (20 participants in total).

  🪧Where are we meeting? Tanzstudio Caminada: Böckhstrase 21, 10967, Berlin.

  😷 Please keep in mind the COVID-19 3G rule (recovered, tested, or vaccinated)

  🙏🏻Support your teachers:

  10 euro one class

  15 euro both classes

  Send me or Martyna a DM if you want to save your space! We are very excited to see you all! 🥰

  #bachata #bachatacouple #bachatafusion #bachatagermany #bachatasensual #bachatadominican #couple #couplegoals #dance #dancers #dancerlife #highheels #styling #technique #workshop #bachataturkey #bachataistakingover #bachatalithuania
type: event
duration: "120"
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2F3ucRV7NCdPMWMf2mHXAutsuorhm2%2F0a453da0-04a2-4c29-a1d4-b2fe3b8ca86d?alt=media&token=c92a820f-a988-40cc-bec0-736d7f404e0c
promo: Yes
createdAt: 1633640775805
watchersCount: 0
price: 10EUR
commentsLast: ~
promoter: eNm
place: ChIJAVkDPzdOqEcRcDteW0YgIQQ
promotedBy: 3ucRV7NCdPMWMf2mHXAutsuorhm2
id: vPugplMCO1C2ZtmEKvyc
international: No
views: 12
updatedAt: 1633640775805
updatedBy: 3ucRV7NCdPMWMf2mHXAutsuorhm2
visibility: Public
facebook: https://www.facebook.com/events/665838091054732
eventType: Workshop
organiser: eNm
form: No
createdBy: 3ucRV7NCdPMWMf2mHXAutsuorhm2
commentsCount: 0
name: Bachata Workshops with Erol & Martyna - October 2021
online: No
styles:
  BachataModerna:
    level: Interested
    highlighted: false
    selected: true
  SensualBachata:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  DominicanBachata:
    level: Interested
    highlighted: false
    selected: true
  HighHeels:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Berlin
  location:
    country: Germany
    latitude: 52.52000659999999
    locality: Berlin
    usedGps: false
    place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
    longitude: 13.404954
startDate: 2021-10-17T10:30:00.000Z
username: eNm
viewsCount: 59
