endDate: 2021-05-30T18:00:00.000Z
link: https://vk.com/blizhniykosmos
description: >-
  Проект "Танцевальная психология" совместно с AfroFusion и FelizLatino
  ПРЕДСТАВЛЯЕТ уикенд с уникальной программой для танцующих Bachata, Kizomba и
  Salsa!

  Для любого уровня танцевания.


  Хочешь узнать больше о танце, о себе, о своëм теле и о том, как они влияют друг на друга? Ищешь новые способы для самовыражения и импровизации в танце? Задаëшься вопросом, как грамотно наладить связь с партнëром?


  Мы создали этот уикенд специально для вас.

  👨‍🎓👩‍🎓"Ток шоу" с компетентными психологами танцорами

  🤯8 часов полезнейших классов

  🤗"Обратная связь" с обсуждением самых важных тем в конце каждого дня

  😇Relax Party

  🙃Круглый танцпол с психологом или "Беседка Pro танцы"


  Программа включает в себя теоретический и практический блоки. Основное содержание программы — это как танцы влияют на нашу жизнь и как танцы можно использовать эффективно во благо, т.е. ознакомление с биомеханическими, социальными, психофизиологическими и природными процессами взаимодействия во время танца.

  Классы ведут профессиональные танцоры и психологи.


  Результаты обучения:


  — расширение знаний о танце в целом и его значении в жизни отдельного человека, и социума;


  — знакомство с понятием Биомеханика и его универсальном применении в сольном и парном танцах;


  — вы узнаете всë об импровизации и о том как придать индивидуальный окрас своему танцу и выделиться;


  — узнаете больше о женственности и мужественности, их проявлении и влиянии на ваш танец, а так же проработаете эти состояния;


  — узнаете больше о взаимодействии в паре, о механизмах и жизненных проекциях влияющих на это взаимодействие;


  — более вдумчиво станете относиться к движениям в своëм теле через профессиональную изоляцию;


  — узнаете о целительных (терапевтических) свойствах танцев и и ощутите их на себе;


  — расширение знаний о человеческой личности и еë потребностях в социальных танцах.


  Главный организатор — проект "Танцевальная психология".


  29—30 МАЯ мы ждëм вас на нашем уикенде.


  💰 Стоимость:

  первые 10 пассов 2500р.

  далее повышение цены


  🎁К каждому пассу прилагается подарок:

  СКИДКА на одно посещение вечеринки FelizLatino Kizomba или Bachata на выбор🎁


  📍Адрес проведения:

  Сретенский бульвар, 6/1с2, школа танцев

  AfroFusion.📍


  Наши педагоги: Артур Черненко, Мария Медведева, Евгения Руденко, Александр Никулин, Борис Кириленко


  Пассы приобрести можно у администратора группы Любовь и Артура Черненко, все вопросы также можно задавать им.


  Контакты:

  +7 (977) 970-12-14 Любовь

  +7 (916) 190-20-96 Артур


  #bachata #bachatasensual #bachatadance #танцевальнаяпсихология #kizomba #kiz #kizombaurban #bachatadance #психология #salsa #salsacasino #salsadance
type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FErP9WITL4eMyf36LQ5iR9nCAIJ82%2F83f9fdd0-9e0b-4de1-8b74-3268c2754220?alt=media&token=b01d736f-6062-4829-b4bc-199bba90de64
createdAt: 1621584800991
watchersCount: 0
price: 2500 руб.
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FvWWCNMnwRSLWMvmaeCzW.png?generation=1621584816747350&alt=media
commentsLast: ~
id: vWWCNMnwRSLWMvmaeCzW
place: ChIJybDUc_xKtUYRTM9XV8zWRD0
views: 1
updatedAt: 1621584800992
address: Сретенский бульвар, 6/1с2, школа танцев AfroFusion
updatedBy: ErP9WITL4eMyf36LQ5iR9nCAIJ82
visibility: Public
eventType: Workshop
form: Yes
createdBy: ErP9WITL4eMyf36LQ5iR9nCAIJ82
commentsCount: 0
name: '"БЛИЖНИЙ КОСМОС" танцевальный уикенд'
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Moscow
  location:
    country: Russia
    latitude: 55.755826
    locality: Moscow
    usedGps: false
    place_id: ChIJybDUc_xKtUYRTM9XV8zWRD0
    longitude: 37.6172999
startDate: 2021-05-29T09:00:00.000Z
username: MaryRys
viewsCount: 2
