endDate:
  _seconds: 1633899600
  _nanoseconds: 0
description: Von Tango Argentino und brasilianischer Musik über Cumbia und
  karibische Klänge bis zu einem Musical für Kinder erwartet das Publikum wieder
  eine Reise quer durch Lateinamerika beim großen Solidaritäts-Konzert für
  Kinder in Südamerika im neuen Kulturareal Sugar Mountain (Helfenriederstr./U3
  Machtlfingerstr.). Am 9. Oktober gibt es ab 19 Uhr eine argentinische Milonga
  mit dem Quinteto Garufa und Lo de Laura. Am 10. Oktober folgen um 15 Uhr das
  Kindermusical „La Nota Magica – Die magische Note“ mit Luis Borda & friends
  und anschließend zwei Konzerte mit Luis Viola, Guto Alves da Silva & Friends
  sowie Ximena Mariño & Consorcio Latino. Die Einnahmen gehen an zwei Projekte
  für Kinder in Argentinien und Brasilien. Mehr Informationen zu den
  Veranstaltungen und Projekten, Spenden und Vorverkauf findet man auf
  www.solidaritaetskonzerte.de
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2Fdac5344a-4929-4dc5-a5e6-5aa6d1d917d4?alt=media&token=51652dfc-423e-4c11-824a-fcaa0ff4bbd4
promo: ""
duration: "240"
createdAt: 1633508842090
watchersCount: 0
price: 15 EUR
commentsLast: ~
id: wDxEuor3cEVFT1Fg4Ogc
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 2
updatedAt: 1633508842090
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Concert
organiser: LatinoDancer
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Lateinamerikanisches Solidaritätskonzert
online: No
styles:
  Cumbia:
    level: Interested
    highlighted: false
    selected: true
  ForroLove:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
  BrazilianZouk:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-10T17:00:00.000Z
username: Vitali
viewsCount: 3
