venue:
  website: https://www.salsa-y-corazon.de/
  formatted_address: Zenettistraße 7, 80337 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "7"
      short_name: "7"
    - types:
        - route
      long_name: Zenettistraße
      short_name: Zenettistraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Ludwigsvorstadt-Isarvorstadt
      short_name: Ludwigsvorstadt-Isarvorstadt
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80337"
      short_name: "80337"
  url: https://maps.google.com/?cid=8616399599048238742
  name: Salsa Y Corazon - dance school
  geometry:
    viewport:
      south: 48.12187606970849
      north: 48.12457403029149
      east: 11.5593379802915
      west: 11.5566400197085
    location:
      lng: 11.557894
      lat: 48.12314479999999
  international_phone_number: +49 172 9659579
  place_id: ChIJ7SAJ9Rd3nkcRlqYWoMiZk3c
endDate:
  _seconds: 1639260000
  _nanoseconds: 0
claimed: No
organisedBy: ""
link: salsafreaks.splashthat.com
description: >-
  Hola liebe 🌴*SALSAFREAKS*🌴

  Nach Rücksprache und Absicherung mit dem *Landesamt für Gesundheit* können wir am Samstag den 11.12. nach den Vorgaben der *2G+ Regel* einen Salsa Bachata Übungsabend *durchführen*. 

  Bitte einen PCR oder Antigen Test (nicht älter als 24 Std.) mitbringen und vorzeigen.

  *Antigen Test für €3,- auch in der Tanzschule erhältlich*. Kleine Teststation vor dem Eingang der Tanzschule.

  *Maske von Eingang bis zur Kasse tragen*

  Bitte das Impf- oder Genesen Zertifikat mit PCR oder Antigen Test an der Tür, mit Ausweis, vorzeigen.
          🌴 🌴 🌴 🌴 🌴
  *WORKSHOP:*

  Bachata Mittelstufe mit *Rubén Díaz aus Cádiz* 

  18 - 19 Uhr Workshop: 10€
         🌴 🌴 🌴 🌴 🌴
  19 - 23:45 Übungsabend 10€

  Veranstalter: *SALSAFREAKS* 


  👇🏽Registrierung des Übungsabends 👇🏽

  salsafreaks.splashthat.com


  Registrierung für den Workshop:👇🏿

  Info@salsa-y-corazon.de
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2F449f68b4-b38d-4b74-b96b-945c43f2e86e?alt=media&token=198834dd-7b8f-4535-aaa0-211ccf0f6873
duration: "240"
createdAt: 1639244078040
watchersCount: 0
price: 10-20  EUR
commentsLast: ~
promoter: Vitali
id: wLFhAC6llIYFx5xWFRMz
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
international: No
views: 2
updatedAt: 1639244078040
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Party
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Salsa & Bachata Übungsabend
online: No
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-12-11T18:00:00.000Z
username: Vitali
viewsCount: 4
