organisedBy: ""
claimed: No
type: event
cover: ""
duration: 60
createdAt: 1638019904688
watchersCount: 0
price: FREE
commentsLast: ~
promoter: Cuorlieto
promotedBy: IWXVNyn3lefgmenNuuj8ox8Eawt2
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: WN502qyQ5bGj4BC0bBRV
international: No
views: 5
updatedAt: 1638019904688
updatedBy: IWXVNyn3lefgmenNuuj8ox8Eawt2
visibility: Public
viewsCount: 5
eventType: Party
organiser: ""
form: No
createdBy: IWXVNyn3lefgmenNuuj8ox8Eawt2
commentsCount: 0
name: 🎼 https://www.smule.com/sing-recording/1701375363_4221050787
online: No
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
username: Cuorlieto
