venue:
  website: https://www.hyatt.com/en-US/hotel/france/hyatt-regency-paris-etoile/parhr?src=corp_lclb_gmb_seo_parhr
  formatted_address: 3 Pl. du Général Kœnig, 75017 Paris, France
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "3"
      short_name: "3"
    - types:
        - route
      long_name: Place du Général Kœnig
      short_name: Pl. du Général Kœnig
    - types:
        - locality
        - political
      long_name: Paris
      short_name: Paris
    - types:
        - administrative_area_level_2
        - political
      long_name: Département de Paris
      short_name: Département de Paris
    - types:
        - administrative_area_level_1
        - political
      long_name: Île-de-France
      short_name: IDF
    - types:
        - country
        - political
      long_name: France
      short_name: FR
    - types:
        - postal_code
      long_name: "75017"
      short_name: "75017"
  url: https://maps.google.com/?cid=4980267253142486820
  name: Hyatt Regency Paris Étoile
  geometry:
    viewport:
      south: 48.87931451970849
      north: 48.88201248029149
      east: 2.285663730291502
      west: 2.282965769708498
    location:
      lng: 2.2844977
      lat: 48.88046139999999
  place_id: ChIJT0BJgYtv5kcRJH8RHq52HUU
  international_phone_number: +33 1 40 68 12 34
description: >-
  - 4 days of dance


  SEMBA / KIZOMBA / URBANKIZ / TARRAXO 


  - 2 intensive workshops on sunday 

  - In one of the best hotel in Paris 

  - It's ALL IN ONE HOTEL 


  - Music will be very good 


  - Paris is the place where to dance kizomba is very good because you can find a lot of leaders 
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FFGBU2yqOClNVEQkSH3cEGnhIE7C2%2Fe3acfacf-d073-4421-ace8-2c7ee36426e5?alt=media&token=65d925d9-88f1-4db0-8f4b-73a3119069a1
promo: Yes
duration: custom
createdAt: 1631456917671
watchersCount: 0
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FwuHlPXGEhJJB8aYPmX3v.png?generation=1632492797619767&alt=media
place: ""
id: wuHlPXGEhJJB8aYPmX3v
views: 19
updatedAt: 1631456917671
updatedBy: FGBU2yqOClNVEQkSH3cEGnhIE7C2
visibility: Public
eventType: Festival
organiser: toureiffel
form: No
createdBy: FGBU2yqOClNVEQkSH3cEGnhIE7C2
name: "Paris Etoile Festival / New Year Eve / Kizomba / All in One "
online: No
styles:
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
username: toureiffel
watch:
  count: 1
  list:
    alejito: true
star:
  count: 1
  list:
    alejito: true
price: 100EUR
organisedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
facebook: https://fb.me/e/30DPLQfX9
commentsCount: 3
commentsLast:
  updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
  postId: wuHlPXGEhJJB8aYPmX3v
  body: |
    Festival is rescheduled to 19 August
  createdAt: 1640885914891
  createdBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
  commentId: ""
  username: alejito
  updatedAt: 1640885914892
endDate: 2022-01-03T18:00
startDate: 2021-12-30T20:00
viewsCount: 30
