venue:
  formatted_address: Westenriederstraße 41, 80331 München, Germany
  website: http://www.salsaclub-munich.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "41"
      short_name: "41"
    - types:
        - route
      long_name: Westenriederstraße
      short_name: Westenriederstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Altstadt-Lehel
      short_name: Altstadt-Lehel
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80331"
      short_name: "80331"
  url: https://maps.google.com/?cid=17999243784988121499
  name: Salsa Club Munich by Hakan
  geometry:
    viewport:
      south: 48.13383846970849
      north: 48.13653643029149
      east: 11.5813775802915
      west: 11.5786796197085
    location:
      lng: 11.5800714
      lat: 48.1353416
  international_phone_number: +49 172 8533891
  place_id: ChIJU60HW-F1nkcRm9nfvdsoyvk
endDate: 2022-01-11T18:45:00.000Z
organisedBy: ""
claimed: No
link: ""
description: >-
  You can learn Salsa New York. The most elegant Salsa Style!



  Attention This is a 2G+. You should be vaccinated / recovered + need a negative test to come in.
type: event
duration: custom
createdAt: 1640295869009
watchersCount: 0
price: 80 EUR
commentsLast: ~
promoter: Vitali
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: WuKZgTnKLcywRjEgpAg7
international: No
views: 6
updatedAt: 1640295869009
website: https://salsaclub-munich.de/course.php?kid=120
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
facebook: https://salsaclub-munich.de/course.php?kid=120
eventType: Course
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Salsa New York Beginner 1
online: No
styles:
  SalsaNewYork:
    level: Beginner
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2022-01-11T17:30:00.000Z
username: Vitali
cover: ""
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
viewsCount: 20
