venue:
  website: http://www.tanzschule-tanzraum.de/
  formatted_address: Neusser Str. 216, 50733 Köln, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "216"
      short_name: "216"
    - types:
        - route
      long_name: Neusser Straße
      short_name: Neusser Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Nippes
      short_name: Nippes
    - types:
        - locality
        - political
      long_name: Köln
      short_name: Köln
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Köln
      short_name: Kreisfreie Stadt Köln
    - types:
        - administrative_area_level_2
        - political
      long_name: Köln
      short_name: K
    - types:
        - administrative_area_level_1
        - political
      long_name: Nordrhein-Westfalen
      short_name: NRW
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "50733"
      short_name: "50733"
  url: https://maps.google.com/?cid=2981146820628674026
  name: Ballet School Annette Farber
  geometry:
    viewport:
      south: 50.96033351970851
      north: 50.96303148029151
      east: 6.955849630291502
      west: 6.953151669708498
    location:
      lng: 6.954593999999999
      lat: 50.9616923
  place_id: ChIJy85DyZwlv0cR6nXbEj0pXyk
  international_phone_number: +49 221 233233
endDate:
  _seconds: 1641679200
  _nanoseconds: 0
organisedBy: ""
claimed: No
description: >-
  
  - You like urban kiz and want to start with it?

  - You dance at parties and festivals ... but you have the feeling that you are still missing something?

  - Are you still looking for the so-called "connection" to your partner?

  - Do you have trouble finding your balance when your partner leads you slowly or quickly?

  - Do you even know what makes the difference between “urban kiz” and “kizomba” in terms of dance?


  You are here at the right place!


  I am pleased to welcome you to my customized URBAN KIZ program. For the first time here in NRW! This series of workshops will be INTENSIVE and will challenge you 100% in URBAN KIZ.


  It doesn't matter if you are a beginner or not!

  It doesn't matter if you are a follower or not!


  Within 7 appointments you will get the elements, exercises, theory and practice time that you need to get the best out of yourself. As a highlight you will be assisted by 4 experienced international Kizomba and Urbankiz teachers.

  Under an international and high quality pedagogy, we will accompagne you in various dance topics and remove your obstacles.

  ************************************************** ***************

  Head teacher:

  Stone’s rock


  Guest teacher:

  Ledoux Dianza

  Danielle Dejong

  Ramona


  URBAN KIZ BASICS-SYNCOPATION & -ORIENTATIONS-POWERFUL SAIDAS-LEG LEADING & CONNECTION-FOOTWORK
   FEMALE KIZ ATTITUDE-MALE KIZ ATTITUDE-MUSICALITY 1-2-3

  ** A LOOOOT OF PRACTICE TIME **

  ** A LOOOOT OF PRACTICE TIME **

  Registration: contact rockyourdance@gmail.com or @ramona / @ stone’s rock

  ************************************************** ***************

  7 DATES (January2022-April 2022)

  Date1: Sat. January 8, 2022

  Date2: Sun. January 9, 2022

  Date3: Sun. January 30, 2022

  Date4: Sun. February 20, 2022

  Date5: Sun. February 27, 2022

  Date6: Sat. April 02, 2022

  Date7: Su. April 03, 2022


  ******************************************************************

  DANCE LEVEL AT EACH DATE (14:00 - 18:00):

  Urban kiz Open level / Foundamentals (2 hours)

  Urban kiz Intermediate to Advanced (2 hours)

  ************************************************** ***************

  Tickets:

  🔔Large Pass: 210 euro  all 7 dates-28 hours-Foundamental- intermediate-advanced level 

  🔔Small pass: 120 euro  all 7 dates-14 hours-Foundamental level rockyourdance@gmail.com or @ramona / @ stone’s rock


  ☝🏾☝🏾☝🏾☝🏾☝🏾😃☝🏾☝🏾☝🏾☝🏾☝🏾☝🏾☝🏾☝🏾

  The sessions are each time under strict respect of the Corona regulations. According to the current regulations, 2G + applies. So recovered or vaccinated and a negative Covid test.


  ******************************************
type: event
cover: ""
duration: "240"
createdAt: 1639522721392
watchersCount: 0
price: /
commentsLast: ~
promoter: Stones
place: ChIJAVkDPzdOqEcRcDteW0YgIQQ
id: wxaF813Ii4z9mdbLCSsl
promotedBy: m6ZLnWaUfCU1rfzcZuI93E1B1r43
international: No
views: 4
updatedAt: 1639522721392
updatedBy: m6ZLnWaUfCU1rfzcZuI93E1B1r43
visibility: Public
eventType: Course
organiser: ""
form: No
createdBy: m6ZLnWaUfCU1rfzcZuI93E1B1r43
commentsCount: 0
name: Intensive urbankiz classes
online: No
styles:
  UrbanKizz:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Berlin
  location:
    country: Germany
    latitude: 52.52000659999999
    locality: Berlin
    usedGps: false
    place_id: ChIJAVkDPzdOqEcRcDteW0YgIQQ
    longitude: 13.404954
startDate: 2022-01-08T18:00:00.000Z
username: Stones
viewsCount: 31
