endDate: 2021-07-08T20:30:00.000Z
link: https://docs.google.com/forms/d/e/1FAIpQLSeBMqA8NGlRhh624CqQ5VrpvLPu0--ZSvbQYROSkY--p_hi9g/viewform
description: Bachata Workshop + Übungsabend Salsa und Bachata
type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FSxx9Y1rMeEh8vmaIhFsWRWzeooA2%2F26651402-cc38-4137-96d2-8c688b8d31f8?alt=media&token=0f4e3447-1291-4a03-ace5-8a9762c7187e
createdAt: 1625511411047
watchersCount: 0
price: "15"
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FxkgwrQHQF91badiTrmh5.png?generation=1625512336625719&alt=media
commentsLast: ~
id: xkgwrQHQF91badiTrmh5
place: ChIJzdzMDgXBl0cR1zokRADq5u8
views: 1
updatedAt: 1625511411047
updatedBy: Sxx9Y1rMeEh8vmaIhFsWRWzeooA2
address: Handelsstrasse 9a Eppelheim
visibility: Public
eventType: Workshop
form: Yes
createdBy: Sxx9Y1rMeEh8vmaIhFsWRWzeooA2
commentsCount: 0
name: Bachata/Salsa Übungsabend
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Heidelberg
  location:
    country: Germany
    latitude: 49.3987524
    locality: Heidelberg
    usedGps: false
    place_id: ChIJzdzMDgXBl0cR1zokRADq5u8
    longitude: 8.6724335
startDate: 2021-07-08T17:30:00.000Z
username: prinhony
viewsCount: 22
