venue:
  formatted_address: Am Schützeneck 3, 81241 München, Germany
  website: https://www.salsamas-pasing.de/de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "3"
      short_name: "3"
    - types:
        - route
      long_name: Am Schützeneck
      short_name: Am Schützeneck
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Pasing-Obermenzing
      short_name: Pasing-Obermenzing
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81241"
      short_name: "81241"
  url: https://maps.google.com/?cid=8948474523406618165
  name: Salsamás Pasing - Tanzkurse für Singles und Paare
  geometry:
    viewport:
      south: 48.1464650697085
      north: 48.1491630302915
      east: 11.4637166802915
      west: 11.4610187197085
    location:
      lng: 11.4623658
      lat: 48.14774430000001
  international_phone_number: +49 89 17929039
  place_id: ChIJ0QgbwuJ3nkcRNc5IASteL3w
endDate: 2021-11-13T23:00:00.000Z
claimed: No
organisedBy: ""
description: >-
  SALSAMÁS PASING JUBILÄUMSFEIER

  Sa. 13.11.21 19:00-00:30 Uhr


  ✨ Preparty Workshops

  ✨ Tanzshows

  ✨ Begrenzte Teilnehmerzahl

  ✨ Gast DJ

  ✨ Verlosung & vieles mehr…


  *Ablauf:*

  19:00 - Salsa Cool Moves in Partnerwork 

  19:45 - Different Types of Crossbodylead 

  20:30 - Party Beginn DJ

  23:00 - Show-Programm 

  00:30 - Ende


  *Musik: Salsa, Bachata & Kizomba* 


  *Eintrittspreise:*

  Vertragsmitglieder:     07,50 €*

  Kursteilnehmer:           10,00 €*

  Nicht Kursteilnehmer: 15,00 €*

  * Workshops in dem Preis inklusive 


  ✨AKTUELL GILT FÜR DIE PARTY DIE 2G-REGELN, WIR KÖNNEN NUR ZUTRITT FÜR GENESEN ODER GEIMPFTEN GEWEHREN!


  *Bitte meldet Euch rechtzeitig per Email oder WhatsApp für das Event an:*

  WhatsApp: 0172 82 165 69

  E-Mail:         info@salsa-mas.de
type: event
duration: custom
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2Ffacc47a8-b9bd-4e6d-a432-2538c086d80b?alt=media&token=bab7ae41-ff84-42e8-8242-80706d6997e4
createdAt: 1636372462622
watchersCount: 0
price: 7,5-15 EUR
commentsLast: ~
promoter: Vitali
id: XKR14b2F5vYR1atmk7zu
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
international: No
views: 17
updatedAt: 1636372462622
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
facebook: https://facebook.com/events/s/salsamas-pasing-jubilaumsfeier/1514905188893768/
eventType: Party
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Salsamas Jubiläumsfeier
online: No
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-13T18:00:00.000Z
username: Vitali
viewsCount: 20
