venue:
  website: http://www.tanzstudio-rebecca.com/
  formatted_address: Anglerstraße 6, 80339 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "6"
      short_name: "6"
    - types:
        - route
      long_name: Anglerstraße
      short_name: Anglerstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Schwanthalerhöhe
      short_name: Schwanthalerhöhe
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80339"
      short_name: "80339"
  room: white
  url: https://maps.google.com/?cid=14332716633642345223
  name: Studio Rebecca | Tanzstudio Rebecca
  geometry:
    viewport:
      south: 48.1328691697085
      north: 48.1355671302915
      east: 11.5365322802915
      west: 11.53383431970849
    location:
      lng: 11.5350651
      lat: 48.1342039
  map: ""
  place_id: ChIJz0JxsqjYnUcRB6OVHtcJ6MY
  international_phone_number: +49 176 24414498
endDate:
  _seconds: 1636570800
  _nanoseconds: 0
organisedBy: ""
claimed: No
link: https://fb.me/e/2S0SjFh59
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FG008dEeTZJcXLBzzL2krS0Ynumu2%2F3bcc4c80-043e-4e3b-8a78-2816487a6d34?alt=media&token=b47cacf7-9182-44f4-885e-bd6293cd4f24
duration: "120"
promo: ""
createdAt: 1635358574589
watchersCount: 0
price: ""
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FXNE54UCD25sOMPU8VdpH.png?generation=1635766208638527&alt=media
commentsLast: ~
promoter: Thomas
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
id: XNE54UCD25sOMPU8VdpH
promotedBy: G008dEeTZJcXLBzzL2krS0Ynumu2
international: No
views: 18
updatedAt: 1635358574589
updatedBy: G008dEeTZJcXLBzzL2krS0Ynumu2
visibility: Public
facebook: https://fb.me/e/2S0SjFh59
eventType: Course
organiser: ""
form: Yes
createdBy: G008dEeTZJcXLBzzL2krS0Ynumu2
commentsCount: 0
name: Zouk Beginners Crash Course
online: No
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-10T17:00:00.000Z
username: Thomas
styles:
  BrazilianZouk:
    level: Beginner
    highlighted: false
    selected: true
viewsCount: 66
