venue:
  formatted_address: Sonnenstraße 24-26, 80331 München, Germany
  website: http://www.isarpost-eventlocation.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: 24-26
      short_name: 24-26
    - types:
        - route
      long_name: Sonnenstraße
      short_name: Sonnenstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Ludwigsvorstadt-Isarvorstadt
      short_name: Ludwigsvorstadt-Isarvorstadt
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80331"
      short_name: "80331"
  url: https://maps.google.com/?cid=14604975425998091393
  name: ISARPOST Eventlocation
  geometry:
    viewport:
      south: 48.1337302197085
      north: 48.1364281802915
      east: 11.5665639302915
      west: 11.5638659697085
    location:
      lng: 11.5650711
      lat: 48.13503660000001
  place_id: ChIJg2EMgljfnUcRgfTs-8RLr8o
  international_phone_number: +49 89 1499037894
endDate: 2021-11-21T03:00:00.000Z
organisedBy: ""
claimed: No
link: https://bit.ly/3CfYCA6
description: "Munich de Noche lädt ein zum nächsten Paukenschlag für alle
  Liebhaber des Reggaetons. Am Sa, 20.11.21 gibt es in der Isarpost das Beste
  aus 25 Jahren Reggaeton. Von Rakim y Ken-Y, Wisin y Yandel, Tego Calderon,
  Daddy Yankee, Don Omar über Ivy Queen & Zion y Lennox. 😍


  📻 Ticketlink: https://bit.ly/3CfYCA6 📻


  Für den richtigen musikalischen Mix begrüßen wir unsere Residents DJ Javi &
  DJ Benido con Flow an den Plattenspieler. Die beiden legen das Beats aus Old
  School Reggaeton / Merengue und Dembow auf.


  Wegen das zu erwarteten großen Andrangs empfehlen wir frühzeitig zu
  erscheinen oder einen Tischreservierung zu tätigen unter
  munichdenoche@gmail.com


  ❌ WICHTIGE INFO ❌

  Dieses Event findet gemäß der aktuellen Coronaverordnung statt. Wir bitten
  euch daher folgende Punkte zu beachten:

  • Zutritt zur Veranstaltung nach dem 3G-Prinzip nur für Geimpfte, Genesene
  oder PCR Getestete. Impfausweis / Genesenennachweis muss am Einlass vorgezeigt
  werden.

  • Keine Maskenpflicht

  • Es darf getanzt werden 💃

  • Um einen sicheren Einlass zu garantieren empfehlen wir die Karten im
  Vorverkauf zu erwerben.

  • Vorverkauf: 10€ // Abendkasse: lt. Aushang - Ticketlink:
  https://bit.ly/3CfYCA6

  \ "
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2Fe0267f6e-2151-44d6-bd9d-bfa3d8d72936?alt=media&token=c0307f07-596f-4553-b5a2-383ed77e9bb4
promo: ""
duration: custom
createdAt: 1635179534790
watchersCount: 0
price: 10 EUR
commentsLast: ~
promoter: Vitali
id: XQhdrSRKW05L0lPcfTqr
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
international: No
views: 10
updatedAt: 1635179534790
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
facebook: https://facebook.com/events/s/reggaeton-de-la-vieja-escuela-/297527435538856/
eventType: Party
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Reggaeton de la vieja escuela
online: No
styles:
  Salsaton:
    level: Interested
    selected: true
  SensualBachata:
    level: Interested
    selected: true
  Merengue:
    level: Interested
    highlighted: false
    selected: true
  Reggaeton:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Intermediate
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-20T21:00:00.000Z
username: Vitali
viewsCount: 16
