venue:
  website: http://capo-world.com/
  formatted_address: Humboldtstraße 29, 81543 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "29"
      short_name: "29"
    - types:
        - route
      long_name: Humboldtstraße
      short_name: Humboldtstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Au-Haidhausen
      short_name: Au-Haidhausen
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81543"
      short_name: "81543"
  url: https://maps.google.com/?cid=15339360251921049344
  name: Capoeira Gerais – Sport und Kultur vereint e.V.
  geometry:
    viewport:
      south: 48.1182935197085
      north: 48.1209914802915
      east: 11.5764631302915
      west: 11.5737651697085
    location:
      lng: 11.5751481
      lat: 48.1196802
  place_id: ChIJwVh2SkrfnUcRACeAseBa4NQ
  international_phone_number: +49 175 2840454
endDate:
  _seconds: 1630357200
  _nanoseconds: 0
link: https://facebook.com/events/s/workshops-with-camila-alves/820560895313164/
description: >-
  SAVE THE DATE! 

  We are welcoming Camila Alves to Munich and we could not be happier. She is one of the most dedicated, active and passionate teacher and dancer of our community. Be ready to get inspired! 

  Below you can read more about Camila, and here you can see her dancing: 

  https://www.youtube.com/channel/UC2ILK-jpF4IJdHN_cmOf7mw


  WORKSHOP SCHEDULE:

  18:00 - 19:00 Advanced

  19:15 - 20:15 Intermediate

  20:30 - 21:30 Beginner Plus

  ____________

  REGISTRATION:

  Further information about prices, registration and Corona measures will follow soon.
   
  ******


  ENG


  Camila Alves is a Portuguese Forró teacher living in Lisbon. 

  She is a very active instructor since 2012 and is known for teaching at numerous festivals and events around the world, developing courses and workshops focused on contemporary topics such as the role of leaders and followers and how they can take a more feminist approach when dancing, encouraging students to dance however they want. Her career is focused on fighting for both men and women to have the same rights to express themselves through dance.

  Camila is involved in the organisation team of many events, such as Maria Bonita Festival, Baião in Lisboa Festival & Forró Douro Festival, attracting hundreds of people to Portugal every year.

  Entrepreneur by nature, she studied Business Management with Marketing in London where her solo career as a forró teacher took off. 

  Camila is currently teaching & managing Espaço Baião, one of the biggest forró schools in Europe based in Lisbon. She also just launched an online Forró Shop called Xiado da Xinela Shop, providing forró products such as clothes & accessories for both women and men, having as its motto “Be whoever you want to be on the dance floor”. 


  PT


  Camila Alves é Portuguesa e professora de Forró residente em Lisboa.

  É muito activa na cena de Forró desde 2012 e é conhecida por dar aulas em inúmeros festivais e eventos no mundo inteiro, dando cursos e workshops focados em assuntos contemporâneos como o papel de leaders e followers e como estes podem ter uma abordagem mais feminista quando dançam, encorajando os alunos a dançar da forma que quiserem. A sua carreira está intensamente ligada na luta de direitos entre homens e mulheres de se expressarem através da dança.

  Camila está envolvida na equipa de organização de diversos eventos, como o Maria Bonita Festival, Baião in Lisboa Festival e Forró Douro Festival, que atraem centenas de pessoas a Portugal todos os anos.


  Empreendedora por natureza, estudou Administração de Empresas com Marketing em Londres, onde a sua carreira a solo como professora de forró se iniciou. Atualmente, dá aulas e administra o Espaço Baião, uma das maiores escolas de Forró da Europa com base em Lisboa. Um dos pontos altos da sua vida foi ter lançado recentemente uma loja online de Forró chamada Xiado da Xinela Shop que vende roupas e acessórios para mulheres e homens, tendo como lema “Be whoever you want to be on the dance floor - Seja o que quiser na pista de dança”.
type: event
duration: "300"
cover: ""
promo: ""
createdAt: 1628983861802
watchersCount: 0
price: FOLLOWING SOON
commentsLast: ~
id: yEEbD2tHefzW95EI4uGa
place: ""
views: 1
updatedAt: 1628983861802
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Workshop
organiser: LatinoDancer
form: Yes
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Forró Workshop with Camila Alves
online: Yes
styles:
  ForroLove:
    level: Interested
    highlighted: false
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
startDate: 2021-08-30T16:00:00.000Z
username: Vitali
viewsCount: 3
