venue:
  formatted_address: Landwehrstraße 24, 80336 München, Germany
  website: https://www.dancewithgeorge.com/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "24"
      short_name: "24"
    - types:
        - route
      long_name: Landwehrstraße
      short_name: Landwehrstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Ludwigsvorstadt-Isarvorstadt
      short_name: Ludwigsvorstadt-Isarvorstadt
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80336"
      short_name: "80336"
  url: https://maps.google.com/?cid=7158368571314548597
  name: Dance With George Tanzschule München
  geometry:
    viewport:
      south: 48.13505101970851
      north: 48.13774898029151
      east: 11.5632495302915
      west: 11.5605515697085
    location:
      lng: 11.5618859
      lat: 48.1364618
  international_phone_number: +49 172 4513580
  place_id: ChIJpyPj-_d1nkcRdS-G-EmiV2M
endDate:
  _seconds: 1633813200
  _nanoseconds: 0
link: https://www.dancewithgeorge.com/
description: >-
  ‼️Attention‼️

  *We changed the times!*

  *This Saturday we are starting our community indoor party with 2 timeslots.🤩*

  Many thanks to the dance school (Dance with George) for making it possible 🥰


  *Date: Saturday 9.10. from*

  *20:00-22:00*

  and

  *22:00-23:59*

  *Location: DWG Landwehrstraße 24, 80336*

  *DJs: Momo and friends*

  *Entry: Free*

  *Participants: 40*

  *Entrance rules: 3G*

  *Pre-Registration:* https://www.dancewithgeorge.com/ or using the DanceWithGeorge App  (Pre-Registration mandatory!) 


  *Please register only for 1 social and sign out as early as possible if you can't come, so more people have the chance to participate*

  Already done registrations will be changed to the time 22:00-24:00. 

  If you want to come earlier, please cancel your registration and register again for the earlier social.


  Let's Bachata 💃🏽🕺
type: event
cover: ""
duration: "240"
createdAt: 1633503362635
watchersCount: 0
price: FREE
commentsLast: ~
id: yq4xdZALbslSI3Lc8d4V
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
views: 14
updatedAt: 1633503362635
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
viewsCount: 14
eventType: Party
organiser: LatinoDancer
form: Yes
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Bachata Community indoor Party  DWG
online: No
styles:
  SensualBachata:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-09T17:00:00.000Z
username: Vitali
