venue:
  formatted_address: 73 Av. Henri Dunant, 77100 Meaux, France
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "73"
      short_name: "73"
    - types:
        - route
      long_name: Avenue Henri Dunant
      short_name: Av. Henri Dunant
    - types:
        - locality
        - political
      long_name: Meaux
      short_name: Meaux
    - types:
        - administrative_area_level_2
        - political
      long_name: Seine-et-Marne
      short_name: Seine-et-Marne
    - types:
        - administrative_area_level_1
        - political
      long_name: Île-de-France
      short_name: IDF
    - types:
        - country
        - political
      long_name: France
      short_name: FR
    - types:
        - postal_code
      long_name: "77100"
      short_name: "77100"
  url: https://maps.google.com/?q=73+Av.+Henri+Dunant,+77100+Meaux,+France&ftid=0x47e8a141dab1f641:0xf2c61077588007b7
  name: 73 Av. Henri Dunant
  geometry:
    viewport:
      south: 48.9421674197085
      north: 48.9448653802915
      east: 2.900983330291502
      west: 2.898285369708498
    location:
      lng: 2.8998756
      lat: 48.9436984
  place_id: ChIJQfax2kGh6EcRtweAWHcQxvI
endDate: 2022-01-04T05:00:00.000Z
organisedBy: ""
claimed: No
link: https://www.weezevent.com/iydj-nye-6
description: >
  ## I’M YOUR DJ NEW YEAR: Édition 6 - Paris


  - **Start:** Friday, December 31, 2021

  - **End:** Sunday, January 2, 2022

  - **Address:** Colisée de Meaux - 73 avenue Henri Dunant - 77100 Meaux

  - **Facebook event:** [https://www.facebook.com/events/s/im-your-dj-new-year-2022-paris/478706930100103/](https://www.facebook.com/events/s/im-your-dj-new-year-2022-paris/478706930100103/)


  ## Facts


  - A new location more than 1500m2

  - A free and big carpark

  - 3 socials

  - 3 parties

  - 2 rooms 2 atmospheres

  - 25 dj’s and teachers

  - 1 ladystyling masterclass

  - An amazing atmosphere

  - 1 before (Li regue) and 1 after (Saida) in Paris


  ## DJ’S


  - DJ Madiss

  - DJ Zay’x

  - DJ Gass

  - DJ Lionnax

  - DJ Snakes

  - DJ Lass

  - DJ David Ruela

  - DJ Onfire

  - DJ Derick Banks

  - DJ Rico

  - DJ JDN

  - DJ Diablo

  - DJ Tyrz

  - DJ Ichigo

  - DJ Maxxx

  - DJ Dee C Beats

  - DJ No Limits

  - DJ May

  - DJ LD

  - DJ DLV


  ## Teachers


  - Lydia Laprade

  - Laho

  - Manon Batrel

  - Azzedine

  - Mike


  ## Photographers and cameraman


  - Polina

  - LNA

  - Benkos


  ## Ticketing & Prices


  *Before (30 december) and after party (4 January) are not included in the pass.*


  - Pass 3 days WOMAN : 80€

  - Pass 3 days MAN : 70€

  - Pass 3 DAYS + masterclass ladystyling : 90€

  - Pass resale (changing name mandatory) : 10€


  **Sold Out**


  - Pass 3 days WOMAN 60€

  - Pass 3 days 60€

  - Pass 3 days 50€


  ## Contact


  👉 [i.am.your.dj.newyear@gmail.com](mailto:i.am.your.dj.newyear@gmail.com)
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2F51ceced8-8a93-4683-972f-42970e128e22?alt=media&token=629e86e6-2e26-4581-81f0-028197868084
duration: custom
promo: No
createdAt: 1638832426848
watchersCount: 0
price: 70-90 EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FZ0k4mXFW1qMPnotuY0v3.png?generation=1638832583376963&alt=media
commentsLast: ~
promoter: alejito
place: ""
promotedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
id: Z0k4mXFW1qMPnotuY0v3
international: Yes
views: 13
updatedAt: 1638832426848
website: https://www.weezevent.com/iydj-nye-6
updatedBy: tvR012ArEpQhCJdPHh6G7sLuqoO2
visibility: Public
facebook: https://facebook.com/events/s/im-your-dj-new-year-2022-paris/478706930100103/
eventType: Festival
confirmation: >
  To finish reservation please purchase your ticket at
  https://www.weezevent.com/iydj-nye-6
organiser: ""
form: Yes
createdBy: 5hkUljYCTSPJwsDqNqgGYRe1Tok2
commentsCount: 0
name: I'M YOUR DJ New Year 2022
online: No
styles:
  Tarraxinha:
    level: Interested
    highlighted: false
    selected: true
  Tarraxo:
    level: Interested
    highlighted: false
    selected: true
  UrbanTarraxa:
    level: Interested
    highlighted: false
    selected: true
  UrbanKizz:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
startDate: 2021-12-30T19:00:00.000Z
username: Promoter
star:
  count: 1
  list:
    alejito: true
watch:
  count: 1
  list:
    alejito: true
viewsCount: 22
