venue:
  formatted_address: Zellstraße 4, 81667 München, Germany
  website: http://www.muffatwerk.de/
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "4"
      short_name: "4"
    - types:
        - route
      long_name: Zellstraße
      short_name: Zellstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Au-Haidhausen
      short_name: Au-Haidhausen
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "81667"
      short_name: "81667"
  url: https://maps.google.com/?cid=5843927271141599712
  name: Muffathalle
  geometry:
    viewport:
      south: 48.1313994197085
      north: 48.1340973802915
      east: 11.5905477302915
      west: 11.5878497697085
    location:
      lng: 11.5894505
      lat: 48.1328405
  place_id: ChIJGZydHH3fnUcR4OmcAeTMGVE
  international_phone_number: +49 89 45875000
endDate: 2021-11-06T05:00:00.000Z
organisedBy: ""
claimed: No
description: >-
  *Versión en español, más abajo.


  Liebe Freunde, am Freitag, den 05. November bringen wir euch den Spirit of Lateinamerika nach München. Genieße mit uns eine spektakuläre Nacht zu feuriger Tanzstimmung und coolen Drinks. 😍 💃🏽 🕺🏽 🎉 


  Mit dabei sind die beliebtesten Latino-DJs der Stadt: 🎧 💯

  DJ YENNY: Salsa / Bachata / Reggaeton / Merengue / Cumbia y más

  DJ TORI SEGURA: Reggaeton / Latin Urban Beats

  und mucho amor ❤️


  Wir freuen uns auf ein unvergessliches Fest mit euch!


  Eckdaten:

  Wann: Freitag, den 05. November ab 23:00 Uhr 

  Wo: Muffatcafé - Zellstrasse 4 

  Eintritt: 10€
                              

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
  #BACKTOLIVE  #MUENCHENTANZTWIEDER



  📸 Für Bilder, Videos & zukünftige Einladungen

  ● LATINSCENE MUNICH bei Instagram Adden

  @latinscene.munich

  LINK 👉🏽 https://www.instagram.com/latinscene.munich/

  ● unsere Gruppe beitreten

  LINK 👉🏽https://www.facebook.com/groups/latinscene.munich/

  ● und LATIN SCENE MUNICH liken

  LINK 👉🏽 www.facebook.com/latinscene.munich/


  ACHTUNG: Es gilt für den Abend die 2G-Regel (geimpft oder genesen). Bitte die entsprechenden Nachweise mit Ausweisdokument am Einlass parat halten. Es muss kein Abstand gehalten und keine Maske getragen werden.


  🇪🇸

  El viernes 15 de octubre, te traeremos el calor y la alegría de Latino América a Munich!  😍 💃🏽🕺🏽🎉 

  Disfruta de una noche espectacular con nosotros en un ambiente excelente, con la música que te gusta y te hace bailar y con mucho perreo hasta el piso de los latino DJs mas solicitados de Munich. 🎧 💯 💯

  DJ YENNY: Salsa / Bachata / Reggaeton / Merengue / Cumbia y más

  DJ TORI SEGURA: Reggaeton / Latin Urban Beats

  y mucho amor ❤️,                                                               


  Dale Me Gusta a nuestra página "Latin Scene Munich" para más eventos latinos y las fotos de la fiesta! 🙌🏼

  https://www.facebook.com/latinscene.munich/


  ATENCIÓN: Se aplicará la regla 2G para el acceso al club (vacunados o recuperados). 
type: event
duration: custom
promo: ""
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FHPjWaGMC5pWlfgnRhrQwNxio3lv2%2F7a9e7e3c-28e7-4f88-9c9e-5fb58742a0cc?alt=media&token=216b926a-83b7-4c6d-b20b-77b9472e5bc0
createdAt: 1635880072201
watchersCount: 0
price: 10 EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FzFIP2EbbrrNyVlMG7GDS.png?generation=1635880235587438&alt=media
commentsLast: ~
promoter: Vitali
id: zFIP2EbbrrNyVlMG7GDS
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 25
updatedAt: 1635880072201
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
facebook: https://facebook.com/events/s/la-fiesta-latina-muffatcafe/197654405845327/
eventType: Party
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: La fiesta latina
online: No
styles:
  Cumbia:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Merengue:
    level: Interested
    selected: true
  Reggaeton:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-11-05T22:00:00.000Z
username: Vitali
viewsCount: 59
