venue:
  formatted_address: Göttinger Str. 1, 83052 Bruckmühl, Germany
  website: https://m.facebook.com/pages/category/Restaurant/Br%C3%BCckenwirt-1872883502770901/?locale2=de_DE
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "1"
      short_name: "1"
    - types:
        - route
      long_name: Göttinger Straße
      short_name: Göttinger Str.
    - types:
        - locality
        - political
      long_name: Bruckmühl
      short_name: Bruckmühl
    - types:
        - administrative_area_level_3
        - political
      long_name: Rosenheim
      short_name: RO
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "83052"
      short_name: "83052"
  url: https://maps.google.com/?cid=18010679776535684501
  name: Brückenwirt
  geometry:
    viewport:
      south: 47.87856936970851
      north: 47.8812673302915
      east: 11.9123447802915
      west: 11.9096468197085
    location:
      lng: 11.9110789
      lat: 47.879921
  place_id: ChIJFduhxPT2nUcRlaW4A9XJ8vk
  international_phone_number: +49 8062 9083334
endDate: 2021-09-11T14:00:00.000Z
description: >
  Hola Familia,

  Wir sind wieder sehr stolz euch Ramses Sariol (Kuba) aus Mallorca nach Rosenheim für das Wochenende vom 10.09.21 bis einschließlich 12.09.21 zu holen.

  Ramses ist auf allerlei internationalen Events und Festivals mit seinen Workshops erfolgreich unterwegs. Er unterrichtet mit einer eigens entwickelten Lehrmethode den traditionellen kubanischen Salsa Casino Stil – Salsa so wie man ihn immer auf Kuba tanzt.

  Dieser Stil zeichnet sich im Vergleich zum hier unterrichteten Salsa Cubana dadurch aus, dass er ohne den Rückschritt auskommt. Dadurch wirkt der Tanz wesentlich eleganter, weicher und fließender in seinen Abläufen.


  Wir bieten an diesen 3 Tagen 3 aufeinander bauende Workshops von jeweils 4 Stunden an.


  *Basico 1 (Freitag 10.09, 18:30 Uhr bis 23 Uhr)*

  Grundlagen des Salsa Casino, die ersten Schritte und Figuren.


  *Basico 2 (Samstag 11.09, 11:30 Uhr bis 16 Uhr)*

  Kurze Wiederholung des Basico 1, weitere Figuren und Kombinationen. Auch geeignet für Salseros die schon mal beim Ramses waren.


  *Basico 3 (Sonntag 12.09)*

  Uhrzeit und Inhalt nach Absprache mit Ramses und Kursteilnehmern


  Ort:

  Brückenwirt,

  Göttinger Str. 1,

  83052 Bruckmühl


  Zutritt und Teilnahme nach der 3G Regel. Es darf gerne ein Schnelltest mitgebracht und vor Ort unter Aufsicht getestet werden.


  Die Workshops sind für ALLE Salseros (Linie und kubanisch) ab Niveau Mittelstufe geeignet.


  Kosten pro Workshop und Person – 50 EUR

  Teilnehmer der Workshops Basico 1 und 2 zahlen 90 EUR.

  Kosten Basico 3 nach Absprache.


  Mehr Infos, sowie verbindliche Anmeldung bitte telefonisch oder per Whatsapp bei

  Salsabina Casinera unter +4917683209699.
   
  Nutze die Gelegenheit! Probiere den Unterschied! Wir freuen uns auf Euch.


  Ramses, Salsabina und das Baila y Fiesta Team
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FtvR012ArEpQhCJdPHh6G7sLuqoO2%2Ff992ca03-4f33-446e-a231-fc3d3e10197b?alt=media&token=1125d584-e873-4d37-8cc1-d109b3411e8a
promo: Yes
duration: custom
createdAt: 1631007680810
watchersCount: 0
price: 50EUR
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FZFWNOYeMFsY4pUYVNqfu.png?generation=1631009896827089&alt=media
commentsLast: ~
place: ""
id: ZFWNOYeMFsY4pUYVNqfu
views: 7
updatedAt: 1631007680810
updatedBy: uZ1VEvLP7bP7ryCIyMFyuUDWm7n1
visibility: Members
eventType: Workshop
organiser: MiMe72
form: No
createdBy: uZ1VEvLP7bP7ryCIyMFyuUDWm7n1
commentsCount: 0
name: Workshop Salsa Cubana Casino Stil mit Ramses
online: No
styles:
  Salsa:
    level: Interested
    highlighted: false
    selected: true
  Casino:
    level: Interested
    highlighted: false
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
startDate: 2021-09-10T16:30:00.000Z
username: MiMe72
viewsCount: 11
