venue:
  formatted_address: Gellertstraße 12, 76185 Karlsruhe, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "12"
      short_name: "12"
    - types:
        - route
      long_name: Gellertstraße
      short_name: Gellertstraße
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Weststadt
      short_name: Weststadt
    - types:
        - locality
        - political
      long_name: Karlsruhe
      short_name: Karlsruhe
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt Karlsruhe
      short_name: Kreisfreie Stadt Karlsruhe
    - types:
        - administrative_area_level_2
        - political
      long_name: Karlsruhe
      short_name: KA
    - types:
        - administrative_area_level_1
        - political
      long_name: Baden-Württemberg
      short_name: BW
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "76185"
      short_name: "76185"
  url: https://maps.google.com/?q=Gellertstra%C3%9Fe+12,+76185+Karlsruhe,+Germany&ftid=0x479706effaaf66e7:0xfd9e09edb208fde1
  name: Gellertstraße 12
  geometry:
    viewport:
      south: 49.0087043197085
      north: 49.0114022802915
      east: 8.373122430291502
      west: 8.370424469708498
    location:
      lng: 8.3718532
      lat: 49.0102989
  place_id: ChIJ52av-u8Gl0cR4f0Isu0Jnv0
endDate: 2021-11-06T00:00:00.000Z
organisedBy: bMDkcdLCNgXW3kVq0OfW0HxltQo1
claimed: Yes
description: "  ## 💯❤️ dance practice  \ 

  \    \ 

  Questions to https://www.instagram.com/streetparty11/                     \ 

  \    \ 

  - No drinks allowed.

  - From 9pm to 1am.

  - Places: 120 People.

  - With DJ.\ 

  - Pre-registration desired.


  ## Music

  Bachata 3 / Salsa 3\ 

  - Bachata sensual + moderna\ 

  - 50% Line salsa / 50% cuban salsa.


  ## CoronaVO:


  Hygiene concept in place, taking into account the current CoronaVO.\ 

  3G or 2G depends on the applicable regulation of the country.


  3G only with PCR test\ 



  ## Address


  - Gellertstraße 12, 76337 Karlsruhe


  Photo by https://unsplash.com/@7seth


  <w-instagram url=\"https://www.instagram.com/reel/CRZN9MEnOjD/\">









  \ "
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FbMDkcdLCNgXW3kVq0OfW0HxltQo1%2F056551f3-e007-4c73-b232-5c00a8f67f79?alt=media&token=0b167106-dacc-43ac-9f95-8f6b8ea140c4
duration: custom
promo: Yes
createdAt: 1632174489536
watchersCount: 0
price: 7 Euro
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FZt4e7JaDp2pn2JK6MksW.png?generation=1635967121929240&alt=media
commentsLast: ~
promotedBy: bMDkcdLCNgXW3kVq0OfW0HxltQo1
id: Zt4e7JaDp2pn2JK6MksW
place: ChIJCXjgokgGl0cRf-63THNV_LY
international: No
views: 300
updatedAt: 1632174489536
website: beacons.ai/streetparty
updatedBy: bMDkcdLCNgXW3kVq0OfW0HxltQo1
visibility: Public
confirmation: |-
  Dear guest, you are registered for "💯❤️".

  Please bring your certificate for the corona 🛂 checkup 

  We would also appreciate if you bring exactly 7 euros 🙏
eventType: Other
organiser: streetparty
form: No
createdBy: bMDkcdLCNgXW3kVq0OfW0HxltQo1
commentsCount: 0
name: dance practice 💯❤️
online: No
styles:
  Bachata:
    level: Intermediate
    highlighted: false
    selected: true
  Salsa:
    level: Intermediate
    highlighted: false
    selected: true
region:
  name: Karlsruhe
  location:
    country: Germany
    latitude: 49.0068901
    locality: Karlsruhe
    usedGps: false
    place_id: ChIJCXjgokgGl0cRf-63THNV_LY
    longitude: 8.4036527
startDate: 2021-11-05T20:00:00.000Z
username: streetparty
viewsCount: 320
