endDate: 2021-05-24T01:00:00.000Z
description: |-
  🔥Hola amigos!

  Свежее расписанием вечеринок!

  ▪️ВОСКРЕСЕНИЕ (23.05) - Battle Party 
  ⏰ зажигаем с 21:00-03:00ч.
  📍 Papa’s Bar
  🎧 ARI | TiM
  Формат: B|S|K 4-1-1

  На наших вечеринках снимает сторис Хукас Никогосян

  Приходи сам и приводи друзей!

  #SBKвечеринки #SBK #wedancemoscow
type: event
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FErP9WITL4eMyf36LQ5iR9nCAIJ82%2F7e112589-bd70-49c4-bf4a-697ca42cd4ca?alt=media&token=cd110041-9fd9-46a1-bdd3-843e4a39ff74
duration: custom
createdAt: 1621621243863
watchersCount: 0
price: "300 - 500 руб. "
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FZVBQW2hsWCSnYxZgyl1V.png?generation=1621621415653248&alt=media
commentsLast: ~
id: ZVBQW2hsWCSnYxZgyl1V
place: ChIJybDUc_xKtUYRTM9XV8zWRD0
views: 1
updatedAt: 1621621243863
address: "Papa’s Bar: Никольская улица, 10, Россия, Москва"
updatedBy: ErP9WITL4eMyf36LQ5iR9nCAIJ82
visibility: Public
eventType: Party
form: No
createdBy: ErP9WITL4eMyf36LQ5iR9nCAIJ82
commentsCount: 0
name: Battle Party in Tiki
styles:
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
  Salsa:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Moscow
  location:
    country: Russia
    latitude: 55.755826
    locality: Moscow
    usedGps: false
    place_id: ChIJybDUc_xKtUYRTM9XV8zWRD0
    longitude: 37.6172999
startDate: 2021-05-23T19:00:00.000Z
username: MaryRys
viewsCount: 2
