venue:
  website: http://www.zagreb.hr/
  formatted_address: Zagreb, Croatia
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png
  html_attributions: []
  address_components:
    - types:
        - locality
        - political
      long_name: Zagreb
      short_name: Zagreb
    - types:
        - country
        - political
      long_name: Croatia
      short_name: HR
  url: https://maps.google.com/?q=Zagreb,+Croatia&ftid=0x4765d692c902cc39:0x3a45249628fbc28a
  name: Zagreb
  geometry:
    viewport:
      south: 45.74085269898914
      north: 45.93953920070314
      east: 16.10697267901845
      west: 15.82169038274528
    location:
      lng: 15.981919
      lat: 45.8150108
  place_id: ChIJOcwCyZLWZUcRisL7KJYkRTo
endDate: 2021-10-25T13:00:00.000Z
link: https://zagrebpassion.net
description: >-
  ### BACHATA • URBAN KIZ • KIZOMBA


  Everyone wants to be part of our crazy energy and atmosphere and if you want to know why, ASK YOUR FRIENDS 😏


  Our motto I NEED TO DANCE, DANCE, DANCE is taking over! 🖤
   
  Mark your calendars, FUEL YOUR PASSION and DANCE IT OUT with us!!


  - 3NIGHT PARTIES 

  - SOCIAL PARTIES 

  - WORKSHOPS


  ☑️ TICKETS: https://www.goandance.com/en/events/4927-4th-zagreb-passion-festival-2021-sensual-edition


  ## ARTISTS, VIDEO/PHOTO, DANCERS TEAM


  BACHATA TEACHERS:


  ....to be announced


  🎧 DJs:


  ....to be announced


  KIZOMBA TEACHERS:


  ....to be announced


  🎧 DJs:


  ....to be announced


  🎬 VIDEO/PHOTO:



  ....to be announced



  ## TICKETS

  • sale will open on 13.09.2021.


  Directly link: https://www.goandance.com/en/events/4927-4th-zagreb-passion-festival-2021-sensual-edition


  - VIP PASS (includes all kizomba & bachata workshops & parties)

  - BACHATA PASS (includes only bachata workshops & parties)

  - KIZOMBA PASS (includes only kizomba workshops & parties)


  ❗️Money for bought passes is not refundable. Check FESTIVAL RULES on our website before purchasing a ticket. You can change name on ticket without fee until 15.10.2021.
type: event
promo: Yes
cover: https://firebasestorage.googleapis.com/v0/b/wedance-4abe3.appspot.com/o/media%2FQeQxXz0UGEcLualNWMTN6mOTreD2%2F033ce828-e6fc-4740-9290-3ef4046f5425?alt=media&token=4b449ffd-1ad3-4045-9b6c-7feb4b3a47d1
duration: custom
createdAt: 1631189235087
watchersCount: 0
price: ""
socialCover: https://storage.googleapis.com/download/storage/v1/b/wedance-4abe3.appspot.com/o/share%2Fevents%2FZyxuJDr2PzY6ggazKiPW.png?generation=1631189521979456&alt=media
commentsLast: ~
place: ""
id: ZyxuJDr2PzY6ggazKiPW
views: 21
updatedAt: 1631189235087
updatedBy: QeQxXz0UGEcLualNWMTN6mOTreD2
visibility: Public
eventType: Festival
organiser: Kropus13
form: Yes
createdBy: QeQxXz0UGEcLualNWMTN6mOTreD2
commentsCount: 0
name: Zagreb Passion Festival - Sensual edition
online: No
styles:
  UrbanKizz:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Interested
    highlighted: false
    selected: true
  Kizomba:
    level: Interested
    highlighted: false
    selected: true
region:
  placeId: ""
  loaded: true
  name: Anywhere
startDate: 2021-10-22T12:00:00.000Z
username: Kropus13
viewsCount: 22
