venue:
  website: https://www.pinakothek-der-moderne.de/
  formatted_address: Barer Str. 40, 80333 München, Germany
  icon: https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/museum-71.png
  html_attributions: []
  address_components:
    - types:
        - street_number
      long_name: "40"
      short_name: "40"
    - types:
        - route
      long_name: Barer Straße
      short_name: Barer Str.
    - types:
        - sublocality_level_1
        - sublocality
        - political
      long_name: Maxvorstadt
      short_name: Maxvorstadt
    - types:
        - locality
        - political
      long_name: München
      short_name: München
    - types:
        - administrative_area_level_3
        - political
      long_name: Kreisfreie Stadt München
      short_name: Kreisfreie Stadt München
    - types:
        - administrative_area_level_2
        - political
      long_name: Oberbayern
      short_name: Oberbayern
    - types:
        - administrative_area_level_1
        - political
      long_name: Bayern
      short_name: BY
    - types:
        - country
        - political
      long_name: Germany
      short_name: DE
    - types:
        - postal_code
      long_name: "80333"
      short_name: "80333"
  url: https://maps.google.com/?cid=14384342178029021798
  name: Pinakothek der Moderne
  geometry:
    viewport:
      south: 48.1457500697085
      north: 48.1484480302915
      east: 11.5730605802915
      west: 11.5703626197085
    location:
      lng: 11.5723021
      lat: 48.1471559
  international_phone_number: +49 89 23805360
  place_id: ChIJW8LuYO51nkcRZqoW2f9yn8c
endDate: 2021-10-11T20:30:00.000Z
claimed: No
organisedBy: ""
description: Eine spontane Outdoor Party mit DJs Josi und Tuan
type: event
cover: ""
duration: custom
createdAt: 1633930462914
watchersCount: 0
price: FREE
commentsLast: ~
promoter: Vitali
promotedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
id: zz6vXt2ezyZsaMLftvlJ
place: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
international: No
views: 8
updatedAt: 1633930462914
updatedBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
visibility: Public
eventType: Party
organiser: ""
form: No
createdBy: HPjWaGMC5pWlfgnRhrQwNxio3lv2
commentsCount: 0
name: Bachata@Pina
online: No
styles:
  BachataModerna:
    level: Intermediate
    highlighted: false
    selected: true
  SensualBachata:
    level: Interested
    highlighted: false
    selected: true
  Bachata:
    level: Intermediate
    highlighted: false
    selected: true
  DominicanBachata:
    level: Interested
    highlighted: false
    selected: true
region:
  name: Munich
  location:
    country: Germany
    latitude: 48.1351253
    locality: Munich
    usedGps: false
    place_id: ChIJ2V-Mo_l1nkcRfZixfUq4DAE
    longitude: 11.5819805
startDate: 2021-10-11T17:30:00.000Z
username: Vitali
viewsCount: 12
